### ISSUE TITLE
Deploying GPU-Operator on AWS EC2 with (K8S v.19.1, Ubuntu 20.04.1LTS)

### ISSUE THREAD

**Issue by danniel1205** [NVIDIA/gpu-operator#100]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

When deploying gpu-operator on K8S clusters on EC2, the `nvidia-driver-validation` pod is `CrashLoopBackoff` with the following error message:

```
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
[Vector addition of 50000 elements]
```

### 2. Steps to reproduce the issue

- Install K8S v1.19.1 cluster on Amazon EC2 with ami-054006e5fedebab3 
  - OS: `Ubuntu 20.04.1 LTS`
  - Instance type: `g4dn.xlarge`
  - GPUs: `NVIDIA T4 Tensor Core GPUs`
- Deploy `Node Feature Discovery` by following https://github.com/kubernetes-sigs/node-feature-discovery
- Follow https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-nouveau-ubuntu to disable the `nouveau` driver and update `initramfs`
- Update helm repo: 
  ```
  helm repo add nvidia https://nvidia.github.io/gpu-operator \
     && helm repo update
  ```
- Install gpu-operator:
  ```
  helm install --wait --generate-name nvidia/gpu-operator
  ```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] kubernetes pods status: `kubectl get pods --all-namespaces`
[kubectl-get-pods.txt](https://github.com/NVIDIA/gpu-operator/files/5520519/kubectl-get-pods.txt)

 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [x] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
[kubectl-describe-pod.txt](https://github.com/NVIDIA/gpu-operator/files/5520523/kubectl-describe-pod.txt)

 - [x] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`
[kubectl-logs-pod.txt](https://github.com/NVIDIA/gpu-operator/files/5520528/kubectl-logs-pod.txt)

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [x] Docker configuration file: `cat /etc/docker/daemon.json`
[docker-daemon-json.txt](https://github.com/NVIDIA/gpu-operator/files/5520530/docker-daemon-json.txt)

 - [x] Docker runtime configuration: `docker info | grep runtime`
[docker-info-runtime.txt](https://github.com/NVIDIA/gpu-operator/files/5520534/docker-info-runtime.txt)

 - [x] NVIDIA shared directory: `ls -la /run/nvidia`
[ls-run-nvidia.txt](https://github.com/NVIDIA/gpu-operator/files/5520542/ls-run-nvidia.txt)

 - [x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
[ls-nvidia-toolkit.txt](https://github.com/NVIDIA/gpu-operator/files/5520541/ls-nvidia-toolkit.txt)

 - [x] NVIDIA driver directory: `ls -la /run/nvidia/driver`
[ls-nvidia-driver.txt](https://github.com/NVIDIA/gpu-operator/files/5520539/ls-nvidia-driver.txt)

 - [x] kubelet logs `journalctl -u kubelet > kubelet.logs`
[journal-kubelet.txt](https://github.com/NVIDIA/gpu-operator/files/5520538/journal-kubelet.txt)

**Comment by shivamerla** [comment]
@danniel1205 did you override any of the default params in values.yaml? Can you confirm you have installed 450.80.02 driver by describing driver pod?

**Comment by danniel1205** [comment]
I did not override any default params.

And seems the 450.80.02 driver is listed there:

```
 ~/tmp/gpu-test  kubectl describe pod nvidia-driver-daemonset-9htx4 -n gpu-operator-resources
Name:         nvidia-driver-daemonset-9htx4
Namespace:    gpu-operator-resources
Priority:     0
Node:         ip-10-0-1-246.us-west-2.compute.internal/10.0.1.246
Start Time:   Tue, 10 Nov 2020 13:37:43 -0800
Labels:       app=nvidia-driver-daemonset
              controller-revision-hash=8494dc97d8
              pod-template-generation=1
Annotations:  scheduler.alpha.kubernetes.io/critical-pod:
Status:       Running
IP:           10.0.1.246
IPs:
  IP:           10.0.1.246
Controlled By:  DaemonSet/nvidia-driver-daemonset
Containers:
  nvidia-driver-ctr:
    Container ID:  containerd://c6168287dcefa1bcdc777b2bcdbec6f027fa12155439feaba5c46fbfcbbba323
    Image:         nvcr.io/nvidia/driver:450.80.02-ubuntu20.04
    Image ID:      nvcr.io/nvidia/driver@sha256:7e281f0521ce3e14b53b19a03e45bcdbb46eba713d3dc025debe015e6908b9cb
    Port:          <none>
    Host Port:     <none>
    Command:
      nvidia-driver
    Args:
      init
    State:          Running
      Started:      Tue, 10 Nov 2020 13:37:43 -0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/containers/oci/hooks.d from config (rw)
      /run/nvidia from run-nvidia (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nvidia-driver-token-wbj79 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  run-nvidia:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      nvidia-driver
    Optional:  false
  nvidia-driver-token-wbj79:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nvidia-driver-token-wbj79
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  nvidia.com/gpu.present=true
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:          <none>
```

**Comment by shivamerla** [comment]
@danniel1205 With this driver installed, cuda sample should run. Can you try to delete and re-deploy the chart again to see if the issue is persistent?

**Comment by danniel1205** [comment]
I performed the following steps, however the issue is still persist:
- `helm uninstall` the gpu operator
- `sudo systemctl restart docker` on all nodes
- `helm install --wait --generate-name --set nfd.enabled=false nvidia/gpu-operator`

**Comment by shivamerla** [comment]
@danniel1205 we will try to repro and debug this. Meanwhile can you try with different validation image and confirm? ``` helm install --wait --generate-name --set nfd.enabled=false --set operator.validator.repository=nvidia --set operator.validator.image=samples --set operator.validator.version=cuda10.2-vectorAdd nvidia/gpu-operator```

**Comment by danniel1205** [comment]
@shivamerla, thanks for the quick reply. 

Do we currently only support `docker` and `crio` as container runtime ? I just realized that one of my environments is using `containerd`

**Comment by shivamerla** [comment]
ah, we are yet to add containerd support, and its currently in the works.

**Comment by shivamerla** [comment]
`containerd` support is added from v1.4.0. Please refer to documentation for specific settings to pass for `containerd` : https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#install-nvidia-gpu-operator

**Comment by mannusillegal** [comment]
We are facing the same issue in gpu server g4dn-xlarge with aws linux image. This server is a part of the kuberenetes cluster but unable to use the GPU in our deployment , pod is in pending state and after that we have describe the node, GPU's are not visible but we are able to run the nvidia-smi after login inside the server. So far i have followed all the steps mention here - https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

Any suggestions would be appreciated!
