### ISSUE TITLE
state-device-plugin-validation schedules on wrong node in multi-node cluster

### ISSUE THREAD

**Issue by zzh8829** [NVIDIA/gpu-operator#101]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

We noticed state-device-plugin-validation pod could schedule on the wrong node in a multi-node cluster

### 2. Steps to reproduce the issue

1. spin up one gpu node A and wait for it to become ready
2. spin up another gpu node B
3. if node A is not being used, state-device-plugin-validation from node B could be scheduled on node A and then report gpu status for the wrong node
4. both node A, B are ready but B was never truly validated (both state-device-plugin-validation pods are shown completed on node A).

This normally doesn't cause any user-facing error since plugin-validation rarely notice failure.
However, this introduces a huge operation challenge for clusters equipped with autoscaler

autoscaling problem we saw:
1. the above process happens, state-device-plugin-validation pods are both on node A.
2. Some user gpu workload gets scheduled on node B, while node A remains unused.
3. Cluster autoscaler scale down node A due to inactivity. Both state-device-plugin-validation for A and B gets removed
5. gpu-operator notices node B's plugin-validation no longer exist and tries to recreate it, node B cannot fit plugin-validation pod because it's used by user workload
6. autoscaler gets in to infinite scale-up -> scale-down loop because from this point on node B will always have broken state until the user workload gets removed.
 

 could fix this by adding podAffinity to validation pods or make it a daemonset.

**Comment by shivamerla** [comment]
@zzh8829 I think you meant device-plugin-validation and driver-validation pods both running on same node. With 1.5.1 driver-validation pod has been moved as initContainer within other Daemonset pods that depend on driver to be loaded. device-plugin validation is still a single pod as it validates if k8s scheduler can schedule this onto GPU node with resource request.

```
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
```

We don't have an easy mechanism to trigger enough pods to ensure that K8s scheduler will cover all GPU nodes through resource requests.

**Comment by zzh8829** [comment]
I'm not sure if that fix it, the problem is device-plugin-validation doesn't always run on every node. I think the easiest way to do it is thru node-selector assignment in the gpu controller

**Comment by kpouget** [comment]
I'm not sure to understand what is going wrong exactly, could you please try to clarify?

> We noticed state-device-plugin-validation pod could schedule on the wrong node in a multi-node cluster

this Pod should never end-up on a non-GPU node because of this constraint:
```
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
```
It may fail to be scheduled if no GPU is available, but that's different. Could you get the logs of the `nvidia-device-plugin-validation` and the description `kubectl describe pod/nvidia-device-plugin-validation`?

> I'm not sure if that fix it, the problem is device-plugin-validation doesn't always run on every node.

this Pod is mostly an internal validation of the good deployment of the previous step, it has no impact on the external services, so it doesn't matter that if it runs on a given node or not

> could fix this by adding podAffinity to validation pods or *make it a daemonset.*

just FYI, it's not possible to make it a DaemonSet, because DaemonSet Pods are expected to be always running, while this one completes to indicate success (that could be worked around though, of course)

**Comment by shivamerla** [comment]
@zzh8829 Starting with `v1.7.0` plugin validation pods are run on each GPU node. Please try it out and re-open this if you don't see any issue.

**Comment by zzh8829** [comment]
> @zzh8829 Starting with `v1.7.0` plugin validation pods are run on each GPU node with nodeSelector of each node name. Please try it out and re-open this if you don't see any issue.

thanks that should fix the issue!
