### ISSUE TITLE
nvidia-driver-validation pod tolerations are not configurable

### ISSUE THREAD

**Issue by borremosch** [NVIDIA/gpu-operator#102]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

I have got the GPU operator running just fine. I have updated the taints that are applied to the nodes running GPU loads, because I need to differentiate between several GPU node types. I was able to change the tolerations on all of the GPU operator pods, except the driver validation pod. I have simply not found any configuration that allows me to change it. The pods therefore stay in `Pending` state indefinitely.

### 2. Steps to reproduce the issue

Attempt to change the tolerations on the driver validation pod.

**Comment by shivamerla** [comment]
@borremosch nvidia-driver-validation container is moved as initContainers within other Daemonsets now. So, the issue you have outlined should be resolved with next gpu-operator update: https://github.com/NVIDIA/gpu-operator/commit/c937c68a5f8469cdedea4c78fc8d681ad5d7c62c
