### ISSUE TITLE
Disconnected operator capabilities

### ISSUE THREAD

**Issue by geoberle** [NVIDIA/gpu-operator#103]
Since we run several disconnected Openshift GPU Clusters it would be very important to have disconnected install and update capabilities for the GPU operator. There is documentation on how an operator must reference all used images in the operator clusterserviceversion (relatedImages) and reference all images via digest instead of tags.

See https://docs.openshift.com/container-platform/4.6/operators/admin/olm-restricted-networks.html

**Comment by shivamerla** [comment]
@geoberle gpu-operator supported on disconnected installs is targeted for early December. Meanwhile you would need to build private gpu-operator image and install using helm.

**Comment by geoberle** [comment]
december sounds great. thank you very much for your efforts!

**Comment by shivamerla** [comment]
1.4.0 published to RH catalog supports disconnected installs.
