### ISSUE TITLE
Stucking into init or crashbackoff status on some pods (nvidia-cuda-validator and nvidia-operator-validator)

### ISSUE THREAD

**Issue by thsmfe001** [NVIDIA/gpu-operator#1043]
I faced with gpu operator validator crashbackoff after installing gpu operator.
I installed 24.3.0 and 24.6.2 for gpu operator version but the issue was same.
The situation was that nvidia-cuda-validator and nvidia-operator-validator put into init or crashbackoff status.

When i check init container of nvidia-cuda-validator (cuda-validation) i saw below messages.

"Failed to allocate device vector A (error code system not yet initialized)! [Vector addition of 5000 elements]

In spite of validation issue i could assign gpu resource to pods but it couldn't work properly with nccl like tool using cuda.

kubectl get pdo -n gpu-operator

poc01@poc01:~$ kubectl get po -n gpu-operator

NAME                                                          READY   STATUS       RESTARTS        AGE

gpu-feature-discovery-dzmlj                                   1/1     Running      0               15m

gpu-feature-discovery-pwks6                                   1/1     Running      0               15m

gpu-feature-discovery-q992c                                   1/1     Running      0               15m

gpu-feature-discovery-qzsm4                                   1/1     Running      0               15m

gpu-operator-7bbf8bb6b7-9tw4v                                 1/1     Running      0               15m

gpu-operator-node-feature-discovery-gc-79d6d968bb-rc76k       1/1     Running      0               15m

gpu-operator-node-feature-discovery-master-6d9f8d497c-6k5xh   1/1     Running      0               15m

gpu-operator-node-feature-discovery-worker-96kkr              1/1     Running      0               15m

gpu-operator-node-feature-discovery-worker-qzr4n              1/1     Running      0               15m

gpu-operator-node-feature-discovery-worker-rv9zl              1/1     Running      0               15m

gpu-operator-node-feature-discovery-worker-tzcdq              1/1     Running      0               15m

nvidia-container-toolkit-daemonset-bcjvs                      1/1     Running      0               15m

nvidia-container-toolkit-daemonset-ght4t                      1/1     Running      0               15m

nvidia-container-toolkit-daemonset-l2d4q                      1/1     Running      0               15m

nvidia-container-toolkit-daemonset-vh8vf                      1/1     Running      0               15m

nvidia-cuda-validator-7c679                                   0/1     Init:0/1     4 (60s ago)     3m45s

nvidia-cuda-validator-b8g9c                                   0/1     Init:0/1     4 (62s ago)     3m45s

nvidia-cuda-validator-mrdx2                                   0/1     Init:0/1     4 (70s ago)     3m52s

nvidia-cuda-validator-v648k                                   0/1     Init:Error   4 (80s ago)     4m1s

nvidia-dcgm-exporter-2f8vc                                    1/1     Running      0               15m

nvidia-dcgm-exporter-dtq4t                                    1/1     Running      0               15m

nvidia-dcgm-exporter-np86c                                    1/1     Running      0               15m

nvidia-dcgm-exporter-rk85x                                    1/1     Running      0               15m

nvidia-device-plugin-daemonset-6fmpf                          1/1     Running      0               15m

nvidia-device-plugin-daemonset-b87ks                          1/1     Running      0               15m

nvidia-device-plugin-daemonset-n7qvm                          1/1     Running      0               15m

nvidia-device-plugin-daemonset-vbdcn                          1/1     Running      0               15m

nvidia-mig-manager-hc9rj                                      1/1     Running      0               15m

nvidia-mig-manager-vqwdt                                      1/1     Running      0               15m

nvidia-mig-manager-x5wzd                                      1/1     Running      0               15m

nvidia-mig-manager-xbvjm                                      1/1     Running      0               15m

nvidia-operator-validator-6fmwb                               0/1     Init:2/4     2 (3m58s ago)   15m

nvidia-operator-validator-j2dx9                               0/1     Init:2/4     2 (4m9s ago)    15m

nvidia-operator-validator-jfxnd                               0/1     Init:2/4     2 (4m16s ago)   15m

nvidia-operator-validator-lswn4                               0/1     Init:2/4     2 (4m ago)      15m

kubectl describe node -A | grep nvidia.com/cuda

poc01@poc01:~$ kubectl describe node -A | grep nvidia.com/cuda

                    nvidia.com/cuda.driver-version.full=550.54.15

                    nvidia.com/cuda.driver-version.major=550

                    nvidia.com/cuda.driver-version.minor=54

                    nvidia.com/cuda.driver-version.revision=15

                    nvidia.com/cuda.driver.major=550

                    nvidia.com/cuda.driver.minor=54

                    nvidia.com/cuda.driver.rev=15

                    nvidia.com/cuda.runtime-version.full=12.4

                    nvidia.com/cuda.runtime-version.major=12

                    nvidia.com/cuda.runtime-version.minor=4

                    nvidia.com/cuda.runtime.major=12

                    nvidia.com/cuda.runtime.minor=4

                    nvidia.com/cuda.driver-version.full=550.54.15

                    nvidia.com/cuda.driver-version.major=550

                    nvidia.com/cuda.driver-version.minor=54

                    nvidia.com/cuda.driver-version.revision=15

                    nvidia.com/cuda.driver.major=550

                    nvidia.com/cuda.driver.minor=54

                    nvidia.com/cuda.driver.rev=15

                    nvidia.com/cuda.runtime-version.full=12.4

                    nvidia.com/cuda.runtime-version.major=12

                    nvidia.com/cuda.runtime-version.minor=4

                    nvidia.com/cuda.runtime.major=12

                    nvidia.com/cuda.runtime.minor=4

                    nvidia.com/cuda.driver-version.full=550.54.15

                    nvidia.com/cuda.driver-version.major=550

                    nvidia.com/cuda.driver-version.minor=54

                    nvidia.com/cuda.driver-version.revision=15

                    nvidia.com/cuda.driver.major=550

                    nvidia.com/cuda.driver.minor=54

                    nvidia.com/cuda.driver.rev=15

                    nvidia.com/cuda.runtime-version.full=12.4

                    nvidia.com/cuda.runtime-version.major=12

                    nvidia.com/cuda.runtime-version.minor=4

                    nvidia.com/cuda.runtime.major=12

                    nvidia.com/cuda.runtime.minor=4

                    nvidia.com/cuda.driver-version.full=560.35.03

                    nvidia.com/cuda.driver-version.major=560

                    nvidia.com/cuda.driver-version.minor=35

                    nvidia.com/cuda.driver-version.revision=03

                    nvidia.com/cuda.driver.major=560

                    nvidia.com/cuda.driver.minor=35

                    nvidia.com/cuda.driver.rev=03

                    nvidia.com/cuda.runtime-version.full=12.6

                    nvidia.com/cuda.runtime-version.major=12

                    nvidia.com/cuda.runtime-version.minor=6

                    nvidia.com/cuda.runtime.major=12

                    nvidia.com/cuda.runtime.minor=6

 +-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          Off |   00000000:19:00.0 Off |                    0 |
| N/A   37C    P0            115W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          Off |   00000000:3B:00.0 Off |                    0 |
| N/A   34C    P0            116W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          Off |   00000000:4C:00.0 Off |                    0 |
| N/A   33C    P0             72W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          Off |   00000000:5D:00.0 Off |                    0 |
| N/A   35C    P0             69W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          Off |   00000000:9B:00.0 Off |                    0 |
| N/A   36C    P0             72W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          Off |   00000000:BB:00.0 Off |                    0 |
| N/A   34C    P0             70W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          Off |   00000000:CB:00.0 Off |                    0 |
| N/A   36C    P0             71W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          Off |   00000000:DB:00.0 Off |                    0 |
| N/A   33C    P0             70W /  700W |       0MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

**Comment by thsmfe001** [comment]
I just resolved this issue to meet fabric manager's compatibility with cuda version.
Thank you.

**Comment by gss2002** [comment]
How did you resolve this with fabricmanager. Running into similar issue

**Comment by thsmfe001** [comment]
> How did you resolve this with fabricmanager. Running into similar issue

As you know nvidia-fabricmanager  supports nvswitch for intra communication among gpus on a host.
In case of a system with nvswitch you should check if fabricmanager is installed or not.
"systemctl status nvidia-fabricmanager"
Without installing fabricmanager you could faced with gpu operator validator issue.

**Comment by jiangxiaobin96** [comment]
> > How did you resolve this with fabricmanager. Running into similar issue
> 
> As you know nvidia-fabricmanager supports nvswitch for intra communication among gpus on a host. In case of a system with nvswitch you should check if fabricmanager is installed or not. "systemctl status nvidia-fabricmanager" Without installing fabricmanager you could faced with gpu operator validator issue.

I met the same problem, but my system has no nvswitch and when I install nvidia-fabricmanager, it presents error `request to query NVSwitch device information from NVSwitch driver failed with error:WARNING Nothing to do`
