### ISSUE TITLE
Missing GFD labels

### ISSUE THREAD

**Issue by eachirei** [NVIDIA/gpu-operator#106]
Just installed version 1.3.0 of the operator. Besides having to delete the old release and restarting some docker services the upgrade went smoothly. Great work!

But the GFD labels were missing from the cluster nodes. Checking logs I found the following error message:

```2020/11/24 09:15:59 Namespace 'nvidia.com' is not allowed. Ignoring label 'nvidia.com/cuda.runtime.major'```

Fix: Add `--extra-label-ns=nvidia.com` to the args property of the NFD master deployment.

**Comment by klueska** [comment]
Yes. This is a known issue and the fix is already merged for the next release:
https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/141
