### ISSUE TITLE
Monitoring ?

### ISSUE THREAD

**Issue by jrabary** [NVIDIA/gpu-operator#11]
Can we do monitoring as well this `gpu-operator` ? Is it possible to integrate it with an existing prometheus installation ?

**Comment by RenaudWasTaken** [comment]
Hello!

This will be part of the next release of the GPU Operator :) !

**Comment by tamaramiteva** [comment]
Hello, when will be the next release? Thanks!

**Comment by nvjmayo** [comment]
Data Center GPU Manager (DCGM) is part of the [1.0.0 release](https://github.com/NVIDIA/gpu-operator#changelog-for-v100). For more information see [DCGM](https://developer.nvidia.com/dcgm)
