### ISSUE TITLE
nvidia-driver-daemonset kernel header installation issue on Openshift 4.6

### ISSUE THREAD

**Issue by geoberle** [NVIDIA/gpu-operator#110]
When i'm installing the GPU operator 1.3.1 on Openshift 4.6.4, the nvidia-driver-daemonset pods crash with an error during the linux kernel-header installation.

This is not a build entitlement issue, we followed guides to enable entitled builds on all nodes and they work fine for other things. You can also see that the Redhat repos can be queried up to a certain point.

The nodes are running Red Hat Enterprise Linux CoreOS 46.82.202011061621-0
uname -a
Linux XXXXXX 4.18.0-193.29.1.el8_2.x86_64 #1 SMP Thu Oct 22 10:09:53 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Here is the complete log of one of the pods

+ set -eu
+ RUN_DIR=/run/nvidia
+ PID_FILE=/run/nvidia/nvidia-driver.pid
+ DRIVER_VERSION=450.80.02
+ KERNEL_UPDATE_HOOK=/run/kernel/postinst.d/update-nvidia-driver
+ '[' 1 -eq 0 ']'
+ command=init
+ shift
+ case "${command}" in
++ getopt -l accept-license -o a --
+ options=' --'
+ '[' 0 -ne 0 ']'
+ eval set -- ' --'
++ set -- --
+ ACCEPT_LICENSE=
++ uname -r
+ KERNEL_VERSION=4.18.0-193.29.1.el8_2.x86_64
+ PRIVATE_KEY=
+ PACKAGE_TAG=
+ for opt in ${options}
+ case "$opt" in
+ shift
+ break
+ '[' 0 -ne 0 ']'
+ init
+ echo -e '\n========== NVIDIA Software Installer ==========\n'

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 450.80.02 for Linux kernel version 4.18.0-193.29.1.el8_2.x86_64

+ echo -e 'Starting installation of NVIDIA driver version 450.80.02 for Linux kernel version 4.18.0-193.29.1.el8_2.x86_64\n'
+ exec
+ flock -n 3
+ echo 86066
+ trap 'echo '\''Caught signal'\''; exit 1' HUP INT QUIT PIPE TERM
+ trap _shutdown EXIT
+ _unload_driver
+ rmmod_args=()
+ local rmmod_args
+ local nvidia_deps=0
+ local nvidia_refs=0
+ local nvidia_uvm_refs=0
+ local nvidia_modeset_refs=0
Stopping NVIDIA persistence daemon...
+ echo 'Stopping NVIDIA persistence daemon...'
+ '[' -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ']'
Unloading NVIDIA driver kernel modules...
+ echo 'Unloading NVIDIA driver kernel modules...'
+ '[' -f /sys/module/nvidia_modeset/refcnt ']'
+ '[' -f /sys/module/nvidia_uvm/refcnt ']'
+ '[' -f /sys/module/nvidia/refcnt ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
Unmounting NVIDIA driver rootfs...
+ return 0
+ _unmount_rootfs
+ echo 'Unmounting NVIDIA driver rootfs...'
+ findmnt -r -o TARGET
+ grep /run/nvidia/driver
+ _kernel_requires_package
+ local proc_mount_arg=
+ echo 'Checking NVIDIA driver packages...'
Checking NVIDIA driver packages...
+ [[ ! -d /usr/src/nvidia-450.80.02/kernel ]]
+ cd /usr/src/nvidia-450.80.02/kernel
+ proc_mount_arg='--proc-mount-point /lib/modules/4.18.0-193.29.1.el8_2.x86_64/proc'
++ ls -d -1 'precompiled/**'
+ return 0
+ _update_package_cache
+ '[' '' '!=' builtin ']'
+ echo 'Updating the package cache...'
Updating the package cache...
+ yum -q makecache
+ _install_prerequisites
++ mktemp -d
+ local tmp_dir=/tmp/tmp.HEKbBQg5qM
+ trap 'rm -rf /tmp/tmp.HEKbBQg5qM' EXIT
+ cd /tmp/tmp.HEKbBQg5qM
+ echo 'Installing elfutils...'
Installing elfutils...
+ dnf install -q -y elfutils-libelf.x86_64 elfutils-libelf-devel.x86_64
+ rm -rf /lib/modules/4.18.0-193.29.1.el8_2.x86_64
+ mkdir -p /lib/modules/4.18.0-193.29.1.el8_2.x86_64/proc
Enabling RHOCP and EUS RPM repos...
+ echo 'Enabling RHOCP and EUS RPM repos...'
+ dnf config-manager --set-enabled rhocp-4.6-for-rhel-8-x86_64-rpms
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
+ dnf makecache --releasever=8.2
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Red Hat Enterprise Linux 8 for x86_64 - AppStre  16 MB/s |  19 MB     00:01    
Red Hat OpenShift Container Platform 4.6 for RH 2.1 MB/s | 1.9 MB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   19 MB/s |  22 MB     00:01    
Red Hat Universal Base Image 8 (RPMs) - BaseOS  176 kB/s | 3.8 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre 206 kB/s | 4.2 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea 208 kB/s | 3.8 kB     00:00    
Metadata cache created.
+ dnf config-manager --set-enabled rhel-8-for-x86_64-baseos-eus-rpms
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Error: No matching repo to modify: rhel-8-for-x86_64-baseos-eus-rpms.
+ true
+ dnf makecache --releasever=8.2
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Red Hat Enterprise Linux 8 for x86_64 - AppStre  14 kB/s | 4.5 kB     00:00    
Red Hat OpenShift Container Platform 4.6 for RH  13 kB/s | 4.1 kB     00:00    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   12 kB/s | 4.1 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - BaseOS  203 kB/s | 3.8 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre 219 kB/s | 4.2 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea 198 kB/s | 3.8 kB     00:00    
Metadata cache created.
Installing Linux kernel headers...
+ echo 'Installing Linux kernel headers...'
+ dnf -q -y --releasever=8.2 install kernel-headers-4.18.0-193.29.1.el8_2.x86_64 kernel-devel-4.18.0-193.29.1.el8_2.x86_64
Error: Unable to find a match: kernel-headers-4.18.0-193.29.1.el8_2.x86_64 kernel-devel-4.18.0-193.29.1.el8_2.x86_64
++ rm -rf /tmp/tmp.HEKbBQg5qM
+ _shutdown
+ _unload_driver
+ rmmod_args=()
+ local rmmod_args
+ local nvidia_deps=0
+ local nvidia_refs=0
+ local nvidia_uvm_refs=0
+ local nvidia_modeset_refs=0
Stopping NVIDIA persistence daemon...
+ echo 'Stopping NVIDIA persistence daemon...'
+ '[' -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ']'
Unloading NVIDIA driver kernel modules...
+ echo 'Unloading NVIDIA driver kernel modules...'
+ '[' -f /sys/module/nvidia_modeset/refcnt ']'
+ '[' -f /sys/module/nvidia_uvm/refcnt ']'
+ '[' -f /sys/module/nvidia/refcnt ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ '[' 0 -gt 0 ']'
+ return 0
+ _unmount_rootfs
+ echo 'Unmounting NVIDIA driver rootfs...'
Unmounting NVIDIA driver rootfs...
+ findmnt -r -o TARGET
+ grep /run/nvidia/driver
+ rm -f /run/nvidia/nvidia-driver.pid /run/kernel/postinst.d/update-nvidia-driver
+ return 0

**Comment by geoberle** [comment]
Here is the yaml of the nvidia-driver-daemonset generated by the operator

kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    deprecated.daemonset.template.generation: '1'
    openshift.io/scc: nvidia-driver
  name: nvidia-driver-daemonset
  labels:
    app: nvidia-driver-daemonset
spec:
  selector:
    matchLabels:
      app: nvidia-driver-daemonset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nvidia-driver-daemonset
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        nvidia.com/gpu.present: 'true'
      restartPolicy: Always
      serviceAccountName: nvidia-driver
      hostPID: true
      schedulerName: default-scheduler
      hostNetwork: true
      affinity: {}
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: nvidia-driver-ctr
          command:
            - nvidia-driver
          env:
            - name: RHEL_VERSION
              value: '8.2'
            - name: OPENSHIFT_VERSION
              value: '4.6'
          securityContext:
            privileged: true
            seLinuxOptions:
              level: s0
          imagePullPolicy: Always
          volumeMounts:
            - name: run-nvidia
              mountPath: /run/nvidia
              mountPropagation: Bidirectional
            - name: config
              mountPath: /etc/containers/oci/hooks.d
          terminationMessagePolicy: File
          image: 'nvcr.io/nvidia/driver:450.80.02-rhcos4.6'
          args:
            - init
      serviceAccount: nvidia-driver
      volumes:
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: ''
        - name: config
          configMap:
            name: nvidia-driver
            items:
              - key: oci-nvidia-hook-json
                path: oci-nvidia-hook.json
            defaultMode: 420
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10

**Comment by shivamerla** [comment]
@zvonkok @ArangoGutierrez Can you please check if this version is missing in RHCOS/EUS repos?

**Comment by ArangoGutierrez** [comment]
Does your entitlement have EUS enabled?

**Comment by geoberle** [comment]
I'm not sure. I basically just use a regular entitlement that comes from enabling an openshift subscription.
I will have a look and will come back with my findings. Thanks for the hint!

**Comment by geoberle** [comment]
Just found out about EUS. This is the extended update support option from Redhat. I'm not sure we have access to this and need to find out with the redhat support.

But i'm puzzled why i would need to have access to such a repository when my operating system is actually the latest version available.

**Comment by zvonkok** [comment]
The `29.1` is definitely in the EUS repository. 
```
$ yum config-manager --set-enabled rhel-8-for-x86_64-baseos-eus-rpms
$ yum  info kernel-devel-4.18.0-193.29.1.el8_2.x86_64 --releasever=8.2
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Last metadata expiration check: 0:01:19 ago on Mon Nov 23 10:50:06 2020.
Available Packages
Name         : kernel-devel
Version      : 4.18.0
Release      : 193.29.1.el8_2
Architecture : x86_64
Size         : 15 M
Source       : kernel-4.18.0-193.29.1.el8_2.src.rpm
Repository   : rhel-8-for-x86_64-baseos-eus-rpms
Summary      : Development package for building kernel modules to match the kernel
URL          : http://www.kernel.org/
License      : GPLv2 and Redistributable, no modification permitted
Description  : This package provides kernel headers and makefiles sufficient to build modules
             : against the kernel package.```

@shivamerla @ArangoGutierrez I see that we need more logic on enabling the repositories. The dnf makecache does not fail if there is no repository, which is weird.  

```
Error: No matching repo to modify: rhel-8-for-x86_64-baseos-eus-rpms.
```

@geoberle The EUS is separate from the default OpenShift entitlement. You need another SKU to have EUS in 4.6 enabled.

**Comment by zvonkok** [comment]
@shivamerla @ArangoGutierrez I think we can leave it as is. It will fail if the entitlement is not right anyway. If the customer has entitlement it will work.

**Comment by geoberle** [comment]
Having a separate premium SKU on top of the regular Openshift one is somehow suboptimal just to be able to install a GPU driver.
Am i assuming correct that this is an implication because the packages you require are only available in the EUS repos?

**Comment by shivamerla** [comment]
@geoberle closing this one as expected. Please re-open if you think we need further action items from RedHat on entitlement requirements.

**Comment by geoberle** [comment]
I will highlight this with our Redhat Technical Account Manager. The required RPMs should be made available in non EUS repos because running GPU workloads is not supposed to be a premium feature. and should work with standard SKUs.  this is most likely a political thing and i will keep you posted about the progress.
