### ISSUE TITLE
GPU Operator issues a huge mount of logging message after rebooting nodes

### ISSUE THREAD

**Issue by shirotori-east** [NVIDIA/gpu-operator#111]
After rebooting master and worker nodes, a lot of logging messages (more than 100 million) has been issued by GPU Operator and compressed a storage space for Elasticsearch. And I was able to see three types of messages, "+ wait", "+ continue" and "+ true" in the logging files. 
Since I would like to control output of these messages, could you let me know how to stop (or reduce) these message? Or could you fix this if it is a degradation? 

My environment is as follows, 

* OCP: 4.4.3（CoreOS is 44.81.202004260825-0 (Ootpa)）
* Kubernetes: v1.17.1
* CRIO: cri-o://1.17.4-8.dev.rhaos4.4.git5f5c5e4.el8
* NVIDIA-Operator: 1.1.7-r2

The amount of messages and the actual messages are as follows, 
```
# grep "^Oct 28" messages-20201029 | grep "+ wait" | wc; grep "^Oct 28" messages-20201029 | grep "+ continue" | wc; grep "^Oct 28" messages-20201029 | grep "+ true" | wc**

141854084 1560394924 29080106924

141853036 1418530360 28796166308

141854226 1418542260 28229011514
```

(1) Message with "+ wait"
```
# grep "^Oct 28" messages-20201029 | grep "+ wait" | head

Oct 28 07:18:39 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-container-toolkit-ctr, pod_name=nvidia-container-toolkit-daemonset-bqv8c, message=+ wait 4025

Oct 28 07:18:39 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-container-toolkit-ctr, pod_name=nvidia-container-toolkit-daemonset-bqv8c, message=+ wait 4025

Oct 28 07:18:39 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-container-toolkit-ctr, pod_name=nvidia-container-toolkit-daemonset-bqv8c, message=+ wait 4025
```

(2) Message with "+ continue"
```
# grep "^Oct 28" messages-20201029 | grep "+ continue" | head

Oct 28 07:18:47 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-driver-ctr, pod_name=nvidia-driver-daemonset-zc9zs, message=+ continue

Oct 28 07:18:47 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-driver-ctr, pod_name=nvidia-driver-daemonset-zc9zs, message=+ continue

Oct 28 07:18:47 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-driver-ctr, pod_name=nvidia-driver-daemonset-zc9zs, message=+ continue
```

(3) Message with "+ true"
```
# grep "^Oct 28" messages-20201029 | grep "+ true" | head

Oct 28 07:18:39 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-container-toolkit-ctr, pod_name=nvidia-container-toolkit-daemonset-bqv8c, message=+ true

Oct 28 07:18:39 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-container-toolkit-ctr, pod_name=nvidia-container-toolkit-daemonset-bqv8c, message=+ true

Oct 28 07:18:39 e13sinjuk-ivwn901000 kubernetes.var.log.containers.nv: namespace_name=gpu-operator-resources, container_name=nvidia-container-toolkit-ctr, pod_name=nvidia-container-toolkit-daemonset-bqv8c, message=+ true
```

**Comment by shivamerla** [comment]
@shirotori-east If any of the gpu-operator managed pods are not running fine, then it will indefinitely continue to fetch their latest status after every fixed interval. On node reboot, sometimes toolkit container can start first and cause driver pods to fail as nvidia runtime will not work without drivers loaded. In those cases, we recommend to un-install and install ClusterPolicy instance again. We are working on handling node reboot scenarios better in future release.

**Comment by shirotori-east** [comment]
@shivamerla Thank you for your answer. 
I understand that the many logs indicate the situation you mentions `cause driver pods to fail`, am I correct?

**Comment by kpouget** [comment]
@shivamerla I found an issue with the handling of the list of states known by the GPU-operator, 
which makes the number of states very large. 
I guess this is related to this issue, I'll share a patch as soon as it's finalized

**Comment by shivamerla** [comment]
@shirotori-east @kpouget This has been fixed with 1.5.0. Now operator pods will start in correct order to avoid getting into RunTimeConfig error and huge amount of logging due to reconciliation.

**Comment by kpouget** [comment]
I pushed a PR related to this issue (too late for the release, sorry ...)

https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/162/

what I observed is that the number of states the GPU operator was deploying was increasing at each iteration of the operator reconciliation loop, thus potentially logging a huge quantity of messages when the deployment is finished.

**Comment by shivamerla** [comment]
> @shivamerla I found an issue with the handling of the list of states known by the GPU-operator,
> which makes the number of states very large.
> I guess this is related to this issue, I'll share a patch as soon as it's finalized

Thanks @kpouget. The fix is merged. With 1.5.0 since pods will not get into crash loop due to correct ordering, chances of repeated reconciliation are less, so we are in better shape.
