### ISSUE TITLE
[Feature] Support a custom e2e validation

### ISSUE THREAD

**Issue by changhyuni** [NVIDIA/gpu-operator#1117]
## Issue or feature description
I sometimes elastically manage GPU nodes to save costs, creating and deleting them as needed. It would be helpful to have a validation feature that assigns a GPU to a real pod to ensure it functions correctly when a node is provisioned and validated.

## Questions:
Is this possible? If enabled, after all the basic validations pass, the nvidia-operator could taint the node, deploy a pod (e.g., an application called e2e-check), and assign the GPU to perform a specific task, such as a basic inference or any workload utilizing the GPU. If the gpu operate good, the taint would be removed from the node.

Or, is there an existing method that currently supports this? I could implement it myself, but it would be good if a validation feature like this could be added to the nvidia-operator.

**Comment by Hexoplon** [comment]
The gpu-operator-validator component supports perforing cuda validation by running a workload, by setting the WITH_WORKLOAD env variable to "true". This might help with what you are looking for, the values is listed in the default helm chart values file

**Comment by changhyuni** [comment]
Thanks for your comment, @Hexoplon!
If we set the WITH_WORKLOAD environment variable to "true", can you explain how it functions? Does it only check if CUDA is installed, or does it perform additional validation tasks?

**Comment by changhyuni** [comment]
> Thanks for your comment, [@Hexoplon](https://github.com/Hexoplon)! If we set the WITH_WORKLOAD environment variable to "true", can you explain how it functions? Does it only check if CUDA is installed, or does it perform additional validation tasks?
I don't think this is the behavior I want
https://github.com/NVIDIA/gpu-operator/blob/ca1259c65bc349bca64b132535483ab2e2f37c54/validator/main.go#L1093
