### ISSUE TITLE
Nvidia GPU-Operator helm chart version does not reflect the branch tags

### ISSUE THREAD

**Issue by yonkatian** [NVIDIA/gpu-operator#1118]
Hi 

I was updating my GPU-operator from v23.9.0 to v24.6.x.
However when I further inspect the helm chart - mainly  "deployment/gpu-operator/Charts.yaml

I notice that the version is   "**v1.0.0-devel**"  instead of  "v24.6.x".  on all the v24 branch

Hence I wondering was it an oversight or is it as plan. If it is the former, would it be possible to get it patch ?

Thanks 

For reference:
![Image](https://github.com/user-attachments/assets/b798f2f7-b821-4463-9226-e9e1c2cdd6a9)

![Image](https://github.com/user-attachments/assets/813a0c54-1b09-4248-980a-09512a8d8190)

**Comment by cdesiniotis** [comment]
@yonkatian please get the released helm charts from NGC https://catalog.ngc.nvidia.com/orgs/nvidia/helm-charts/gpu-operator

**Comment by yonkatian** [comment]
Noted..  In future we will try to get al Nvidia helm chart from ngc if possible.
