### ISSUE TITLE
tolerations element isn't set to GPU related DaemonSet

### ISSUE THREAD

**Issue by shirotori-east** [NVIDIA/gpu-operator#112]
I tried to set `tolerations` to GPU related DaemonSet which had been installed via OpenShift OperatorHub but it wasn't reflected to YAML. So I think it may be a defect. 

How I configure `tolerations` is that, 
 1) OpenShift WebConsole Workloads > `Daemon Sets`
 2) Select target DaemonSet, 
 3) Click Tolerations in `Details` modify the content
 4) Click Save
But then `tolerations` was not set to YAML. 

What I would like to do is to set `tolerations` to GPU related DaemonSet. Though I have installed GPU Operator via OperatorHub, if I should install the operator via Helm to realize what I would like to do. 

For more information, `tolerations` that I would like to set are as follows, 

```
- key: "developerID"
     operator: "Exists"
     effect: "NoSchedule"
- key: "aipf-schedulable"
     operator: "Exists"
     effect: "NoSchedule" DaemonSet
```
 and target daemonsets are as follows, 
```
NAMESPACE                NAME
 gpu-operator-resources   nvidia-container-toolkit-daemonset
 gpu-operator-resources   nvidia-dcgm-exporter
 gpu-operator-resources   nvidia-device-plugin-daemonset
 gpu-operator-resources   nvidia-driver-daemonset
```

And, my environment is as follows, 
* OCP: 4.4.3（CoreOS is 44.81.202004260825-0 (Ootpa)）
* Kubernetes: v1.17.1
* CRIO: cri-o://1.17.4-8.dev.rhaos4.4.git5f5c5e4.el8
* NVIDIA-Operator: 1.1.7-r2

**Comment by shivamerla** [comment]
@shirotori-east Did you try setting tolerations while deploying operator itself through ClusterPolicy instance? In the UI when you try to create ClusterPolicy instance, you can expand each of these Daemonsets and add tolerations.

**Comment by shirotori-east** [comment]
@shivamerla, Thank you for your comment. 
I tried to set the parameters through ClusterPolicy instance but I didn't figure out how to set. 
Actually, I guess that I will modify and add tolerations setting into YAML when I create ClusterPolicy instance but I am not sure where and how I will insert tolerations. 
The following is the YAML I have seen on my environment. 

```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
 creationTimestamp: '2020-07-01T06:58:36Z'
 generation: 1
 labels:
 app.kubernetes.io/component: gpu-operator
 name: cluster-policy
 resourceVersion: '194395970'
 selfLink: /apis/nvidia.com/v1/clusterpolicies/cluster-policy
 uid: 154cfa30-5aec-42ba-b429-725c5bb82908
spec:
 dcgmExporter:
 image: dcgm-exporter
 repository: nvidia
 version: 1.7.2-2.0.0-rc.9-ubuntu18.04
 devicePlugin:
 image: k8s-device-plugin
 repository: nvidia
 version: 1.0.0-beta6
 driver:
 image: driver
 repository: nvidia
 version: 440.64.00
 operator:
 defaultRuntime: crio
 toolkit:
 image: container-toolkit
 repository: nvidia
 version: 1.0.2
status:
 state: ready
```

Thank you for your help in advance.

**Comment by shivamerla** [comment]
@shirotori-east What version of gpu-operator are you using? We have added tolerations support from v1.3.0 onwards. here are the snapshots of how to edit tolerations for each component of ClusterPolicy instance.
![Screen Shot 2020-12-04 at 8 48 44 AM](https://user-images.githubusercontent.com/30056107/101190799-c014de80-360d-11eb-8230-d2fbd8734578.png)

![Screen Shot 2020-12-04 at 8 48 30 AM](https://user-images.githubusercontent.com/30056107/101190827-c7d48300-360d-11eb-9953-73a30cd82aac.png)

**Comment by shirotori-east** [comment]
@shivamerla Thank you for your answer. 
Though I have been using `NVIDIA-Operator: 1.1.7-r2`, is there any method that allows me to configure `tolerations` using this version? Or do I have to upgrade to 1.3 or later?

**Comment by shivamerla** [comment]
@shirotori-east You would have to manually edit each Daemonset spec in `gpu-operator-resources` namespace using `oc edit` command. From support using UI, you need to update to 1.3.0 or later.

**Comment by shivamerla** [comment]
closing this one as expected. Please re-open if you think further action is required from our side.
