### ISSUE TITLE
Documentation: set operator.version in Helm charts

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#113]
Currently, [NVidia GPU-operator documentation](https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html#openshift-gpu-install-gpu-operator-via-helmv3) gives the following command to install the GPU operator on OpenShift:

```
$  helm install gpu-operator nvidia/gpu-operator --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=false,devicePlugin.version=v0.7.0-ubi8,dcgmExporter.version=2.0.13-2.1.0-ubi8,toolkit.version=1.3.0-ubi8 --wait
```

However, it can lead to deployment crashes when the command is used with the wrong GPU-operator version (ie, using an outdated command).

I would suggest setting the [GPU-operator version](https://github.com/NVIDIA/gpu-operator/blob/2caaf94/deployments/gpu-operator/values.yaml#L15) (`--set operator.version=1.4.0`) in the command-line, so that it works regardless of the current operator release:

```
$  helm install gpu-operator nvidia/gpu-operator --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=false,devicePlugin.version=v0.7.0-ubi8,dcgmExporter.version=2.0.13-2.1.0-ubi8,toolkit.version=1.3.0-ubi8,operator.version=1.4.0 --wait
```

**Comment by shivamerla** [comment]
@kpouget they we would need to keep updating this for every release. Generally latest gpu-operator version picked by default by helm should work. I know this came from the recent issue with device-plugin, but it will be addressed in a day or two.

**Comment by kpouget** [comment]
@shivamerla, that's not related to the device-plugin issue, but rather to observing people use an outdated command and struggling 

and with the current `helm install` command, you already have to update the documentation each time a container image is changed.

Another way to proceed is to specify the release tarball:
```
helm install --devel https://github.com/NVIDIA/gpu-operator/archive/1.4.0.tar.gz ...
```
but that doesn't change the problem, the version of the UBI8 images still have to be specified in the CLI ...

**Comment by kpouget** [comment]
and yet another solution would be to have an image flavor configuration bit, something like `--set operator.use_ubi=true` that would imply change replace `-ubuntu*` by `-ubi8` in the image tags/versions

**Comment by shivamerla** [comment]
@kpouget `-ubi8` tag is not consistent currently with all components. For example GFD doesn't have a `ubi-8` tag as we only have UBI based image for that. I plan to create a `values.yaml` specifically for OCP with each operator release. In the documentation this file can be used to deploy on OCP using help.
