### ISSUE TITLE
Wrong node pci labels when using NFD

### ISSUE THREAD

**Issue by AbdYsn** [NVIDIA/gpu-operator#114]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

Node labels added by the NFD have unexpected values for the pci.vendors labels

### 2. Steps to reproduce the issue

Deploy GPU operator 1.3 or higher using default helm chart values

### 3. nodes labels
                    ...
                    feature.node.kubernetes.io/pci-0300_102b.present=true
                    feature.node.kubernetes.io/pci-0302_10de.present=true
                    feature.node.kubernetes.io/pci-0302_10de.sriov.capable=true
                    ...
### 4. Expected Labels
                    ...
                    feature.node.kubernetes.io/pci-102b.present=true
                    feature.node.kubernetes.io/pci-10de.present=true
                    feature.node.kubernetes.io/pci-10de.sriov.capable=true
                    ...
### 5. cause
The node feature discovery values found at the [main chart](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml#L155-L159) use `worker.options` to configure the labels, but the node feature discovery [values](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/charts/node-feature-discovery/values.yaml#L43-L128) uses a `config` field to do that, which causes the node feature discovery to use its default values to label the nodes.

**Comment by adrianchiris** [comment]
Currently Network-Operator relies on `feature.node.kubernetes.io/pci-10de.present="true"` node label to deploy NV Peer memory driver similarly to GPU Operator assets up until V1.2.0.

we will change Network operator to use gpu-feature-discovery plugin generated label : `nvidia.com/gpu.present=true`

**Comment by shivamerla** [comment]
@AbdYsn Thanks for reporting this. Yes, with update to 2.0.0 of NFD these seem to have moved under config section. GPU operator is looking for any of below labels and adding 'nvidia.com/gpu.present=true' label. We will fix this with next gpu-operator helm release.

https://github.com/NVIDIA/gpu-operator/blob/master/pkg/controller/clusterpolicy/state_manager.go#L25

**Comment by shivamerla** [comment]
This is fixed with 1.5.0 version of operator.
