### ISSUE TITLE
The virtual machine was created  by kubevirt and the card was used, but the number of available allocations is still 1

### ISSUE THREAD

**Issue by xrwang8** [NVIDIA/gpu-operator#1141]
**What happened**:

I have a t4 card in my node, and a virtual machine has been started to occupy it, but the node shows that the number of allocable cards is still 1
![image](https://github.com/user-attachments/assets/b78c7ef1-693f-4d35-bc79-647a39bad094)
**What you expected to happen**:

![image](https://github.com/user-attachments/assets/0a7e290d-bf58-4df2-bc57-a19e925e5f48)

allocateable:
nvidia.com/TU104GL_TESLA T4:  0

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2
- Kubernetes version (use `kubectl version`): 1.28.1+k3s
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by chipzoller** [comment]
You're under the wrong impression as to the intended result. The value of allocatable will never change to be decremented based on the workloads.
