### ISSUE TITLE
GPU-Operator v1.3.0 dcgm-exporter persistent CrashLoopBackoff AND  “nvidia-nvswitch: Version mismatch, kernel version 450.80.02 user version 450.51.06” 

### ISSUE THREAD

**Issue by Gus-Gilliland** [NVIDIA/gpu-operator#115]
### 1. Quick Debug Checklist
- [18.04.5 ] Are you running on an Ubuntu 18.04 node?
- [v1.19.3 ] Are you running Kubernetes v1.13+?
- [v19.03.13 ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [Yes ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ Yes] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)
Name:   cluster-policy
Namespace:
Labels:       app.kubernetes.io/component=gpu-operator

### 1. Issue or feature description
Changes to the helm chart between Oct.22 and Nov.7 seem to have broken nvidia-dcgm-exporter.
Video of successful install (Oct.22) here: https://www.youtube.com/watch?v=U5NyieQrOpg
Simultaneous issues: (related? to be determined)
1. gpu-operator-resources pod/nvidia-dcgm-exporter persistent CrashLoopBackoff state
2. “nvidia-nvswitch: Version mismatch, kernel version 450.80.02 user version 450.51.06” error begins after GPU-Operator helm chart install.

System:
SuperMicro X9SRA Motherboard with Xeon E5-2650 CPU, and a P40 GPU  (no NVLink switch chip/hardware)
Host ubu18.04.5  running KVM , GPU pass-through to VM with Docker, K8s, Helm and NVIDIA GPU-Operator 
(18.04.5 VM successful install in video)
I've tried both ubu18.04.5 and ubu20.04.1 VMs  since Nov 7 and both fail with above errors.
![nvidia-nvswitch-Version mismatch-12-1-20](https://user-images.githubusercontent.com/75744281/101675664-bb8e6280-3a1f-11eb-8321-19c393c27a3d.jpg)

Questions raised:
Why is NVSwitch being installed? and trying to run when hardware isn't present? And as it keeps throwing “nvidia-nvswitch: Version mismatch, kernel version 450.80.02 user version 450.51.06” errors...  is it interfering with dcgm-exporter causing the persistent CrashLoopBackoff failures ?

### 2. Steps to reproduce the issue
Steps provided here:
[https://gus-gpu.gitlab.io/html/egx-on-vm.html#gpu-o](https://gus-gpu.gitlab.io/html/egx-on-vm.html#gpu-o)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Just went to reinstall and capture logs. Found version had switched from 1.3.0 to 1.4.0. 
New iInstall hung on gpu-operator-resources   pod/nvidia-driver-daemonset-pbtw9  0/1     CrashLoopBackOff (for 22minutes and counting.)
Will leave this for reference and post new issue for new version.

**Comment by hashio** [comment]
I resolved same problem
https://docs.nvidia.com/datacenter/tesla/hgx-software-guide/index.html#nscq

**Comment by Gus-Gilliland** [comment]
Circled back around to this install. Re-ran same install instructions with current (Apr 2021) GPU-Operator 1.6.2. Works flawlessly. Thanks for your hard work and perseverance team green!
