### ISSUE TITLE
GPU-Operator v1.4.0  pod/nvidia-driver-daemonset  0/1  CrashLoopBackOff  persistent

### ISSUE THREAD

**Issue by Gus-Gilliland** [NVIDIA/gpu-operator#116]
### 1. Quick Debug Checklist
- [ 20.04.1 ] Are you running on an Ubuntu 18.04 node?
- [ 1.20.0 ] Are you running Kubernetes v1.13+?
- [ 19.03.14 ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ Yes ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ Yes ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
pod/nvidia-driver-daemonset  0/1  CrashLoopBackOff  persistent
![nvidia-driver-daemonset](https://user-images.githubusercontent.com/75744281/101947342-ec080500-3bb5-11eb-845d-deff7b1682bb.jpg)

### 2. Steps to reproduce the issue
Located here in detail. [https://gus-gpu.gitlab.io/html/egx-on-vm-ubu20.html#gpu-o](https://gus-gpu.gitlab.io/html/egx-on-vm-ubu20.html#gpu-o
)  Helm GPU operator 1.4.0  install from chart  helm.ngc.nvidia.com.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
"kubectl describe pod/nvidia-driver-daemonset-pbtw9" attached 
[nvidia-driver-daemonset.txt](https://github.com/NVIDIA/gpu-operator/files/5681216/nvidia-driver-daemonset.txt)
<pre>
Additional requested commands:
gus@ubu20vm:~$ kubectl logs -n gpu-operator-resources   pod/nvidia-driver-daemonset-pbtw9
gus@ubu20vm:~$ cat /etc/docker/daemon.json
{
  "exec-opts": [
    "native.cgroupdriver=systemd"
  ],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2",
  "runtimes": {
    "nvidia": {
      "path": "/usr/local/nvidia/toolkit/nvidia-container-runtime"
    }
  },
  "default-runtime": "nvidia"
}
gus@ubu20vm:~$ docker info | grep runtime
WARNING: No swap limit support
gus@ubu20vm:~$ ls -la /run/nvidia
total 4
drwxr-xr-x  2 root root   60 Dec 11 12:49 .
drwxr-xr-x 36 root root 1120 Dec 11 12:49 ..
-rw-r--r--  1 root root    6 Dec 11 12:49 toolkit.pid
gus@ubu20vm:~$ ls -la /usr/local/nvidia/toolkit
total 4484
drwxr-xr-x 3 root root    4096 Dec 11 12:49 .
drwxr-xr-x 3 root root    4096 Dec 11 12:49 ..
drwxr-xr-x 3 root root    4096 Dec 11 12:49 .config
lrwxrwxrwx 1 root root      30 Dec 11 12:49 libnvidia-container.so.1 -> ./libnvidia-container.so.1.3.0
-rwxr-xr-x 1 root root  175120 Dec 11 12:49 libnvidia-container.so.1.3.0
-rwxr-xr-x 1 root root     154 Dec 11 12:49 nvidia-container-cli
-rwxr-xr-x 1 root root   43024 Dec 11 12:49 nvidia-container-cli.real
-rwxr-xr-x 1 root root     166 Dec 11 12:49 nvidia-container-runtime
lrwxrwxrwx 1 root root      26 Dec 11 12:49 nvidia-container-runtime-hook -> ./nvidia-container-toolkit
-rwxr-xr-x 1 root root 2008936 Dec 11 12:49 nvidia-container-runtime.real
-rwxr-xr-x 1 root root     195 Dec 11 12:49 nvidia-container-toolkit
-rwxr-xr-x 1 root root 2331544 Dec 11 12:49 nvidia-container-toolkit.real
gus@ubu20vm:~$ ls -la /run/nvidia/driver
ls: cannot access '/run/nvidia/driver': No such file or directory
gus@ubu20vm:~$ journalctl -u kubelet > kubelet.logs
gus@ubu20vm:~$
</pre>

**Comment by dualvtable** [comment]
Hi @Gus-Gilliland - what is the output of `kubectl logs nvidia-driver-daemonset-pbtw9 -n gpu-operator-resources` and also the output of `kubectl get events --sort-by=.metadata.creationTimestamp` 

Also - please do review the Getting Started guide in the official product documentation:
`https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#install-nvidia-gpu-operator` 

Other documents/blogs may be suffering from bit rot.

**Comment by shivamerla** [comment]
@dualvtable Can you paste the Ubuntu kernel version?

**Comment by Gus-Gilliland** [comment]
This was due to a typo in my GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0 cgroup_enable=memory swapaccount=1"
The: WARNING: No swap limit support (previous post) was the giveaway
For future troubleshooters:
cat /etc/default/grub | grep LINUX_DEFAULT
Make sure it matches above.
Once you've installed Docker, run: 
sudo docker info | grep -E 'swap|runtime' 
Verify no:  " No swap limit support" error present.
![resolved-nvidia-driver-daemonset-12-12-20](https://user-images.githubusercontent.com/75744281/102242757-098fe400-3ec0-11eb-87df-34a8117c2cd4.jpg)

**Comment by Gus-Gilliland** [comment]
Thanks for the help on this!
I had a typo in my GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0
cgroup_enable=memory swapaccount=1"
Issue closed.

I've got a question I can't find an answer to re gpu-operator:
I complete the gpu-opertor and everything is 1/1 perfect install.
If I shutdown my VM to take a snapshot:
kubectl drain ubu20vm --delete-local-data --force --ignore-daemonsets &&
kubectl delete pod,svc --all && sudo shutdown -h now
and bring it back up with:
virsh start ubu20vm && virsh console ubu20vm
kubectl uncordon ubu20vm
watch kubectl get all -A
I get
[image: image.png]

Is there a graceful way to shutdown and restart the VM keeping GPU-Operator
intact? or is it always a matter of deleting - helm delete $(helm list |
grep gpu-operator | awk '{print $1}')   and re-installing?
