### ISSUE TITLE
Is the defaultRuntime containerd supported ?

### ISSUE THREAD

**Issue by dummys** [NVIDIA/gpu-operator#119]
Hi, I would like to know if the defaultRuntime `containerd` is supported ? I see that you support already `CRI-O`

**Comment by dummys** [comment]
its ok I see that you support it, but there is no documentation about it unfortunately.

**Comment by klueska** [comment]
Documentation is coming soon. In the meantime.....
```
The following table shows the helm settings available for configuring the GPU operator with containerd support.

operator:
  defaultRuntime: containerd
 
toolkit:
  env:
  - name: CONTAINERD_CONFIG
    value: /etc/containerd/config.toml
  - name: CONTAINERD_SOCKET
    value: /run/containerd/containerd.sock
  - name: CONTAINERD_RUNTIME_CLASS
    value: nvidia
  - name: CONTAINERD_SET_AS_DEFAULT
    value: true

**Comment by klueska** [comment]
Documentation is coming soon. In the meantime.....
> The following table shows the helm settings available for configuring the GPU operator with containerd support.
> ```
> operator:
>   defaultRuntime: containerd
> 
> toolkit:
>   env:
>   - name: CONTAINERD_CONFIG
>     value: /etc/containerd/config.toml
>   - name: CONTAINERD_SOCKET
>     value: /run/containerd/containerd.sock
>   - name: CONTAINERD_RUNTIME_CLASS
>     value: nvidia
>   - name: CONTAINERD_SET_AS_DEFAULT
>     value: true
> ```
> The only required setting is for `operator.defaultRuntime` to be set to `containerd`. This will trigger the GPU operator to load the “Container Toolkit” with `containerd` support. The rest of the settings are optional and are used to customize specific `containerd` settings under the hood. The values shown here are the defaults.
> 
> `CONTAINERD_CONFIG`: The path on the host to the `containerd` config you would like to have updated with support for the `nvidia-container-runtime`. By default this will point to `/etc/containerd/config.toml` (the default location for `containerd`). It should be customized if your `containerd` installation is not in the default location.
> 
> `CONTAINERD_SOCKET`: The path on the host to the socket file used to communicate with `containerd`. The operator will use this to send a `SIGHUP` signal to the `containerd` daemon to reload its config. By default this will point to `/run/containerd/containerd.sock` (the default location for `containerd`). It should be customized if your `containerd` installation is not in the default location.
> 
> `CONTAINERD_RUNTIME_CLASS`: The name of the [Runtime Class ](https://kubernetes.io/docs/concepts/containers/runtime-class/)you would like to associate with the `nvidia-container-runtime`. Pods launched with a `runtimeClassName` equal to `CONTAINERD_RUNTIME_CLASS` will always run with the `nvidia-container-runtime`. The default `CONTAINERD_RUNTIME_CLASS` is `nvidia`.
> 
> `CONTAINERD_SET_AS_DEFAULT`: A flag indicating whether you want to set `nvidia-container-runtime` as the default runtime used to launch all containers. When set to false, only containers in pods with a `runtimeClassName` equal to `CONTAINERD_RUNTIME_CLASS` will be run with the `nvidia-container-runtime`. The default value is `true`.
> 
> Below is an example of launching the GPU Operator with `containerd` support with explicit values for each of the optional settings described above.
> ```
> helm install --wait --generate-name \
>     nvidia/gpu-operator \
>     --set operator.defaultRuntime=containerd \
>     --set toolkit.env[0].name=CONTAINERD_CONFIG \
>     --set toolkit.env[0].value=/etc/containerd/config.toml \
>     --set toolkit.env[1].name=CONTAINERD_SOCKET \
>     --set toolkit.env[1].value=/run/containerd/containerd.sock \
>     --set toolkit.env[2].name=CONTAINERD_RUNTIME_CLASS \
>     --set toolkit.env[2].value=nvidia \
>     --set toolkit.env[3].name=CONTAINERD_SET_AS_DEFAULT \
>     --set toolkit.env[3].value=true
> ```
> And that’s it! You should now have all the tools you need to get the GPU operator up and running with `containerd`.

**Comment by dummys** [comment]
Oh yes I figured it out and now I'm testing it. Thanks klueska.
I found that there is a problem somewhere as in my log I see this:
```
kubelet[25824]: W1216 15:50:53.405057   25824 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix:///run/containerd/containerd.sock: timeout". Reconnecting...
```
It seems to appeard after deploying gpu-operator...

Another question for you, do you have a way to use traefik ingressroute to publish only the grafana dashbord ?

**Comment by klueska** [comment]
> Another question for you, do you have a way to use traefik ingressroute to publish only the grafana dashbord ?

I am not sure, but someone else may be able to help. I would open a separate issue with this question.
