### ISSUE TITLE
User "system:serviceaccount:default:gpu-operator" cannot list resource "clusterpolicies" in API group "nvidia.com" at the cluster scope

### ISSUE THREAD

**Issue by ccnankai** [NVIDIA/gpu-operator#123]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [y ] Are you running on an Ubuntu 18.04 node?
- [y] Are you running Kubernetes v1.13+?
- [y] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [y] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

E1229 04:20:20.848290       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.ClusterPolicy: clusterpolicies.nvidia.com is forbidden: User "system:serviceaccount:default:gpu-operator" cannot list resource "clusterpolicies" in API group "nvidia.com" at the cluster scope

![image](https://user-images.githubusercontent.com/33537489/103259416-4259ae00-49d4-11eb-96af-b23c28247a61.png)

### 2. Steps to reproduce the issue

I execute the following commands,
![image](https://user-images.githubusercontent.com/33537489/103259429-50a7ca00-49d4-11eb-9918-5c019d56c7ab.png)
 and then type **kubectl get pods  --all-namespaces** to get the pod name.
execute  **kubectl logs pod-name** to see  the above error.

I added the key-value pair namespace:deault to the role_binding.ymal file to avoid this error. But when running **kubectl apply -f nvidia_xxx_cr.yaml,** it caused other errors.

ServiceAccount":"nvidia-container-toolkit","Namespace":"gpu-operator-resources","Error":"serviceaccounts is forbidden: User \"system:serviceaccount:default:gpu-operator\" cannot create resource \"serviceaccounts\" in API group \"\" in the namespace \"gpu-operator-resources\""

![image](https://user-images.githubusercontent.com/33537489/103265068-acc81980-49e7-11eb-9a08-45d9d17f1e0f.png)

![33333](https://user-images.githubusercontent.com/33537489/103269133-1ba97080-49f0-11eb-9b25-9289b9f6b022.png)

I would like to ask what caused this error. Even if I comment out the apiGroups in the role.yaml file, it doesn't work.

**Comment by shivamerla** [comment]
@ccnankai Any reason you are deploying manually using deploy/ folder? Please use the helm install instead. Deploy/ folder might be little outdated with wrong namespace hardcoded. Helm applies them correctly.

**Comment by ccnankai** [comment]
@shivamerla    
I want to learn the details of the gpu-operator project. I added the namespace and the above problem was solved. I should use the .yaml files in the deployment folder instead of deploy, right? Are the files in the deployment folder used for deployment?

**Comment by shivamerla** [comment]
@ccnankai we don't have one static yaml file for gpu-operator deployment. Only supported modes are either using Helm or OLM(Operator Lifecycle Manager). deployment/ folder is for Helm and deploy/ folder is for OLM bundle generation. Please use `helm install` command as described here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html

**Comment by ccnankai** [comment]
@shivamerla    
Now I know the structure of this project very well, and it can work in any way. Thank you very much for your help.
