### ISSUE TITLE
ClusterServiceVersion missing required 'displayName' field

### ISSUE THREAD

**Issue by strangiato** [NVIDIA/gpu-operator#125]
### 1. Issue or feature description

The ClusterServiceVersion definition located [here](https://github.com/NVIDIA/gpu-operator/blob/c937c68a5f8469cdedea4c78fc8d681ad5d7c62c/bundle/manifests/gpu-operator.clusterserviceversion.yaml#L146) is missing the displayName field required under `spec.customresourcedefinitions[0].owned.displayName`.

Documentation on the required fields for the owned object can be found [here](https://docs.openshift.com/container-platform/4.4/operators/operator_sdk/osdk-generating-csvs.html#osdk-crds-owned_osdk-generating-csvs).

**Comment by shivamerla** [comment]
@strangiato Thanks for the report. Will get this fixed.

**Comment by shivamerla** [comment]
This is fixed in 1.5.1 release.
