### ISSUE TITLE
Operator breaks on hosts that already have drivers installed

### ISSUE THREAD

**Issue by joedborg** [NVIDIA/gpu-operator#126]
For context, we're hoping to use the operator with MicroK8s, in order to remove the need to package the nvidia-container-toolkit and template the containerd config file.

The issue we see is that, when the host already have the nvidia drivers installed, the `nvidia-driver-daemonset` pod fails to start.  The logs contain:

```
========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 450.80.02 for Linux kernel version 5.4.0-1034-aws

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use

```

Would it be possible for the operator to check for the presence of existing drivers and use them instead of trying to re-install them?

**Comment by shivamerla** [comment]
@joedborg Yes, we have this planned for next release of operator.

**Comment by 0x6b756d6172** [comment]
Hello @shivamerla, are there any updates on this? There have been two gpu-operator releases since your comment (v1.5.1 and v1.5.2). Is there an estimated date for this? I am blocked by this issue for the same reasons as @joedborg, trying running gpu-operator with K3s/MicroK8s on my dev machine with the drivers preinstalled.

**Comment by shivamerla** [comment]
We found that, drivers installed outside of operator are always not compatible with the configuration done with other components. There are some assumptions made w.r.t root install path of the driver etc. The problem we are trying to solve in short term is to allow driver container to detect same version driver modules are loaded and ignore unload/compile/installing part.  But this might not be done until next month.

**Comment by jabstone** [comment]
Hello. @shivamerla @klueska - Just wanted to reach out and see if there's an update on this issue. Like many others, we're anxiously awaiting a fix. Our use case requires Microk8s in a semi-production environment and this problem has been a huge headache. Any update and ETA on a resolution would be greatly appreciated.

**Comment by shivamerla** [comment]
@jabstone We are currently testing changes for this: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/202

Since this has dependency on container-toolkit release as well, I will work with PM's to get the ETA for releasing this.

**Comment by jabstone** [comment]
This is great news. Really appreciate the quick reply and look forward to having some sense of an ETA.

**Comment by shivamerla** [comment]
@jabstone Looks like these changes will be part of our next operator release which is currently planned for last week of April. Let me know if you want to try out pre-release bits, i can point you to the images and steps to deploy.

**Comment by jabstone** [comment]
@shivamerla - I would love to try out the pre-release bits when ready. Thanks

**Comment by shpwrck** [comment]
> @jabstone Looks like these changes will be part of our next operator release which is currently planned for last week of April. Let me know if you want to try out pre-release bits, i can point you to the images and steps to deploy.

@shivamerla Can you share how I might test the release where it is possible to skip driver installation?

**Comment by joedborg** [comment]
Hey all, has the official build been release yet?

**Comment by IvanJosipovic** [comment]
+1 awaiting this feature.

**Comment by shivamerla** [comment]
Sorry, release has been pushed out by two weeks, due to addition of other important features required for MIG configurations.

**Comment by shivamerla** [comment]
@joedborg @IvanJosipovic  `v1.7.0` is released. Please try out with pre-installed drivers/toolkit. Please check [release notes]( https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html#id1) and [documentation](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-with-pre-installed-nvidia-drivers) for pre-installed use cases (i.e usage of `--set driver.enabled=false` and `--set toolkit.enabled=false` options)

**Comment by GuoLiuFang** [comment]
> @joedborg @IvanJosipovic `v1.7.0` is released. Please try out with pre-installed drivers/toolkit. Please check [release notes](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html#id1) and [documentation](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-with-pre-installed-nvidia-drivers) for pre-installed use cases (i.e usage of `--set driver.enabled=false` and `--set toolkit.enabled=false` options)

![image](https://user-images.githubusercontent.com/10841581/121649789-7ed51e00-cacb-11eb-920b-fa43bdb11f03.png)

![image](https://user-images.githubusercontent.com/10841581/121650356-133f8080-cacc-11eb-9764-08c08f394780.png)

**Comment by joedborg** [comment]
Hi @GuoLiuFang, please see this branch https://github.com/ubuntu/microk8s/pull/2149.  From there you can grab the built .snap from https://github.com/ubuntu/microk8s/pull/2149/checks?check_run_id=2804915041 (once it's finished building) and that should give you the most up-to-date operator.
