### ISSUE TITLE
Cannot deploy GPU operator on OpenShift following the documentation

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#127]
The documentation in [this page](https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html#openshift-gpu-install-gpu-operator-via-helmv3) for deploying the GPU Operator on OpenShift still mentions the broken `DevicePlugin ` image (`v0.7.0-ubi8`):
```
$  helm install gpu-operator nvidia/gpu-operator --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=false,devicePlugin.version=v0.7.0-ubi8,dcgmExporter.version=2.0.13-2.1.0-ubi8,toolkit.version=1.3.0-ubi8 --wait
```

as fixed images have been published (`v0.7.3-ubi8`), the documentation should be updated accordingly.

**Comment by shivamerla** [comment]
@kpouget We are in the process of migrating this under https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html, hence the delay. Meanwhile will look into updating the current page. Thanks for the reminder.

**Comment by shivamerla** [comment]
@kpouget doc has been updated now.
