### ISSUE TITLE
Failed to fetch https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized

### ISSUE THREAD

**Issue by jobvarkey** [NVIDIA/gpu-operator#13]
Hello,
I am trying to install GPU Operator using the instructions from https://ngc.nvidia.com/catalog/containers/nvidia:gpu-operator. 

The first step in 'Install GPU Operator' section is failing as below:
root@0939-jdeml-m01:~# helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
Error: Looks like "https://helm.ngc.nvidia.com/nvidia" is not a valid chart repository or cannot be reached: Failed to fetch https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized

Can anyone please help to resolve this?

ThanksYou,
Job Varkey

**Comment by dualvtable** [comment]
This issue with the NGC Helm repo has been resolved now - please try again.

**Comment by jobvarkey** [comment]
Thank you for fixing it. Getting below error with helm install

root@0939-jdeml-m01:~# helm install --devel nvidia/gpu-operator -n test-operator --wait
E1122 14:10:54.926891  170335 portforward.go:233] lost connection to pod
Error: transport is closing

Please advise.

**Comment by Lucasjuv** [comment]
@dualvtable I'm having this issues again: 
```
helm repo add nvidia https://helm.ngc.nvidia.com/nvidia \
    && helm repo update
Error: looks like "https://helm.ngc.nvidia.com/nvidia" is not a valid chart repository or cannot be reached: failed to fetch https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized
```

**Comment by eiqops** [comment]
+1 

started today a few minutes ago.

```
Error: looks like "https://helm.ngc.nvidia.com/nvidia" is not a valid chart repository or cannot be reached: failed to fetch https://helm.ngc.nvidia.com/nvidia/index.yaml : 401 Unauthorized
```

**Comment by Lucasjuv** [comment]
It seems like it has changed to https://nvidia.github.io/gpu-operator
