### ISSUE TITLE
nvidia-driver-validation  nvidia-driver-daemonset  CrashLoopBackOff

### ISSUE THREAD

**Issue by Leteong** [NVIDIA/gpu-operator#130]
pod:
  nvidia-driver-daemonset:  CrashLoopBackOff
  nvidia-driver-validation:  CrashLoopBackOff
describe  pod:
  Error: failed to start container "nvidia-driver-ctr": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: initialization error: driver error: failed to process request: unknown

450.80.02 is referenced in kubectl describe clusterpolicies --all-namespaces 

Name:         cluster-policy
Namespace:    
Labels:       app.kubernetes.io/component=gpu-operator
              app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: gpu-operator-1611023258
              meta.helm.sh/release-namespace: default
API Version:  nvidia.com/v1
Kind:         ClusterPolicy
Metadata:
  Creation Timestamp:  2021-01-19T02:27:42Z
  Generation:          1
  Managed Fields:
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:dcgmExporter:
          .:
          f:args:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:devicePlugin:
          .:
          f:args:
          f:image:
          f:imagePullPolicy:
          f:nodeSelector:
            .:
            f:nvidia.com/gpu.present:
          f:repository:
          f:securityContext:
            .:
            f:privileged:
          f:version:
        f:driver:
          .:
          f:image:
          f:imagePullPolicy:
          f:nodeSelector:
            .:
            f:nvidia.com/gpu.present:
          f:repository:
          f:securityContext:
            .:
            f:privileged:
            f:seLinuxOptions:
              .:
              f:level:
          f:tolerations:
          f:version:
        f:gfd:
          .:
          f:discoveryIntervalSeconds:
          f:image:
          f:imagePullPolicy:
          f:migStrategy:
          f:nodeSelector:
            .:
            f:nvidia.com/gpu.present:
          f:repository:
          f:version:
        f:operator:
          .:
          f:defaultRuntime:
          f:deployGFD:
          f:validator:
            .:
            f:image:
            f:repository:
            f:version:
        f:toolkit:
          .:
          f:image:
          f:imagePullPolicy:
          f:nodeSelector:
            .:
            f:nvidia.com/gpu.present:
          f:repository:
          f:securityContext:
            .:
            f:privileged:
            f:seLinuxOptions:
              .:
              f:level:
          f:tolerations:
          f:version:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2021-01-19T02:27:42Z
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:state:
    Manager:         gpu-operator
    Operation:       Update
    Time:            2021-01-19T02:28:40Z
  Resource Version:  1978
  Self Link:         /apis/nvidia.com/v1/clusterpolicies/cluster-policy
  UID:               2aa9b670-9370-4951-8836-26e26930d757
Spec:
  Dcgm Exporter:
    Args:
      -f
      /etc/dcgm-exporter/dcp-metrics-included.csv
    Image:              dcgm-exporter
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/k8s
    Version:            2.0.13-2.1.2-ubuntu20.04
  Device Plugin:
    Args:
      --mig-strategy=none
      --pass-device-specs=false
      --fail-on-init-error=true
      --device-list-strategy=envvar
    Image:              k8s-device-plugin
    Image Pull Policy:  IfNotPresent
    Node Selector:
      nvidia.com/gpu.present:  true
    Repository:                nvcr.io/nvidia
    Security Context:
      Privileged:  true
    Version:       v0.7.1
  Driver:
    Image:              driver
    Image Pull Policy:  IfNotPresent
    Node Selector:
      nvidia.com/gpu.present:  true
    Repository:                nvcr.io/nvidia
    Security Context:
      Privileged:  true
      Se Linux Options:
        Level:  s0
    Tolerations:
      Effect:    NoSchedule
      Key:       nvidia.com/gpu
      Operator:  Exists
    Version:     450.80.02
  Gfd:
    Discovery Interval Seconds:  60
    Image:                       gpu-feature-discovery
    Image Pull Policy:           IfNotPresent
    Mig Strategy:                none
    Node Selector:
      nvidia.com/gpu.present:  true
    Repository:                nvcr.io/nvidia
    Version:                   v0.2.2
  Operator:
    Default Runtime:  docker
    Deploy GFD:       true
    Validator:
      Image:       cuda-sample
      Repository:  nvcr.io/nvidia/k8s
      Version:     vectoradd-cuda10.2
  Toolkit:
    Image:              container-toolkit
    Image Pull Policy:  IfNotPresent
    Node Selector:
      nvidia.com/gpu.present:  true
    Repository:                nvcr.io/nvidia/k8s
    Security Context:
      Privileged:  true
      Se Linux Options:
        Level:  s0
    Tolerations:
      Key:       CriticalAddonsOnly
      Operator:  Exists
      Effect:    NoSchedule
      Key:       nvidia.com/gpu
      Operator:  Exists
    Version:     1.4.0-ubuntu18.04
Status:
  State:  notReady
Events:   <none>

**Comment by shivamerla** [comment]
@Leteong This will be resolved with operator version 1.5.0 which will be released tomorrow.

**Comment by Leteong** [comment]
> @Leteong This will be resolved with operator version 1.5.0 which will be released tomorrow.

thank you

**Comment by shivamerla** [comment]
1.5.0 is released. Please verify and close this if resolved. Thanks.
