### ISSUE TITLE
documentation: cannot deploy the operator on a MIG-enabled GPU

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#132]
When the MIG mode of A100 GPU is enabled, the GPU operator cannot deploy successfully. 
I don't think this is properly documented.

```
# query the current MIG mode
nvidia-smi --query-gpu=mig.mode.current --format=csv,noheader
# disable the MIG mode
nvidia-smi -mig "0"
# reset the GPU if necessary
nvidia-smi --gpu-reset
```

See also https://github.com/NVIDIA/gpu-operator/issues/129

**Comment by elezar** [comment]
@kpouget could you confirm that the device with MIG mode enabled has been configured with valid MIG devices? From #129 it seems as there are no devices configured?

**Comment by kpouget** [comment]
@elezar I tried to configure the MIG devices and relanched the GPU-operator, but my GPU instances disappeared on the way, I'm not sure how this setting is persist? (or maybe I did something wrong that erased them, but I don't think so)

but nonetheless, the `none` MIG strategy is coded in the default `ClusterPolicy` values, so the [DevicePlugin](https://github.com/NVIDIA/gpu-operator/blob/0c745be/deployments/gpu-operator/values.yaml#L98) and [GFD](https://github.com/NVIDIA/gpu-operator/blob/0c745be/deployments/gpu-operator/values.yaml#L142) cannot operate properly:



```
gfd:
  migStrategy: none
devicePlugin:
  args:
    - "--mig-strategy=none"
```

**Comment by shivamerla** [comment]
@kpouget With 1.5.2 MIG mode of "single" is enabled by default with device-plugin and GFD. Can you verify and close this?
