### ISSUE TITLE
add the ability to define tolerations for validation pods

### ISSUE THREAD

**Issue by raffaelespazzoli** [NVIDIA/gpu-operator#135]
gpu-enabled nodes may be defined with taints to prevent normal workload from landing on them. The gpu-operator addresses this use case by allowing to specify toleration for several of its components. But it is not possible to specify toleration for the validation pods.
These prevents these pods from being scheduled in the gpu-enabled nodes.

**Comment by shivamerla** [comment]
@raffaelespazzoli This should be resolved with 1.5.1. `driver-validation` logic is now part of initContainers within toolkit/device-plugin/dcgm. So any tolerations added to those will apply for validation containers as well. `device-plugin-validation` is a standalone pod which gets scheduled on gpu nodes anyway as there is a gpu resources request in the spec.
