### ISSUE TITLE
Deployment fails from OperatorHub: namespaces "gpu-operator-resources" not found

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#136]
I tried twice to install the GPU Operator from OpenShift OperatorHub on fresh OCP 4.7 and OCP 4.6.12 clusters, but the deployment failed because of this:

```
{"level":"info","ts":1611655576.0943882,"logger":"controller_clusterpolicy","msg":"Couldn't create","ServiceAccount":"nvidia-driver","Namespace":"gpu-operator-resources","Error":"namespaces \"gpu-operator-resources\" not found"}                            
```

Manually creating the namespace/project and updating the ClusterPolicy to trigger the operator reconciliation works around the problem.

---
```
ClusterServiceVersion Details
    gpu-operator-certified.v1.4.0
```

**Comment by shivamerla** [comment]
@kpouget Yes, its a known pre-requisite. `gpu-operator-resources` project has to be created prior to gpu-operator install. We have plans to avoid this in future by deploying all resources in single namespace wherever the operator is deployed. Thus we can avoid `MultiNamespace` or `AllNamespaces` install modes with OLM as well.
