### ISSUE TITLE
dcgm-exporter can be scheduled and run on a non-GPU node which will end with failure.

### ISSUE THREAD

**Issue by Heniland** [NVIDIA/gpu-operator#138]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Are you running Kubernetes v1.13+? No, K3S version v1.20.2+k3s1
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

All components that need to run on GPU nodes are labeled with `nodeSelector: nvidia.com/gpu.present: "true"` except `node-feature-discovery`,  `operator` and `dcgm-exporter`.  

https://github.com/NVIDIA/gpu-operator/blob/565ea353fec1a434a59a3e1eceae21dd3dd2cacb/deployments/gpu-operator/values.yaml#L122

so I moved `dcgm-exporter` to a non-GPU node and it failed to run with the following error messages. 

```
kubectl logs --namespace gpu-operator-resources nvidia-dcgm-exporter-l75sj -c toolkit-validation | head

Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
[Vector addition of 50000 elements]
waiting for nvidia drivers to be loaded
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
[Vector addition of 50000 elements]
waiting for nvidia drivers to be loaded
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
[Vector addition of 50000 elements]
waiting for nvidia drivers to be loaded
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```

The scheduler did run the `dcgmExporter` on a non-GPU node and there is no explicit declaration of `nodeSelector: nvidia.com/gpu.present: "true"`, therefore the scheduler can put `dcgmExporter` on any node and this can create a problem. 

### 2. Steps to reproduce the issue

Install the operator with the following `values.yaml`
**note**: master does not have GPU
 
```yaml
node-feature-discovery:
  master:
    nodeSelector:
      kubernetes.io/hostname: master

dcgmExporter:
  nodeSelector:
    kubernetes.io/hostname: master

operator:
  nodeSelector:
    kubernetes.io/hostname: master
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [x] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [x] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

```
kubectl get nodes -o wide
NAME      STATUS   ROLES                  AGE   VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
decider   Ready    <none>                 25h   v1.20.2+k3s1   172.19.0.2    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   docker://20.10.2
master    Ready    control-plane,master   25h   v1.20.2+k3s1   172.19.0.1    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   docker://20.10.2
```

```
kubectl cluster-info 
Kubernetes control plane is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
hanoch@hanoch-ThinkPad-E490:~/Documents/Dev/SeedX/SEED/shlomo/shlomo-predict$ 
hanoch@hanoch-ThinkPad-E490:~/Documents/Dev/SeedX/SEED/shlomo/shlomo-predict$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2+k3s1", GitCommit:"1d4adb0301b9a63ceec8cabb11b309e061f43d5f", GitTreeState:"clean", BuildDate:"2021-01-14T23:52:37Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shivamerla** [comment]
@Heniland Which version of gpu-operator are you using? I do see we apply the following nodeSelector for DCGM exporter as well 
```
      nodeSelector:
        nvidia.com/gpu.present: "true"
```

**Comment by shivamerla** [comment]
@Heniland After going through the steps you followed, looks like you are overriding nodeSelector for `dcgmExporter` to specifically let it run on master node. What is the intention for this? If GPU's doesn't exist on that node, then its bound to fail and expected.

**Comment by Heniland** [comment]
> @Heniland Which version of gpu-operator are you using? I do see we apply the following nodeSelector for DCGM exporter as well
> 
> ```
>       nodeSelector:
>         nvidia.com/gpu.present: "true"
> ```

@shivamerla  As I mentioned in the Issue section, I didn't see a `nodeSelector` tag with GPU label. here is the gpu-operator `values.yaml` file for the latest version. 
https://github.com/NVIDIA/gpu-operator/blob/565ea353fec1a434a59a3e1eceae21dd3dd2cacb/deployments/gpu-operator/values.yaml#L122

There a chance I'm looking at the wrong place, can you point me where you saw  
```
nodeSelector:
     nvidia.com/gpu.present: "true"
```
for DCGM exporter, please


> @Heniland After going through the steps you followed, looks like you are overriding nodeSelector for `dcgmExporter` to specifically let it run on master node. What is the intention for this? If GPU's doesn't exist on that node, then its bound to fail and expected.

We are trying to make the GPU node as free as possible by moving all the pods that don't require GPU, this is for reducing load and for better predictability of the system that runs over the GPU node.

**Comment by shivamerla** [comment]
@Heniland Default node selector is set by the operator for all components. For `dcgm exporter` its [here](https://github.com/NVIDIA/gpu-operator/blob/master/assets/state-monitoring/0900_daemonset.yaml#L61). As i mentioned before, DCGM exporter needs to run on GPU nodes as it needs to communicate with Nvidia devices/drivers to fetch metrics on each node, hence its deployed as a Daemonset with default nodeSelector as

```
nodeSelector:
     nvidia.com/gpu.present: "true"
```

Through values.yaml we provided an override option, in case if users have different labels for GPU nodes and want to enforce them for GPU operator components. But looks like you are trying to run them on non GPU nodes, which is not supported for DCGM exporter.

**Comment by Heniland** [comment]
@shivamerla Thank you for clarifying it for me. That answers my question.

**Comment by Heniland** [comment]
@shivamerla Just one more simple question, why not add a `nvidia.com/gpu.present: "true"` for DCGM exporter on values.yaml just like others? Is there any particular reason for it?

**Comment by shivamerla** [comment]
@Heniland Sure, will update this with `dcgmExporter` with next revision so that it will be consistent with others. Thanks for the input. Closing this as no issue as such with dcgm-exporter..
