### ISSUE TITLE
erro when deploying version 1.5.1 with helm on kubernetes

### ISSUE THREAD

**Issue by dummys** [NVIDIA/gpu-operator#139]
```
 helm upgrade --wait --create-namespace gpu-operator nvidia/gpu-operator --set=operator.defaultRuntime=containerd
Error: UPGRADE FAILED: cannot patch "cluster-policy" with kind ClusterPolicy: ClusterPolicy.nvidia.com "cluster-policy" is invalid: spec.operator.deployGFD: Required value
```

**Comment by kpouget** [comment]
@shivamerla I noticed this error as well,

I guess what happens is that spec.operator.deployGFD field was mandatory in the previous CRD; then it was removed (9df6f75),
but when upgrading between 1.4 and 1.5 the CRD isn't properly updated and the new ClusterPolicy fails to be created.

> @dummys
> But I used helm delete gpu-operator. So the clusterPolicy should be remove, right ?

I'm not 100%, could you try to confirm this? you delete the gpu-operator, then:
```
oc get crd clusterpolicies.nvidia.com
oc get clusterpolicy
```

**Comment by dummys** [comment]
What is oc ? I don't have such utilities

**Comment by kpouget** [comment]
thanks, I think that confirms what I thought: the CRD is not delete/recreated as part of `helm upgrade`.

If you didn't manage to upgrade yet, you should be able to work around your problem by running 
```
kubectl delete clusterpolicies.nvidia.com
```
to get rid of the old CRD

**Comment by dummys** [comment]
ok it works, thanks
btw the command is : `kubectl delete crd clusterpolicies.nvidia.com`

**Comment by shivamerla** [comment]
Thanks @kpouget for helping with this. Yes, `helm delete` usually doesn't get rid of old CRD, so manually needs to be deleted. @dummys We don't support `helm upgrade` currently, as driver components cannot be upgraded without workloads being drained or some reference holding onto drivers. Hence the recommendation is to always delete/install the chart after ensuring drivers are unloaded correctly.

**Comment by dummys** [comment]
@shivamerla can we update the chart to delete the clusterpolicies.nvidia.com when deleting the chart with `helm delete gpu-operator` ?

**Comment by shivamerla** [comment]
@dummys That's the helm behavior and known issue from long time: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

CrashLoop should not happen if driver is loaded and toolkit is installed properly. Can you describe the pod and try to get logs from initContainer within those pods?

**Comment by kpouget** [comment]
@dummys is this after a reboot? it must be as all the DaemonSets are already created.

could you show the end of `nvidia-driver-daemonset-cbvm6` Pod logs, to confirm that the driver is correctly loaded?

**Comment by dummys** [comment]
```
[  120.122339] nvidia-uvm: Unloaded the UVM driver.
[  120.159225] nvidia-nvlink: Unregistered the Nvlink Core, major device number 236
Installing 'NVIDIA Accelerated Graphics Driver for Linux-x86_64' (450.80.02):
  Installing: [##############################] 100%
Driver file installation is complete.
Running post-install sanity check:
  Checking: [##############################] 100%
Post-install sanity check passed.
Running runtime sanity check:
  Checking: [##############################] 100%
Runtime sanity check passed.

Installation of the kernel module for the NVIDIA Accelerated Graphics Driver for Linux-x86_64 (version 450.80.02) is now complete.

Loading ipmi and i2c_core kernel modules...
Loading NVIDIA driver kernel modules...
Starting NVIDIA persistence daemon...
Mounting NVIDIA driver rootfs...
Done, now waiting for signal
```

Yes after reboot

**Comment by dummys** [comment]
logs for nvidia-device-plugin-daemonset-h8sst:
```
2021/01/28 11:24:35 Loading NVML
2021/01/28 11:24:35 Starting FS watcher.
2021/01/28 11:24:35 Starting OS watcher.
2021/01/28 11:24:35 Retreiving plugins.
2021/01/28 11:24:35 Starting GRPC server for 'nvidia.com/gpu'
2021/01/28 11:24:35 Starting to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
2021/01/28 11:24:35 Registered device plugin for 'nvidia.com/gpu' with Kubelet
2021/01/28 14:28:41 Received signal "terminated", shutting down.
2021/01/28 14:28:41 Stopping to serve 'nvidia.com/gpu' on /var/lib/kubelet/device-plugins/nvidia-gpu.sock
```

Logs for dgcm-exporter:

```
time="2021-01-28T12:20:41Z" level=info msg="Starting dcgm-exporter"
time="2021-01-28T12:20:41Z" level=info msg="DCGM successfully initialized!"
time="2021-01-28T12:20:41Z" level=info msg="Not collecting DCP metrics: Error getting supported metrics: Profiling is not supported for this group of GPUs or GPU"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 51 ('DCGM_FI_PROF_GR_ENGINE_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 52 ('DCGM_FI_PROF_SM_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 53 ('DCGM_FI_PROF_SM_OCCUPANCY'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 54 ('DCGM_FI_PROF_PIPE_TENSOR_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 55 ('DCGM_FI_PROF_DRAM_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 56 ('DCGM_FI_PROF_PIPE_FP64_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 57 ('DCGM_FI_PROF_PIPE_FP32_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 58 ('DCGM_FI_PROF_PIPE_FP16_ACTIVE'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 59 ('DCGM_FI_PROF_PCIE_TX_BYTES'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=warning msg="Skipping line 60 ('DCGM_FI_PROF_PCIE_RX_BYTES'): DCP metrics not enabled"
time="2021-01-28T12:20:41Z" level=info msg="Kubernetes metrics collection enabled!"
time="2021-01-28T12:20:41Z" level=info msg="Pipeline starting"
time="2021-01-28T12:20:41Z" level=info msg="Starting webserver"

```

**Comment by shivamerla** [comment]
@dummys from your output looks like both DCGM and Device-Plugin are running fine. Can you confirm if you are still seeing this issue?

**Comment by dummys** [comment]
yes I'm seeing it. but all seems to be working, that's weird

**Comment by shivamerla** [comment]
@dummys sorry i didn't get that, you mean you still see some pods in CrashLoop?

**Comment by anaconda2196** [comment]
@dummys,
 my dcgm-exporter pod is crashing with same error. Did you get any solution?

**Comment by kpouget** [comment]
@anaconda2196 we don't have logs for what is crashing into error, can you show what's going wrong?

```
kubectl get pods -n gpu-operator-resources
kubectl logs ds/nvidia-dcgm-exporter -n gpu-operator-resources
kubectl logs ds/nvidia-dcgm-exporter -c toolkit-validation -n gpu-operator-resources
kubectl logs ds/nvidia-driver-daemonset -n gpu-operator-resources
```

a workaround might be to delete the DCGM pod and let it be recreated:
```
kubectl delete pod -lapp=nvidia-dcgm-exporter -n gpu-operator-resources
```

**Comment by shivamerla** [comment]
Closing this, please re-open if you still see this with latest operator version.
