### ISSUE TITLE
gpu-operator crashloopbackoff when scaled down to zero GPUs

### ISSUE THREAD

**Issue by worsco** [NVIDIA/gpu-operator#142]
### 1. Issue or feature description

When I have no GPU workloads on AWS, I scale down my GPU-based machinesets to zero. Subsequently, the gpu-operator goes into a crashloopbackoff with the log ending with:

```
{"level":"info","ts":1611596227.7272515,"logger":"controller_clusterpolicy","msg":"Failed to apply transformation 'nvidia-driver-daemonset' with error: 'ERROR: Could not find kernel full version: ('', '')'"}
```

I am using the gpu-operator 1.4.0 that is currently available in the OperatorHub.

Would it be possible to run the operator without the crashloopbackoff if there are no GPU nodes available?

### 2. Steps to reproduce the issue

Install gpu-operator as outlined on using Operator Hub: https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html

After validating that node is working with nvidia gpu driver (via 'nvidia-smi' in one of the nvidia-driver-daemonset pods), scale the machinesets for GPU nodes to zero.

The gpu-operator goes into a crashloopbackoff cycle.

**Comment by shivamerla** [comment]
@worsco This is fixed in 1.5.0, but RH seems to have issues pushing new operators to catalog. We had published 1.5.1 last week, but still doesn't appear in Operator Catalog in OCP. Meanwhile, if you want to workaround, you need to install using helm instead of OLM.

```
helm repo add nvidia https://nvidia.github.io/gpu-operator
helm repo update
```

```
helm install gpu-operator nvidia/gpu-operator --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=false,devicePlugin.version=v0.7.3-ubi8,dcgmExporter.version=2.0.13-2.1.2-ubi8,toolkit.version=1.4.3-ubi8 --wait
```
