### ISSUE TITLE
GPU-Operator failing health check on OCP4.6 and in crashloopbackoff

### ISSUE THREAD

**Issue by tommiyau** [NVIDIA/gpu-operator#145]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [ ] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Follwoing the nvidia [documentation](https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html) for installation, the operator ends up in crashloopbackoff due to the health checkfailing (stat /tmp/operator-sdk-ready). 

 
### 2. Steps to reproduce the issue
Follow the nvida openshift instructions on installing the GPU operator. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

The gpu-operator pod logs state that it can not stat the associated file as the filesystem is readonly by the looks. 

{"level":"info","ts":1613026027.1501405,"logger":"cmd","msg":"Go Version: go1.13.15"}
{"level":"info","ts":1613026027.1502194,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1613026027.1502292,"logger":"cmd","msg":"Version of operator-sdk: v0.17.0"}
{"level":"info","ts":1613026027.1513083,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1613026033.4368675,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1613026033.4369507,"logger":"leader","msg":"Continuing as the leader."}
{"level":"error","ts":1613026033.4370759,"logger":"cmd","msg":"","error":"open /tmp/operator-sdk-ready: read-only file system","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\t/go/src/github.com/NVIDIA/gpu-operator/cmd/manager/main.go:76\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by kpouget** [comment]
Hello @tommiyau, could you give us further information about the operator you installed? OperatorHub or HELM?

```
# only for OperatorHub:
oc get subscription -n openshift-operators
oc get clusterserviceversion
```
and confirm the image used by the operator:

```
oc get pods -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' -n openshift-operators
```
if this command returns nothing, please lookup the right namespace with this command, and change it above
```
# oc get pods -A | grep gpu-operator- 
openshift-operators                                gpu-operator-575546cc4-95wxb                                      1/1     Running        0          40h
```
(`openshift-operators` for me, but it might be different between OperatorHub and Helm installs)

**Comment by tommiyau** [comment]
Hello, thanks for the response. I have many operators installed so it is interesting the response below.

oc get subscription -n openshift-operators
No resources found in openshift-operators namespace

oc get clusterserviceversion
NAME                                         DISPLAY                                VERSION                 REPLACES                                     PHASE
gpu-operator-certified.v1.5.2                NVIDIA GPU Operator                    1.5.2                   gpu-operator-certified.v1.5.1                Failed

oc get pods -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' -n openshift-operators
gpu-operator-7fff67d757-s49gq:  nvcr.io/nvidia/gpu-operator@sha256:679fea62eb2c207d26354ac088fbe4625457a329dee080d90479a411603eb694,

**Comment by shivamerla** [comment]
@tommiyau Is the issue still persistent? Can you re-install and collect gpu-operator pod logs soon after install. The snippet you have pasted seems to be after a while and can be a manifest of many restarts.

**Comment by tommiyau** [comment]
The logs is complete as what is provided. Noting that this is simply the start of the normal part of the log when the operator runs. In my particular case the operator does not run and hence only the few lines in the log. I've discovered that the cause of the issue is that some how the gpu-operator pod manages to get a scc that is defining that a readonly file system is to be used. I'm trying to figure out how that gets defined and why this is the case. If I repeat in another duplicate environment and change the elected scc context and make the fs read/write then the operator starts. I've tried quite a few things but have not been able to alter that the operator by default install ends up with a gpu-operator pod that uses a read only file system in the scc.

**Comment by shivamerla** [comment]
@tommiyau you are right, for "gpu-operator" serviceaccount we don't have a pre-defined scc, but i think so far we have not seen this issue due to other SCC's assigned by OCP to the operator pod which doesn't mount filesystem read-only. Once we migrate to newer operator-sdk version, readiness probes are changed to http based instead of file based, so that might help. For your case, can you add "gpu-operator" service account to other SCC's than with read-only access?

**Comment by tommiyau** [comment]
Thanks. I have done that. I'm still working with redhat to figure out exactly why the readonly filesystem scc was used by the admission controller. But have changed the gpu-operator sa association until the issue is resolved.

**Comment by jrxs-cg** [comment]
@tommiyau We're seeing something similar with the GPU operator picking up a SCC that it shouldn't. Did you ever find root cause for that?

**Comment by shivamerla** [comment]
@jrxs-cg we have defined to use following SCC with gpu-operator ClusterRole. Can you check what SCC was used in your case? Also, did you see operator pod failing due to health check? What version of operator are you using?

```
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - hostmount-anyuid
  - ```

**Comment by jrxs-cg** [comment]
@shivamerla datadog-cluster-agent.  NVIDIA GPU Operator v1.6.2. This is not our bug report but describes almost exactly what we are seeing: https://bugzilla.redhat.com/show_bug.cgi?id=1973005

Our gpu-operator ClusterRole lacks the resourceNames part. Will try that as a workaround. This is what came out-of-the-box and has been working fine up to this point:

```
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
```

Interestingly, another of our clusters which is configured more-or-less identically was upgraded the same day from and to the same versions with no issues. That's why I was asking if root cause for the random SCC showing up had been found. 

Anyway, not trying to hijack a closed thread for our own troubleshooting. Just wanted to see if the OP had gotten to the bottom of their issue. We also have a case open with Red Hat so I'll share what comes of that.
