### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by trollkarlen** [NVIDIA/gpu-operator#146]
If you set API endpoint to be tls 1.3 minversion then the operator cant connect and start porperly.

Ubuntu 20.04
deepops 20.12
"nvidia/gpu-operator" --version "1.1.7"

### 1. Issue or feature description
$ kubectl --kubeconfig=config/artifacts/admin.conf logs nvidia-gpu-operator-node-feature-discovery-master-7d88b984gdfww
2021/02/11 17:27:02 Node Feature Discovery Master v0.5.0
2021/02/11 17:27:02 NodeName: '*******-server-02'
2021/02/11 17:27:02 ERROR: failed to update master node: Get https://****:443/api/v1/nodes/********-server-02: remote error: tls: protocol version not supported

### 2. Steps to reproduce the issue
Set the following in all.yml
tls_min_version: "VersionTLS13"

**Comment by shivamerla** [comment]
@trollkarlen This seem to be due to old version of NFD (v0.5.0 built with go1.10 which doesn't support tls1.13 with https client). Also, GPU operator version 1.1.7 is very old too. Can you upgrade to latest version of operator 1.5.2 which uses v0.6.0 of NFD?

**Comment by trollkarlen** [comment]
Im using latest deepops and that version is bound to that version. So to solve the issue temporarly i added TLSminversion to 1.2 instead of 1.3.

Does the 1.5.2 version with the new NFD support tls1.3 ? Or you wanted me to test ?

//T

**Comment by shivamerla** [comment]
@trollkarlen TLS1.3 support is enabled in crypto/tls package by default in go 1.13: https://golang.org/doc/go1.12#tls_1_3
NFD version v0.6.0 used with GPU operator v1.5.x uses go 1.13+ so should resolve the issue you are seeing.

**Comment by trollkarlen** [comment]
Sounds good then you can close the issue.
Maybe push the deepops to change to atleast version 1.5.0, if you have any connections over there.

//R

**Comment by shivamerla** [comment]
@trollkarlen seems like they did bump the version two weeks back..:)

https://github.com/NVIDIA/deepops/blob/09db4be5bd6668fa0880b020ac87a72bf10ee717/roles/nvidia-gpu-operator/defaults/main.yml
