### ISSUE TITLE
GPU operator on OpenShift 4.6 does not install or update properly

### ISSUE THREAD

**Issue by damora** [NVIDIA/gpu-operator#147]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [NO ] Are you running on an Ubuntu 18.04 node? coreos 4.6
- [ YES] Are you running Kubernetes v1.13+?
- [ CRIO] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [no ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [yes ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
When installing GPU-operator, nvidia-driver-daemonsets fail because they can't reach external repos

### 2. Steps to reproduce the issue
Install GPU-operator from OpenShift web console

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`
 
### 4. Fixing the problem:

CoreOS is running on the worker nodes and as such does not have entitlement keys in /etc/pki/entitlement or the /etc/rhsm/rhsm.conf file that is required to access the repositories where kernel-devel source is located in the event that the Nvidia drivers need to be rebuilt against a newer kernel. I do not think there is an automated update of the machineconfigs on the worker nodes with the entitlement keys during operator install - maybe there is but it is not working.

Until the machineconfigs with new entitlement keys are applied to the worker nodes, the nvidia-driver-daemonsets can not successfully transition to RUN state.

**Comment by shivamerla** [comment]
@damora This is expected and OCP cluster should be entitled for driver installation to work as it pulls kernel-devel, kernel-headers packages which are available through EUS repos. Steps to enable have been documented with helm install but applicable via OLM as well: https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html#openshift-gpu-install-gpu-operator-via-helmv3

**Comment by damora** [comment]
OK, well the template for the clusterwide entitlement key is also not correct. It has the following which uses BASE64_ENCODED_PEM_FILE as the replacement string. I think you want a different replacement string for 50-entitlement-pem and 50-entitlement-key-pem or you will end up overwriting  one *.pem with *-key.pem. I had to udpate that file for the machineconfig to be correctly applied.

---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-entitlement-pem
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,BASE64_ENCODED_PEM_FILE
        filesystem: root
        mode: 0644
        path: /etc/pki/entitlement/entitlement.pem
--- 
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-entitlement-key-pem
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,BASE64_ENCODED_PEM_FILE
        filesystem: root
        mode: 0644
        path: /etc/pki/entitlement/entitlement-key.pem
