### ISSUE TITLE
Error not explicit when NFD is missing

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#149]
The NFD Operator is required for the GPU Operator to operator properly, but when it's missing, the error message in the GPU Operator logs is not very clear about what went wrong:

```
{"level":"info","ts":1613468313.7898238,"logger":"controller_clusterpolicy","msg":"Could not get any nodes to match nvidia.com/gpu.present label","Request.Namespace":"default","Request.Name":"Node","ERROR":""}
{"level":"info","ts":1613468313.7898407,"logger":"controller_clusterpolicy","msg":"Failed to apply transformation 'nvidia-driver-daemonset' with error: 'ERROR: Could not find kernel full version: ('', '')'"}
{"level":"info","ts":1613468313.7898452,"logger":"controller_clusterpolicy","msg":"Could not pre-process","DaemonSet":"nvidia-driver-daemonset","Namespace":"gpu-operator-resources","Error":"ERROR: Could not find kernel full version: ('', '')"}   
```
This could be improved with a hint that the kernel version comes the `feature.node.kubernetes.io/kernel-version.full=` label and that the NFD operator is likely missing.

Actually, looking at the code, the hint is [there](https://github.com/NVIDIA/gpu-operator/blob/master/pkg/controller/clusterpolicy/object_controls.go#L206):
```
		logger.Info("Couldn't get kernelVersion, did you run the node feature discovery?", err)
```

but it doesn't show up in my logs ...

But anyway, at this is fully blocking the operator deployment, this could be turned into a big fat warning, surrounded with a rectangle of '#' :-)

And the same could be applied for the `gpu-operator-resources` namespace. The GPU Operator is currently stopping this this error message:

```
{"level":"info","ts":1613468527.8950045,"logger":"controller_clusterpolicy","msg":"Couldn't create","ServiceAccount":"nvidia-driver","Namespace":"gpu-operator-resources","Error":"namespaces \"gpu-operator-resources\" not found"}                            
```

**Comment by Dimiftb** [comment]
Hi @kpouget and everyone, 

I'm experiencing the same issue on my Kubernetes cluster.
 
### Cluster Setup

  `kubectl get node`

<img width="520" alt="image" src="https://user-images.githubusercontent.com/26279721/113428392-9bb7eb80-93ce-11eb-8d2d-3f8ed82189c3.png">


Worker node has 1x Nvidia GTX 1070 Ti and no drivers, container runtime or device plugin installed on it as explicitly stated at: [https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#prerequisites](url)


### Steps: 

Following latest guide here: [https://kubernetes-sigs.github.io/node-feature-discovery/master/get-started/deployment-and-usage.html#deployment](url)

After running `helm install -n gpu-operator --create-namespace --wait --generate-name nvidia/gpu-operator` 

`kubectl get pod -A` 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/26279721/113427451-f18b9400-93cc-11eb-9636-577b10e736c0.png">

Namespace gpu-operator-resources does not get created at all. 

`kubectl logs gpu-operator-65d474cc8-k8cl4 -n gpu-operator` gives 

[https://filebin.net/rxppum3sutos5sy4](url)

In particular error looks the same as @kpouget: 

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/26279721/113429009-ba6ab200-93cf-11eb-8abe-36de7e08b543.png">


I attempted to install NFD separately using helm following guide here: 
https://kubernetes-sigs.github.io/node-feature-discovery/master/get-started/deployment-and-usage.html#deployment

Then installed gpu-operator with `--set nfd.enabled=false` however this didn't fix the issue

Any advice on how can I fix this?

Thanks.

**Comment by kpouget** [comment]
Hello,
I noticed that this error (`Could not find kernel full version`) can mean two things:
1. NFD missing
2. no GPU node available

for 1, try `kubectl get nodes --show-labels` to ensure that NFD labeled the nodes
for 2, try this to confirm that the GPU cards are found:
```
(         kubectl get nodes -oname --ignore-not-found=false -l feature.node.kubernetes.io/pci-10de.present
       || kubectl get nodes -oname --ignore-not-found=false -l feature.node.kubernetes.io/pci-0302_10de.present
       || kubectl get nodes -oname --ignore-not-found=false -l feature.node.kubernetes.io/pci-0300_10de.present
      ) | grep .
```

**Comment by Dimiftb** [comment]
Hi @kpouget, 

Appreciate your quick reply


1.
`kubectl get nodes --show-labels`

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/26279721/113430992-fd7a5480-93d2-11eb-89f7-bc7b3039aa3e.png">

2.
<img width="887" alt="image" src="https://user-images.githubusercontent.com/26279721/113431284-6c57ad80-93d3-11eb-9e3e-b73bba68b81b.png">


Another thing I noticed is one of the NFD worker pods has restarted 13 times: 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/26279721/113431468-b2147600-93d3-11eb-977a-24955b2712b8.png">

Upon further inspection: 

`kubectl logs gpu-operator-1617375263-node-feature-discovery-worker-w26ns -n gpu-operator`

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/26279721/113431540-ce181780-93d3-11eb-9ccc-501699d0bf77.png">

Not sure if that is related. 

Any ideas?

**Comment by kpouget** [comment]
hum, I think your screenshots make it clear that NFD is not running 100% fine, the master node `tehr00`is labeled, but not `tehr01`. But `tehr01` role is empty (`<none>`), maybe that's why NFD isn't catching it?

I never debugged NFD so I can't really help much :#

**Comment by shivamerla** [comment]
Looks like NFD worker is not able to talk to NFD master. Can you check your CNI config for any error?

**Comment by Dimiftb** [comment]
Appreciate your help. 

@shivamerla how can I do that? 

Sorry if the question is stupid, I'm very new at this.

**Comment by shivamerla** [comment]
@Dimiftb you can logs of sdn pod running on this node `$ oc get pods -n openshift-sdn -o wide | grep sdn` and `oc logs -f <sdn-pod> -n openshift-sdn`.

Also, looks like only one worker pod is crashing and other is running fine. Can you check logs of that?

**Comment by Dimiftb** [comment]
Hi everyone, 

Just to give you an update in case my situation helps someone else. I didn't manage to solve the issue, however I assume it's something to do with Calico CNI. The plugin wasn't working properly and as a result NFD wasn't working properly and hence the gpu-operator. I resorted to using weave-net and installing everything the old fashioned way following steps here: https://docs.nvidia.com/datacenter/cloud-native/kubernetes/install-k8s.html#install-nvidia-dependencies 

It took a little longer, however everything works as expected now. Thank you for your help

**Comment by shivamerla** [comment]
Closing this as it seems related to CNI issue also NFD missing logs are added now.
