### ISSUE TITLE
GPU Monitoring not working on OpenShift OperatorHub

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#151]
When deploying the GPU Operator from OpenShift OperatorHub, the Prometheus DCGM monitoring is not working.

This can be confirmed by checking that there is no `dcgm` target in Prometheus:
```
https://prometheus-k8s-openshift-monitoring.apps.$CLUSTER_ADDR/targets
```

or programmatically, by checking prometheus configuration file:

```
oc get secret prometheus-k8s -n openshift-monitoring -ojson | jq -r '.data["prometheus.yaml.gz"]' | base64 -d | gunzip | grep dcgm
# (empty)
```
---

The issue comes from the labeling of the `namespace/gpu-operator-resources`, which is missing the label `openshift.io/cluster-monitoring=true`, so this should be included in the deployment documentation.

```
oc label ns/gpu-operator-resources openshift.io/cluster-monitoring=true
```

This command ^^^ solves the issue, after a few minutes Prometheus notices the DCGM `ServiceMonitor` and starts exposing the GPU metrics.

**Comment by ArangoGutierrez** [comment]
++

**Comment by shivamerla** [comment]
@kpouget Thanks, will take care of documenting this soon.

**Comment by shivamerla** [comment]
This is fixed with: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/199. operator will now create 'gpu-operator-resources' namespace automatically and apply the labels required to enable metric collection.
