### ISSUE TITLE
Validator pod cannot specify toleration

### ISSUE THREAD

**Issue by tianhe-oi** [NVIDIA/gpu-operator#154]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ x ] Are you running on an Ubuntu 18.04 node?
- [ x ] Are you running Kubernetes v1.13+?
- [ x ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ x ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ x ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Validator cannot specify toleration

### 2. Steps to reproduce the issue
Our GPU node has specific taint. The validator pod cannot be scheduled unless manually edit the toleration. We used helm to install the GPU operator and all other components can specify toleration through clusterpolicy definition.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by shivamerla** [comment]
@tianhe-oi Starting from 1.6.0, tolerations/affinity/node-selector labels from device-plugin pods are applied to device-plugin-validation pod as well.
