### ISSUE TITLE
nvidia-device-plugin-validation does not tolerate taint on gpu node

### ISSUE THREAD

**Issue by worsco** [NVIDIA/gpu-operator#156]
Cluster: OpenShift 4.5.31
GPU Operator: v1.5.2

### 1. Issue or feature description

I've applied a taint to a machineset.  I've added the toleration in the ClusterPolicy for dcgmExporter, devicePlugin, driver, gfd, and toolkit.

nvidia-device-plugin-validation reports: 

```
  reason: Unschedulable
      message: >-
        0/10 nodes are available: 1 node(s) had taint {workload: aiml}, that the
        pod didn't tolerate, 9 Insufficient nvidia.com/gpu.
```

### 2. Steps to reproduce the issue

Apply taint to machineset.  Configure the ClusterPolicy appropriately.

The following pods start:
* nvidia-driver-daemonset-bqqzh
* nvidia-device-plugin-daemonset-vbhkw
* nvidia-container-toolkit-daemonset-nlsv8

This pod will not start:
* nvidia-device-plugin-validation

**Comment by worsco** [comment]
It looks like tolerations are picked up in the TransformDevicePlugin via:

https://github.com/NVIDIA/gpu-operator/blob/85f0d1972a2402d549db99d536e85a7fd57bd4b1/pkg/controller/clusterpolicy/object_controls.go#L763-L766

However, there are no transformations in the TransformDevicePluginValidator at:
https://github.com/NVIDIA/gpu-operator/blob/85f0d1972a2402d549db99d536e85a7fd57bd4b1/pkg/controller/clusterpolicy/object_controls.go#L957-L977

Perhaps it is as simple as inheriting/copying the tolerations from the TransformDevicePlugin into the TransformDevicePluginValidator?

**Comment by shivamerla** [comment]
Yes, that should do it. Since others also reported this use case fixing it as part of 1.6.0: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/185

**Comment by shivamerla** [comment]
1.6.0 version is now published to RH catalog with these changes.
