### ISSUE TITLE
Any plan to support priorityClassName in values.yaml for daemonsets?

### ISSUE THREAD

**Issue by Wennn** [NVIDIA/gpu-operator#158]
Hi team,

Is there any plan to support priorityClassName in values.yaml for daemonsets?
If the driver related pods are evicted and crash, we will lose the whole driver on host machines. So refer to [this](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/), maybe we need a way to set priorityClassName for the critical daemonsets.

Thanks

**Comment by shivamerla** [comment]
@Wennn Thanks for reporting this. We seemed to be missed on this. All critical resources have annotation of `scheduler.alpha.kubernetes.io/critical-pod` which is deprecated from 1.16. We should be fixing this with next operator update.

**Comment by shivamerla** [comment]
This is fixed with: https://github.com/NVIDIA/gpu-operator/commit/515f33595566d01c1c41b93622b0b5df43c21688
