### ISSUE TITLE
GPU Operator Installation failed with failed with nvidia-device-plugin-daemonset stuck in CrashLoopBackOff and with the error message 'flag provided but not defined: -nvidia-driver-root'.

### ISSUE THREAD

**Issue by hongweijia** [NVIDIA/gpu-operator#159]
Hello
Thanks for your help in advance!
We are following this guide for GPU Operator Installation  on OCP 4.5.15.
https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html

But during the installation, the GPU Operator failed with  nvidia-device-plugin-daemonset stuck in CrashLoopBackOff and with the error message 'flag provided but not defined: -nvidia-driver-root'.

Here's the command we used.
`helm install gpu-operator gpu-operator-1.5.2.tgz --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=true,devicePlugin.version=v0.7.3-ubi8,dcgmExporter.version=2.0.13-2.1.2-ubi8,toolkit.version=1.4.0-ubi8 --wait`

And the logs.
[root@bastion01 ~]# oc logs nvidia-device-plugin-daemonset-ltqww -n gpu-operator-resources
flag provided but not defined: -nvidia-driver-root
Usage of nvidia-device-plugin:
  -device-list-strategy string
        the desired strategy for passing the device list to the underlying runtime
        [envvar | volume-mounts] (default "envvar")
  -fail-on-init-error
        fail the plugin if an error is encountered during initialization, otherwise block indefinitely [default: true]
         (default true)
  -mig-strategy string
        the desired strategy for exposing MIG devices on GPUs that support it
        [none | single | mixed] (default "none")
  -pass-device-specs
        pass the list of DeviceSpecs to the kubelet on Allocate()
[root@bastion01 ~]#

Could you please help to investigate and kindly share the solution? 

Thanks!

**Comment by shivamerla** [comment]
@hongweijia This document is still not updated with latest versions. Please use `devicePlugin.version=v0.8.2-ubi8` and `dcgmExporter.version=2.1.4-2.2.0-ubi8` and `toolkit.version=1.4.5-ubi8`

**Comment by hongweijia** [comment]
@shivamerla Thank you for your help! We'll have a try!
