### ISSUE TITLE
Nvidia GPU Installer problem in IBM Cloud

### ISSUE THREAD

**Issue by relyt0925** [NVIDIA/gpu-operator#160]
there’s a lingering bug in the 1.5 and beyond GPU operator. The exact issue is that they switched up how they’re generating some of the initial deployment configuration and trying to be smart. They pick a container based on sha, not based on tag. To override it (I just did this last night with the 1.6 operator that just came out) - you…

1) Install the GPU Operator
2) Create an instance of the GPU Operator’s ClusterPolicy. In the default screens expand the “Driver” section and replace the sha driver version with 450.80.02 (see the screenshot) :
3) 
![image](https://user-images.githubusercontent.com/7716924/109835592-f52ece00-7c08-11eb-9c88-c751e5b8f48e.png)

This should either be updated in the documentation or fixed for IBM Cloud Openshift deployments

**Comment by shivamerla** [comment]
@relyt0925 its one of the requirement with OCP to use all images with digest to support in Disconnected environments. What was the problem that you had to overwrite it with? Its running on different OS than rhcos4.5/4.6/4.7?

**Comment by relyt0925** [comment]
In IBM Cloud Openshift the machines run based off of RHEL 7 machines:
https://github.com/NVIDIA/gpu-operator/issues/64

**Comment by shivamerla** [comment]
Got it. Thanks. will update the documentation.

**Comment by ticlazau** [comment]
Hello,

I have the same issue with GPU Operator 1.6.2 on OCP 4.6

(base) coredump@Deceneu ~ % oc get all -n gpu-operator-resources
NAME                                           READY   STATUS                  RESTARTS   AGE
pod/nfd-master-bj47q                           1/1     Running                 0          12h
pod/nfd-master-dxp4x                           1/1     Running                 0          12h
pod/nfd-master-t22dd                           1/1     Running                 0          12h
pod/nfd-master-wngmk                           1/1     Running                 0          12h
pod/nfd-worker-dqh8r                           1/1     Running                 0          12h
pod/nfd-worker-fqqjz                           1/1     Running                 0          12h
pod/nfd-worker-qjggd                           1/1     Running                 0          12h
pod/nfd-worker-x8d5b                           1/1     Running                 0          12h
pod/nvidia-container-toolkit-daemonset-pg6xq   1/1     Running                 0          9m30s
**pod/nvidia-device-plugin-daemonset-pfrlf       0/1     Init:CrashLoopBackOff   6          6m26s**
pod/nvidia-driver-daemonset-5f42b              1/1     Running                 0          10m

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
service/nfd-master   ClusterIP   172.21.31.27   <none>        12000/TCP   7d15h

NAME                                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/nfd-master                           4         4         4       4            4           node-role.kubernetes.io/master=   7d15h
daemonset.apps/nfd-worker                           4         4         4       4            4           <none>                            7d15h
daemonset.apps/nvidia-container-toolkit-daemonset   1         1         1       1            1           nvidia.com/gpu.present=true       9m30s
daemonset.apps/nvidia-device-plugin-daemonset       1         1         0       1            0           nvidia.com/gpu.present=true       6m26s
daemonset.apps/nvidia-driver-daemonset              1         1         1       1            1           nvidia.com/gpu.present=true       10m

**Comment by ticlazau** [comment]
@shivamerla 
What's the reason of cuda-sample@**sha256:2a30fe7e23067bc2c3f8f62a6867702a016af2b80b9f6ce861f3fea4dfd85bc2**
name?

Rgds,

**Comment by shivamerla** [comment]
@ticlazau this image performs validation that toolkit/driver are loaded correctly by running a vector-addition sample. Can you get logs of that container within device-plugin daemonset to see what is going on?

**Comment by shivamerla** [comment]
@ticlazau by the way, you issue is not same as original reported issue here by IBM. Please track your issue with: https://github.com/NVIDIA/gpu-operator/issues/167. Closing this one as IBM issue needs to be documented to overwrite driver version while deploying on OCP for RHEL 7 nodes.

**Comment by ticlazau** [comment]
```
(base) coredump@Deceneu GPU % oc logs nvidia-device-plugin-daemonset-pfrlf -c toolkit-validation -n gpu-operator-resources
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```

**Comment by ticlazau** [comment]
++
```
(base) coredump@Deceneu GPU % oc exec -it nvidia-driver-daemonset-5f42b nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Wed Mar 17 20:27:49 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   31C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   31C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by shivamerla** [comment]
@ticlazau Did you override the driver version to use 450.80.02? Because 1.6.2 installs `460.32.03` by default.

**Comment by ticlazau** [comment]
@shivamerla Yes, I have use 450.80.02. With default values is not working. The pod/nvidia-container-toolkit-daemonset-srf6l will remain in init state. In addition Nvidia-SMI will not work 

```
(base) coredump@Deceneu GPU % oc exec -it nvidia-driver-daemonset-q45bl nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
ERRO[0000] exec failed: container_linux.go:366: starting container process caused: exec: "nvidia-smi": executable file not found in $PATH
command terminated with exit code 1
```
++

```
(base) coredump@Deceneu GPU % oc get all -n gpu-operator-resources
NAME                                           READY   STATUS     RESTARTS   AGE
pod/nfd-master-bj47q                           1/1     Running    0          29h
pod/nfd-master-dxp4x                           1/1     Running    0          29h
pod/nfd-master-t22dd                           1/1     Running    0          29h
pod/nfd-master-wngmk                           1/1     Running    0          29h
pod/nfd-worker-dqh8r                           1/1     Running    0          29h
pod/nfd-worker-fqqjz                           1/1     Running    0          29h
pod/nfd-worker-qjggd                           1/1     Running    0          29h
pod/nfd-worker-x8d5b                           1/1     Running    0          29h
pod/nvidia-container-toolkit-daemonset-srf6l   0/1     Init:0/1   0          5m
pod/nvidia-driver-daemonset-q45bl              1/1     Running    4          5m11s

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
service/nfd-master   ClusterIP   172.21.31.27   <none>        12000/TCP   8d

NAME                                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/nfd-master                           4         4         4       4            4           node-role.kubernetes.io/master=   8d
daemonset.apps/nfd-worker                           4         4         4       4            4           <none>                            8d
daemonset.apps/nvidia-container-toolkit-daemonset   1         1         0       1            0           nvidia.com/gpu.present=true       5m1s
daemonset.apps/nvidia-driver-daemonset              1         1         1       1            1           nvidia.com/gpu.present=true       5m11s
```

**Comment by ticlazau** [comment]
`(base) coredump@Deceneu GPU % oc get all -n gpu-operator-resources
NAME                                           READY   STATUS             RESTARTS   AGE
pod/nfd-master-bj47q                           1/1     Running            0          29h
pod/nfd-master-dxp4x                           1/1     Running            0          29h
pod/nfd-master-t22dd                           1/1     Running            0          29h
pod/nfd-master-wngmk                           1/1     Running            0          29h
pod/nfd-worker-dqh8r                           1/1     Running            0          30h
pod/nfd-worker-fqqjz                           1/1     Running            0          29h
pod/nfd-worker-qjggd                           1/1     Running            0          29h
pod/nfd-worker-x8d5b                           1/1     Running            0          29h
pod/nvidia-container-toolkit-daemonset-srf6l   0/1     Init:0/1           0          18m
pod/nvidia-driver-daemonset-q45bl              0/1     CrashLoopBackOff   7          18m

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
service/nfd-master   ClusterIP   172.21.31.27   <none>        12000/TCP   8d

NAME                                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/nfd-master                           4         4         4       4            4           node-role.kubernetes.io/master=   8d
daemonset.apps/nfd-worker                           4         4         4       4            4           <none>                            8d
daemonset.apps/nvidia-container-toolkit-daemonset   1         1         0       1            0           nvidia.com/gpu.present=true       18m
daemonset.apps/nvidia-driver-daemonset              1         1         0       1            0           nvidia.com/gpu.present=true       18m`
