### ISSUE TITLE
Driver install error on 1.6.0 / Openshift 4.6.16

### ISSUE THREAD

**Issue by rspierz** [NVIDIA/gpu-operator#162]
upgraded from 1.5.2 with a working install. 

Steps to upgrade were to remove everything operator and deployment and delete the nvidia CRD. Noticed you are not pushing to docker.io the latest 1.6.0 release so had to pull nvcr image down for operator and driver and push to internal (please push these to docker.io adding nvcr or new registries is not ideal for openshift. Best solution would be to push to redhat registry for future builds).

Here is my CR spec applied:

> spec:
  dcgmExporter:
    nodeSelector: {}
    imagePullSecrets: []
    resources: {}
    affinity: {}
    podSecurityContext: {}
    repository: nvcr.io/nvidia/k8s
    securityContext: {}
    version: 'sha256:ced606933cd2210768ee8488b624c64ac0bdce6f05d9c4b4210e251370a14ff8'
    image: dcgm-exporter
    tolerations: []
  devicePlugin:
    nodeSelector: {}
    imagePullSecrets: []
    resources: {}
    affinity: {}
    podSecurityContext: {}
    repository: nvcr.io/nvidia
    securityContext: {}
    version: 'sha256:ea353fe57628f4d3c3e1cda126455d02f2277e3ee92fa9da441d409d76b2ac92'
    image: k8s-device-plugin
    tolerations: []
    args:
      - '--mig-strategy=single'
      - '--pass-device-specs=true'
      - '--fail-on-init-error=true'
      - '--device-list-strategy=envvar'
      - '--nvidia-driver-root=/run/nvidia/driver'
  driver:
    licensingConfig:
      configMapName: ''
    nodeSelector: {}
    imagePullSecrets: []
    resources: {}
    affinity: {}
    podSecurityContext: {}
    repository: 'image-registry.openshift-image-registry.svc:5000/gpu-operator-resources'
    securityContext: {}
    repoConfig:
      configMapName: ''
      destinationDir: ''
    version: 'sha256:017d2e2a1bc410e9d2ac116683fc49a6f28e935cadee86e712cc147ea0239469'
    image: driver
    tolerations: []
  gfd:
    nodeSelector: {}
    imagePullSecrets: []
    resources: {}
    affinity: {}
    podSecurityContext: {}
    repository: docker.io/nvidia
    securityContext: {}
    version: 'sha256:bfc39d23568458dfd50c0c5323b6d42bdcd038c420fb2a2becd513a3ed3be27f'
    image: gpu-feature-discovery
    tolerations: []
    migStrategy: single
  operator:
    defaultRuntime: crio
    validator:
      image: samples
      imagePullSecrets: []
      repository: docker.io/nvidia
      version: 'sha256:2a30fe7e23067bc2c3f8f62a6867702a016af2b80b9f6ce861f3fea4dfd85bc2'
  toolkit:
    nodeSelector: {}
    imagePullSecrets: []
    resources: {}
    affinity: {}
    podSecurityContext: {}
    repository: docker.io/nvidia
    securityContext: {}
    version: 'sha256:1cba398a04ec14a5dc3c6229e3674436fdcb574c329cff9ce5048099c8ff2fad'
    image: container-toolkit
    tolerations: []
    `

I am getting the below errors on the driver install on every gpu node:

`Error: container create failed: time="2021-03-04T18:25:26Z" level=warning msg="cgroup: subsystem does not exist" time="2021-03-04T18:25:26Z" level=warning msg="cgroup: subsystem does not exist" time="2021-03-04T18:25:26Z" level=error msg="container_linux.go:366: starting container process caused: process_linux.go:472: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: initialization error: driver error: failed to process request\n"
`
Worker nodes are rhcos on 4.18.0-193.41.1.el8_2.x86_64

**Comment by shivamerla** [comment]
@rspierz Looks like "nvidia" runtime hook was not cleaned up properly after previous un-install. To workaround this issue, please delete `/etc/containers/oci/hooks.d/oci-nvidia-hook.json` from GPU worker nodes. Driver container should start with that along with rest of the components. Also, did you start seeing this issue soon after install or after reboot of all nodes?

**Comment by rspierz** [comment]
I have nothing at "/etc/containers/oci/hooks.d/"

I have not rebooted any nodes since upgrading the gpu operator.

**Comment by shivamerla** [comment]
hmm..wondering if crio daemon is not able to update once config is cleaned up after previous uninstall. Can you try restarting crio daemon "systemctl restart crio". @kpouget Can you confirm if this can happen?

**Comment by kpouget** [comment]
hum, I got this expected (and temporary) error:
```
nvidia-device-plugin-daemonset-4jm6t       0/1     Init:CreateContainerError   0          70s
```
```
  Warning  Failed          9s                kubelet            Error: container create failed: time="2021-03-04T19:23:39Z" level=error msg="container_linux.go:366: starting container process caused: process_linux.go:472: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: initialization error: driver error: failed to process request\n"
```

and after a few minutes everything was deployed successfully:

```NAME                                       READY   STATUS      RESTARTS   AGE
gpu-feature-discovery-thzx7                1/1     Running     0          47s
nvidia-container-toolkit-daemonset-gsvnj   1/1     Running     0          4m18s
nvidia-dcgm-exporter-hvxt8                 1/1     Running     0          70s
nvidia-device-plugin-daemonset-4jm6t       1/1     Running     0          3m51s
nvidia-device-plugin-validation            0/1     Completed   0          78s
nvidia-driver-daemonset-j95m6              1/1     Running     0          4m40s
```

I had 1.5.2 installed, I uninstalled it from OperatorHub, removed the ClusterPolicy, and installed 1.6.0 from OperatorHub.
That was on a pre-release of OCP 4.7

**Comment by rspierz** [comment]
ok so i did restart crio on one of the nodes and it came back without the error on the pod but then the rest of the nodes also did not report the event issue after awhile ( i did not restart crio on the other nodes).

Although, all nodes/driver pods are reporting issue on the run. 

> containerStatuses:
    - restartCount: 6
      started: false
      ready: false
      name: nvidia-driver-ctr
      state:
        waiting:
          reason: CrashLoopBackOff
          message: >-
            back-off 5m0s restarting failed container=nvidia-driver-ctr
            pod=nvidia-driver-daemonset-qwvd6_gpu-operator-resources(2854291f-0cac-43ff-8b38-39d7d0d7cda7)
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/gpu-operator-resources/driver@sha256:017d2e2a1bc410e9d2ac116683fc49a6f28e935cadee86e712cc147ea0239469
      image: >-
        image-registry.openshift-image-registry.svc:5000/gpu-operator-resources/driver@sha256:017d2e2a1bc410e9d2ac116683fc49a6f28e935cadee86e712cc147ea0239469
      lastState:
        terminated:
          exitCode: 1
          reason: Error
          startedAt: '2021-03-04T19:32:15Z'
          finishedAt: '2021-03-04T19:32:35Z'

Pod log:

> 
      + set -eu
      + RUN_DIR=/run/nvidia
      + PID_FILE=/run/nvidia/nvidia-driver.pid
      + DRIVER_VERSION=460.32.03
      + KERNEL_UPDATE_HOOK=/run/kernel/postinst.d/update-nvidia-driver
      + NUM_VGPU_DEVICES=0
      + '[' 1 -eq 0 ']'
      + command=init
      + shift
      + case "${command}" in
      ++ getopt -l accept-license -o a --
      + options=' --'
      + '[' 0 -ne 0 ']'
      + eval set -- ' --'
      ++ set -- --
      + ACCEPT_LICENSE=
      ++ uname -r
      + KERNEL_VERSION=4.18.0-193.41.1.el8_2.x86_64
      + PRIVATE_KEY=
      + PACKAGE_TAG=
      + for opt in ${options}
      + case "$opt" in
      + shift
      + break
      + '[' 0 -ne 0 ']'
      + init
      + '[' passthrough = vgpu ']'
      + sh NVIDIA-Linux-x86_64-460.32.03.run -x
      Creating directory NVIDIA-Linux-x86_64-460.32.03
      Verifying archive integrity... OK
      Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 460.32.03...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
      + cd NVIDIA-Linux-x86_64-460.32.03
      + sh /tmp/install.sh nvinstall
      
      WARNING: Unable to determine the default X library path. The path /tmp/null/lib will be used, but this path was not detected in the ldconfig(8) cache, and no directory exists at this path, so it is likely that libraries installed there will not be found by the loader.
      
      
      WARNING: You specified the '--no-kernel-module' command line option, nvidia-installer will not install a kernel module as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that an NVIDIA kernel module matching this driver version is installed separately.
      
      
      WARNING: Unable to determine the path to install the libglvnd EGL vendor library config files. Check that you have pkg-config and the libglvnd development libraries installed, or specify a path with --glvnd-egl-config-path.
      
      + mkdir -p /usr/src/nvidia-460.32.03
      + mv LICENSE mkprecompiled kernel /usr/src/nvidia-460.32.03
      + sed '9,${/^\(kernel\|LICENSE\)/!d}' .manifest
      
      ========== NVIDIA Software Installer ==========
      
      Starting installation of NVIDIA driver version 460.32.03 for Linux kernel version 4.18.0-193.41.1.el8_2.x86_64
      
      + echo -e '\n========== NVIDIA Software Installer ==========\n'
      + echo -e 'Starting installation of NVIDIA driver version 460.32.03 for Linux kernel version 4.18.0-193.41.1.el8_2.x86_64\n'
      + exec
      + flock -n 3
      + echo 3474425
      + trap 'echo '\''Caught signal'\''; exit 1' HUP INT QUIT PIPE TERM
      + trap _shutdown EXIT
      + _unload_driver
      + rmmod_args=()
      + local rmmod_args
      + local nvidia_deps=0
      + local nvidia_refs=0
      + local nvidia_uvm_refs=0
      + local nvidia_modeset_refs=0
      + echo 'Stopping NVIDIA persistence daemon...'
      Stopping NVIDIA persistence daemon...
      + '[' -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ']'
      + '[' -f /var/run/nvidia-gridd/nvidia-gridd.pid ']'
      Unloading NVIDIA driver kernel modules...
      + echo 'Unloading NVIDIA driver kernel modules...'
      + '[' -f /sys/module/nvidia_modeset/refcnt ']'
      + '[' -f /sys/module/nvidia_uvm/refcnt ']'
      + '[' -f /sys/module/nvidia/refcnt ']'
      + '[' 0 -gt 0 ']'
      + '[' 0 -gt 0 ']'
      + '[' 0 -gt 0 ']'
      + '[' 0 -gt 0 ']'
      + return 0
      + _unmount_rootfs
      Unmounting NVIDIA driver rootfs...
      + echo 'Unmounting NVIDIA driver rootfs...'
      + findmnt -r -o TARGET
      + grep /run/nvidia/driver
      Checking NVIDIA driver packages...
      + _kernel_requires_package
      + local proc_mount_arg=
      + echo 'Checking NVIDIA driver packages...'
      + [[ ! -d /usr/src/nvidia-460.32.03/kernel ]]
      + cd /usr/src/nvidia-460.32.03/kernel
      + proc_mount_arg='--proc-mount-point /lib/modules/4.18.0-193.41.1.el8_2.x86_64/proc'
      ++ ls -d -1 'precompiled/**'
      Updating the package cache...
      + return 0
      + _update_package_cache
      + '[' '' '!=' builtin ']'
      + echo 'Updating the package cache...'
      + yum -q makecache
      Error: Failed to download metadata for repo 'cuda': Cannot download repomd.xml: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/repodata/repomd.xml [error setting certificate verify locations:
        CAfile: /etc/pki/tls/certs/ca-bundle.crt
        CApath: none]
      + _shutdown
      + _unload_driver
      + rmmod_args=()
      + local rmmod_args
      + local nvidia_deps=0
      + local nvidia_refs=0
      + local nvidia_uvm_refs=0
      + local nvidia_modeset_refs=0
      + echo 'Stopping NVIDIA persistence daemon...'
      Stopping NVIDIA persistence daemon...
      + '[' -f /var/run/nvidia-persistenced/nvidia-persistenced.pid ']'
      + '[' -f /var/run/nvidia-gridd/nvidia-gridd.pid ']'
      Unloading NVIDIA driver kernel modules...
      + echo 'Unloading NVIDIA driver kernel modules...'
      + '[' -f /sys/module/nvidia_modeset/refcnt ']'
      + '[' -f /sys/module/nvidia_uvm/refcnt ']'
      + '[' -f /sys/module/nvidia/refcnt ']'
      + '[' 0 -gt 0 ']'
      + '[' 0 -gt 0 ']'
      + '[' 0 -gt 0 ']'
      + '[' 0 -gt 0 ']'
      + return 0
      + _unmount_rootfs
      Unmounting NVIDIA driver rootfs...
      + echo 'Unmounting NVIDIA driver rootfs...'
      + findmnt -r -o TARGET
      + grep /run/nvidia/driver
      + rm -f /run/nvidia/nvidia-driver.pid /run/kernel/postinst.d/update-nvidia-driver
      + return 0

**Comment by kpouget** [comment]
> Error: Failed to download metadata for repo 'cuda': Cannot download repomd.xml: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/repodata/repomd.xml [error setting certificate verify locations:
>    CAfile: /etc/pki/tls/certs/ca-bundle.crt
>   CApath: none]

seems like the issue here is accessing the package repository, not the container hook anymore

**Comment by rspierz** [comment]
hmm is this new with 1.6.0? I am behind a proxy environment and I dont think i saw this with 1.5.2.

**Comment by shivamerla** [comment]
@rspierz Yes, 1.6.0 version automatically injects Proxy env HTTPS_PROXY, HTTP_PROXY, NO_PROXY and trusted CA certificates configured in cluster-wide Proxy into driver container. @zvonkok The path here seems to be  `/etc/pki/tls/certs/ca-bundle.crt` but for OpenShift we mount CA certs at `/etc/pki/ca-trust/extracted/pem`. Any idea how to fix this?

**Comment by zvonkok** [comment]
@rspierz Can you show us how your proxy config on OpenShift looks like? 

```
oc get proxy/cluster -o yaml
```

**Comment by zvonkok** [comment]
What is the output of the test pod for the entitlements? 

https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html

```
$ cat << EOF >> mypod.yaml 
apiVersion: v1
kind: Pod
metadata:
 name: cluster-entitled-build-pod
spec:
 containers:
   - name: cluster-entitled-build
     image: registry.access.redhat.com/ubi8:latest
     command: [ "/bin/sh", "-c", "dnf search kernel-devel --showduplicates" ]
 restartPolicy: Never
EOF
$ oc create -f mypod.yaml
 

$ oc logs cluster-entitled-build-pod -n default
```

**Comment by zvonkok** [comment]
I am unsure why the 1.5.0 version would work in a proxy environment without injecting the proxy env variables vs. why it fails with 1.6.0 where the correct env variables are injected. 

In the 1.5 install did you edit the ClusterPolicy to inject the `env:` block with the correct HTTP, HTTPS_PROXY vars?

**Comment by rspierz** [comment]
> spec:
  httpProxy: http://######:8083
  httpsProxy: http://######:8083
  noProxy: .***.ca,localhost,127.0.0.1,10.0.0.0/8,254.0.0.0/14,254.52.0.0/18
  trustedCA:
    name: ****-ca-certs

We have entitlements on our gpu nodes - it was working with 1.5.x

in 1.5.x we did have the env vars for proxy set in the driver deployment spec.

**Comment by rspierz** [comment]
on debug pod to driver pod:

>   dnf update
  Updating Subscription Management repositories.
  Unable to read consumer identity
  Subscription Manager is operating in container mode.
  cuda                                                                                                                                                                                                         0.0  B/s |   0  B     00:00
  Errors during downloading metadata for repository 'cuda':
    - Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/repodata/repomd.xml [error setting certificate verify locations:
    CAfile: /etc/pki/tls/certs/ca-bundle.crt
    CApath: none]
  Error: Failed to download metadata for repo 'cuda': Cannot download repomd.xml: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/repodata/repomd.xml [error setting certificate verify locations:
    CAfile: /etc/pki/tls/certs/ca-bundle.crt
    CApath: none]

**Comment by zvonkok** [comment]
@rspierz Do you have self signed certificates? Are you using a MITM proxy?  
In the case of 1.5 you did not mount the trustedCA: name: ***-ca-trust into the driver-container right? 

Now that you supplied one, the GPU operator will automatically mount this chain of trust into the driver-container. 

The question is what is created there and if you need it for going forward. If you remove the trustedCA setting does the driver-container work?

**Comment by rspierz** [comment]
we have a corporate ca trust. I believe it is a MITM proxy.

In 1.5 we did not mount the trusted ca into the container just the env vars for proxy no proxy.

I need the trusted ca at the cluster level. Where would my cluster ca certs be injected path wise for the driver pods? /etc/pki/tls/certs/ca-bundle.crt does not show my cluster ca certs

**Comment by shivamerla** [comment]
It will be injected under `/etc/pki/ca-trust/extracted/pem`

**Comment by rspierz** [comment]
Oh perhaps this is the error?

`-----END CERTIFICATE-----# ACCVRAIZ1`

the injected proxy one is on top and then the general ca is directly underneath. I think we need an extra line here.

**Comment by shivamerla** [comment]
Interesting..Operator creates an empty configmap `gpu-operator-trusted-ca` in `gpu-operator-resources` project and network operator injects all system and user CA's into it. So may be a bug in Network Operator merging them? @zvonkok ?

https://docs.openshift.com/container-platform/4.6/networking/configuring-a-custom-pki.html?extIdCarryOver=true&sc_cid=701f2000001Css0AAC#certificate-injection-using-operators_configuring-a-custom-pki

**Comment by rspierz** [comment]
if i remove the tls cert mount in the ds of driver, the install goes through without errors. Proxy set is still there. 

I did have to pull k8s-device-plugin image and driver to internal registy to get it working though. Would be great to get those pushed to redhat registry and docker.io

**Comment by shivamerla** [comment]
@rspierz I do see device-plugin image pushed to dockerhub: ```nvidia/k8s-device-plugin:v0.8.2-ubi8```. Driver images were missing and pushing them now. Thanks for pointing this out. What was the issue with accessing nvcr.io?

**Comment by rspierz** [comment]
our clusters have a whitelist and its a hard process to get new external registries added. redhat registries on openshift are whitelisted by default. We have docker.io whitelisted but will soon be removed.

**Comment by shivamerla** [comment]
@rspierz I think you need to work with your org/RedHat to get nvcr.io whitelisted with the cluster as the decision was made to maintain these images only with nvcr.io and docker.io.
