### ISSUE TITLE
Documentation: helm install command from docs.nvidia.com is broken

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#164]
This [documentation](https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html) page still indicates this command to install the GPU Operator on OpenShift from Helm:

```
$  helm install gpu-operator nvidia/gpu-operator --set platform.openshift=true,operator.validator.version=vectoradd-cuda10.2-ubi8,operator.defaultRuntime=crio,nfd.enabled=false,devicePlugin.version=v0.7.3-ubi8,dcgmExporter.version=2.0.13-2.1.2-ubi8,toolkit.version=1.4.0-ubi8 --wait
```

but this configuration is invalid, the `DevicePlugin` crashes with this error:
```
flag provided but not defined: -nvidia-driver-root
Usage of nvidia-device-plugin:
  -device-list-strategy string
    	the desired strategy for passing the device list to the underlying runtime
    	[envvar | volume-mounts] (default "envvar")
  -fail-on-init-error
    	fail the plugin if an error is encountered during initialization, otherwise block indefinitely [default: true]
    	 (default true)
  -mig-strategy string
    	the desired strategy for exposing MIG devices on GPUs that support it
    	[none | single | mixed] (default "none")
  -pass-device-specs
    	pass the list of DeviceSpecs to the kubelet on Allocate()
```
---
This is due to fact that the helm deployment doesn't specify the version of the Operator, so the latest version is used:
```
Pod: gpu-operator-86db95c4b5-f8629
nvcr.io/nvidia/gpu-operator:1.6.1
```

Remember this issue https://github.com/NVIDIA/gpu-operator/issues/113 ?
`--set operator.version=1.4.0` should really be mentioned along with the `helm install` command

**Comment by shivamerla** [comment]
@kpouget Will get this fixed soon.

**Comment by shivamerla** [comment]
Document updated: https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html

**Comment by shivamerla** [comment]
Document updated: https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html

**Comment by kpouget** [comment]
thanks :)
