### ISSUE TITLE
Can't install the GPU Operator on OCP 4.6

### ISSUE THREAD

**Issue by ticlazau** [NVIDIA/gpu-operator#167]
Hello,

I am running on OCP 4.6.17 (Kubernetes Version: v1.19.0+e405995) and I follow the instructions from the online documentation to add the GPU Operator:
https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html#openshift-gpu-clean-up

I am getting in GUI when installing the GPU operator 1.6.2:
`Danger alert:Operator conflicts exist
Installing Operator in selected namespace would cause conflicts with another Operator providing these APIs:
ClusterPolicy (nvidia.com/v1)`

I had previous GPU operator 1.5.2 that has not been installed correctly:
`
(base) coredump@Deceneu ~ % oc project gpu-operator-resources
Already on project "gpu-operator-resources" on server "https://c113-e.eu-de.containers.cloud.ibm.com:30117".

(base) coredump@Deceneu ~ % oc get pods
NAME               READY   STATUS    RESTARTS   AGE
nfd-master-jdhtg   1/1     Running   0          6d11h
nfd-master-k77gt   1/1     Running   0          6d11h
nfd-master-km4pt   1/1     Running   0          6d11h
nfd-master-z9r29   1/1     Running   0          6d11h
nfd-worker-gcmvj   1/1     Running   7          6d11h
nfd-worker-j2zrn   1/1     Running   4          6d11h
nfd-worker-mmln4   1/1     Running   3          6d11h
nfd-worker-zn6fn   1/1     Running   7          6d11h

(base) coredump@Deceneu ~ % oc exec -it nvidia-driver-daemonset-m7mwk nvidia-smi

kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Error from server (NotFound): pods "nvidia-driver-daemonset-m7mwk" not found
`

Any ideas?

Rgds,
F.M.

**Comment by zvonkok** [comment]
Remove all installed operators and delete the ClusterPolicy CRD.
Did you install via OLM? Delete all subscriptions and instances
DId you install via helm? `helm ls --all-namespaces`  delete all instances.

After you removed all instances and the CRD (OLM will not remove the CRD)
try a fresh install.

**Comment by ticlazau** [comment]
Hi @zvonkok
Installation of the operator was done via OCP GUI from the Operator HUB

```
(base) coredump@Deceneu ~ % helm ls --all-namespaces
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

(base) coredump@Deceneu ~ % helm ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
(base) coredump@Deceneu ~ %
```
<img width="1294" alt="Screenshot 2021-03-16 at 11 57 17" src="https://user-images.githubusercontent.com/30878420/111298464-0f2bd000-864f-11eb-9eb4-8a7ceb210c33.png">
<img width="1290" alt="Screenshot 2021-03-16 at 11 56 07" src="https://user-images.githubusercontent.com/30878420/111298478-118e2a00-864f-11eb-8df8-d750e27801b3.png">
<img width="1290" alt="Screenshot 2021-03-16 at 11 56 58" src="https://user-images.githubusercontent.com/30878420/111298472-10f59380-864f-11eb-92c8-ed35e380542c.png">

After deleting the cluster service version of the GPU operator, the GPU operator disappears and reaper in 5 seconds (2 browser refresh cycles)

**Comment by zvonkok** [comment]
Weird warning, is this a disconnected install?

```
$ oc get catalogsources --all-namespaces
NAMESPACE               NAME                  DISPLAY               TYPE
PUBLISHER   AGE
openshift-marketplace   certified-operators   Certified Operators   grpc
Red Hat     12d
openshift-marketplace   community-operators   Community Operators   grpc
Red Hat     12d
openshift-marketplace   redhat-marketplace    Red Hat Marketplace   grpc
Red Hat     12d
openshift-marketplace   redhat-operators      Red Hat Operators     grpc
Red Hat     12d
```

Can you show me the output of ^^ ? Thanks

**Comment by ticlazau** [comment]
`
(base) coredump@Deceneu ~ % oc get catalogsources --all-namespaces

NAMESPACE               NAME                    DISPLAY               TYPE   PUBLISHER        AGE
olm                     operatorhubio-catalog   Community Operators   grpc   OperatorHub.io   14d
openshift-marketplace   certified-operators     Certified Operators   grpc   Red Hat          24d
openshift-marketplace   community-operators     Community Operators   grpc   Red Hat          24d
openshift-marketplace   redhat-marketplace      Red Hat Marketplace   grpc   Red Hat          24d
openshift-marketplace   redhat-operators        Red Hat Operators     grpc   Red Hat          24d
`

**Comment by zvonkok** [comment]
You need to delete the CSV (ClusterServiceVersion) and the operator.

Just for checking if NFD is correctly installed:

oc describe nodes | grep 10de

**Comment by ticlazau** [comment]
I do have a worker with 2x P100 GPUs

```
(base) coredump@Deceneu ~ % oc describe nodes | grep 10de
                    feature.node.kubernetes.io/pci-10de.present=true
```

**Comment by zvonkok** [comment]
oc get deployment --all-namespaces | grep gpu

To see if you have any operator deployments left.

**Comment by ticlazau** [comment]
```
(base) coredump@Deceneu ~ % oc get deployment --all-namespaces | grep gpu
(base) coredump@Deceneu ~ %

```

**Comment by zvonkok** [comment]
oc get crd | grep nvidia

To see if we have an old ClusterPolicy installed

**Comment by ticlazau** [comment]
```
(base) coredump@Deceneu ~ % oc get crd | grep nvidia
(base) coredump@Deceneu ~ %
```

**Comment by ticlazau** [comment]
For some reasons the OLD 1.5.2 GPU Operator has been hooked somewhere in OCP, and I can't delete it because will reaper in 5 seconds and can't install a newer one 1.6.2 (see below images)
<img width="1270" alt="Screenshot 2021-03-16 at 12 26 04" src="https://user-images.githubusercontent.com/30878420/111301945-1228bf80-8653-11eb-965e-092572fa9dfd.png">
<img width="1284" alt="Screenshot 2021-03-16 at 12 26 19" src="https://user-images.githubusercontent.com/30878420/111301955-1523b000-8653-11eb-903d-b0258afe7347.png">

**Comment by ticlazau** [comment]
I tried to debug this for the last 3 days, but no luck so far :(

**Comment by kpouget** [comment]
let's continue listing all:

```
oc get csv -A 
oc get subscription -A
oc get installplan -loperators.coreos.com/gpu-operator-certified.openshift-operators -n openshift-operators
``

**Comment by ticlazau** [comment]
```
(base) coredump@Deceneu ~ %
(base) coredump@Deceneu ~ % oc get csv -A | grep gpu
ai                                                 gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
anonymous                                          gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
calico-system                                      gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
default                                            gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
development                                        gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
fm-backend                                         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
gpu-operator-resources                             gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
gpu-operator-resources                             jupyterlab-operator.v1.0.0           Jupyterlab               1.0.0                                                      Succeeded
gpu-operator-resources                             nfd.4.6.0-202103010126.p0            Node Feature Discovery   4.6.0-202103010126.p0                                      Succeeded
gpu-operator-resources                             opendatahub-operator.v1.0.0          Open Data Hub Operator   1.0.0                   opendatahub-operator.v0.9.0        Succeeded
gpu-operator-resources                             strimzi-cluster-operator.v0.19.0     Strimzi                  0.19.0                  strimzi-cluster-operator.v0.18.0   Succeeded
ibm-cert-store                                     gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
ibm-observe                                        gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
ibm-system                                         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
kube-node-lease                                    gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
kube-public                                        gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
kube-system                                        gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
multi-tenant-assistant                             gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
olm                                                gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-apiserver-operator                       gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-apiserver                                gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-authentication-operator                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-authentication                           gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cloud-credential-operator                gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cluster-csi-drivers                      gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cluster-machine-approver                 gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cluster-node-tuning-operator             gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cluster-samples-operator                 gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cluster-storage-operator                 gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-cluster-version                          gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-config-managed                           gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-config-operator                          gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-config                                   gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-console-operator                         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-console                                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-controller-manager-operator              gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-controller-manager                       gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-dns-operator                             gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-dns                                      gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-etcd-operator                            gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-etcd                                     gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-image-registry                           gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-infra                                    gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-ingress-operator                         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-ingress                                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-insights                                 gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kni-infra                                gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-apiserver-operator                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-apiserver                           gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-controller-manager-operator         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-controller-manager                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-proxy                               gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-scheduler-operator                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-scheduler                           gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-storage-version-migrator-operator   gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-kube-storage-version-migrator            gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-machine-api                              gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-machine-config-operator                  gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-marketplace                              gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-monitoring                               gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-multus                                   gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-network-operator                         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-node                                     gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-openstack-infra                          gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-operator-lifecycle-manager               gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-operators                                gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-ovirt-infra                              gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-roks-metrics                             gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-service-ca-operator                      gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-service-ca                               gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-user-workload-monitoring                 gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift-vsphere-infra                            gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
openshift                                          gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
operators                                          gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
tekton-pipelines                                   gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
test                                               gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
tigera-operator                                    gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
university                                         gpu-operator-certified.v1.5.2        NVIDIA GPU Operator      1.5.2                   gpu-operator-certified.v1.5.1      Replacing
(base) coredump@Deceneu ~ % oc get subscription -A | grep gpu
(base) coredump@Deceneu ~ % oc get installplan -loperators.coreos.com/gpu-operator-certified.openshift-operators -n openshift-operators
NAME            CSV                             APPROVAL    APPROVED
install-2bdkw   gpu-operator-certified.v1.6.0   Automatic   true
```

**Comment by ticlazau** [comment]
Hello,

I manage to install the GPU Operator 1.6.2 after I have uninstalled all installed operators from the OCP cluster. 
Not an elegant way to do it :(, but it worked. 

Rgds,
F.M.

However, I don't see the GPU driver pod getting up, but this may be another story

```
(base) coredump@Deceneu ~ % oc get all -n gpu-operator-resources
NAME                                           READY   STATUS                  RESTARTS   AGE
pod/nfd-master-bj47q                           1/1     Running                 0          12h
pod/nfd-master-dxp4x                           1/1     Running                 0          12h
pod/nfd-master-t22dd                           1/1     Running                 0          12h
pod/nfd-master-wngmk                           1/1     Running                 0          12h
pod/nfd-worker-dqh8r                           1/1     Running                 0          12h
pod/nfd-worker-fqqjz                           1/1     Running                 0          12h
pod/nfd-worker-qjggd                           1/1     Running                 0          12h
pod/nfd-worker-x8d5b                           1/1     Running                 0          12h
pod/nvidia-container-toolkit-daemonset-pg6xq   1/1     Running                 0          9m30s
**pod/nvidia-device-plugin-daemonset-pfrlf       0/1     Init:CrashLoopBackOff   6          6m26s**
pod/nvidia-driver-daemonset-5f42b              1/1     Running                 0          10m

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
service/nfd-master   ClusterIP   172.21.31.27   <none>        12000/TCP   7d15h

NAME                                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/nfd-master                           4         4         4       4            4           node-role.kubernetes.io/master=   7d15h
daemonset.apps/nfd-worker                           4         4         4       4            4           <none>                            7d15h
daemonset.apps/nvidia-container-toolkit-daemonset   1         1         1       1            1           nvidia.com/gpu.present=true       9m30s
daemonset.apps/nvidia-device-plugin-daemonset       1         1         0       1            0           nvidia.com/gpu.present=true       6m26s
daemonset.apps/nvidia-driver-daemonset              1         1         1       1            1           nvidia.com/gpu.present=true       10m

```

**Comment by kpouget** [comment]
Hello,
you can try looking at the logs of "

pod/nvidia-driver-daemonset-5f42b

"
maybe it is (was) still building the driver, that could explain why the
deviceplugin is (temporarily) failing

**Comment by shivamerla** [comment]
@ticlazau  Please check the logs of `driver` pod to see if the driver installation is successful in the end. Also, from the device-plugin initContainer check logs too `oc logs nvidia-device-plugin-daemonset-pfrlf -c toolkit-validation -n gpu-operator-resources`. Please attach those logs here too for our analysis.

**Comment by ticlazau** [comment]
```
(base) coredump@Deceneu GPU % oc logs nvidia-device-plugin-daemonset-pfrlf -c toolkit-validation -n gpu-operator-resources
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!
```

++

```
(base) coredump@Deceneu GPU % oc exec -it nvidia-driver-daemonset-5f42b nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Wed Mar 17 20:27:49 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
| N/A   31C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:D8:00.0 Off |                    0 |
| N/A   31C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by shivamerla** [comment]
@ticlazau Can you run following command from debug pod and verify if CRIO is looking under `/run/containers/oci/hooks.d` for nvidia runtime?

`cat /etc/crio/crio.conf.d/00-default`

**Comment by shivamerla** [comment]
@ticlazau Probably this is the reason. With RHEL 7.x CRIO config might not be set to use hooks-dir as `/run/containers/oci/hooks.d`. Can you configure this and verify?

**Comment by ablocus** [comment]
@shivamerla If you can specify which `debug pod` to run the cmd from I can try it; i have the same issue with my `nvidia-device-plugin-daemonset` pods.
Also, if that happen to be the problem, how does one resolve it?

**Comment by shivamerla** [comment]
@ablocus if that is the case then, `/run/containers/oci/hooks.d` needs to be added to hooks_dir in `/etc/crio/crio.conf`. To confirm this you can use below commands and check hooks_dir configuration.

oc debug node/<worker-node-name>
# cat /host/etc/crio/crio.conf.d/00-default 
[crio.api]
stream_address = ""
stream_port = "10010"

[crio.runtime]
conmon = "/usr/libexec/crio/conmon"
conmon_cgroup = "pod"
default_env = [
    "NSS_SDB_USE_CACHE=no",
]
log_level = "info"
cgroup_manager = "systemd"
default_sysctls = [
    "net.ipv4.ping_group_range=0 2147483647",
]
hooks_dir = [
    "/etc/containers/oci/hooks.d",
    "/run/containers/oci/hooks.d",
]
manage_ns_lifecycle = true

[crio.image]
global_auth_file = "/var/lib/kubelet/config.json"
pause_image = "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f3b16fb1ea070be814a631a70a664280ca18879b635fb012eb38584ab09f786e"
pause_image_auth_file = "/var/lib/kubelet/config.json"
pause_command = "/usr/bin/pod"

[crio.network]
network_dir = "/etc/kubernetes/cni/net.d/"
plugin_dirs = [
    "/var/lib/cni/bin",
    "/usr/libexec/cni",
]

[crio.metrics]
enable_metrics = true
metrics_port = 9537

**Comment by ablocus** [comment]
@shivamerla I've verified that `/run/containers/oci/hooks.d` wasn't part of `hooks_dir`; i've added it and reloaded `crio` and it now looks like this:
`

[crio]
  root = "/var/data/criorootstorage"
  runroot = "/var/data/crioruntimestorage"
  storage_driver = "overlay"
  log_dir = "/var/log/pods"
  version_file = "/var/run/crio/version"
  version_file_persist = "/var/lib/crio/version"
  [crio.api]
    grpc_max_send_msg_size = 16777216
    grpc_max_recv_msg_size = 16777216
    listen = "/var/run/crio/crio.sock"
    stream_address = "127.0.0.1"
    stream_port = "0"
    stream_enable_tls = false
    stream_tls_cert = ""
    stream_tls_key = ""
    stream_tls_ca = ""
    stream_idle_timeout = "15m"
  [crio.runtime]
    conmon_env = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
    hooks_dir = ["/etc/containers/oci/hooks.d", "**/run/containers/oci/hooks.d**"]
    default_mounts = []
    default_capabilities = ["CHOWN", "DAC_OVERRIDE", "FSETID", "FOWNER", "NET_RAW", "SETGID", "SETUID", "SETPCAP", "NET_BIND_SERVICE", "SYS_CHROOT", "KILL"]
    default_env = []
.......`

Now the pods are failing with this message

`Warning  Failed          19m                        kubelet, 10.241.31.200  Error: container create failed: time="2021-03-26T15:18:23-05:00" level=error msg="container_linux.go:366: starting container process caused: process_linux.go:472: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: /usr/local/nvidia/toolkit/nvidia-container-cli.real: /lib64/libc.so.6: version GLIBC_2.27 not found (required by /usr/local/nvidia/toolkit/libnvidia-container.so.1)\n"`

The `device-plugin` image i'm using is `nvcr.io/nvidia/k8s-device-plugin@sha256:ea353fe57628f4d3c3e1cda126455d02f2277e3ee92fa9da441d409d76b2ac92`

**Comment by shivamerla** [comment]
@ablocus Can you confirm the container-toolkit image tag too?

**Comment by ablocus** [comment]
@shivamerla 
nvidia-container-toolkit : nvcr.io/nvidia/cuda@sha256:ed723a1339cddd75eb9f2be2f3476edf497a1b189c10c9bf9eb8da4a16a51a59

**Comment by shivamerla** [comment]
That is for the initContainer, can you get for the main toolkit container in that pod?

**Comment by ablocus** [comment]
Here : nvcr.io/nvidia/k8s/container-toolkit:1.3.0

**Comment by shivamerla** [comment]
For RHEL7/CentOS we need to use UBI tag for toolkit. Please change it to `nvcr.io/nvidia/k8s/container-toolkit:1.4.7-ubi8`

**Comment by ablocus** [comment]
That was it.

`nvidia-driver : nvcr.io/nvidia/driver:450.80.02-rhel7.9`
`nvidia-device-plugin : nvcr.io/nvidia/k8s-device-plugin@sha256:ea353fe57628f4d3c3e1cda126455d02f2277e3ee92fa9da441d409d76b2ac92` 
`nvidia-container-toolkit : nvcr.io/nvidia/k8s/container-toolkit:1.4.7-ubi8`

Do you have any recommendation on the `nvidia-dcgm-exporter` version I should use. Those pods aren't coming up so far, but i can see the GPU being recognized by the cluster.

**Comment by shivamerla** [comment]
DCGM tag would be `2.1.4-2.2.0-ubi8`

**Comment by ablocus** [comment]
@shivamerla Thank you
All pods under `gpu-operator-resources` are up and running now
`oc -n gpu-operator-resources get pods

NAME                                       READY   STATUS      RESTARTS   AGE
gpu-feature-discovery-2b7rv                1/1     Running     0          2m24s
gpu-feature-discovery-8hb26                1/1     Running     0          2m24s
gpu-feature-discovery-b9wmd                1/1     Running     0          2m23s
gpu-feature-discovery-kcz2l                1/1     Running     0          2m24s
gpu-feature-discovery-n8fb2                1/1     Running     0          2m23s
gpu-feature-discovery-nv8b6                1/1     Running     0          2m24s
gpu-feature-discovery-nxtq2                1/1     Running     0          2m24s
gpu-feature-discovery-t9rxk                1/1     Running     0          2m24s
gpu-feature-discovery-w95qc                1/1     Running     0          2m23s
gpu-feature-discovery-z8cmk                1/1     Running     0          2m24s
nvidia-container-toolkit-daemonset-8s9jb   1/1     Running     0          5m22s
nvidia-container-toolkit-daemonset-9h86m   1/1     Running     0          5m23s
nvidia-container-toolkit-daemonset-f47j2   1/1     Running     0          5m22s
nvidia-container-toolkit-daemonset-g6stx   1/1     Running     0          5m23s
nvidia-container-toolkit-daemonset-g84fd   1/1     Running     0          5m22s
nvidia-container-toolkit-daemonset-ghpqp   1/1     Running     0          5m23s
nvidia-container-toolkit-daemonset-hcg5d   1/1     Running     0          5m23s
nvidia-container-toolkit-daemonset-kdzmx   1/1     Running     0          5m23s
nvidia-container-toolkit-daemonset-p5c2m   1/1     Running     0          5m23s
nvidia-container-toolkit-daemonset-tsn6c   1/1     Running     0          5m23s
nvidia-dcgm-exporter-5fsqc                 1/1     Running     0          2m41s
nvidia-dcgm-exporter-5vgbx                 1/1     Running     0          2m41s
nvidia-dcgm-exporter-8f7qq                 1/1     Running     0          2m42s
nvidia-dcgm-exporter-bcp5s                 1/1     Running     0          2m42s
nvidia-dcgm-exporter-bfcvj                 1/1     Running     0          2m41s
nvidia-dcgm-exporter-ldcp2                 1/1     Running     0          2m42s
nvidia-dcgm-exporter-m8ckr                 1/1     Running     0          2m42s
nvidia-dcgm-exporter-qpr6m                 1/1     Running     0          2m42s
nvidia-dcgm-exporter-sfncv                 1/1     Running     0          2m42s
nvidia-dcgm-exporter-tdmmz                 1/1     Running     0          2m42s
nvidia-device-plugin-daemonset-7fpdq       1/1     Running     0          2m58s
nvidia-device-plugin-daemonset-7hnhb       1/1     Running     0          2m59s
nvidia-device-plugin-daemonset-8ckps       1/1     Running     0          2m58s
nvidia-device-plugin-daemonset-btvnk       1/1     Running     0          2m58s
nvidia-device-plugin-daemonset-jfww9       1/1     Running     0          2m58s
nvidia-device-plugin-daemonset-m8crr       1/1     Running     0          2m58s
nvidia-device-plugin-daemonset-mcx7s       1/1     Running     0          2m58s
nvidia-device-plugin-daemonset-nj4nd       1/1     Running     0          2m59s
nvidia-device-plugin-daemonset-rmvxk       1/1     Running     0          2m59s
nvidia-device-plugin-daemonset-zffpv       1/1     Running     0          2m58s
nvidia-device-plugin-validation            0/1     Completed   0          2m46s
nvidia-driver-daemonset-2hr69              1/1     Running     0          5m29s
nvidia-driver-daemonset-7gngj              1/1     Running     0          5m29s
nvidia-driver-daemonset-88ptp              1/1     Running     0          5m29s
nvidia-driver-daemonset-8vsfk              1/1     Running     0          5m29s
nvidia-driver-daemonset-c5ndx              1/1     Running     0          5m29s
nvidia-driver-daemonset-dhlwd              1/1     Running     0          5m29s
nvidia-driver-daemonset-hvrr5              1/1     Running     0          5m29s
nvidia-driver-daemonset-nfwxm              1/1     Running     0          5m29s
nvidia-driver-daemonset-r9g2l              1/1     Running     0          5m29s
nvidia-driver-daemonset-xdc9m              1/1     Running     0          5m29s`
