### ISSUE TITLE
How do I apply the ClusterPolicy CRD? 

### ISSUE THREAD

**Issue by lamroger** [NVIDIA/gpu-operator#169]
I'm having trouble finding instructions on how to install the ClusterPolicy CRD.

I've tried
```
kubectl apply -f https://github.com/NVIDIA/gpu-operator/blob/1.6.2/deploy/crds/nvidia.com_clusterpolicies_crd.yaml
```
and get 
```
error: error parsing https://github.com/NVIDIA/gpu-operator/blob/1.6.2/deploy/crds/nvidia.com_clusterpolicies_crd.yaml: error converting YAML to JSON: yaml: line 91: mapping values are not allowed in this context
```

**Comment by shivamerla** [comment]
@lamroger  Please use this instead: https://github.com/NVIDIA/gpu-operator/blob/1.6.2/bundle/manifests/nvidia.com_clusterpolicies.yaml

**Comment by lamroger** [comment]
Thanks for the quick reply @shivamerla !

I'm still getting the same error though
```
kubectl apply -f https://github.com/NVIDIA/gpu-operator/blob/1.6.2/bundle/manifests/nvidia.com_clusterpolicies.yaml
error: error parsing https://github.com/NVIDIA/gpu-operator/blob/1.6.2/bundle/manifests/nvidia.com_clusterpolicies.yaml: error converting YAML to JSON: yaml: line 91: mapping values are not allowed in this context
```

**Comment by shivamerla** [comment]
Here is the URL for raw file: https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/bundle/manifests/nvidia.com_clusterpolicies.yaml

**Comment by lamroger** [comment]
thank you! it worked 
`kubectl apply -f https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/bundle/manifests/nvidia.com_clusterpolicies.yaml`
