### ISSUE TITLE
why I cannot use the Nvidia plugging device? 

### ISSUE THREAD

**Issue by tamaramiteva** [NVIDIA/gpu-operator#17]
I have  the device plugging running iside the gpu-operator:
NAME                                       READY   STATUS      RESTARTS   AGE
nvidia-container-toolkit-daemonset-cx9wj   1/1     Running     1          6d
nvidia-device-plugin-daemonset-pl4mh       1/1     Running     0          5d23h
nvidia-device-plugin-validation            0/1     Completed   0          5d23h

But when I try to create new job I get the error:
kubectl create -f cifar10-job-2.yml

error: error validating "job-2.yml": error validating data: [ValidationError(Job.spec.template.spec): unknown field "computeResources" in io.k8s.api.core.v1.PodSpec, ValidationError(Job.spec.template.spec.containers[0]): unknown field "computeResourceRequests" in io.k8s.api.core.v1.Container]; if you choose to ignore these errors, turn validation off with --validate=false

The "computeResources" arg in the yml file should be recognized by the device-plugging but it's not?
Any idea why is that?

**Comment by RenaudWasTaken** [comment]
Hello!

The GPU Operator works with Vanilla Kubernetes, unfortunately "computeResourceRequests" is not part of Vanilla Kubernetes.

You can just fill the resource.limits field to ask for GPUs: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

Hope this helps!
