### ISSUE TITLE
Error pulling a driver: manifest unknown

### ISSUE THREAD

**Issue by lamroger** [NVIDIA/gpu-operator#170]
Hi, I'm seeing an error when I try to run the helm chart.

```
  Warning  Failed     6m59s (x4 over 8m21s)   kubelet            Failed to pull image "nvcr.io/nvidia/driver:460.32.03-amzn2": rpc error: code = Unknown desc = Error response from daemon: manifest for nvcr.io/nvidia/driver:460.32.03-amzn2 not found: manifest unknown: manifest unknown
```
I'm mostly using the default config on an AWS instance

**Comment by shivamerla** [comment]
@lamroger we officially support only these OS distributions: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#linux-distributions

Probably for Amazon Linux, you can use `460.32.03-centos7` image, but we have not verified with that.

**Comment by lamroger** [comment]
thank you again @shivamerla!

**Comment by lamroger** [comment]
Hi @shivamerla , hopefully last question. 
Would I specify the version in my values file like this?
```
gpu-operator:
  driver:
    version: "460.32.03-centos7"
```

If I do it like that, no gpu operator resources show up and I'm not sure how to debug. Thank you again.

**Comment by shivamerla** [comment]
@lamroger gpu-operator will append OS_TAG to the version specified in values.yaml. So either you can re-tag the CentOS image and push it to your registry or you can directly edit the driver Daemonset to change the image you want to deploy. Also if using CentOS based image, you might need to change the toolkit also to be `1.4.7-ubi8`.

**Comment by lamroger** [comment]
@shivamerla Thanks for your help! We decided to stick with just using the docker images to avoid managing more home grown tweaks.

**Comment by v1nc3nt27** [comment]
@lamroger Did this work for you? I also ran into this problem. I changed the driver to the centos one, but without the toolkit (I guess), none of the gpu resource pods will start. I changed the toolkit to what @shivamerla  suggested, but I think there is only, 1.7.0 and 1.7.1 versions available in the repo (nvcr.io/nvidia/cloud-native/gpu-operator-validator), so I'm a bit at a loss here. Any help would be very much appreciated. Thanks!

**Comment by shivamerla** [comment]
@v1nc3nt27 you are looking at wrong repo for toolkit. They are here: https://ngc.nvidia.com/catalog/containers/nvidia:k8s:container-toolkit/tags. Also, if this doesn't work then you can try with experimental centos7 image for toolkit: ```--set toolkit.version=devel-centos7```.

**Comment by v1nc3nt27** [comment]
@shivamerla Thanks a lot for the hint, I'll try it with that version of the toolkit. Is it correct that the driver pod needs to be successfully deployed before any of the other pods start? Because it just states `Could not unload NVIDIA driver kernel modules, driver is in use` and the other pods are waiting endlessly.

**Comment by shivamerla** [comment]
@v1nc3nt27 please refer to [this](https://github.com/NVIDIA/gpu-operator/issues/219#issuecomment-874371249) comment to unload existing modules.

**Comment by v1nc3nt27** [comment]
@shivamerla Unfortunately the gpu could still not be unloaded, even a restart didn't help. Perhaps there is something else installed/running on the Amazon Linux OS, it's really weird. Anyhow, I switched to EKS-supported Ubuntu 20 version and the driver is getting installed just fine. Thanks for your help!
