### ISSUE TITLE
Cannot deploy the "master" branch on OpenShift

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#175]
Hello,

I tried to deploy the GPU Operator from the master branch today, but it fails at this stage:
```
NAME                                       READY   STATUS     RESTARTS   AGE
nvidia-container-toolkit-daemonset-xpb75   1/1     Running    0          6h28m
nvidia-device-plugin-daemonset-dz822       0/1     Init:0/1   0          6h25m
nvidia-driver-daemonset-9k77n              1/1     Running    0          6h30m
```
and in the description of the DevicePlugin:
```
Warning  FailedCreatePodSandBox  4m15s (x1760 over 6h24m)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to find runtime handler nvidia from runtime list map[runc:0xc00044e460]
```

The last successful testing we did was on March 22nd. On March 23rd our CI cluster was down,
and since March 24th, the testing was failing because this [PR](https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/188) moved the location of the `Dockerfile` and I couldn't fix it until today

**Comment by shivamerla** [comment]
Resolved with: https://github.com/NVIDIA/gpu-operator/commit/ec57697c16d6740b8e4ec850cbbef1101695111e
