### ISSUE TITLE
On containerd - Failed to unpack image "quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0"

### ISSUE THREAD

**Issue by vaibhavraizada-hcl** [NVIDIA/gpu-operator#177]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
On a kubernetes cluster with containerd as runtime, the installation of gpu-operator fails with below error:

![image](https://user-images.githubusercontent.com/36700822/113541411-cb016f00-95ff-11eb-841d-9b149a38a840.png)

### 2. Steps to reproduce the issue
1. Set up a kubernetes cluster with runtime as containerd.
2.  Use helm and try to install gpu-operator with belwo command
helm install --wait --generate-name nvidia/gpu-operator --set operator.defaultRuntime=containerd
3. The helm install fails with below error:

![image](https://user-images.githubusercontent.com/36700822/113541356-ac9b7380-95ff-11eb-816c-439f9ee21d8a.png)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [x] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by shivamerla** [comment]
@vaibhavraizada-hcl Looks to be intermittent issue with quay.io. I have verified that NFD image is fine.

```
$ docker pull quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0
v0.6.0: Pulling from kubernetes_incubator/node-feature-discovery
e62d08fa1eb1: Pull complete 
a9b7f910274d: Pull complete 
fc59af4729df: Pull complete 
Digest: sha256:a1e72dbc35a16cbdcf0007fc4fb207bce723ff67c61853d2d8d8051558ce6de7
Status: Downloaded newer image for quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0
quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0
```

**Comment by vaibhavraizada-hcl** [comment]
@shivamerla 

Please note that my kubernetes cluster is running on containerd. You have tried a "docker pull" command which would work but not the containerd pull. See the ouput of "ctr pull" command:

ctr image pull quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0
quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0:                       resolved       |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:a1e72dbc35a16cbdcf0007fc4fb207bce723ff67c61853d2d8d8051558ce6de7: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:e62d08fa1eb18131b4109c7cbece97f4f7e37d6ea09845a21beb3a899d0c963d:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:fc59af4729df0bc2a2dea2a29860c5dd311f79bb564638800847bc562f624f0a:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:a9b7f910274d40e906910707d377a0f1ccac1d5051ae8c6be4b91f1ef4f7c133:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:b7f4ca5c9efca39b2eddbbcb372bffb05d9b458293d03b0626dde71cf5515f54:   done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 0.5 s                                                                    **total:   0.0 B (0.0 B/s)**
unpacking linux/amd64 sha256:a1e72dbc35a16cbdcf0007fc4fb207bce723ff67c61853d2d8d8051558ce6de7...
INFO[0000] apply failure, attempting cleanup             **error="failed to extract layer sha256:83b43189420d069cbdc1421b94c396c6b74d1ad8150933d411a223b145b981ab: failed to get stream processor for application/vnd.docker.image.rootfs.diff.tar.gzip: fork/exec /usr/bin/unpigz: no such file or directory: unknown"** key="extract-676983304-Is1a sha256:83b43189420d069cbdc1421b94c396c6b74d1ad8150933d411a223b145b981ab"
ctr: failed to extract layer sha256:83b43189420d069cbdc1421b94c396c6b74d1ad8150933d411a223b145b981ab: failed to get stream processor for application/vnd.docker.image.rootfs.diff.tar.gzip: fork/exec /usr/bin/unpigz: no such file or directory: unknown

**Comment by shivamerla** [comment]
Its working with containerd too. Do you see this on all systems?

```
$ sudo ctr image pull quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0
quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0:                       resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:a1e72dbc35a16cbdcf0007fc4fb207bce723ff67c61853d2d8d8051558ce6de7: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:fc59af4729df0bc2a2dea2a29860c5dd311f79bb564638800847bc562f624f0a:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:b7f4ca5c9efca39b2eddbbcb372bffb05d9b458293d03b0626dde71cf5515f54:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:e62d08fa1eb18131b4109c7cbece97f4f7e37d6ea09845a21beb3a899d0c963d:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:a9b7f910274d40e906910707d377a0f1ccac1d5051ae8c6be4b91f1ef4f7c133:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 0.5 s                                                                    total:  948.0  (1.9 KiB/s)                                       
unpacking linux/amd64 sha256:a1e72dbc35a16cbdcf0007fc4fb207bce723ff67c61853d2d8d8051558ce6de7...
done
```

**Comment by vaibhavraizada-hcl** [comment]
@shivamerla 

The issue was with my VM. The error says it all: 
/usr/bin/unpigz: no such file or directory

We can mark this issue as non-applicable.
