### ISSUE TITLE
nvidia-smi not found after installing gpu-operator

### ISSUE THREAD

**Issue by benjaminhuo** [NVIDIA/gpu-operator#178]
### 1. Quick Debug Checklist
- [x ] Are you running on an Ubuntu 18.04 node?
- [x ] Are you running Kubernetes v1.13+?
- [ x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
```yaml
root@gpu-worker2:~# nvidia-smi
Command 'nvidia-smi' not found, but can be installed with:
apt install nvidia-340      
apt install nvidia-utils-390
```
### 2. Steps to reproduce the issue
Install gpu-operator following the guide, and the validation job runs successfully.
Then run ` nvidia-smi` on the gpu node

Just wondering how to run `nvidia-smi` after gpu-operator is installed

**Comment by klueska** [comment]
The operator installs all of the driver software on the host under `/run/nvidia/driver`. As such, it will be made available to containers launched on Kubernetes (via the nvidia-container-toolkit), but is not (immediately) available to programs running on the host.

If you are trying to run `nvidia-smi` from the host (which it appears you are), then the easiest way to do this is to run it while `chroot`ed into `/run/nvidia/driver`, i.e.
```
chroot /run/nvidia/driver nvidia-smi
```

**Comment by benjaminhuo** [comment]
> The operator installs all of the driver software on the host under `/run/nvidia/driver`. As such, it will be made available to containers launched on Kubernetes (via the nvidia-container-toolkit), but is not (immediately) available to programs running on the host.
> 
> If you are trying to run `nvidia-smi` from the host (which it appears you are), then the easiest way to do this is to run it while `chroot`ed into `/run/nvidia/driver`, i.e.
> 
> ```
> chroot /run/nvidia/driver nvidia-smi
> ```

Thanks `chroot /run/nvidia/driver nvidia-smi` works for me!
And gpu-operator is really convenient to use GPU!

Ben

**Comment by ryanwcyin** [comment]
@klueska Can I mount the /run/nvidia/driver to the user home to run the nvidia-smi command?
