### ISSUE TITLE
Could not build the driver with the default version (image: nvidia/driver:418.40.04-ubuntu18.04)

### ISSUE THREAD

**Issue by gaopengw** [NVIDIA/gpu-operator#18]
### 1. Quick Debug Checklist
- [ yes] Are you running on an Ubuntu 18.04 node?
ans: 18.04
- [ yes] Are you running Kubernetes v1.13+?
ans: v1.16.2"
- [ yes] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
ans: v19.03
- [yes ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
ans: $ lsmod | grep ipmi
ipmi_devintf           20480  0
ipmi_msghandler       102400  1 ipmi_devintf

- [ yes] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`)
ans: $ kubectl describe specialresources --all-namespaces
Name:         gpu
Namespace:    gpu-operator-resources
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"sro.openshift.io/v1alpha1","kind":"SpecialResource","metadata":{"annotations":{},"name":"gpu","namespace":"gpu-operator-res...
API Version:  sro.openshift.io/v1alpha1
Kind:         SpecialResource
Metadata:
  Creation Timestamp:  2019-12-03T23:02:56Z
  Generation:          1
  Resource Version:    3986121
  Self Link:           /apis/sro.openshift.io/v1alpha1/namespaces/gpu-operator-resources/specialresources/gpu
  UID:                 10670f28-2e12-48fb-9a3b-3409f0fa7850
Spec:
  Scheduling Type:  None
Events:             <none>

### 1. Issue or feature description
The driver will not build in the container of nvidia-driver: (418.40.04)
The log shows 'cc_version_check' error:
========== NVIDIA Software Installer ==========
Starting installation of NVIDIA driver version 418.40.04 for Linux kernel version 4.18.0-17-generic
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Resolving Linux kernel version...
Proceeding with Linux kernel version 4.18.0-17-generic
Installing Linux kernel headers...
Installing Linux kernel module files...
Generating Linux kernel version string...
Compiling NVIDIA driver kernel modules...
make[2]: *** [cc_version_check] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/usr/src/nvidia-418.40.04/kernel] Error 2
make: *** [modules] Error 2
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...

### 2. Steps to reproduce the issue
(With pre-req configured, i.e. nvidia helm repo added)
2.1 install the gpu-operator helm-chart: 
helm install --devel nvidia/gpu-operator -n test-operator --wait

2.2 kubectl apply -f https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/manifests/cr/sro_cr_sched_none.yaml

2.3 check the logs of nvidia-driver-daemonset:
kubectl logs nvidia-driver-daemonset -n gpu-operator-resources

2.4 get the message about the error:
...
Compiling NVIDIA driver kernel modules...
make[2]: *** [cc_version_check] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/usr/src/nvidia-418.40.04/kernel] Error 2
make: *** [modules] Error 2
...

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
$ kubectl get pods --all-namespaces
NAMESPACE                NAME                                              READY   STATUS             RESTARTS   AGE
gpu-operator-resources   nvidia-container-toolkit-daemonset-pxcjp          1/1     Running            0          175m
gpu-operator-resources   nvidia-driver-daemonset-6l898                     0/1     CrashLoopBackOff   37         175m
gpu-operator-resources   nvidia-driver-validation                          0/1     CrashLoopBackOff   39         175m
gpu-operator             special-resource-operator-5bb45fdc46-bwlvc        1/1     Running            0          176m
kube-system              calico-kube-controllers-6d85fdfbd8-j6pxh          1/1     Running            1          33d
kube-system              calico-node-7gjkr                                 1/1     Running            0          179m
kube-system              calico-node-j779x                                 1/1     Running            1          33d
kube-system              coredns-5644d7b6d9-6wj7h                          1/1     Running            1          33d
kube-system              coredns-5644d7b6d9-ckkg8                          1/1     Running            1          33d
kube-system              etcd-sc-ipp-blossom-k8ctl-01                      1/1     Running            1          33d
kube-system              kube-apiserver-sc-ipp-blossom-k8ctl-01            1/1     Running            5          33d
kube-system              kube-controller-manager-sc-ipp-blossom-k8ctl-01   1/1     Running            2          33d
kube-system              kube-proxy-dpmlr                                  1/1     Running            1          33d
kube-system              kube-proxy-hx2vm                                  1/1     Running            0          179m
kube-system              kube-scheduler-sc-ipp-blossom-k8ctl-01            1/1     Running            2          33d
kube-system              tiller-deploy-969865475-kxwxb                     1/1     Running            0          21h
node-feature-discovery   nfd-master-lkq4b                                  1/1     Running            0          176m
node-feature-discovery   nfd-worker-lw2z2                                  1/1     Running            0          176m

 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
$ kubectl get ds --all-namespaces
NAMESPACE                NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                                                                       AGE
gpu-operator-resources   nvidia-container-toolkit-daemonset   1         1         1       1            1           feature.node.kubernetes.io/pci-10de.present=true                                                                    176m
gpu-operator-resources   nvidia-driver-daemonset              1         1         0       1            0           feature.node.kubernetes.io/kernel-version.full=4.18.0-17-generic,feature.node.kubernetes.io/pci-10de.present=true   176m
kube-system              calico-node                          2         2         2       2            2           beta.kubernetes.io/os=linux                                                                                         33d
kube-system              kube-proxy                           2         2         2       2            2           beta.kubernetes.io/os=linux                                                                                         33d
node-feature-discovery   nfd-master                           1         1         1       1            1           node-role.kubernetes.io/master=                                                                                     177m
node-feature-discovery   nfd-worker                           1         1         1       1            1           <none>                                                                                                              177m

 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
$ kubectl describe pod nvidia-driver-daemonset-6l898 -n gpu-operator-resources
Name:         nvidia-driver-daemonset-6l898
Namespace:    gpu-operator-resources
Priority:     0
Node:         nvc-t2-123/10.33.22.179
Start Time:   Wed, 04 Dec 2019 10:03:31 -0800
Labels:       app=nvidia-driver-daemonset
              controller-revision-hash=5bc8f557b8
              pod-template-generation=1
Annotations:  cni.projectcalico.org/podIP: 192.168.29.67/32
              scheduler.alpha.kubernetes.io/critical-pod: 
Status:       Running
IP:           192.168.29.67
IPs:
  IP:           192.168.29.67
Controlled By:  DaemonSet/nvidia-driver-daemonset
Containers:
  nvidia-driver-ctr:
    Container ID:  docker://a457385922c674e22ad6e17fc7eb51002d6cc2c82c589266e9d33fd8d9fd1a45
    Image:         nvidia/driver:418.40.04-ubuntu18.04
    Image ID:      docker-pullable://nvidia/driver@sha256:e735e0f4f28d64584bd0641093c758cb709e0359241d9cfec4059a83cc20c6b4
    Port:          <none>
    Host Port:     <none>
    Command:
      nvidia-driver
    Args:
      init
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 04 Dec 2019 12:56:02 -0800
      Finished:     Wed, 04 Dec 2019 12:56:14 -0800
    Ready:          False
    Restart Count:  37
    Environment:    <none>
    Mounts:
      /etc/containers/oci/hooks.d from config (rw)
      /host from host (rw)
      /run/nvidia from run-nvidia (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nvidia-driver-token-wpbs9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  host:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  
  run-nvidia:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:  
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      nvidia-driver
    Optional:  false
  nvidia-driver-token-wpbs9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nvidia-driver-token-wpbs9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  feature.node.kubernetes.io/kernel-version.full=4.18.0-17-generic
                 feature.node.kubernetes.io/pci-10de.present=true
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:
  Type     Reason   Age                     From                 Message
  ----     ------   ----                    ----                 -------
  Warning  BackOff  2m11s (x763 over 176m)  kubelet, nvc-t2-123  Back-off restarting failed container

 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`
$ kubectl logs nvidia-driver-daemonset-6l898 -n gpu-operator-resources

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 418.40.04 for Linux kernel version 4.18.0-17-generic

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Resolving Linux kernel version...
Proceeding with Linux kernel version 4.18.0-17-generic
Installing Linux kernel headers...
Installing Linux kernel module files...
Generating Linux kernel version string...
Compiling NVIDIA driver kernel modules...
make[2]: *** [cc_version_check] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [_module_/usr/src/nvidia-418.40.04/kernel] Error 2
make: *** [modules] Error 2
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
$ sudo docker run -it alpine echo foo
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
89d9c30c1d48: Already exists 
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
foo

 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
$ cat /etc/docker/daemon.json
{
  "runtimes": {
    "nvidia": {
      "path": "/run/nvidia/toolkit/nvidia-container-runtime"
    }
  },
  "default-runtime": "nvidia"
}

 - [ ] Docker runtime configuration: `docker info | grep runtime`
$ sudo docker info  | grep runtime
WARNING: No swap limit support

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
$ ls -la /run/nvidia
total 8
drwxr-xr-x  3 root root   80 Dec  4 13:01 .
drwxr-xr-x 40 root root 1300 Dec  4 10:03 ..
drwxr-xr-x  3 root root 4096 Dec  4 10:03 toolkit
-rw-r--r--  1 root root    6 Dec  4 10:03 toolkit.pid

 - [ ] NVIDIA packages directory: `ls -la /run/nvidia/toolkit`
$ ls -la /run/nvidia/toolkit
total 3996
drwxr-xr-x 3 root root    4096 Dec  4 10:03 .
drwxr-xr-x 3 root root      80 Dec  4 13:01 ..
drwxr-xr-x 3 root root    4096 Dec  4 10:03 .config
lrwxrwxrwx 1 root root      30 Dec  4 10:03 libnvidia-container.so.1 -> ./libnvidia-container.so.1.0.5
-rwxr-xr-x 1 root root  151088 Dec  4 10:03 libnvidia-container.so.1.0.5
-rwxr-xr-x 1 root root     136 Dec  4 10:03 nvidia-container-cli
-rwxr-xr-x 1 root root   34832 Dec  4 10:03 nvidia-container-cli.real
-rwxr-xr-x 1 root root     148 Dec  4 10:03 nvidia-container-runtime
lrwxrwxrwx 1 root root      26 Dec  4 10:03 nvidia-container-runtime-hook -> ./nvidia-container-toolkit
-rwxr-xr-x 1 root root 2008936 Dec  4 10:03 nvidia-container-runtime.real
-rwxr-xr-x 1 root root     177 Dec  4 10:03 nvidia-container-toolkit
-rwxr-xr-x 1 root root 1871848 Dec  4 10:03 nvidia-container-toolkit.real

 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
$ ls -la /run/nvidia/driver
ls: cannot access '/run/nvidia/driver': No such file or directory

 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`
(repeating)
Dec 04 13:03:53 nvc-t2-123 kubelet[1078]: E1204 13:03:53.073746    1078 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Dec 04 13:03:55 nvc-t2-123 kubelet[1078]: E1204 13:03:55.147398    1078 dns.go:135] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.33.22.57 10.33.24.57 10.33.22.58
Dec 04 13:03:57 nvc-t2-123 kubelet[1078]: E1204 13:03:57.146327    1078 pod_workers.go:191] Error syncing pod 8c98f55d-1457-4fc1-9b1c-90b18f65f43f ("nvidia-driver-daemonset-6l898_gpu-operator-resources(8c98f55d-1457-4fc1-9b1c-90b18f65f43f)"), skipping: failed to "StartContainer" for "nvidia-driver-ctr" with CrashLoopBackOff: "back-off 5m0s restarting failed container=nvidia-driver-ctr pod=nvidia-driver-daemonset-6l898_gpu-operator-resources(8c98f55d-1457-4fc1-9b1c-90b18f65f43f)"
Dec 04 13:04:00 nvc-t2-123 kubelet[1078]: E1204 13:04:00.146374    1078 pod_workers.go:191] Error syncing pod dc8b0aad-9bef-4b51-a6bd-c887ee421e5d ("nvidia-driver-validation_gpu-operator-resources(dc8b0aad-9bef-4b51-a6bd-c887ee421e5d)"), skipping: failed to "StartContainer" for "cuda-vector-add" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cuda-vector-add pod=nvidia-driver-validation_gpu-operator-resources(dc8b0aad-9bef-4b51-a6bd-c887ee421e5d)"
Dec 04 13:04:03 nvc-t2-123 kubelet[1078]: E1204 13:04:03.089888    1078 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Dec 04 13:04:06 nvc-t2-123 kubelet[1078]: E1204 13:04:06.146134    1078 dns.go:135] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.33.22.57 10.33.24.57 10.33.22.58
Dec 04 13:04:09 nvc-t2-123 kubelet[1078]: E1204 13:04:09.146343    1078 pod_workers.go:191] Error syncing pod 8c98f55d-1457-4fc1-9b1c-90b18f65f43f ("nvidia-driver-daemonset-6l898_gpu-operator-resources(8c98f55d-1457-4fc1-9b1c-90b18f65f43f)"), skipping: failed to "StartContainer" for "nvidia-driver-ctr" with CrashLoopBackOff: "back-off 5m0s restarting failed container=nvidia-driver-ctr pod=nvidia-driver-daemonset-6l898_gpu-operator-resources(8c98f55d-1457-4fc1-9b1c-90b18f65f43f)"
Dec 04 13:04:11 nvc-t2-123 kubelet[1078]: E1204 13:04:11.146278    1078 pod_workers.go:191] Error syncing pod dc8b0aad-9bef-4b51-a6bd-c887ee421e5d ("nvidia-driver-validation_gpu-operator-resources(dc8b0aad-9bef-4b51-a6bd-c887ee421e5d)"), skipping: failed to "StartContainer" for "cuda-vector-add" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cuda-vector-add pod=nvidia-driver-validation_gpu-operator-resources(dc8b0aad-9bef-4b51-a6bd-c887ee421e5d)"
Dec 04 13:04:13 nvc-t2-123 kubelet[1078]: E1204 13:04:13.104588    1078 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Dec 04 13:04:21 nvc-t2-123 kubelet[1078]: E1204 13:04:21.146287    1078 pod_workers.go:191] Error syncing pod 8c98f55d-1457-4fc1-9b1c-90b18f65f43f ("nvidia-driver-daemonset-6l898_gpu-operator-resources(8c98f55d-1457-4fc1-9b1c-90b18f65f43f)"), skipping: failed to "StartContainer" for "nvidia-driver-ctr" with CrashLoopBackOff: "back-off 5m0s restarting failed container=nvidia-driver-ctr pod=nvidia-driver-daemonset-6l898_gpu-operator-resources(8c98f55d-1457-4fc1-9b1c-90b18f65f43f)"
Dec 04 13:04:23 nvc-t2-123 kubelet[1078]: E1204 13:04:23.112736    1078 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Dec 04 13:04:26 nvc-t2-123 kubelet[1078]: E1204 13:04:26.145237    1078 pod_workers.go:191] Error syncing pod dc8b0aad-9bef-4b51-a6bd-c887ee421e5d ("nvidia-driver-validation_gpu-operator-resources(dc8b0aad-9bef-4b51-a6bd-c887ee421e5d)"), skipping: failed to "StartContainer" for "cuda-vector-add" with CrashLoopBackOff: "back-off 5m0s restarting failed container=cuda-vector-add pod=nvidia-driver-validation_gpu-operator-resources(dc8b0aad-9bef-4b51-a6bd-c887ee421e5d)"

**Comment by RenaudWasTaken** [comment]
Labelling as a bug, will try to investigate as soon as possible.
