### ISSUE TITLE
nvidia-driver-daemonset crashloopback

### ISSUE THREAD

**Issue by xhejtman** [NVIDIA/gpu-operator#180]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [ x ] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ x ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

installed via helm

### 1. Issue or feature description

from time to time, nvidia-driver-daemonset is (maybe?) reloaded and makes a transition to crashloopbackoff.

kubectl logs nvidia-driver-daemonset-prtpv -n gpu-operator-resources --context hdhu-cluster
nvidia 34041856 32 nvidia_modeset,nvidia_uvm, Live 0xffffffffc099b000 (POE)
Creating directory NVIDIA-Linux-x86_64-460.32.03
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 460.32.03...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

WARNING: Unable to determine the default X library path. The path /tmp/null/lib will be used, but this path was not detected in the ldconfig(8) cache, and no directory exists at this path, so it is likely that libraries installed there will not be found by the loader.

WARNING: You specified the '--no-kernel-module' command line option, nvidia-installer will not install a kernel module as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that an NVIDIA kernel module matching this driver version is installed separately.

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.460.32.03' for copying (Read-only file system)

ERROR: Unable to create '/usr/bin/nvidia-smi' for copying (Read-only file system)

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.460.32.03' for copying (Read-only file system)

ERROR: Unable to create '/usr/bin/nvidia-debugdump' for copying (Read-only file system)

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libcuda.so.460.32.03' for copying (Read-only file system)

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.460.32.03' for copying (Read-only file system)

ERROR: Unable to create '/usr/bin/nvidia-cuda-mps-control' for copying (Read-only file system)

ERROR: Unable to create '/usr/bin/nvidia-cuda-mps-server' for copying (Read-only file system)

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.460.32.03' for copying (Read-only file system)

ERROR: Unable to create '/usr/bin/nvidia-persistenced' for copying (Read-only file system)

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.460.32.03' for copying (Read-only file system)

ERROR: Unable to create '/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.460.32.03' for copying (Read-only file system)

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 460.32.03 for Linux kernel version 5.8.0-49-generic

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use
Could not unload NVIDIA driver kernel modules, driver is in use

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Ask which logs I should provide.

**Comment by shivamerla** [comment]
@xhejtman This is one of the limitation we have with driver container currently. Driver container goes through these steps each time:

1. Unload any existing modules
2. Unmount root filesystem of driver installation on host (**/run/nvidia/driver)**
3. Fetch prerequisites for driver compilation
4. Compile and package drivers
5. Install new driver package along with other CUDA libraries and utilities.
6. Load updated driver modules
7. Bind mount driver root filesystem / onto host at **/run/nvidia/driver**

Once the modules are already loaded, as long as something is holding a reference to it, we cannot unload it. Also, when driver container exits, driver root filesystem on host is inaccessible as well. Only way to restore from this point is to perform host reboot. We are looking to re-architect driver container, but it might be a while.

Do you know the reason why driver container was restarted?

**Comment by xhejtman** [comment]
Hello,

I understand this. I will try to investigate why the container has been restarted next time it happens. So it can be closed now.

**Comment by shivamerla** [comment]
Thanks @xhejtman
