### ISSUE TITLE
How to keep custom daemon.json ?

### ISSUE THREAD

**Issue by jrabary** [NVIDIA/gpu-operator#182]
The gpu-operator changes the /etc/docker/daemon.json to add the nvidia-runtime automatically. But the downside is that it removes all custom configuration written in this file. 
Specifically we would like to add the following lines to our `daemon.json`

```
"exec-opts": ["native.cgroupdriver=systemd"],
"log-driver": "json-file",
"log-opts": {
    "max-size": "100m"
 },
 "storage-driver": "overlay2"
```

How to tell gpu-operator to not remove these lines ?

**Comment by elezar** [comment]
Hi @jrabary the operator should be updating the docker config on the host and applying only the changes required to ensure that the nvidia-container runtime is used while maintaining other options. 

What version of the operator are you seeing this behaviour in and could you provide the contents of your `/etc/docker/daemon.json` file before and after applying the configuration with the operator?

**Comment by shivamerla** [comment]
closing this as answer is provided by Evan. Please re-open if you have further questions.
