### ISSUE TITLE
List the Nvidia GPU device IDs used by a given pod/container

### ISSUE THREAD

**Issue by ashrafgt** [NVIDIA/gpu-operator#183]
### Issue Summary:
Is it possible to somehow list the Nvidia GPU device IDs used by a given pod/container when using `gpu-operator`? If not, could there be a way to do this when using `k8s-device-plugin`?

### Side Note:
I realize it's possible to serve that information from inside the pod/container to `/metrics` for Prometheus to scrap, but I'm looking for a solution that doesn't require modifying the deployments themselves.

Thank you.

**Comment by klueska** [comment]
Neither the operator or the plugin has this information. Only the kubelet holds this state. There may be an actual API for this, but the info can be seen on any individual node by running the following:
```
$ sudo cat /var/lib/kubelet/device-plugins/kubelet_internal_checkpoint | jq
```

**Comment by dualvtable** [comment]
Hi @ashrafgt - yes, this is possible to do using the new `podresources` in Kubernetes. You would have to mount the `/var/lib/kubelet/pod-resources` socket and then call the APIs to gather the devices assigned to the containers in each pod. An implementation example is here in the `dcgm-exporter`:
`https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/pkg/kubernetes.go#L69` 

However, the pod<->device information is easily accessible from `dcgm-exporter`. Is using that not an option? 

BTW, more information on the API can be found here: https://kubernetes.io/blog/2020/12/16/third-party-device-metrics-reaches-ga/

**Comment by ashrafgt** [comment]
Thank you for the info @klueska 

That's great to hear @dualvtable! Thank you.

I do have `dcgm-exporter` deployed and I'm accessing its exposed data using promethus via the `/metrics` endpoint. What I'm getting does comtain info about each GPU in each node, but no information about other workloads running on GPUs.

So I'll look more into accessing that information through the exporter and hopefully be able to view it through prometheus.

**Comment by ashrafgt** [comment]
@dualvtable Just found out the issue in our setup. When running on GKE, the exporter doesn't seem to find information about the pods/containers.

For example, this is an excerpt of the output of a query to `/metrics` on GKE:
```python
dcgm_sm_clock{gpu="0",UUID="GPU-bcb71627-8b00-b4aa-70d7-ce39fd6cbb01",device="nvidia0",Hostname="dcgm-exporter-ln6x4",container="",namespace="",pod=""} 585
dcgm_memory_clock{gpu="0",UUID="GPU-bcb71627-8b00-b4aa-70d7-ce39fd6cbb01",device="nvidia0",Hostname="dcgm-exporter-ln6x4",container="",namespace="",pod=""} 5000
dcgm_gpu_temp{gpu="0",UUID="GPU-bcb71627-8b00-b4aa-70d7-ce39fd6cbb01",device="nvidia0",Hostname="dcgm-exporter-ln6x4",container="",namespace="",pod=""} 76
```

But when testing on a local k3s cluster:
```python
dcgm_sm_clock{gpu="0",UUID="GPU-a2bf9768-0411-f0bb-791c-67d5fec65e2f",device="nvidia0",Hostname="dcgm-exporter-xzpt9",container="cuda-test-main",namespace="default",pod="cuda-test-687bddf45c-qjl6x"} 1860
dcgm_memory_clock{gpu="0",UUID="GPU-a2bf9768-0411-f0bb-791c-67d5fec65e2f",device="nvidia0",Hostname="dcgm-exporter-xzpt9",container="cuda-test-main",namespace="default",pod="cuda-test-687bddf45c-qjl6x"} 9501
dcgm_gpu_temp{gpu="0",UUID="GPU-a2bf9768-0411-f0bb-791c-67d5fec65e2f",device="nvidia0",Hostname="dcgm-exporter-xzpt9",container="cuda-test-main",namespace="default",pod="cuda-test-687bddf45c-qjl6x"} 41
```

The setup is the same. A one-node cluster with `dcgm-exporter` running on it, and a one replica deployment. 

Is GKE restricting the `pod-resources` interface contents or something?

**Comment by ashrafgt** [comment]
It seems that adding the argument `--kubernetes-gpu-id-type device-name` to the `dcgm-exporter` does it.

On GKE, apparently, the pod resource API does not return a value for the GPU's `uid` (which is the default value for the argument), and that's why the information about the pods and containers was getting skipped.
