### ISSUE TITLE
Add support for fabric manager

### ISSUE THREAD

**Issue by MartinForReal** [NVIDIA/gpu-operator#187]
### 1. Issue or feature description
As a cluster admin I want to use container to install fabric manager.

**Comment by kpouget** [comment]
Hello @shivamerla, 

the PR for adding the fabric manager to the driver container is merged (https://gitlab.com/nvidia/container-images/driver/-/merge_requests/116), 
but I don't think the GPU Operator has been updated to use the new image, right?

do you think you'll be able to update the `master` with the right image address for us to test it before the operator is released?

**Comment by shivamerla** [comment]
@kpouget Yes, will look into pushing updated image with fabric-manager support. Testing is underway with private image for this.

**Comment by yzhao-2023** [comment]
Does GPU operator have the capability to install fabric manager already?

From the comments above, it seems the fabric manager image has been packed into GPU operator container image
![image](https://github.com/NVIDIA/gpu-operator/assets/142474494/0b0adeba-33fe-40c0-9748-8f17b8cedb57)

But I could not find confirmation that GPU operator executable has the capability to install this driver during the runtime.
(Although I guess it's straightforward to do that)
