### ISSUE TITLE
Uninstall persists `containerd-template.toml` changes

### ISSUE THREAD

**Issue by null-d3v** [NVIDIA/gpu-operator#188]
### Issue or feature description
After uninstalling the helm chart, my `containerd-template.toml` remained altered. Specifically the `default_runtime_name` was yet `nvidia`. In my particular case this caused Emby pods to fail to start with the following:
```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: initialization error: driver error: failed to process request: unknown
Back-off restarting failed container
```

Manually resetting the `containerd-template.toml` resolved the issue, though this is something that I would expect to be managed by a standard uninstall process or documented in the [uninstall section](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#uninstalling-gpu-operator).

**Comment by shivamerla** [comment]
@null-d3v Can you check the container-toolkit version which had this issue? Also, if you can test this with `v1.7.0` of operator that would be great.

**Comment by null-d3v** [comment]
I wish I had saved the logs including the toolkit version as I have unfortunately since rebuilt the cluster. However I can confirm that a helm uninstall absolutely worked as expected with `v.1.7.0`. Thank you!
