### ISSUE TITLE
Is there plans to support for centos?

### ISSUE THREAD

**Issue by yashbhutwala** [NVIDIA/gpu-operator#19]
Failed to pull image "nvcr.io/nvidia/driver:418.87.01-centos7": rpc error: code = Unknown desc = Error response from daemon: manifest for nvcr.io/nvidia/driver:418.87.01-centos7 not found
  Warning  Failed          105s (x3 over 2m29s)  kubelet, prd-kb-gpu01.dc2.lan  Error: ErrImagePull
  Normal   BackOff         69s (x7 over 2m27s)   kubelet, prd-kb-gpu01.dc2.lan  Back-off pulling image "nvcr.io/nvidia/driver:418.87.01-centos7"
  Warning  Failed          69s (x7 over 2m27s)   kubelet, prd-kb-gpu01.dc2.lan  Error: ImagePullBackOff
  Normal   Pulling         55s (x4 over 2m30s)   kubelet, prd-kb-gpu01.dc2.lan  Pulling image "nvcr.io/nvidia/driver:418.87.01-centos7"

**Comment by RenaudWasTaken** [comment]
Hello!

Centos is definitely planned, though it's probably 3-6 months away.
