### ISSUE TITLE
GPU install on OpenShift 4.7.9 not working

### ISSUE THREAD

**Issue by rspierz** [NVIDIA/gpu-operator#190]
Installing Linux kernel headers...
+ dnf -q -y --releasever=8.2 install kernel-headers-4.18.0-240.22.1.el8_3.x86_64 kernel-devel-4.18.0-240.22.1.el8_3.x86_64
**Error: Unable to find a match: kernel-devel-4.18.0-240.22.1.el8_3.x86_64**

Is there any ETA to when this would be resolved?

**Comment by shivamerla** [comment]
@zvonkok  Can you please check when kernel-headers for this version will be available in EUS repos?

**Comment by shivamerla** [comment]
@rspierz  Are you seeing this after upgrading cluster from 4.6 to 4.7?

**Comment by rspierz** [comment]
Correct, it was working fine on 4.6

**Comment by shivamerla** [comment]
@rspierz  this is a known issue that operator was not updating ENV for already deployed driver containers. We have two options

1. To delete and re-create ClusterPolicy instance
2. To edit 'nvidia-driver-daemonset' to update RHEL_VERSION=8.3 and OPENSHIFT_VERSION=4.7 using "oc edit nvidia-driver-daemonset - n gpu-operator-resources"

This limitation will be fixed from 1.7.0 release.

**Comment by rspierz** [comment]
Thanks for the info!

I seem to get stuck with CA on dnf? 

cuda                                                                                                                                                                                                         0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'cuda':
  - Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/repodata/repomd.xml [error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none]
  
  Is there something extra i need to set if using a proxy? I do see proxy is set properly

**Comment by rspierz** [comment]
Thanks for this information and your speedy help. We are all good - looking forward to the 1.7.0 release
