### ISSUE TITLE
nvidia-driver-daemonset cannot pull image on Ubuntu 21.04 

### ISSUE THREAD

**Issue by olokshyn** [NVIDIA/gpu-operator#192]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

I'm running:
1. Ubuntu 21.04
2. Microk8s 1.21/stable
3. Kubernetes 1.21

I currently have 460.80 version of the driver installed on the host machine if it makes any difference.
The GPU in use is GeForce RTX 2080 Ti.

### 1. Issue or feature description
I need to enable the gpu-operator inside the microk8s deployment
```
microk8s enable gpu
```

It creates the `nvidia-driver-daemonset` daemonset in the `gpu-operator-resources` namespace. Pods of this daemonset cannot pull the image:

```
olokshyn@neptune-linux:~$ mk -n gpu-operator-resources get events --sort-by=.metadata.creationTimestamp
LAST SEEN   TYPE      REASON             OBJECT                              MESSAGE
3m45s       Normal    SuccessfulCreate   daemonset/nvidia-driver-daemonset   Created pod: nvidia-driver-daemonset-dcwrt
3m44s       Normal    Scheduled          pod/nvidia-driver-daemonset-dcwrt   Successfully assigned gpu-operator-resources/nvidia-driver-daemonset-dcwrt to neptune-linux
2m11s       Normal    Pulling            pod/nvidia-driver-daemonset-dcwrt   Pulling image "nvcr.io/nvidia/driver:460.32.03-ubuntu21.04"
2m9s        Warning   Failed             pod/nvidia-driver-daemonset-dcwrt   Failed to pull image "nvcr.io/nvidia/driver:460.32.03-ubuntu21.04": rpc error: code = NotFound desc = failed to pull and unpack image "nvcr.io/nvidia/driver:460.32.03-ubuntu21.04": failed to resolve reference "nvcr.io/nvidia/driver:460.32.03-ubuntu21.04": nvcr.io/nvidia/driver:460.32.03-ubuntu21.04: not found
2m9s        Warning   Failed             pod/nvidia-driver-daemonset-dcwrt   Error: ErrImagePull
118s        Warning   Failed             pod/nvidia-driver-daemonset-dcwrt   Error: ImagePullBackOff
106s        Normal    BackOff            pod/nvidia-driver-daemonset-dcwrt   Back-off pulling image "nvcr.io/nvidia/driver:460.32.03-ubuntu21.04"
```

This image does not exist on [NGC](https://ngc.nvidia.com/catalog/containers/nvidia:driver/tags). I guess the tag that it should be using is `460.32.03-ubuntu20.04`.

This daemonset deployment is controlled by the helm chart. 

**How can I change the image tag?**

The helm chart doesn't seem to explicitly specify it anywhere (maybe that's my lack of experience with helm).

### 2. Steps to reproduce the issue
On Ubuntu 21.04 with a NVidia GPU:

```
sudo snap install microk8s --channel 1.21/stable --classic
sudo usermod -a -G microk8s olokshyn
sudo chown -f -R olokshyn ~/.kube
# reboot
microk8s enable dns dashboard storage
microk8s enable gpu
```

**Comment by shivamerla** [comment]
@olokshyn Ubuntu21.04 has not been officially qualified by us. Will update timeline for this.

**Comment by shivamerla** [comment]
@olokshyn Since `Ubuntu21.04` is not an LTS release, we will not be adding support for this. Our next official support would be with `Ubuntu 22.04 LTS`.
