### ISSUE TITLE
Changing provided DCGM-exporter metrics

### ISSUE THREAD

**Issue by koflerm** [NVIDIA/gpu-operator#195]
Hello Team,

For our GPU monitoring solution we would like to expose some additional metrics provided by the DCGM API. For this purpose, I changed the file /etc/dcgm-exporter/dcp-metrics-included.csv to also include those metrics by creating a config map and adding my custom file to the dcgm-exporter daemonset. This work as expected but my problem is the dcgm-exporter daemonset and the dcgm-exporter configmap (which includes my custom dcp-metrics-included.csv file) are managed by the GPU operator which means if it includes a reconciliation loop in the future my changes will be gone.

Do you have any concerns about the way I am changing this file or will there be no reconciliation loop / updates of the managed resources after creation? If this is a problem do you have any recommended way to change the included metrics or any plans to make this configurable via the cluster policy?

**Comment by shivamerla** [comment]
@koflerm Currently since we don't update existing resources, your approach looks fine. Adding a new option during Operator install to provide ConfigMap as input to DCGM Exporter makes sense. GPU operator can mount this appropriately and pass `-f <metrics file path>` args automatically to DCGM exporter. When we support that, you can change to use that option.

**Comment by koflerm** [comment]
Okay thanks for your help!

**Comment by koflerm** [comment]
Hello again, I got notified in another ticket that there will be reconciliation in the next update. Are there also plans now to allow those kind of changes using the CRD?

**Comment by shivamerla** [comment]
@koflerm Will look into adding this.

**Comment by shivamerla** [comment]
This support has been adding since `v1.8.0`. Please pass additional configmap as `--set dcgmExporter.config.name=<config-map-name>`.

**Comment by harjitdotsingh** [comment]
@koflerm  - Did you create a file locally for the daemonset and then apply it or was it applied to already running instance ?
