### ISSUE TITLE
Error unknown field "priorityClassName"

### ISSUE THREAD

**Issue by anneum** [NVIDIA/gpu-operator#196]
### 1. Issue or feature description
I install the the gpu-operator via helm as part of the [deepops](https://github.com/NVIDIA/deepops/) scripts and got the same error as described in #126. Thankfully @shivamerla has mentioed, that this behavior should be fixed with 1.7.0. If I try to install 1.7.0 I get the following error:
```
stderr: 'Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ClusterPolicy.spec.dcgmExporter): unknown field "priorityClassName" in com.nvidia.v1.ClusterPolicy.spec.dcgmExporter, ValidationError(ClusterPolicy.spec.devicePlugin): unknown field "priorityClassName" in com.nvidia.v1.ClusterPolicy.spec.devicePlugin, ValidationError(ClusterPolicy.spec.driver): unknown field "enabled" in com.nvidia.v1.ClusterPolicy.spec.driver, ValidationError(ClusterPolicy.spec.driver): unknown field "priorityClassName" in com.nvidia.v1.ClusterPolicy.spec.driver, ValidationError(ClusterPolicy.spec.gfd): unknown field "priorityClassName" in com.nvidia.v1.ClusterPolicy.spec.gfd, ValidationError(ClusterPolicy.spec): unknown field "mig" in com.nvidia.v1.ClusterPolicy.spec, ValidationError(ClusterPolicy.spec): unknown field "migManager" in com.nvidia.v1.ClusterPolicy.spec, ValidationError(ClusterPolicy.spec.operator): unknown field "initContainer"
    in com.nvidia.v1.ClusterPolicy.spec.operator, ValidationError(ClusterPolicy.spec): unknown field "psp" in com.nvidia.v1.ClusterPolicy.spec, ValidationError(ClusterPolicy.spec.toolkit): unknown field "enabled" in com.nvidia.v1.ClusterPolicy.spec.toolkit, ValidationError(ClusterPolicy.spec.toolkit): unknown field "priorityClassName" in com.nvidia.v1.ClusterPolicy.spec.toolkit, ValidationError(ClusterPolicy.spec): unknown field "validator" in com.nvidia.v1.ClusterPolicy.spec]'
```
OS Ubuntu 20.04

### 2. Steps to reproduce the issue
```/usr/local/bin/helm upgrade --install nvidia-gpu-operator nvidia/gpu-operator --version 1.7.0 --set driver.enabled=false --set migStrategy=mixed --set operator.defaultRuntime=containerd --set driver.repository=nvcr.io/nvidia --set driver.version=460.32.03 --set gfd.migStrateg=mixed --set devicePlugin.args={--mig-strategy=mixed,--pass-device-specs=true,--fail-on-init-error=true,--device-list-strategy=envvar,--nvidia-driver-root=/run/nvidia/driver} --wait```

**Comment by shivamerla** [comment]
@anneum Helm doesn't support upgrade of CRD's, so we should manually delete existing clusterpolicies CRD before install again. Also, currently operator doesn't support upgrade of already deployed components due to limitations with driver container, that it cannot restart on the fly and node reboot is required. We will add the upgrade support in future releases, meanwhile please follow these steps:

1. Uninstall existing CRD
2. **Install** Helm chart again with updated values instead of using `upgrade` command.

**Comment by anneum** [comment]
@shivamerla thank you for your help. I deleted the CRD and the installation went one step further.
Now only the `nvidia-device-plugin-validator-8fbmn` pod stuck in `Init:CreateContainerError`.
```
Error: failed to generate container "10a6510c9a60e6c0b25e30fd89dadda19f8f877e538e5c889d8335b2fb552dda" spec: failed to generate spec: lstat /run/nvidia/driver/dev/nvidiactl: no such file or directory
```
Did I forget something?

**Comment by shivamerla** [comment]
I see that you have driver disabled with `--set driver.enabled=false` but still `--nvidia-driver-root` is set to `/run/nvidia/driver`. You need to omit nvidia-driver-root setting as gpu-operator will add this appropriately.

**Comment by anneum** [comment]
@shivamerla I followed your instructions and the pods created successfully. Thanks a lot for that!

I have one last question. Why is `"nvidia.com/mig.strategy": "single"` and not mixed if I do a `kubectl get node -o json | jq '.items[].metadata.labels'`?

`helm install nvidia-gpu-operator nvidia/gpu-operator --version 1.7.0 --set driver.enabled=false --set mig.Strategy=mixed --set operator.defaultRuntime=containerd --set driver.repository=nvcr.io/nvidia --set driver.version=460.32.03 --set gfd.migStrateg=mixed --set devicePlugin.args={--pass-device-specs=true,--fail-on-init-error=true,--device-list-strategy=envvar} --wait`

Also if I do a `nvidia-smi` on my host, I can not see that there are MIG devices:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  On   | 00000000:81:00.0 Off |                    0 |
| N/A   33C    P0    34W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by shivamerla** [comment]
@anneum  Looks like there is a typo during install. it should be `mig.strategy=mixed` with lowercase `strategy`. After this, please add the required MIG config label to the node for MIG manager to apply that config. `kubectl label node <node-name> nvidia.com/mig.config=<config-name> --overwrite`. All supported configs are in the ConfigMap mig-parted-config under `gpu-operator-resources` namespace.

**Comment by anneum** [comment]
@shivamerla Now it works. Thanks again.
