### ISSUE TITLE
OpenShift 4.7 OLM GPU Operator 1.7 availability

### ISSUE THREAD

**Issue by sandrich** [NVIDIA/gpu-operator#198]
When will the new GPU Operator v1.7 be available in OpenShift 4.7 OLM?

**Comment by shivamerla** [comment]
@sandrich 4.7 is already published to RH Catalog. Please edit the subscription to use `v1.7` channel. We will be publishing all v1.7.x updates through that channel.

**Comment by sandrich** [comment]
Perfect thanks
