### ISSUE TITLE
Same resource kind in one state

### ISSUE THREAD

**Issue by Ethyling** [NVIDIA/gpu-operator#2]
In the `init` part, what we are doing currently in the `addResourcesControls` function (https://github.com/Ethyling/gpu-operator/blob/master/pkg/controller/specialresource/specialresource_resources.go#L70) is to find all yaml files from the state directory and fill a `Resources` structure with the objects found in them.

When there are two resources of the same kind in the same state directory, I think we are losing the information of the first one and we are only checking the second one. I think we should have a list for each type and iterate over it while the reconcile loop.

Am I missing something?
@zvonkok @rajatchopra

**Comment by zvonkok** [comment]
Every resource has an associated control-function to it. With every resource, the resource and the control-function are appended to the state struct. 

The operator itereates over all resources and calls it associated control-function. 
What information loss are you worried about? 
Do we need to extend something?

**Comment by Ethyling** [comment]
Yes, but what I mean is that currently we have something like this:

```go
res := Resources{}
for _, m := range manifests {
  kind := getKind(m)
  switch kind {
  case "ServiceAccount":
    _, _, err := s.Decode(m, nil, &res.ServiceAccount)
  [...]
  }
}
return res
```

My question is what happens if there is two `ServiceAccount` in the `manifests` list? For me, the `_, _, err := s.Decode(m, nil, &res.ServiceAccount)` call will override the first `ServiceAccount` in `res` and we will lose the object content.

**Comment by zvonkok** [comment]
Ah you're right, there is an array for the states, but not for multiple resources.
If a user has multiple resources of the same kind, should they be handled in a single state or could they be split into seperate states? WDYT? What makes more sense?

**Comment by Ethyling** [comment]
I think we need to add the possibility to have multiple resources of the same kind in the same state.

**Comment by Ethyling** [comment]
What do you think if we just change the `Ressources` type and set list instead of just items for each type? We can then iterate over them

**Comment by zvonkok** [comment]
Agreed makes more sense.
