### ISSUE TITLE
WARNING: infoROM is corrupted at gpu 0000:B3:00.0

### ISSUE THREAD

**Issue by avinashsen707** [NVIDIA/gpu-operator#20]
```
binpick@robotic-Precision-7820-Tower:~/catkin_ws/src/VForce/src$ nvidia-smi
Mon Dec 16 15:53:50 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:B3:00.0  On |                  N/A |
| 46%   35C    P8     6W / 105W |    701MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1676      G   /usr/lib/xorg/Xorg                           293MiB |
|    0      2355      G   compiz                                       156MiB |
|    0      3879      G   /usr/lib/firefox/firefox                       2MiB |
|    0      8528      G   ...uest-channel-token=15053750814686008214   246MiB |
+-----------------------------------------------------------------------------+
WARNING: infoROM is corrupted at gpu 0000:B3:00.0

```

Does this make any problrm in GPU running

**Comment by RenaudWasTaken** [comment]
Hello!

The inforom is a non-volatile storage device on the GPU. It is used to store various data. 
Corrupted means the inforom did not pass some sort of sanity check (e.g. checksum). Therefore the GPU driver won't use or trust its contents.
There is no publicly available utility to fix this. The card is damaged. Unless it is under warranty, there isn't anything you can do to repair it. However, as you are aware, some aspects of the card functionality are still operational.

**Comment by avinashsen707** [comment]
> Hello!
> 
> The inforom is a non-volatile storage device on the GPU. It is used to store various data.
> Corrupted means the inforom did not pass some sort of sanity check (e.g. checksum). Therefore the GPU driver won't use or trust its contents.
> There is no publicly available utility to fix this. The card is damaged. Unless it is under warranty, there isn't anything you can do to repair it. However, as you are aware, some aspects of the card functionality are still operational.

![Screenshot from 2020-02-04 11-58-16](https://user-images.githubusercontent.com/55526162/73630674-cc8e7a80-467c-11ea-828c-01922ee4f98b.png)
