### ISSUE TITLE
PROJECT `version: 3-alpha` is deprecated

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#201]
`version: 3-alpha` is deprecated for Operator-SDK [PROJECT](https://github.com/NVIDIA/gpu-operator/blob/9aad14f7f4073e77b2be5aa345d5e85d99ce501c/PROJECT#L10),

Recent versions of `operator-sdk` refuse to deploy the GPU Operator bundle because of that,
they suggest using [`operator-sdk alpha config-3alpha-to-3`](https://sdk.operatorframework.io/docs/cli/operator-sdk_alpha_config-3alpha-to-3/) to convert the resources.

Note that this is *not* related to OpenShift/OperatorHub, I face it when trying to deploy the master branch manually from the bundle specification.

**Comment by shivamerla** [comment]
PTAL: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/237

**Comment by shivamerla** [comment]
Updated project spec.

**Comment by kpouget** [comment]
Thanks @shivamerla,
for reference, the message I was seeing was this one, with `operator-sdk` v1.8.0:
```
time="2021-06-07T09:34:24Z" level=warning msg="Config version 3-alpha has been stabilized as 3, and 3-alpha is no longer supported. Run `operator-sdk alpha config-3alpha-to-3` to upgrade your PROJECT config file to version 3"
```
