### ISSUE TITLE
Pulling from a private repo with imagePullSecrets fails.

### ISSUE THREAD

**Issue by zbsarashki** [NVIDIA/gpu-operator#202]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [ x] Are you running Kubernetes v1.13+?
- [ x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Greetings,

This is part of porting the operator to starlingx and the requirement to pull the driver and other images from a private registry. Failure is seen in pulling the driver image but not the operator image from the same repository. Any help / insight is much appreciated. 

I use the following command:

helm install ...
--set driver.repository=registry.somewhere.com/staging/nvcr.io/nvidia \
--set driver.imagePullSecrets={my-registry-secret} \
--set operator.repository=registry.somewhere.com/staging/nvcr.io/nvidia \
--set operator.imagePullSecrets={my-registry-secret} \
....

With the above and in my environment, we fail to pull the driver image, but succeed in pulling the operator image. 

I know that the driver.repository and my-registry-secret are correct because I can create a standalone driver pod using the same values as set in the above helm command. 

From the clusterpolicy:

  Driver:
    Env:
      Name:             IGNORE_PREEMPT_RT_PRESENCE
      Value:            1
    Image:              driver
    Image Pull Policy:  IfNotPresent
    Image Pull Secrets:
      my-registry-secret
    Licensing Config:
      Config Map Name:
    Node Selector:
      nvidia.com/gpu.present:  true
    Repo Config:
      Config Map Name:
      Destination Dir:
    Repository:         registry.somewhere.com/staging/nvcr.io/nvidia
    Security Context:
      Privileged:  true
      Se Linux Options:
        Level:  s0
    Tolerations:
      Effect:    NoSchedule
      Key:       nvidia.com/gpu
      Operator:  Exists
    Version:     460.73.01-stx4

charts version 1.6.0.

**Comment by shivamerla** [comment]
@zbsarashki you will need to create registry-secret in `gpu-operator-resources` namespace too as driver Daemonset is deployed there. Also, GPU operator appends os-tag(ubuntu20.04 etc) to the provided image `version`. So please check if the image is pushed with appropriate tag as required. If you describe the Daemonset, it will indicate the actual tag its looking for.

**Comment by zbsarashki** [comment]
@shivamerla Thanks. That works. The image is pushed with driver:version>-stx4-centos7.
