### ISSUE TITLE
GPU sharing among pods

### ISSUE THREAD

**Issue by xhejtman** [NVIDIA/gpu-operator#203]
Hello,

is it possible to share single GPU among several pods? There are some existing hacks mostly deploing NVidia driver on their own. Would it be possible to request only a fragment of GPU mem, e.g.? How about two pods that have to share the same GPU? (E.g., running xserver in one pod and desktop in another, they need to share the same GPU othervise GLX does segfault)

**Comment by shivamerla** [comment]
@xhejtman It's not possible to share GPU's among Pods through device-plugin. It's possible only with NVIDIA Ampere architecture GPU's (such as NVIDIA A100) using MIG where GPU's can be partitioned into multiple instances and each instance can be assigned to a different Pod: https://developer.nvidia.com/blog/getting-kubernetes-ready-for-the-a100-gpu-with-multi-instance-gpu/

**Comment by xhejtman** [comment]
With MIG, the card is actually partitioned and no real sharing happnes, isn't it?

I wondered whether something like this:
https://blog.ml6.eu/a-guide-to-gpu-sharing-on-top-of-kubernetes-6097935ababf

or better this:
https://partners-intl.aliyun.com/help/doc-detail/163996.htm

could be implemented in gpu operator, i.e., request a portion of gpu memory instead of gpu instance itself:

resources:
          limits:
            # GiB
            aliyun.com/gpu-mem: 3

**Comment by shivamerla** [comment]
@xhejtman after talking to internal folks looks like this is officially not supported. MPS is other way to achieve this, but currently not supported with GPU operator: https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf
