### ISSUE TITLE
containerd config.toml

### ISSUE THREAD

**Issue by zbsarashki** [NVIDIA/gpu-operator#207]
when setting default runtime to containerd, the nvidia-toolkit from container-toolkit overrides containerd/config.toml and restarts the daemon. Is there an option for the toolkit to not alter config.toml. Use case is that the containerd has already been configured and includes a number of other changes and we cannot restart it.

**Comment by elezar** [comment]
Hi @zbsarashki. Thanks for the request.

I have some clarifying questions:

The modifications that the toolkit container make to the config file should be limited to setting up the NVIDIA Container Runtime to be used with containerd. These should not affect other settings. If you don't want the default runtime to be changed, launching the operator with:
```
--set toolkit.env[0].name=CONTAINERD_SET_AS_DEFAULT --set toolkit.env[0].value=false
```

Since you mention that your containerd config has already been modified, I assume that this also includes the setting up of the NVIDIA runtime classes.

**Comment by zbsarashki** [comment]
Hi @elezar 

I am seeing two problems here.

1 - helm install ... --set toolkit.env[0].name=CONTAINERD_SET_AS_DEFAULT --set toolkit.env[0].value=false fails with:

           spec.toolkit.env.value in body must be of type string: "boolean"

2 - Changing it to: --set toolkit.env[0].name=CONTAINERD_SET_AS_DEFAULT --set-string toolkit.env[0].value=false or setting in the values.yaml:
....
`toolkit:`
 `env:`
 `- name: CONTAINERD_SET_AS_DEFAULT`
  `  value: "false"`
         
The following pods fail to start:

1 - monitoring
2 - device-plugin
3 - device-plugin-valiation
4 - gfd

Question: How do the above 4 pods have their hooks inserted if not part of the runtimeClass nvidia?

We can run the gpu-operator using changes (to the assets/) from here:  https://github.com/zbsarashki/gpu-operator/tree/starlingX. Is there a better/correct way to add the runtimeClassName: nvidia to the 4 pods?

Current setup:

cat  /etc/containerd/config.toml:
....
        [plugins.cri.containerd.runtimes.nvidia]
          runtime_type = "io.containerd.runc.v1"
          [plugins.cri.containerd.runtimes.nvidia.options]
            BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime"
...

And the following class created:
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
   name: nvidia
handler: nvidia

**Comment by elezar** [comment]
Thanks for trying out the suggestion @zbsarashki 

I think @shivamerla should have more experience in setting the options for the various components.

**Comment by shivamerla** [comment]
@zbsarashki If config.toml is pre-configured and container-toolkit is pre-installed, then you can use "--set toolkit.enabled=false" option when installing GPU Operator.  Other thing to note with this setting is `root = /run/nvidia/driver` should be set in `/usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml` manually. Currently GPU operator by default adds RuntimeClass as "nvidia" for DCGM/Device-Plugin/GFD pods. So your manual setting in `/etc/containerd/config.toml` should match this. We will add an option to change the runtimeClass name with `v1.8.0`.

**Comment by zbsarashki** [comment]
@shivamerla Thanks. This will work.
