### ISSUE TITLE
Pods not schedulable with gpu-operator

### ISSUE THREAD

**Issue by apdibbo** [NVIDIA/gpu-operator#209]
I am having an issue the gpu operator where it looks like the appropriate labelling for assigning GPUs to pods is not added to nodes with a GPU.

I am running kubernetes v1.16.13 on Fedora CoreOS 32 with docker 19.3.11..

Here is the output of the log from  the gpu-operator on the GPU node:
`2021/06/16 06:32:39 Configuration successfully loaded from "/etc/kubernetes/node-feature-discovery/nfd-worker.conf"
2021/06/16 06:32:39 cpu-hardware_multithreading = true
2021/06/16 06:32:39 cpu-cpuid.AVX = true
2021/06/16 06:32:39 cpu-cpuid.SSE4A = true
2021/06/16 06:32:39 cpu-cpuid.FMA3 = true
2021/06/16 06:32:39 cpu-cpuid.ADX = true
2021/06/16 06:32:39 cpu-cpuid.SHA = true
2021/06/16 06:32:39 cpu-cpuid.AVX2 = true
2021/06/16 06:32:39 ERROR: can't detect whether turbo boost is enabled: open /host-sys/devices/system/cpu/intel_pstate/no_turbo: no such file or directory
2021/06/16 06:32:39 cpu-cpuid.IBPB = true
2021/06/16 06:32:39 cpu-cpuid.AESNI = true
2021/06/16 06:32:39 cpu-cpuid.STIBP = true
2021/06/16 06:32:39 kernel-version.full = 5.7.12-200.fc32.x86_64
2021/06/16 06:32:39 kernel-version.major = 5
2021/06/16 06:32:39 kernel-version.minor = 7
2021/06/16 06:32:39 kernel-version.revision = 12
2021/06/16 06:32:39 Failed to read /proc/config.gz: open /proc/config.gz: no such file or directory
2021/06/16 06:32:39 ERROR: Failed to read kconfig: open /host-boot/config-5.7.12-200.fc32.x86_64: no such file or directory
2021/06/16 06:32:39 Failed to detect the status of selinux, please check if the system supports selinux and make sure /sys on the host is mounted into the container: open /host-sys/fs/selinux/enforce: permission denied
2021/06/16 06:32:39 SR-IOV not supported for network interface: cni0: open /host-sys/class/net/cni0/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: docker0: open /host-sys/class/net/docker0/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: ens3: open /host-sys/class/net/ens3/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth34441cb5: open /host-sys/class/net/veth34441cb5/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth3b115292: open /host-sys/class/net/veth3b115292/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth41111e95: open /host-sys/class/net/veth41111e95/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth4289c8de: open /host-sys/class/net/veth4289c8de/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth50926795: open /host-sys/class/net/veth50926795/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth50dd63a6: open /host-sys/class/net/veth50dd63a6/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth6a319a00: open /host-sys/class/net/veth6a319a00/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth708f882d: open /host-sys/class/net/veth708f882d/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth8cd9b262: open /host-sys/class/net/veth8cd9b262/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: veth9ba2b6dd: open /host-sys/class/net/veth9ba2b6dd/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: vethb908f94f: open /host-sys/class/net/vethb908f94f/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: vethc5c99a8d: open /host-sys/class/net/vethc5c99a8d/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 SR-IOV not supported for network interface: vethdde4e587: open /host-sys/class/net/vethdde4e587/device/sriov_totalvfs: no such file or directory
2021/06/16 06:32:39 pci-1013.present = true
2021/06/16 06:32:39 system-os_release.ID = fedora
2021/06/16 06:32:39 system-os_release.VERSION_ID = 32
2021/06/16 06:32:39 system-os_release.VERSION_ID.major = 32
2021/06/16 06:32:39 INFO: Custom features: [{Name:rdma.capable MatchOn:[{PciID:0xc0000ba500 UsbID:<nil> LoadedKMod:<nil>}]} {Name:rdma.available MatchOn:[{PciID:<nil> UsbID:<nil> LoadedKMod:0xc00021d120}]}]
2021/06/16 06:32:39 Sending labeling request to nfd-master`

Here is the corresponding log from the master gpu-operator:
`2021/06/16 06:31:54 REQUEST Node: jupyter-training-3-0-s5e4bd5x4gil-node-1 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.FMA3:true cpu-cpuid.IBPB:true cpu-cpuid.SHA:true cpu-cpuid.SSE4A:true cpu-cpuid.STIBP:true cpu-hardware_multithreading:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:32:38 REQUEST Node: jupyter-training-3-0-gpu-worke-r3my7owtqqja-node-0 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.AVX512BW:true cpu-cpuid.AVX512CD:true cpu-cpuid.AVX512DQ:true cpu-cpuid.AVX512F:true cpu-cpuid.AVX512VL:true cpu-cpuid.AVX512VNNI:true cpu-cpuid.FMA3:true cpu-cpuid.IBPB:true cpu-cpuid.MPX:true cpu-cpuid.STIBP:true cpu-cpuid.VMX:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true pci-10de.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:32:39 REQUEST Node: jupyter-training-3-0-s5e4bd5x4gil-node-0 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.FMA3:true cpu-cpuid.IBPB:true cpu-cpuid.SHA:true cpu-cpuid.SSE4A:true cpu-cpuid.STIBP:true cpu-hardware_multithreading:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:32:47 REQUEST Node: jupyter-training-3-0-s5e4bd5x4gil-master-0 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.AVX512BW:true cpu-cpuid.AVX512CD:true cpu-cpuid.AVX512DQ:true cpu-cpuid.AVX512F:true cpu-cpuid.AVX512VL:true cpu-cpuid.FMA3:true cpu-cpuid.HLE:true cpu-cpuid.MPX:true cpu-cpuid.RTM:true cpu-cpuid.VMX:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:32:50 REQUEST Node: jupyter-training-3-0-s5e4bd5x4gil-master-1 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.AVX512BW:true cpu-cpuid.AVX512CD:true cpu-cpuid.AVX512DQ:true cpu-cpuid.AVX512F:true cpu-cpuid.AVX512VL:true cpu-cpuid.FMA3:true cpu-cpuid.HLE:true cpu-cpuid.MPX:true cpu-cpuid.RTM:true cpu-cpuid.VMX:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:32:54 REQUEST Node: jupyter-training-3-0-s5e4bd5x4gil-node-1 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.FMA3:true cpu-cpuid.IBPB:true cpu-cpuid.SHA:true cpu-cpuid.SSE4A:true cpu-cpuid.STIBP:true cpu-hardware_multithreading:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:33:38 REQUEST Node: jupyter-training-3-0-gpu-worke-r3my7owtqqja-node-0 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.AVX512BW:true cpu-cpuid.AVX512CD:true cpu-cpuid.AVX512DQ:true cpu-cpuid.AVX512F:true cpu-cpuid.AVX512VL:true cpu-cpuid.AVX512VNNI:true cpu-cpuid.FMA3:true cpu-cpuid.IBPB:true cpu-cpuid.MPX:true cpu-cpuid.STIBP:true cpu-cpuid.VMX:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true pci-10de.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]
2021/06/16 06:33:39 REQUEST Node: jupyter-training-3-0-s5e4bd5x4gil-node-0 NFD-version: v0.6.0 Labels: map[cpu-cpuid.ADX:true cpu-cpuid.AESNI:true cpu-cpuid.AVX:true cpu-cpuid.AVX2:true cpu-cpuid.FMA3:true cpu-cpuid.IBPB:true cpu-cpuid.SHA:true cpu-cpuid.SSE4A:true cpu-cpuid.STIBP:true cpu-hardware_multithreading:true kernel-version.full:5.7.12-200.fc32.x86_64 kernel-version.major:5 kernel-version.minor:7 kernel-version.revision:12 pci-1013.present:true system-os_release.ID:fedora system-os_release.VERSION_ID:32 system-os_release.VERSION_ID.major:32]`

Here is the output of kubectl describe on the GPU node:
`root@mission-control:~# kubectl describe nodes jupyter-training-3-0-gpu-worke-r3my7owtqqja-node-0
Name:               jupyter-training-3-0-gpu-worke-r3my7owtqqja-node-0
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=09f05d05-c587-48c0-b9b3-ffb633274bb4
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=RegionOne
                    failure-domain.beta.kubernetes.io/zone=ceph
                    feature.node.kubernetes.io/cpu-cpuid.ADX=true
                    feature.node.kubernetes.io/cpu-cpuid.AESNI=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX2=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512BW=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512CD=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512DQ=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512F=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VL=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI=true
                    feature.node.kubernetes.io/cpu-cpuid.FMA3=true
                    feature.node.kubernetes.io/cpu-cpuid.IBPB=true
                    feature.node.kubernetes.io/cpu-cpuid.MPX=true
                    feature.node.kubernetes.io/cpu-cpuid.STIBP=true
                    feature.node.kubernetes.io/cpu-cpuid.VMX=true
                    feature.node.kubernetes.io/kernel-version.full=5.7.12-200.fc32.x86_64
                    feature.node.kubernetes.io/kernel-version.major=5
                    feature.node.kubernetes.io/kernel-version.minor=7
                    feature.node.kubernetes.io/kernel-version.revision=12
                    feature.node.kubernetes.io/pci-1013.present=true
                    feature.node.kubernetes.io/pci-10de.present=true
                    feature.node.kubernetes.io/system-os_release.ID=fedora
                    feature.node.kubernetes.io/system-os_release.VERSION_ID=32
                    feature.node.kubernetes.io/system-os_release.VERSION_ID.major=32
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=jupyter-training-3-0-gpu-worke-r3my7owtqqja-node-0
                    kubernetes.io/os=linux
                    magnum.openstack.org/nodegroup=gpu-worker
                    magnum.openstack.org/role=gpu
                    topology.cinder.csi.openstack.org/zone=ceph
Annotations:        csi.volume.kubernetes.io/nodeid: {"cinder.csi.openstack.org":"377550af-1b59-40f4-b1dd-fa70a0985569"}
                    flannel.alpha.coreos.com/backend-data: null
                    flannel.alpha.coreos.com/backend-type: host-gw
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.0.0.149
                    nfd.node.kubernetes.io/extended-resources:
                    nfd.node.kubernetes.io/feature-labels:
                      cpu-cpuid.ADX,cpu-cpuid.AESNI,cpu-cpuid.AVX,cpu-cpuid.AVX2,cpu-cpuid.AVX512BW,cpu-cpuid.AVX512CD,cpu-cpuid.AVX512DQ,cpu-cpuid.AVX512F,cpu-...
                    nfd.node.kubernetes.io/worker.version: v0.6.0
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 15 Jun 2021 15:02:46 +0000
Taints:             nvidia.com/gpu=present:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  jupyter-training-3-0-gpu-worke-r3my7owtqqja-node-0
  AcquireTime:     <unset>
  RenewTime:       Wed, 16 Jun 2021 06:36:05 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 16 Jun 2021 06:35:23 +0000   Tue, 15 Jun 2021 15:02:46 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 16 Jun 2021 06:35:23 +0000   Tue, 15 Jun 2021 15:02:46 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 16 Jun 2021 06:35:23 +0000   Tue, 15 Jun 2021 15:02:46 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 16 Jun 2021 06:35:23 +0000   Tue, 15 Jun 2021 15:03:16 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  10.0.0.149
Capacity:
  attachable-volumes-csi-cinder.csi.openstack.org:  256
  cpu:                                              5
  ephemeral-storage:                                104322028Ki
  hugepages-1Gi:                                    0
  hugepages-2Mi:                                    0
  memory:                                           82375700Ki
  pods:                                             110
Allocatable:
  attachable-volumes-csi-cinder.csi.openstack.org:  256
  cpu:                                              5
  ephemeral-storage:                                96143180846
  hugepages-1Gi:                                    0
  hugepages-2Mi:                                    0
  memory:                                           82273300Ki
  pods:                                             110
System Info:
  Machine ID:                 3c732088e7f141358d292535f2521fb0
  System UUID:                377550af-1b59-40f4-b1dd-fa70a0985569
  Boot ID:                    a661ea24-4f1c-4ed7-834c-313fe311c439
  Kernel Version:             5.7.12-200.fc32.x86_64
  OS Image:                   Fedora CoreOS 32.20200809.3.0
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.11
  Kubelet Version:            v1.15.7
  Kube-Proxy Version:         v1.15.7
PodCIDR:                      10.100.5.0/24
PodCIDRs:                     10.100.5.0/24

ProviderID:                   openstack:///377550af-1b59-40f4-b1dd-fa70a0985569
Non-terminated Pods:          (3 in total)
  Namespace                   Name                                                           CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                           ------------  ----------  ---------------  -------------  ---
  gpu-operator                gpu-operator-1623769563-node-feature-discovery-worker-6d7hn    0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kube-system                 csi-cinder-nodeplugin-q7fjx                                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         15h
  kube-system                 kube-flannel-ds-nblzb                                          100m (2%)     100m (2%)   50Mi (0%)        50Mi (0%)      15h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                                         Requests   Limits
  --------                                         --------   ------
  cpu                                              100m (2%)  100m (2%)
  memory                                           50Mi (0%)  50Mi (0%)
  ephemeral-storage                                0 (0%)     0 (0%)
  hugepages-1Gi                                    0 (0%)     0 (0%)
  hugepages-2Mi                                    0 (0%)     0 (0%)
  attachable-volumes-csi-cinder.csi.openstack.org  0          0
Events:                                            <none>`

Could you point me in the right direction for investigating/fixing this?

Thanks

Alex
[kubectl get daemonset -A.txt](https://github.com/NVIDIA/gpu-operator/files/6660790/kubectl.get.daemonset.-A.txt)
[kubectl get pods -A.txt](https://github.com/NVIDIA/gpu-operator/files/6660791/kubectl.get.pods.-A.txt)

**Comment by apdibbo** [comment]
After some experimenting, I've found that I dont get this issue with 1.5.2 version of the chart

**Comment by shivamerla** [comment]
@apdibbo  can you share the logs of gpu-operator pod? The required label by NFD seems to be added fine. Need to check logs on why gpu-operator couldn't add other component labels.

```
feature.node.kubernetes.io/pci-10de.present=true
```
