### ISSUE TITLE
How to handle a cluster with multiple kernel version.

### ISSUE THREAD

**Issue by yujunz** [NVIDIA/gpu-operator#21]
### 1. Issue or feature description

https://github.com/NVIDIA/gpu-operator/blob/cb3bbd96ff38a27e89d1b54355a191e5126d5d6a/pkg/controller/specialresource/specialresource_controls.go#L236

The code comments assumes all node have the same kernel version which is not true in my case (the GPU nodes have a different version to the CPU nodes).

Is there a way to handle a cluster with multiple kernel version?

### 2. Steps to reproduce the issue

N/A

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

N/A

**Comment by yujunz** [comment]
Besides, it is not rare case if the cluster is upgraded several times. For example:

<img width="700" alt="Screen Shot 2020-01-02 at 2 02 25 PM" src="https://user-images.githubusercontent.com/6813397/71653635-8639b900-2d68-11ea-9400-ae23a6a7728a.png">

**Comment by yujunz** [comment]
My current workaround is modifying the DaemonSet manually.

But then pod crashed. Seems the same problem in #18 .

**Comment by RenaudWasTaken** [comment]
Hello!

This is a feature we plan to tackle pretty soon (1-2 months).

It already should work as driver containers will recompile the drivers for the current kernel.
The line you highlighted points to a feature where the driver that lands on a node is already compiled for that specific kernel.
