### ISSUE TITLE
gpu-operator can't running at centos7

### ISSUE THREAD

**Issue by daniel-hutao** [NVIDIA/gpu-operator#211]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ N] Are you running on an Ubuntu 18.04 node?
- [ Y] Are you running Kubernetes v1.13+?
- [ Y] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ N] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ Y] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

I deployed the gpu-operator according to the document, but encountered many errors continuously. I have been debugging on this for several days.  For example, the nvidia/driver centos mirror corresponding to the version in the helm package does not exist. Then I downloaded the latest version of the centos mirror and changed the version number in values.yaml (460.32.03).

After a lot of hard work, I got a lot of programs, and finally got stuck on the nvidia-driver container. The startup command of this container is nvidia-driver init. I found this script, added set -x, and debugged it many times. I don't quite understand some of these issues, such as `curl -fsSL $(repoquery --location kernel-${KERNEL_VERSION}) | rpm2cpio | cpio -idm --quiet` ，the rpm pkg of kernel-4.19.113-300.el7.x86_64.rpm is empty，modules files are in `kernel-modules-4.19.113-300.el7.x86_64.rpm` and `kernel-core-4.19.113-300.el7.x86_64.rpm`. but the kernel-${KERNEL_VERSION} of old version such as 3.x do has modules file. maybe gpu-operator can running at centos7 with kernel 3.10. But my system needs a 4.x kernel in order to use ipvs and other functions. The system only has rhel 7 and centos7. At the same time, I want to use gpu-operator, and I feel very headache for it. I hope the gpu-operator can better support centos7.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by shivamerla** [comment]
@daniel-hutao  Please refer to [this](https://github.com/NVIDIA/gpu-operator/issues/197#issuecomment-876209712) thread. Using toolkit version `--set toolkit.version=devel-centos7` seems to resolve this. This version will be officially released soon.

**Comment by shivamerla** [comment]
This is fixed by choosing toolkit version as `1.7.2-centos7`
