### ISSUE TITLE
Validation Pod failing to do its job when the driver failed to be removed

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#212]
Hello,

we noticed that if for any reason, the kernel driver cannot be removed when the GPU Operator is uninstalled,
the validation Pod will lift the `driver` barrier right away (`nvidia-smi` works), allowing the other operands to run.

Because of these operands keeping the driver busy, the driver-container will not be able to remove the old driver, and thus will fail forever to load the new one.

---

here is what the validation pod reports (1.6.2 driver):
```
$ oc logs nvidia-operator-validator-z94hz --all-containers
all validations are successful
running command chroot with args [/run/nvidia/driver nvidia-smi]
Thu Jun 17 19:15:50 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   34C    P0    26W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```
and the driver contains fails on this:
```
Starting installation of NVIDIA driver version 460.73.01 for Linux kernel version 4.18.0-240.22.1.el8_3.x86_64
...
+ nvidia_refs=47
+ rmmod_args+=("nvidia")
+ '[' 47 -gt 2 ']'
+ echo 'Could not unload NVIDIA driver kernel modules, driver is in use'
Could not unload NVIDIA driver kernel modules, driver is in use
+ return 1
+ exit 1
```

---

I guess the validation pod should ensure that the right version of the driver is loaded before lifting its barrier.

**Comment by shivamerla** [comment]
@kpouget this is one of the reason to require a host reboot after gpu-operator is un-installed, before re-installing again. bind mount of `/run/nvidia/driver` would be stale as old container died/restarted, but nvidia-smi still works with chroot. Even if we add the version check, it would be same too if we are re-installing with same driver version. Also, in some cases even when driver modules were not loaded, `nvidia-smi` loads them again from stale `/run/nvidia/driver`.  Will look more into handling these cases with refactoring we are doing to use pre-compiled modules.
