### ISSUE TITLE
Switch the MIG Strategy after deploying the gpu-opeataor

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#215]
Is it possible to swtich the mig strategy after deploying the gpu-operator?

**Comment by kpouget** [comment]
Hello @Kaka1127, 
no, with the current (1.7.x) version of the GPU Operator, changing the MIG strategy isn't supported.
It should work with the next release (1.8) coming this summer, see this [PR](https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/245).

for information: https://www.openshift.com/blog/multi-instance-gpu-support-with-the-gpu-operator-v1.7.0
> This field must be configured in the GPU Operator ClusterPolicy during its initial deployment.
> Please note that updates to the ClusterPolicy after it has been deployed are currently silently ignored.

A workaround to force the regeneration of the DaemonSets is to delete them (all but the `driver` DaemonSet):
> oc delete ds nvidia-operator-validator nvidia-mig-manager nvidia-device-plugin-daemonset nvidia-dcgm-exporter nvidia-container-toolkit-daemonset gpu-feature-discovery

they will be recreated and redeployed with the correct value

**Comment by Kaka1127** [comment]
Hi kpouget

Thank you for your kindly response.
I see. I will check this feature by new release gpu-operator in this summer.

Best regards.
Kaka
