### ISSUE TITLE
vGPU GRID on OKD

### ISSUE THREAD

**Issue by snelis** [NVIDIA/gpu-operator#220]
I'm running the gpu-operator on top of OKD4.5. (fedora coreos 5.6.19-300.fc32.x86_64 | crio 1.18.2 | kubernetes v1.18.3.)

The VM's have a vGPU (through vmware).
Installation went fine, pods see the GPU and can use them.
The first couple of minutes are fine, all goes smooth, but after a few minutes the GPU memory allocation is really slow.
Like a few MB's per couple of seconds, feels throttled.

I know there is some throttling in vGPU when there is no license.
A licensingConfig is configured and i see the gridd.conf appear in the nodes.
I will check for logs on the licencing server, but is there a way to check the logs for this licensing lease on the kubernetes or VM side ?

**Comment by shivamerla** [comment]
@snelis nvidia-gridd logs to syslog under /var/log, so you can verify for any errors there. Also, licensing status can be found using `sudo chroot /run/nvidia/driver/ nvidia-smi -q` on the host.

**Comment by snelis** [comment]
Thanks, the nvidia-smi -q helped on confirming.

```
    vGPU Software Licensed Product
        Product Name                      : NVIDIA Virtual Compute Server
        License Status                    : Unlicensed
```
I cannot find any logs for it though.
Do you have a direction for me on which application or service should write these logs?
I have a feeling it might not even attempted the lisencing.

Is this the correct location for it ?
`/run/nvidia/driver/drivers/gridd.conf` since i also see the 
`/run/nvidia/driver/etc/nvidia/gridd.conf.template`

**Comment by shivamerla** [comment]
@snelis driver container will copy the `/drivers/gridd.conf` into `/etc/nvidia/gridd.conf` was DRIVER_TYPE=vgpu set when building the driver image? Checking driver container logs will indicate if nvidia-gridd service was started at the end.

**Comment by snelis** [comment]
ah, I can see what you're talking about in the rhel8 folder of the driver repo, but the fedora folder is a bit outdated it seems and OKD runs on fedora.

However, thanks to your pointers I managed to put the vGPU part from the rhel8 setup into my fedora image.
It now shows up as Licensed and working fine. 

Thanks !
