### ISSUE TITLE
DCGM Disabled option

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#223]
Is there any way to be disabled the installing DCGM operator when deployed the GPU Operator?

Best regards.
Kaka

**Comment by shivamerla** [comment]
@Kaka1127 Currently there is no option to disable this. We can look into adding this. Do you plan to install DCGM manually?

**Comment by Kaka1127** [comment]
Yes, I planed to install the DCGM manually but I could find the solution to get the host ip from other labels. 
Background: 
 As you may know, the following template did not work correctly if using the GPU operator because the "instance" variable was used the internal address. As a result, other metrics was not gotten from node-exporters.
  Tempalte: https://github.com/NVIDIA/deepops/blob/master/src/dashboards/gpu-dashboard.json
