### ISSUE TITLE
nvidia/driver: could not resolve Linux kernel version for Amazon Linux 2

### ISSUE THREAD

**Issue by aliciayang1** [NVIDIA/gpu-operator#227]
Trying to install gpu-operator and these are the logs for one of the NVIDIA driver daemonset pods. We have confirmed that we have the appropriate kernel headers installed which is the solution to https://github.com/NVIDIA/gpu-operator/issues/85. Any thoughts on how to resolve this issue?

```
========== NVIDIA Software Installer ==========
Starting installation of NVIDIA driver version 460.73.01 for Linux kernel version 4.14.232-177.418.amzn2.x86_64
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Resolving Linux kernel version...
Could not resolve Linux kernel version
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...

**Comment by cdesiniotis** [comment]
Amazon Linux is not supported by the GPU Operator, and there are no published driver images for it. Please see our docs for what operating systems the GPU Operator supports and is tested on: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#linux-distributions
