### ISSUE TITLE
Upgrade/reboot issue related to the container-toolkit

### ISSUE THREAD

**Issue by kpouget** [NVIDIA/gpu-operator#228]
Hello,

in a recent cluster upgrade (4.7 -> 4.8) CI test, using the GPU Operator `master` branch ([commit](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.7-upgrade-gpu-operator-e2e-upgrade/1420353446782963712/artifacts/gpu-operator-e2e-upgrade/0-preupgrade-gpu-operator-test-master-branch/artifacts/009__gpu_operator__bundle_from_commit/operator-image-builder-pod.log) 8188766aac0b280b90332248430d540d79653a62), we [observed](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.7-upgrade-gpu-operator-e2e-upgrade/1420353446782963712/artifacts/gpu-operator-e2e-upgrade/2-postupgrade-gpu-operator-validate-deployment/artifacts/001__gpu-operator__must-gather/004__gpu_operator__capture_deployment_state/gpu_operator_pods.list) a failure with the Pods unable to start:
```
NAME                                       READY   STATUS                      RESTARTS   AGE    IP            NODE                          NOMINATED NODE   READINESS GATES
gpu-feature-discovery-9xbmz                0/1     CreateContainerError        0          43m    10.130.2.13   ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-container-toolkit-daemonset-x6rkr   1/1     Running                     0          43m    10.130.2.2    ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-cuda-validator-wtxld                0/1     Completed                   0          32m    10.130.2.14   ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-dcgm-btl2f                          0/1     CreateContainerError        0          43m    10.130.2.5    ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-dcgm-exporter-z55rt                 0/1     Init:CreateContainerError   0          43m    10.130.2.12   ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-device-plugin-daemonset-mpsbn       0/1     CreateContainerError        0          43m    10.130.2.4    ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-driver-daemonset-4rfm7              0/1     CreateContainerError        0          32m    10.130.2.15   ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-node-status-exporter-462xg          1/1     Running                     0          114m   10.130.2.9    ip-10-0-164-90.ec2.internal   <none>           <none>
nvidia-operator-validator-x4bxj            0/1     Init:CreateContainerError   2          43m    10.130.2.7    ip-10-0-164-90.ec2.internal   <none>           <none>
```

From the `events`, we [see](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.7-upgrade-gpu-operator-e2e-upgrade/1420353446782963712/artifacts/gpu-operator-e2e-upgrade/gather-extra/artifacts/events.json) that they are failing because of the container toolkit:
```
"message": "Error: container create failed: time=\"2021-07-28T14:17:45Z\" level=error msg=\"container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: initialization error: driver error: failed to process request\\n\"\n",

--> nvidia-container-cli.real: initialization error: driver error: failed to process request
```

The toolkit [seems](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.7-upgrade-gpu-operator-e2e-upgrade/1420353446782963712/artifacts/gpu-operator-e2e-upgrade/2-postupgrade-gpu-operator-validate-deployment/artifacts/001__gpu-operator__must-gather/004__gpu_operator__capture_deployment_state/gpu_operator_nvidia-container-toolkit-daemonset.log) to eventually run fine.

I'm not sure where to look for more clues, and obviously it's a post-mortem analysis, we didn't see it yet with a live cluster ...

**Comment by omertuc** [comment]
Full run logs available [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-psap-ci-artifacts-release-4.7-upgrade-gpu-operator-e2e-upgrade/1420353446782963712) (under "Arifacts")

**Comment by shivamerla** [comment]
thanks @omertuc  will take a look

**Comment by omertuc** [comment]
It was @kpouget who posted it, I just gave a link to the full logs cause it was missing.

And just to make sure it's clear - this is not an issue with operator upgrades, but with OCP upgrades

**Comment by shivamerla** [comment]
This should be fixed with `NVIDIA_VISIBLE_DEVICES=void` set now with rhcos images.
