### ISSUE TITLE
Resource limits

### ISSUE THREAD

**Issue by klamkma** [NVIDIA/gpu-operator#229]
Hello,

On big kubernetes cluster we have OOM for the operator pod. Can resource limits be configurable from the values https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/templates/operator.yaml#L66-L67?

Regards,

**Comment by shivamerla** [comment]
@klamkma sure, we can make this configurable with helm. Can you share the operator resource usage on your cluster?

**Comment by klamkma** [comment]
I do not need much more, memory limit: 300Mi is enough.
Thank you.

**Comment by shivamerla** [comment]
Closing this as the [change](https://github.com/NVIDIA/gpu-operator/commit/da026665ade57ed5b79bcceb90df239f673d70e3) is now merged:
