### ISSUE TITLE
Unable to setup NVIDIA GPU operator in OKD 4.6

### ISSUE THREAD

**Issue by shubhamoli** [NVIDIA/gpu-operator#231]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? 
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

**Unable to setup NVIDIA GPU operator in OKD v4.6**

Apologies if this is not the right place to ask this but since NVIDIA GPU operator is not available in the Operator Hub for OKD so the only option is to install it via Helm. I followed this article found in issue #95 but it doesn't seem to work on Fedora CoreOS 33 / Kernel `v5.9.12-200.fc33.x86_64`

`nvidia-driver-daemonset` is failing with the following error while other deployments are stuck in the `Init` step

```
Generating Linux kernel version string...
+ echo 'Generating Linux kernel version string...'
+ extract-vmlinux ./lib/modules/5.9.12-200.fc33.x86_64/vmlinuz
+ strings
+ grep -E '^Linux version'
+ sed 's/^\(.*\)\s\+(.*)$/\1/'
extract-vmlinux: Cannot find vmlinux.
+ '[' -z '' ']'
+ echo 'Could not locate Linux kernel version string'
Could not locate Linux kernel version string
+ return 1
```

### 2. Steps to reproduce the issue
I followed [this link](https://hackmd.io/-vpQKhC8SVmDewmJLQgGnw) found in issue #95 but seems like it doesn't work in Fedora 33 kernel version `5.9.12-200.fc33.x86_64`

**Comment by shivamerla** [comment]
@shubhamoli we don't officially support OKD with GPU operator. Independent of GPU Operator, we need to make sure fedora driver images are working on OKD. Looking at the script, the path we check for vmlinuz file seems wrong. It should be absolute path `/lib/modules/${KERNEL_VERSION}/vmlinuz`. You can try building new image with that change and verify.

```
    echo "Generating Linux kernel version string..."
    extract-vmlinux ./lib/modules/${KERNEL_VERSION}/vmlinuz | strings | grep -E '^Linux version' | sed 's/^\(.*\)\s\+(.*)$/\1/' > version
    if [ -z "$(<version)" ]; then
        echo "Could not locate Linux kernel version string" >&2
        return 1
    fi
```

**Comment by shubhamoli** [comment]
@shivamerla Thank you for the quick reply. 

> Looking at the script, the path we check for vmlinuz file seems wrong. It should be absolute path
It might a dumb question but where do I've to make this change?

**Comment by shivamerla** [comment]
@shubhamoli you need to build from here: https://gitlab.com/nvidia/container-images/driver/-/tree/master/fedora

**Comment by shubhamoli** [comment]
Thanks again @shivamerla I'll try it out.
