### ISSUE TITLE
one gpu is missing

### ISSUE THREAD

**Issue by sysThematic** [NVIDIA/gpu-operator#232]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
We have an HP DL380 Gen10 servers with four Nvidia T4 GPUs attached.
Acting as baremetal workers of Openshift 4.6 cluster.
When we install gpu-operator it discovers only 3 out of 4 GPUs.

We have following logs on driver pod:
[  204.009631] nvidia: module verification failed: signature and/or required key missing - tainting kernel
[  204.016338] nvidia-nvlink: Nvlink Core is being initialized, major device number 508
[  204.016893] nvidia 0000:12:00.0: enabling device (0140 -> 0142)
[  204.067287] nvidia 0000:13:00.0: enabling device (0140 -> 0142)
[  204.112178] nvidia 0000:37:00.0: enabling device (0140 -> 0142)
[  204.163230] nvidia 0000:af:00.0: enabling device (0140 -> 0142)
[  204.163286] NVRM: request_mem_region failed for 0M @ 0x0. This can
               NVRM: occur when a driver such as rivatv is loaded and claims
               NVRM: ownership of the device's registers.
[  204.163305] nvidia: probe of 0000:af:00.0 failed with error -1
[  204.163337] NVRM: The NVIDIA probe routine failed for 1 device(s).
[  204.163338] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  460.73.01  Thu Apr  1 21:40:36 UTC 2021
[  204.184229] nvidia-uvm: Loaded the UVM driver, major device number 506.
[  204.188976] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  460.73.01  Thu Apr  1 21:32:31 UTC 2021
[  204.191416] nvidia-modeset: Unloading
[  204.398228] nvidia-uvm: Unloaded the UVM driver.
[worker-console.log](https://github.com/NVIDIA/gpu-operator/files/6916218/worker-console.log)

### 2. Steps to reproduce the issue
I have a second cluster with two more workers (with identical hardware configs) experiencing the same issue.
So I can reproduce it by having 4 Nvidia Tesla T4 gpus and installing operator using documentation:
https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [x] NVIDIA shared directory: `ls -la /run/nvidia`
 - [x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [x] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by shivamerla** [comment]
@sysThematic Can you run "/run/nvidia/driver/usr/bin/nvidia-bug-report.sh" from any of the worker nodes(using `oc debug node <node-name>`) having failures and attach the repo generated under "/var/log/" here.

**Comment by sysThematic** [comment]
Hi @shivamerla ,
Log file is attached.
[nvidia-bug-report.log.gz](https://github.com/NVIDIA/gpu-operator/files/6926730/nvidia-bug-report.log.gz)
