### ISSUE TITLE
nvidia-device-plugin-validator fails - Requested: 1, Available: 0

### ISSUE THREAD

**Issue by klamkma** [NVIDIA/gpu-operator#233]
Hello,

### 1. Issue or feature description

nvidia-device-plugin-validator fails with:
```
  Type     Reason                    Age   From                   Message
  ----     ------                    ----  ----                   -------
  Warning  UnexpectedAdmissionError  110s  kubelet, xxxxx  Allocate failed due to requested number of devices unavailable for nvidia.com/gpu. Requested: 1, Available: 0, which is unexpected

```
### 2. Steps to reproduce the issue
1. Kubernetes cluster has pending pod waiting for available GPU.
2. Start the nvidia operator and driver installation.
3. If the pending pod picks up the GPU faster than the validator, nvidia-device-plugin-validator fails as there are 0 available GPUs left.

Is there anything I can do to avoid this error? 
I'm using your helm chart for the installation https://github.com/NVIDIA/gpu-operator/tree/master/deployments/gpu-operator.

Kind regards,

**Comment by shivamerla** [comment]
@klamkma You can disable device-plugin validation with workload using GPU operator. Please install GPU operator with below validator settings.

```
validator:
  plugin:
    env:
      - name: WITH_WORKLOAD
        value: "false"
```

**Comment by klamkma** [comment]
@shivamerla, thank you for the quick reply.
I applied this modification in ClusterPolicy, but operator is not modifying the nvidia-operator-validator DaemonSet.
Do I need to modify objects created by the operator manually if they already exists?

I'm using https://github.com/NVIDIA/gpu-operator/tree/v1.7.0/deployments/gpu-operator helm chart.

Regards

**Comment by shivamerla** [comment]
@klamkma v1.7.x doesn't support auto updates of Daemonsets. We are adding this with 1.8 which will be released in a week. Meanwhile you need to edit gpu-operator-validator pod (plugin-validation container within it) and pass this env variable to it.

**Comment by klamkma** [comment]
Thank you, I have no failing pods now.
I'll close this issue.
