### ISSUE TITLE
Unable to open the file '/lib/modules/3.10.0-1160.36.2.el7.x86_64/proc/version' (No such file or directory).Could not resolve Linux kernel version

### ISSUE THREAD

**Issue by yug0slav** [NVIDIA/gpu-operator#235]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ no ] Are you running on an Ubuntu 18.04 node? (CentOS 7.9)
- [ yes ] Are you running Kubernetes v1.13+? (v1.21.2)
- [ no ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? (containerd 1.4.9)
- [ yes ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
- nvidia-driver-ctr  - Back-off restarting failed container
```
2021-08-03T15:47:07Z ========== NVIDIA Software Installer ==========
2021-08-03T15:47:07Z 
2021-08-03T15:47:07Z Starting installation of NVIDIA driver version 460.73.01 for Linux kernel version 3.10.0-1160.36.2.el7.x86_64
2021-08-03T15:47:07Z 
2021-08-03T15:47:07Z Stopping NVIDIA persistence daemon...
2021-08-03T15:47:07Z Unloading NVIDIA driver kernel modules...
2021-08-03T15:47:07Z Unmounting NVIDIA driver rootfs...
2021-08-03T15:47:07Z Checking NVIDIA driver packages...
2021-08-03T15:47:07Z Updating the package cache...
2021-08-03T15:47:14Z Resolving Linux kernel version...
2021-08-03T15:47:14Z Proceeding with Linux kernel version 3.10.0-1160.36.2.el7.x86_64
2021-08-03T15:47:14Z Installing Linux kernel headers...
2021-08-03T15:47:48Z Installing Linux kernel module files...
2021-08-03T15:47:54Z Unable to open the file '/lib/modules/3.10.0-1160.36.2.el7.x86_64/proc/version' (No such file or directory).curl: (60) Peer's Certificate issuer is not recognized.
```
### 2. Steps to reproduce the issue
- deploy gpu-operator helm chart with repo-config CM per https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/install-gpu-operator-air-gapped.html#install-gpu-operator-air-gapped

**Comment by cdesiniotis** [comment]
This is failing here:
```
echo "Installing Linux kernel module files..."
curl -fsSL $(repoquery --location kernel-${KERNEL_VERSION}) | rpm2cpio | cpio -idm --quiet
```
From the error message, it appears that the driver container needs the CA certificate of your local server that is hosting the mirrored repository. Could you try injecting the custom CA certificate file into the driver container (i.e. mounting /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors)?

Currently we do not have an option to mount CA certificates when deploying the GPU operator via helm. Until we make this configurable, you can try editing the driver Daemonset manually to mount the CA certificate. You must be using GPU Operator <v1.8 for this to work.

**Comment by yug0slav** [comment]
I'll give it a try. 
Was thinking sslverify=false in repo-config... :). No luck.

**Comment by yug0slav** [comment]
What would be the easiest way to inject a CA file or mount /etc/pki/ca-trust/source/anchors?

- I've tried the following updates in nvidia.com_clusterpolicies_crd.yaml
```
                  certConfig:
                    description: 'Optional: CA certificate for local repo'
                    properties:
                      configMapName:
                        type: string
                      destinationDir:
                        type: string
                    type: object
```
- and clusterpolicy.yaml
```
    {{- if .Values.driver.certConfig }}
    certConfig: {{ toYaml .Values.driver.certConfig | nindent 6 }}
    {{- end }}
```
- followed by updates to values.yaml
```
  # Local repo CA cert
  certConfig:
    configMapName: root-ca
    destinationDir: /etc/pki/ca-trust/source/anchors
```

with no luck... :(

**Comment by shivamerla** [comment]
@yug0slav This require a gpu-operator change to mount a configmap for certs which is not supported yet. You need to manually edit driver daemonset in `gpu-operator-resources` namespace and add `/etc/pki/ca-trust/source/anchors` host path mount.

**Comment by yug0slav** [comment]
- mounting /etc/pki/ca-trust/extracted as hostPath into nvidia-driver-daemonset worked!
  - are there plans to add this functionality into the 1.8 release?

- had to unload nouveau module too, don't think its in the instructions for centos 7.9 / 3.10.0 kernel.

Thanks!

**Comment by cdesiniotis** [comment]
@yug0slav this feature was not added in 1.8. We are discussing this internally but don't have a target release for this
