### ISSUE TITLE
vectorAdd not run after helm installation with "RuntimeHandler \"nvidia\" not supported"

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/gpu-operator#236]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

I want to run vectoradd on gpu operator with following operation but failed with following error.
Would you any suggestions?

- Kubernetes 1.21

I install following helm chart.

```
curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
   && chmod 700 get_helm.sh \
   && ./get_helm.sh
helm repo add nvidia https://nvidia.github.io/gpu-operator \
   && helm repo update
helm install --wait --generate-name \
     nvidia/gpu-operator \
     --set driver.enabled=false --set toolkit.enabled=false --set operator.defaultRuntime=containerd
```

I try to run vectorAdd, But failed with `RuntimeHandler  nvidia not supported.`
It seems following message comes from dockershim. But I set helm chart with containerd as defaultRuntime (strange).

```
Jul 30 04:54:23 du3 kubelet[50437]: E0730 04:54:23.216598   50437 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = RuntimeHandler \"nvidia\" not supported"
Jul 30 04:54:23 du3 kubelet[50437]: E0730 04:54:23.216686   50437 kuberuntime_sandbox.go:68] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = RuntimeHandler \"nvidia\" not supported" pod="gpu-operator-resources/nvidia-device-plugin-daemonset-7dvgv"
Jul 30 04:54:23 du3 kubelet[50437]: E0730 04:54:23.216731   50437 kuberuntime_manager.go:790] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = RuntimeHandler \"nvidia\" not supported" pod="gpu-operator-resources/nvidia-device-plugin-daemonset-7dvgv"
Jul 30 04:54:23 du3 kubelet[50437]: E0730 04:54:23.216830   50437 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"nvidia-device-plugin-daemonset-7dvgv_gpu-operator-resources(a7699fe6-d928-4c0a-837f-52c4269c25d8)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"nvidia-device-plugin-daemonset-7dvgv_gpu-operator-resources(a7699fe6-d928-4c0a-837f-52c4269c25d8)\\\": rpc error: code = Unknown desc = RuntimeHandler \\\"nvidia\\\" not supported\"" pod="gpu-operator-resources/nvidia-device-plugin-daemonset-7dvgv" podUID=a7699fe6-d928-4c0a-837f-52c4269c25d8
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

/etc/docker/daemon.json is follows

```json
{
        "default-runtime": "nvidia",
        "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

**Comment by shivamerla** [comment]
@sakaia Looks like you are installing with runtime set to `containerd`, but toolkit is disabled. So you need to manually configure `/etc/containerd/config.toml` in this case. You seem to have configured /etc/docker/daemon.json instead. Below is an example of how containerd config should looks like.

```
$ cat /etc/containerd/config.toml 
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "k8s.gcr.io/pause:3.4.1"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v1"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime"
```

**Comment by sakaia** [comment]
Thank you for your help.

It fails. The message "RuntimeHandler \"nvidia\" not supported" still keeps.

From seeing this, I need to change kubelet configuration from `docker` to `remote`.?

## Dockershim source code
From seeing this, container runtime `docker` is running at this moment. and its RuntimeHandler name seems to be `nvidia` not `docker`. It causes this problem. 

```go
	// Step 2: Create the sandbox container.
	if r.GetRuntimeHandler() != "" && r.GetRuntimeHandler() != runtimeName {
		return nil, fmt.Errorf("RuntimeHandler %q not supported", r.GetRuntimeHandler())
	}
```


https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/dockershim/docker_sandbox.go#L106-L109

## kubectl get nodes -o wide
From seeing this, kubectl is  configured container runtime as docker.

```
$ kubectl get nodes -o wide
NAME   STATUS   ROLES                  AGE     VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION        CONTAINER-RUNTIME
du3    Ready    control-plane,master   6d23h   v1.21.3   192.168.123.22   <none>        Ubuntu 18.04.5 LTS   5.4.0-64-lowlatency   docker://19.3.15
```




## Reference

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

```
--container-runtime string     Default: `docker`
   The container runtime to use. Possible values: `docker`, `remote`.
```

**Comment by sakaia** [comment]
It stacks this problem.
I try to execute another method to build environment.

**Comment by shivamerla** [comment]
> It stacks this problem.
> I try to execute another method to build environment.

I think you are trying to install with "containerd" as runtime setup, but you actually have docker installed instead. You can remove `--set operator.defaultRuntime=containerd` if you want to use docker instead. Or setup kubelet to use containerd.
