### ISSUE TITLE
1.8.0 install loop does not settle

### ISSUE THREAD

**Issue by rspierz** [NVIDIA/gpu-operator#246]
Upgraded fresh to 1.8.0. Seem to be in a loop on two gpu clusters. Events showing:

"Error: cannot find volume "run-nvidia" to mount into container "k8s-driver-manager"

"Allocate failed due to requested number of devices unavailable for nvidia.com/gpu. Requested: 1, Available: 0, which is unexpected"

On Openshift 4.7.22.

**Comment by shivamerla** [comment]
@rspierz Looks like we missed mounting with path type as `DirectoryOrCreate` which fails on few OCP versions and created by default with 4.8. Will fix this soon with 1.8.1.

**Comment by shivamerla** [comment]
This has been resolved.
