### ISSUE TITLE
Questions related to GPU Operator

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#256]
Hi 

I have some questions. Please let me confirm them.

1. It possible to deploy the gpu-operator to the mixed the environment of DGX-Station(installed the gpu driver and toolkit) and OEM server(not installed the gpu driver and toolkit) cluster?
2. Does the GPU operator support to run correctly on one server which is installed different SKUs(ex. A100 x1 and A6000 x3)? Note: I am not sure that OEM vender supported this configuration.
3. Does the mig-manager work DGX or  the Server (pre-installed nvidia gpu driver)?

Best regards.
Kaka

**Comment by shivamerla** [comment]
@Kaka1127  below are the responses:

1. It possible to deploy the gpu-operator to the mixed the environment of DGX-Station(installed the gpu driver and toolkit) and OEM server(not installed the gpu driver and toolkit) cluster?
>>> Yes, its possible to deploy in this environment but with some tweaks. You need to manually label DGX nodes with

`nvidia.com/gpu.deploy.driver=false` and `nvidia.com/gpu.deploy.container-toolkit=false` before installing GPU operator with default values. Currently GPU Operator doesn't not automatically detect pre-installed drivers/toolkit, so this label change is required to get this work.


2. Does the GPU operator support to run correctly on one server which is installed different SKUs(ex. A100 x1 and A6000 x3)? Note: I am not sure that OEM vender supported this configuration.
>>> Yes, this is supported and don't recollect any issues being reported with this config.

3. Does the mig-manager work DGX or the Server (pre-installed nvidia gpu driver)?
>>> No, MIG manager doesn't work currently with pre-installed drivers. Work is on-going to support this.

**Comment by Kaka1127** [comment]
@shivamerla 

Thank you for your kinds response. I got it.
Would you please  answer one more question?

4. If used the server of installing mix SKUs, it is possible to work the task on the specified SKU?
It will be labeled the multiple SKU and family to this server. As a result, the task will be assigned the server by checking the label but I think the task cannot control which SKU will run. Is my understanding correct?

Best regards.
Kaka

**Comment by Kaka1127** [comment]
Could you please show us your plans about when you are going to release that?

**Comment by shivamerla** [comment]
@Kaka1127 its targeted to be supported with `v1.9` of operator, which is sometime in November.

**Comment by Kaka1127** [comment]
@shivamerla 
Thank you for your comment.
