### ISSUE TITLE
nvidia-driver-daemonset stuck in Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by ctromans** [NVIDIA/gpu-operator#258]
Having trouble getting the gpu-operator running, any suggestions much appreciated.   Full details below.  Thank you in advance!

Using microk8s v1.21.3, installed via snap tracking the latest/stable channel on Ubuntu 21.04.  The system has a Geforce RTX 3070:

nvidia-smi
Fri Sep 10 13:53:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8    13W /  N/A |      5MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    138084      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

Installed GPU-Operator via:

microk8s.helm3 install gpu-operator nvidia/gpu-operator
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2346/credentials/client.config
NAME: gpu-operator
LAST DEPLOYED: Fri Sep 10 13:57:10 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

Which gives:

kubectl get pods -A
NAMESPACE                NAME                                                          READY   STATUS                  RESTARTS   AGE
default                  cuda-vector-add                                               0/1     Pending                 0          14h
jupyter                  proxy-765678ffd5-55l89                                        1/1     Running                 11         13d
kube-system              metrics-server-8bbfb4bdb-mwxvw                                1/1     Running                 11         14d
kube-system              dashboard-metrics-scraper-78d7698477-nrfpj                    1/1     Running                 59         14d
kube-system              coredns-7f9c69c78c-8s5qf                                      1/1     Running                 11         14d
jupyter                  user-scheduler-5644cbdd86-cdkqz                               1/1     Running                 49         13d
kube-system              kubernetes-dashboard-85fd7f45cb-tq5zp                         1/1     Running                 15         14d
jupyter                  user-scheduler-5644cbdd86-ct2sj                               1/1     Running                 66         13d
container-registry       registry-9b57d9df8-w272g                                      1/1     Running                 11         14d
jupyter                  continuous-image-puller-cszw7                                 1/1     Running                 11         13d
kube-system              calico-kube-controllers-57c667c964-h685m                      1/1     Running                 3          38h
kube-system              hostpath-provisioner-5c65fbdb4f-b9spt                         1/1     Running                 13         14d
kube-system              calico-node-2zlbn                                             1/1     Running                 3          38h
jupyter                  hub-7888c65fd4-4w9qr                                          1/1     Running                 19         9d
default                  gpu-operator-node-feature-discovery-worker-nh8rw              1/1     Running                 0          11m
default                  gpu-operator-node-feature-discovery-master-58d884d5cc-p45xs   1/1     Running                 0          11m
default                  gpu-operator-74dcf6544d-76gwc                                 1/1     Running                 0          11m
gpu-operator-resources   nvidia-container-toolkit-daemonset-lwjxc                      0/1     Init:0/1                0          46s
gpu-operator-resources   nvidia-dcgm-exporter-8pc4z                                    0/1     Init:0/1                0          46s
gpu-operator-resources   nvidia-device-plugin-daemonset-c5p7z                          0/1     Init:0/1                0          46s
gpu-operator-resources   nvidia-operator-validator-m74zj                               0/1     Init:0/4                0          46s
gpu-operator-resources   gpu-feature-discovery-npbtw                                   0/1     Init:0/1                0          46s
gpu-operator-resources   nvidia-dcgm-8lzk6                                             0/1     Init:0/1                0          46s
gpu-operator-resources   nvidia-driver-daemonset-v5gqj                                 0/1     Init:CrashLoopBackOff   6          11m

microk8s.kubectl describe pod nvidia-driver-daemonset-v5gqj --namespace gpu-operator-resources
Name:                 nvidia-driver-daemonset-v5gqj
Namespace:            gpu-operator-resources
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 blade-15-rz09-0369/192.168.1.73
Start Time:           Fri, 10 Sep 2021 13:57:29 +0100
Labels:               app=nvidia-driver-daemonset
                      controller-revision-hash=8487d66f45
                      pod-template-generation=1
Annotations:          cni.projectcalico.org/podIP: 10.1.203.215/32
                      cni.projectcalico.org/podIPs: 10.1.203.215/32
Status:               Pending
IP:                   10.1.203.215
IPs:
  IP:           10.1.203.215
Controlled By:  DaemonSet/nvidia-driver-daemonset
Init Containers:
  k8s-driver-manager:
    Container ID:  containerd://2849dd5811b4d6f9e0bd0f83e8dfba854d1f9d5dcf277f9bb965454871b8d3c0
    Image:         nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.1.0
    Image ID:      nvcr.io/nvidia/cloud-native/k8s-driver-manager@sha256:907ab0fc008bb90149ed059ac3a8ed3d19ae010d52c58c0ddbafce45df468d5b
    Port:          <none>
    Host Port:     <none>
    Command:
      driver-manager
    Args:
      uninstall_driver
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 10 Sep 2021 14:07:10 +0100
      Finished:     Fri, 10 Sep 2021 14:07:47 +0100
    Ready:          False
    Restart Count:  6
    Environment:
      NODE_NAME:                    (v1:spec.nodeName)
      NVIDIA_VISIBLE_DEVICES:      void
      ENABLE_AUTO_DRAIN:           true
      DRAIN_USE_FORCE:             false
      DRAIN_POD_SELECTOR_LABEL:    
      DRAIN_TIMEOUT_SECONDS:       0s
      DRAIN_DELETE_EMPTYDIR_DATA:  false
    Mounts:
      /run/nvidia from run-nvidia (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-skjmg (ro)
Containers:
  nvidia-driver-ctr:
    Container ID:  
    Image:         nvcr.io/nvidia/driver:470.57.02-ubuntu21.04
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      nvidia-driver
    Args:
      init
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /dev/log from dev-log (rw)
      /host-etc/os-release from host-os-release (ro)
      /run/mellanox/drivers from run-mellanox-drivers (rw)
      /run/nvidia from run-nvidia (rw)
      /run/nvidia-topologyd from run-nvidia-topologyd (rw)
      /var/log from var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-skjmg (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  run-nvidia:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia
    HostPathType:  DirectoryOrCreate
  var-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  
  dev-log:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/log
    HostPathType:  
  host-os-release:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  
  run-nvidia-topologyd:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia-topologyd
    HostPathType:  DirectoryOrCreate
  run-mellanox-drivers:
    Type:          HostPath (bare host directory volume)
    Path:          /run/mellanox/drivers
    HostPathType:  DirectoryOrCreate
  run-nvidia-validations:
    Type:          HostPath (bare host directory volume)
    Path:          /run/nvidia/validations
    HostPathType:  DirectoryOrCreate
  kube-api-access-skjmg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              nvidia.com/gpu.deploy.driver=true
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
                             nvidia.com/gpu:NoSchedule op=Exists
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned gpu-operator-resources/nvidia-driver-daemonset-v5gqj to blade-15-rz09-0369
  Normal   Pulled     10m (x5 over 14m)     kubelet            Container image "nvcr.io/nvidia/cloud-native/k8s-driver-manager:v0.1.0" already present on machine
  Normal   Created    10m (x5 over 14m)     kubelet            Created container k8s-driver-manager
  Normal   Started    10m (x5 over 14m)     kubelet            Started container k8s-driver-manager
  Warning  BackOff    4m40s (x27 over 13m)  kubelet            Back-off restarting failed container

microk8s.kubectl logs nvidia-driver-daemonset-v5gqj --namespace gpu-operator-resources
Error from server (BadRequest): container "nvidia-driver-ctr" in pod "nvidia-driver-daemonset-v5gqj" is waiting to start: PodInitializing

microk8s.kubectl get ds --all-namespaces
NAMESPACE                NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                      AGE
jupyter                  continuous-image-puller                      1         1         1       1            1           <none>                                             13d
kube-system              calico-node                                  1         1         1       1            1           kubernetes.io/os=linux                             14d
default                  gpu-operator-node-feature-discovery-worker   1         1         1       1            1           <none>                                             18m
gpu-operator-resources   nvidia-driver-daemonset                      1         1         0       1            0           nvidia.com/gpu.deploy.driver=true                  17m
gpu-operator-resources   nvidia-mig-manager                           0         0         0       0            0           nvidia.com/gpu.deploy.mig-manager=true             17m
gpu-operator-resources   nvidia-device-plugin-daemonset               1         1         0       1            0           nvidia.com/gpu.deploy.device-plugin=true           17m
gpu-operator-resources   nvidia-dcgm                                  1         1         0       1            0           nvidia.com/gpu.deploy.dcgm=true                    17m
gpu-operator-resources   gpu-feature-discovery                        1         1         0       1            0           nvidia.com/gpu.deploy.gpu-feature-discovery=true   17m
gpu-operator-resources   nvidia-operator-validator                    1         1         0       1            0           nvidia.com/gpu.deploy.operator-validator=true      17m
gpu-operator-resources   nvidia-container-toolkit-daemonset           1         1         0       1            0           nvidia.com/gpu.deploy.container-toolkit=true       17m
gpu-operator-resources   nvidia-dcgm-exporter                         1         1         0       1            0           nvidia.com/gpu.deploy.dcgm-exporter=true           17m

**Comment by cdesiniotis** [comment]
Hi @ctromans we don't officially support GeForce GPUs and microk8s (meaning we do not test/validate the gpu-operator on these). See our platform support page: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#platform-support

With that said, it seems like you have the nvidia driver preinstalled on the host. You need to install the GPU Operator like such:
```
helm install --wait --generate-name \
     nvidia/gpu-operator \
     --set driver.enabled=false
```

**Comment by FlorinAndrei** [comment]
@cdesiniotis 

> You need to install the GPU Operator like such:

It would be great to have a page where all these different install options are described, along with what they do and when it might be good to use them.

**Comment by treo** [comment]
@FlorinAndrei 
All options are listed here:
https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml

But you are right that it would be nice if they were a bit more commented as for how they are supposed to be used.

**Comment by cdesiniotis** [comment]
@FlorinAndrei  we appreciate the feedback. We are continually working to improve our documentation.

It is worth noting that under `Common Deployment Scenarios`, we cover most of the common deployment scenarios we have seen from our users (i.e. pre-installed drivers like I mentioned above in this issue). The examples in this section should be a good reference of how to use our various install options.

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#common-deployment-scenarios

**Comment by gigony** [comment]
Installing microk8s v1.22 worked.
It looks like an issue with microk8s: https://github.com/canonical/microk8s/issues/2634
