### ISSUE TITLE
Pods do not wait for nvidia-driver to be ready

### ISSUE THREAD

**Issue by v1nc3nt27** [NVIDIA/gpu-operator#261]
Hey there,

we are running the GPU-Operator on AWS EKS and since we also deploy spot instances, GPU nodes will come and go frequently. The issue is that the pods that run ML models on the GPUs won't wait for the nvidia driver to be ready. As soon as the node is up, they will spawn on it, but by that time the nvidia-driver pod hasn't finished, so the ML applications will instead run on the CPU, which is quite problematic. 

Currently, we solve this by having an initContainer with a sleep timer. I was wondering if there is a better solution to this, as the other pods like validator or dcgm-exporter also wait for the driver. They seem to mount /run/nvidia and a secret, so I'm not sure if this is a valid option for my own pods. Perhaps it could be done with readiness probes but I don't see any in the nvidia pods. 

Has anyone else experienced this issue and if yes, do you have any solution for this? Thanks!

**Comment by shivamerla** [comment]
@v1nc3nt27 Can you share the pod spec of ML workload? If you have explicit GPU resource `nvidia.com/gpu` request in the spec, then the pod should be in pending state until device-plugin is loaded which happens only after driver is loaded.

**Comment by v1nc3nt27** [comment]
@shivamerla thanks for your response. Oh, I remember this resource annotation, but I did remove it because this would limit the GPU node to one deployment with that annotation. Is this still the case? We need to have several deployments/models that use the GPU on a single node (with only one running at a time). If this is what prevents the pods to launch before the device-plugin is loaded, then it makes sense that it's not working for me.

What I tested now is copying the toolkit-validation initContainer from the dcgm-exporter to my deployment as an initContainer and it seemed to work:

```        
- name: toolkit-validation # copied from nvidia-dcgm-exporter
  image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.7.1
  command:
    - sh
    - '-c'
  args:
    - >-
      until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting
      for nvidia container stack to be setup; sleep 5; done
  resources: { }
  volumeMounts:
    - name: run-nvidia
      mountPath: /run/nvidia
      mountPropagation: HostToContainer```

Is this just a coincidence or may this actually be a workaround?

**Comment by shivamerla** [comment]
yes, this should work as well, its just that this initContainer would have to be added to all of your deployments. Yes, it is a limitation that with resource annotation the GPU will not be freed until the container is exited. If you are running multiple pods and each co-ordinating to run one at a time, it will not work with resource annotation.

**Comment by v1nc3nt27** [comment]
Alright, thanks a lot for your confirmation. I've tested it a few times by now and it indeed seems to work fine with the initContainer - it's not an issue for us to add it to the deployment. 

Perhaps, as a future suggestion, it might be interesting to natively allow multiple containers with that resource annotation on a GPU (although there might be good reasons not to do so which I'm not aware of). However, I'm also fine with that fix, so I will close the issue and thank you again for your feedback.
