### ISSUE TITLE
Unable to load nvidia.ko. OCP 4.8.13.The target kernel has CONFIG_MODULE_SIG set

### ISSUE THREAD

**Issue by rhn-gps-roellis** [NVIDIA/gpu-operator#266]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? - NO
- [ ] Are you running Kubernetes v1.13+? - YES
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? CRIO
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? - DONT KNOW
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`) - DONT KNOW

### 1. Issue or feature description
Utilizing GPU operator 1.8.2 from the operator hub.  Cluster policy set to all defaults as per instructions for openshift with GPUs.  Driver container fails to load nvidia.ko and gives the following message repeatedly until carshloopbackoff:

Building kernel modules
  : [##############################] 100%

ERROR: The kernel module failed to load, because it was not signed by a key that is trusted by the kernel. Please try installing the driver again, and sign the kernel module when prompted to do so.

ERROR: Unable to load the kernel module 'nvidia.ko'.  This happens most frequently when this kernel module was built against the wrong or improperly configured kernel sources, with a version of gcc that differs from the one used to build the target kernel, or if another driver, such as nouveau, is present and prevents the NVIDIA kernel module from obtaining ownership of the NVIDIA GPU(s), or no NVIDIA GPU installed in this system is supported by this NVIDIA Linux graphics driver release.

Please see the log entries 'Kernel module load error' and 'Kernel messages' at the end of the file '/var/log/nvidia-installer.log' for more information.

Kernel module compilation complete.

The target kernel has CONFIG_MODULE_SIG set, which means that it supports cryptographic signatures on kernel modules. On some systems, the kernel may refuse to load modules without a valid signature from a trusted key. This system also has UEFI Secure Boot enabled; many distributions enforce module signature verification on UEFI systems when Secure Boot is enabled. Would you like to sign the NVIDIA kernel module?
Valid responses are:
 (1)	"Sign the kernel module"
 (2)	"Install without signing" [ default ]
Please select your response by number or name:
The target kernel has CONFIG_MODULE_SIG set, which means that it supports cryptographic signatures on kernel modules. On some systems, the kernel may refuse to load modules without a valid signature from a trusted key. This system also has UEFI Secure Boot enabled; many distributions enforce module signature verification on UEFI systems when Secure Boot is enabled. Would you like to sign the NVIDIA kernel module? (Answer: Install without signing)
Kernel module load error: Required key not available
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by robynellis** [comment]
Per your documentation, openshift 4.8 is a supported platform.  This is a default install from the operator hub.  If this is no longer functional, then I'd suggest that you update your documentation.  Recommend options???

**Comment by rhn-gps-roellis** [comment]
Good morning.  Disabling secureboot on the GPU node did resolve this issue for me.  Do you have a seperate repo for your documentation.  PR against it for inclusion of this into either preq or troubleshooting section?  I think this could save a lot of others headaches around secureboot.
