### ISSUE TITLE
Multiple issues with dcgm and dcgm-exporter in latest release (v1.8.2)

### ISSUE THREAD

**Issue by IvanDechovsky** [NVIDIA/gpu-operator#269]
### Platform
Platform EKS 1.21 + AMI [AMI v20210722](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210722)

###  Issue or feature description
Multiple issues with latest release v1.8.2

#### Problem 1
Breaking change introduced in 1.8.0. Upgrading from 1.7.1 is not possible due to changed selector label - which is immutable. Release notes for 1.8.0+ did not mention any breaking changes.

#### Problem 2
Pod security policy `gpu-operator-privileged` is missing extra permissions required by `nvidia-dcgm`. `nvidia-dcgm` tried to start a container with a `hostPort` configured on 5555. However, the psp does not allow that. To fix, we need to add to the privileged psp:

```
  hostPorts:
    - max: 5555
      min: 5555
```

However, the problems do not end here. Once the psp is updated, the daemonset starts up okay (although no logs are available - this part could be intended) but the `nvidia-dcgm-exported` pods are now failing as they cannot connect to the `nvidia-dcgm` pods on each node respectively. Upon further investigation, it turns out that while you would expect the `nvidia-dcgm` container with `hostPort` configured to be reachable on 5555, after looking at the networking (netstat on each node there is nothing listening on port 5555. To check:

```sh
sudo netstat -tulpn | grep LISTEN | grep 5555
```

A fix to this is to, again, alter the psp `gpu-operator-privileged` to add `hostNetwork: true` and also alter the `nvidia-dcgm` daemonset to add `hostNetwork: true` to the `spec`. Correct me if i am wrong, but the daemonset should not need to have `hostNetwork: true` in order to bind to a specific host port using the `hostPort` setting.

**Comment by shivamerla** [comment]
@IvanDechovsky I will look further into this, meanwhile to avoid this you can set `dcgm.enabled=false` during install which will allow `dcgmExporter` to use an embedded DCGM hostengine instead of creating a separate pod for itself. So you can avoid patching PSP rules and enabling `hostNetwork: true`.

**Comment by shivamerla** [comment]
@IvanDechovsky Please try out `v1.9.0-beta` to fix this issue.

**Comment by IvanDechovsky** [comment]
@shivamerla Hi,
I saw that v1.9.0 has been released so I wanted to try it out. However, the same issues persist.

The psp `gpu-operator-privileged` has no entry to allow `hostPorts`. Both `nvidia-dcgm` and `nvidia-dcgm-exporter` have `hostPort` defined. Here are errors from the daemonsets:

`nvidia-dcgm-exporter`
```
  Warning  FailedCreate  2m55s (x7 over 30m)  daemonset-controller  Error creating: pods "nvidia-dcgm-exporter-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].hostPort: Invalid value: 9400: Host port 9400 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].hostPort: Invalid value: 9400: Host port 9400 is not allowed to be used. Allowed ports: []]
```

`nvidia-dcgm`
```
  Warning  FailedCreate  2m55s (x7 over 30m)  daemonset-controller  Error creating: pods "nvidia-dcgm-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].hostPort: Invalid value: 5555: Host port 5555 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].hostPort: Invalid value: 5555: Host port 5555 is not allowed to be used. Allowed ports: []]
```

`nvidia-dcgm` can be disabled so that part can be resolved, however, the exported is required and in the new chart version it fails. I compared it to v1.8.2 and ther `hostPort` was not used so the `exported` daemonset was able to run without having to allow `hostPorts` in the PSP.

**Comment by IvanDechovsky** [comment]
Upon further investigation, in order for the dcgm-exporter to work we need to add the following permissions to the PSP:
```
  hostNetwork: true
  hostPorts:
  - max: 9400
    min: 9400
  allowedHostPaths:
  - pathPrefix: "/var/lib/kubelet/pod-resources"
    readOnly: true
  - pathPrefix: "/run/nvidia"
    readOnly: false
  volumes:
  - projected
```
