### ISSUE TITLE
GPU-operator doesn't allow to specify a volume to mount metrics file for nvidia-dcgm-exporter

### ISSUE THREAD

**Issue by GuillaumeSmaha** [NVIDIA/gpu-operator#275]
Hi,

A comment on `nvidia-dcgm-exporter` recommands to define by ourself the list of metrics to export: https://github.com/NVIDIA/gpu-monitoring-tools/issues/143#issuecomment-926807911
For example, to enable `DCGM_FI_DEV_GPU_UTIL` or others metrics in https://github.com/NVIDIA/dcgm-exporter/blob/main/etc/dcp-metrics-included.csv.
It is possible to specify the location of the exporter collections with an environment var
https://github.com/NVIDIA/gpu-operator/blob/e0299a01333e43e9c234cddbe4058f7e42cc9568/deployments/gpu-operator/values.yaml#L190-L191
But there is currently no way to specify a ConfigMap or a Volume to mount into `nvidia-dcgm-exporter` daemonset in CRDs of gpu-operator:
https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/crds/nvidia.com_clusterpolicies_crd.yaml#L402-L718

Do you have any plans to update CRDs to add this ?

**Comment by esparig** [comment]
> @GuillaumeSmaha Yes, creating a ConfigMap by default is a new functionality with newer exporter versions, which is not yet integrated with gpu-operator.

@shivamerla is this functionality added to the new gpu-operator v22.9.0? Is there any available documentation that explains how to apply this configmap? Thx

**Comment by esparig** [comment]
> @shivamerla is this functionality added to the new gpu-operator v22.9.0? Is there any available documentation that explains how to apply this configmap? Thx

I'll answer my own question in case is useful for anyone: Yes, creating a configmap for dcgm metrics is possible in the gpu-operator v22.9.0 and here are the docs:
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#custom-metrics-config

**Comment by GuillaumeSmaha** [comment]
Thank you for the information @esparig
