### ISSUE TITLE
separate containers with nvidia.com/gpu set to 1 land on same GPU

### ISSUE THREAD

**Issue by bhanupisupati** [NVIDIA/gpu-operator#28]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- Are you running on an Ubuntu 18.04 node - YES
 Are you running Kubernetes v1.13 - YES (v1.13)
-  Are you running Docker (>= 18.06) or CRIO (>= 1.13+) - YES (Docker)
- Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? (Not sure)
- Did you apply the CRD (`kubectl describe specialresources --all-namespaces`) (Not sure)

### 2. Issue or feature description
We are seeing this issue with deploying GPU containers using kubernetes whereby containers each reserving a GPU using the nvidia.com/gpu construct within the pod definition are landing on the same GPU.
This is for the deepstream workload, and we have run the same helm chart for a while now without this issue on kubernetes clusters. We see this issue after transitioning to a new kernel (5.3) and GPU driver (440.33) late last week. We are using the GPU operator (1.0.0-techpreview8).  

### 3. Steps to reproduce the issue
Run multiple deepstream containers within a pod on kubernetes, each requesting a GPU. Please ping me offline for helm chart to create this deployment.

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
Snippet below from "kubectl describe pods/dsits-deepstream-its-5d8f567f56-4xzxd" shows that each container is requesting a GPU, which means they should land on separate GPUs from one another.

kubectl describe pods/dsits-deepstream-its-5d8f567f56-4xzxd

<Pruned output>

deepstream-its-1:
    <omitted>
   Limits:
      **nvidia.com/gpu:  1**
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
deepstream-its-2:
   <omitted>
   Limits:
      **nvidia.com/gpu:  1**
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>

Running nvidia-smi shows that only GPU has been loaded (GPU #0) since both containers are running on the same GPU.

~$ nvidia-smi
Tue Jan 28 18:39:33 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
| N/A   74C    P0    60W /  70W |  11735MiB / 15109MiB |     **66%**      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:5E:00.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            On   | 00000000:60:00.0 Off |                    0 |
| N/A   33C    P8     9W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            On   | 00000000:86:00.0 Off |                    0 |
| N/A   30C    P8     9W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Quadro P1000        On   | 00000000:88:00.0 Off |                  N/A |
| 34%   29C    P8    N/A /  N/A |     12MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla T4            On   | 00000000:AF:00.0 Off |                    0 |
| N/A   31C    P8     9W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla T4            On   | 00000000:D8:00.0 Off |                    0 |
| N/A   31C    P8    10W /  70W |     11MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by nvjmayo** [comment]
we think this one is not a bug in gpu-operator, and has to do with your environment. Please track this issue on your end. Comment or re-open if there is action you need from us.
