### ISSUE TITLE
CRI-O runtime detection issues with 1.9.0

### ISSUE THREAD

**Issue by nick-oconnor** [NVIDIA/gpu-operator#290]
Runtime detection in 1.9.0 appears to be broken for bare metal clusters running recent versions of k8s with cri-o. My `containerRuntimeVersion` is being reported as `cri-o://1.21.4` which fails detection since the [code](https://github.com/NVIDIA/gpu-operator/blob/6bdc0b902c7e55d87cb65399632a074f046678df/controllers/state_manager.go#L337) checks for the prefix [`crio`](https://github.com/NVIDIA/gpu-operator/blob/6bdc0b902c7e55d87cb65399632a074f046678df/api/v1/clusterpolicy_types.go#L87) and `cri-o` doesn't match. It then defaults to `containerd` and fails to start. I'm running k8s 1.21.7 with cri-o 1.21.4 and gpu-operator 1.9.0.

**Comment by elezar** [comment]
Thanks @nick-oconnor for reporting this.

We will have a look on our end. cc @cdesiniotis @shivamerla

**Comment by shivamerla** [comment]
@nick-oconnor This was missed as we didn't try `cri-o` outside of openshift. Will fix this soon with a patch.

**Comment by cdesiniotis** [comment]
@nick-oconnor `1.9.1` has been released, which should address this bug.

**Comment by nick-oconnor** [comment]
@cdesiniotis confirmed the fix in 1.9.1 resolved the issue. Thanks again!
