### ISSUE TITLE
 Collection of GPU metrics in MIG mode is not supported with 470+ drivers.

### ISSUE THREAD

**Issue by yug0slav** [NVIDIA/gpu-operator#292]
From Known Limitations: "Collection of GPU metrics in MIG mode is not supported with 470+ drivers"

Could you please elaborate more don't this?
Are there any plans to address this in the near future?

**Comment by shivamerla** [comment]
@yug0slav This seems to be fixed with updated dcgm-exporter, please use the latest version when deploying with v1.9.0. We will bump it with v1.9.1: https://github.com/NVIDIA/dcgm-exporter/releases

**Comment by kpouget** [comment]
FYI, I'm using `2.3.1-2.6.1` image since a few days, and from what I've seen, MIG metrics collection work well on OCP

```
oc patch clusterpolicy/gpu-cluster-policy --type='json' -p='[{"op": "replace", "path": "/spec/dcgmExporter/repository", "value": "nvcr.io/nvidia/k8s"}]'

oc patch clusterpolicy/gpu-cluster-policy --type='json' -p='[{"op": "replace", "path": "/spec/dcgmExporter/image", "value": "dcgm-exporter"}]'

oc patch clusterpolicy/gpu-cluster-policy --type='json' -p='[{"op": "replace", "path": "/spec/dcgmExporter/version", "value": "2.3.1-2.6.1-ubi8"}]'
```

**Comment by yug0slav** [comment]
I am still on 1.8.2 due to https://github.com/NVIDIA/gpu-operator/issues/299. 
Tested 1.8.2 chart / 470.57.02-centos driver-daemonset with dcgm-exporter-2.3.1-2.6.1-ubi8 per your suggestion... getting all metrics "0" with mig enabled on my A100 GPUs node.

**Comment by yug0slav** [comment]
Confirmed working MIGed GPU metrics with dcgm-exporter:2.3.2-2.6.2-ubi8
