### ISSUE TITLE
GPU operator pods not coming up in centos 8.4

### ISSUE THREAD

**Issue by prpaul** [NVIDIA/gpu-operator#293]
able to install operator helm chart, but Nvidia pods not coming online

Setup details
==============
GCP VM Instance
Centos 8.4 2105
Nvidia MIG A100
Driver version - NVIDIA-Linux-x86_64-470.82.01

Below pods are not coming online after deploying operator helm chart

robinio       gpu-feature-discovery-66zcd                                 0/1     Init:0/1   0          34m
robinio       nvidia-dcgm-9qkfz                                                 0/1     Init:0/1   0          34m
robinio       nvidia-dcgm-exporter-4m5wf                                0/1     Init:0/1   0          34m
robinio       nvidia-device-plugin-daemonset-x54jk                  0/1     Init:0/1   0          34m
robinio       nvidia-operator-validator-7cmpp                           0/1     Init:0/4   0          34m

Error shown inside pods is as below
========================
Events:
  Type     Reason                  Age                    From               Message
  ----     ------                  ----                   ----               -------
  Normal   Scheduled               34m                    default-scheduler  Successfully assigned robinio/gpu-feature-discovery-66zcd to priyanko-test-mig1
  Warning  FailedCreatePodSandBox  4m26s (x141 over 34m)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = Exception calling application: ErrorUnknown:StatusCode.UNKNOWNtimeHandler "nvidia" not supported

Step -1 
---------
Installed driver
==========
[priyanko_robin_io@priyanko-test-mig1 ~]$ sudo su
[root@priyanko-bnp-mig1 priyanko_robin_io]# sh NVIDIA-Linux-x86_64-470.82.01.run -q -a -n -X -s
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 470.82.01..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

WARNING: nvidia-installer was forced to guess the X library path '/usr/lib64' and X module path '/usr/lib64/xorg/modules'; these paths were not queryable from the system.  If X fails to find the NVIDIA
         driver module, please install the `pkg-config` utility and the X.Org SDK/development package for your distribution and reinstall the driver.

Step-2
--------
[root@priyanko-test-mig1 priyanko_robin_io]# nvidia-smi
Wed Dec  8 06:52:56 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    46W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Step-3
--------
deployed operator helm chart
====================
[root@priyanko-test-mig1 priyanko_robin_io]# ./helm install gpu-operator nvidia/gpu-operator --set driver.enabled=false -n robinio
NAME: gpu-operator
LAST DEPLOYED: Wed Dec  8 07:14:49 2021
NAMESPACE: robinio
STATUS: deployed
REVISION: 1
TEST SUITE: None

Please let us know what could be the issue for the pods not coming up.

**Comment by cdesiniotis** [comment]
You need to specify the CentOS toolkit image during install as described [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-default-configurations-on-centos). 
Try reinstalling with `--set toolkit.version=1.7.2-centos8`

**Comment by cdesiniotis** [comment]
@prpaul any update on this?
