### ISSUE TITLE
DCGM cannot load NSCQ

### ISSUE THREAD

**Issue by dbugit** [NVIDIA/gpu-operator#294]
### Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? (CentOS 7.6.1810)
- [X] Are you running Kubernetes v1.13+? (v1.22)
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? (Containerd 1.4.9-3.1.el7)
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? (No)
- [X] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Using `gpu-operator` v1.9.0 on CentOS 7, the `nvidia-dcgm-XXXXX` pod comes up in a `Running` state, but `nvidia-dcgm-exporter-XXXXX` dumps to a `CrashLoopBackoff` shortly after initialization.

### 2. Steps to reproduce the issue
Given an **override.yaml** file with these contents:

```yaml
operator:
  defaultRuntime: containerd

toolkit:
  version: 1.7.2-ubi8

dcgm:
  version: 2.3.1-ubi8
  args:
    - "-n"
    - "-b"
    - "0.0.0.0"
    - "--log-level"
    - "INFO"
    - "-f"
    - "-"

dcgmExporter:
  version: 2.3.1-2.6.0-ubi8

migManager:
  version: v0.2.0-ubi8
```

Install via Helm:
```
helm install --values override.yaml test nvidia/gpu-operator --version v1.9.0
```

### 3. Further Information
I'm using the UBI versions of images because of CentOS 7 and #72, but I see the same results using the Ubuntu versions.

```shell
$ uname -r
3.10.0-1160.11.1.el7.x86_64
```

Pod status of DCGM:
```
NAME                          READY   STATUS             RESTARTS       AGE
nvidia-dcgm-XXXXX             1/1     Running            0              3m52s
nvidia-dcgm-exporter-XXXXX    0/1     CrashLoopBackOff   4 (17s ago)    3m51s
```

Log output from `nvidia-dcgm-XXXXX` Pod:
```
2021-12-08 17:12:48.374 INFO  [1:1] version:2.3.1;arch:x86_64;buildtype:Release;buildid:4;builddate:2021-10-14;commit:58dee5b7d36a6a9572d80dd1ba63f5a3000df63a;branch:rel_dcgm_2_3;buildplatform:Linux 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64;;crc:2daadee6a4a852d93855ef6127e30fbe [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmApi.cpp:6809] [dcgmStartEmbedded_v2]
2021-12-08 17:12:48.378 INFO  [1:1] Parsed driver string is 4708201, IsR450OrNewer: 1 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmCacheManager.cpp:2331] [DcgmCacheManager::ReadAndCacheDriverVersions]
2021-12-08 17:12:48.391 INFO  [1:1] Got 0 blacklisted GPUs [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmCacheManager.cpp:1087] [DcgmCacheManager::ReadAndCacheGpuBlacklist]
2021-12-08 17:12:48.391 INFO  [1:1] Created thread named "cache_mgr_event" ID 1529988864 DcgmThread ptr 0x0xa59f80 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/common/DcgmThread.cpp:135] [DcgmThread::Start]
2021-12-08 17:12:48.391 INFO  [1:9] DcgmCacheManagerEventThread started [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmCacheManager.cpp:12217] [DcgmCacheManagerEventThread::run]
2021-12-08 17:12:48.393 ERROR [1:1] [[NvSwitch]] Could not load NSCQ. dlwrap_attach ret: Can not access a needed shared library (-79) [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmNvSwitchManager.cpp:444] [DcgmNs::DcgmNvSwitchManager::AttachToNscq]
2021-12-08 17:12:48.393 ERROR [1:1] [[NvSwitch]] AttachToNscq() returned -25 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmNvSwitchManager.cpp:317] [DcgmNs::DcgmNvSwitchManager::Init]
2021-12-08 17:12:48.393 ERROR [1:1] [[NvSwitch]] Could not initialize switch manager. Ret: DCGM library could not be found [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:34] [DcgmNs::DcgmModuleNvSwitch::DcgmModuleNvSwitch]
2021-12-08 17:12:48.393 INFO  [1:1] [[NvSwitch]] Created thread named "" ID 1521596160 DcgmThread ptr 0x0xaa7788 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/common/DcgmThread.cpp:135] [DcgmThread::Start]
2021-12-08 17:12:48.393 INFO  [1:1] Loaded module 1 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmHostEngineHandler.cpp:3592] [DcgmHostEngineHandler::LoadModule]
2021-12-08 17:12:48.393 WARN  [1:10] [[NvSwitch]] ReadNvSwitchStatusAllSwitches() returned Object is in an undefined state [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:381] [DcgmNs::DcgmModuleNvSwitch::RunOnce]
2021-12-08 17:12:48.393 WARN  [1:1] Got 0 entities from GetAllEntitiesOfEntityGroup() of eg 3 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmGroupManager.cpp:160] [DcgmGroupManager::AddAllEntitiesToGroup]
2021-12-08 17:12:48.393 INFO  [1:1] Created thread named "cache_mgr_main" ID 1513203456 DcgmThread ptr 0x0xa90e80 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/common/DcgmThread.cpp:135] [DcgmThread::Start]
2021-12-08 17:12:48.393 INFO  [1:11] Cache manager update thread starting [/workspaces/dcgm-rel_dcgm_2_3-postmerge/dcgmlib/src/DcgmCacheManager.cpp:5866] [DcgmCacheManager::run]
2021-12-08 17:12:48.394 INFO  [1:1] Created thread named "dcgm_ipc" ID 1504810752 DcgmThread ptr 0x0xa8f5c0 [/workspaces/dcgm-rel_dcgm_2_3-postmerge/common/DcgmThread.cpp:135] [DcgmThread::Start]
Started host engine version 2.3.1 using port number: 5555 
2021-12-08 17:13:18.393 WARN  [1:10] [[NvSwitch]] ReadNvSwitchStatusAllSwitches() returned Object is in an undefined state [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:381] [DcgmNs::DcgmModuleNvSwitch::RunOnce]
2021-12-08 17:13:48.393 WARN  [1:10] [[NvSwitch]] ReadNvSwitchStatusAllSwitches() returned Object is in an undefined state [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:381] [DcgmNs::DcgmModuleNvSwitch::RunOnce]
2021-12-08 17:14:18.395 WARN  [1:10] [[NvSwitch]] ReadNvSwitchStatusAllSwitches() returned Object is in an undefined state [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:381] [DcgmNs::DcgmModuleNvSwitch::RunOnce]
2021-12-08 17:14:48.395 WARN  [1:10] [[NvSwitch]] ReadNvSwitchStatusAllSwitches() returned Object is in an undefined state [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:381] [DcgmNs::DcgmModuleNvSwitch::RunOnce]
2021-12-08 17:15:18.397 WARN  [1:10] [[NvSwitch]] ReadNvSwitchStatusAllSwitches() returned Object is in an undefined state [/workspaces/dcgm-rel_dcgm_2_3-postmerge/modules/nvswitch/DcgmModuleNvSwitch.cpp:381] [DcgmNs::DcgmModuleNvSwitch::RunOnce]
```

Log output from `nvidia-dcgm-exporter-XXXXX` Pod:
```
time="2021-12-08T17:16:27Z" level=info msg="Starting dcgm-exporter"
time="2021-12-08T17:16:27Z" level=info msg="Attemping to connect to remote hostengine at 192.168.11.7:5555"
time="2021-12-08T17:16:32Z" level=fatal msg="Error connecting to nv-hostengine: Host engine connection invalid/disconnected"
```

I believe this behavior is also the cause of #288 and possibly related to #222.

**Comment by shivamerla** [comment]
@dbugit Can you share the output of `chroot /run/nvidia/driver nvidia-smi` on the node.

**Comment by glowkey** [comment]
The dcgm-exporter pod is trying to connect to the dcgm pod at 192.168.11.7:5555. Can you share the log output from the dcgm pod?

**Comment by dbugit** [comment]
> Can you share the log output from the dcgm pod?

@glowkey Is what you're asking for different than what's in the original post?

**Comment by glowkey** [comment]
Whelp, you're right. That output shows the dcgm pod running without a major issue but for some reason the exporter pod can't connect. Investigating...

**Comment by dbugit** [comment]
@shivamerla Output of `chroot /run/nvidia/driver nvidia-smi` on the GPU node (only 1 in cluster):

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:37:00.0 Off |                    0 |
| N/A   37C    P0    28W / 250W |      0MiB / 12198MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   34C    P0    26W / 250W |      0MiB / 12198MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by dbugit** [comment]
Tracing through code in the DCGM project led me to the [`nscq_dl_load`](https://github.com/NVIDIA/DCGM/blob/7196e004c2bb7b30e07e3437da900b4cb42ba123/sdk/nvidia/nscq/dlwrap/posix.c#L63) function, which tries to load the `libnvidia-nscq.so.X` library. However, as expected from the error message, there is no such library in the `nvidia-dcgm-XXXXX` pod (from `kubectl exec`):

```shell
sh-4.4# find / -name 'libnvidia*'
/usr/lib/libnvidia-ml.so.470.82.01
/usr/lib/libnvidia-opencl.so.470.82.01
/usr/lib/libnvidia-ptxjitcompiler.so.470.82.01
/usr/lib/libnvidia-allocator.so.470.82.01
/usr/lib/libnvidia-compiler.so.470.82.01
/usr/lib/libnvidia-allocator.so.1
/usr/lib/libnvidia-ptxjitcompiler.so.1
/usr/lib/libnvidia-opencl.so.1
/usr/lib/libnvidia-ml.so.1
/usr/lib64/libnvidia-ml.so.470.82.01
/usr/lib64/libnvidia-cfg.so.470.82.01
/usr/lib64/libnvidia-opencl.so.470.82.01
/usr/lib64/libnvidia-ptxjitcompiler.so.470.82.01
/usr/lib64/libnvidia-allocator.so.470.82.01
/usr/lib64/libnvidia-compiler.so.470.82.01
/usr/lib64/libnvidia-allocator.so.1
/usr/lib64/libnvidia-ptxjitcompiler.so.1
/usr/lib64/libnvidia-opencl.so.1
/usr/lib64/libnvidia-cfg.so.1
/usr/lib64/libnvidia-ml.so.1
/usr/local/cuda-11.4/compat/libnvidia-ptxjitcompiler.so.1
/usr/local/cuda-11.4/compat/libnvidia-ptxjitcompiler.so.470.57.02
```

I wonder if this is just a packaging issue in the DCGM project. Looking at their [Dockerfile](https://github.com/NVIDIA/DCGM/blob/7196e004c2bb7b30e07e3437da900b4cb42ba123/dcgmbuild/Dockerfile), I see no such reference to anything library or `nscq` related. Admittedly, however, I haven't really spent enough time to understand that project's `builder` system.

**Comment by shivamerla** [comment]
@dbugit Can you run the below test pod to make sure if exporter can actually connect to this port and to confirm that DCGM engine is not listening on this port due to these errors. You can restart exporter pod after this to make sure it attempts to connect again.

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
   hostNetwork: true
   containers:
     - name: ubuntu
       image: ubuntu
       command: [ "/bin/bash", "-c", "--" ]
       args: [ "apt update;apt install netcat -y;netcat -l -k 5555" ]
```

**Comment by klueska** [comment]
Support for injecting `ibnvidia-nscq.so.X` into a container was added in [`v1.4.0`](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.4.0) of the NVIDIA container toolkit. The only stipulation being that the container is started with `utility` set in the `NVIDIA_DRIVER_CAPABILITIES` envvar for the container (usually by the container image).

**Comment by dbugit** [comment]
@klueska I see no such environment variable in either the DCGM or toolkit pod.

Running `kubectl get pod nvidia-container-toolkit-daemonset-XXXXX -o yaml` (other parameters omitted for brevity) yields this container spec (note also the **override.yaml** file from the original post):

```yaml
  containers:
  - args:
    - /usr/local/nvidia
    env:
    - name: RUNTIME_ARGS
      value: --socket /runtime/sock-dir/containerd.sock --config /runtime/config-dir/config.toml
    - name: NVIDIA_DRIVER_ROOT
      value: /run/nvidia/driver
    - name: RUNTIME
      value: containerd
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    image: nvcr.io/nvidia/k8s/container-toolkit:1.7.2-ubi8
    imagePullPolicy: Always
    name: nvidia-container-toolkit-ctr
    resources: {}
    securityContext:
      privileged: true
      seLinuxOptions:
        level: s0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/nvidia
      mountPropagation: Bidirectional
      name: nvidia-run-path
    - mountPath: /usr/local/nvidia
      name: nvidia-local
    - mountPath: /usr/share/containers/oci/hooks.d
      name: crio-hooks
    - mountPath: /runtime/config-dir/
      name: containerd-config
    - mountPath: /runtime/sock-dir/
      name: containerd-socket
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qw5hf
      readOnly: true
```

Adding that envvar and value to my **override.yaml** file, as such:

```yaml
toolkit:
  version: 1.7.2-ubi8
  env:
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: utility
```

successfully injects the variable into the container spec:

```yaml
    env:
    - name: RUNTIME_ARGS
      value: --socket /runtime/sock-dir/containerd.sock --config /runtime/config-dir/config.toml
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: utility
    - name: NVIDIA_DRIVER_ROOT
      value: /run/nvidia/driver
    - name: RUNTIME
      value: containerd
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
```

However, the results are the same: same errors, same log messages, and the library still isn't in the `nvidia-dcgm-XXXXX` pod. Did I specify the envvar correctly, and in the correct pod?

**Comment by klueska** [comment]
It’s usually set in the container image and not in the pod spec. That said, if it’s not set, it defaults to „utility,compute“ as described here (https://github.com/NVIDIA/nvidia-container-runtime#nvidia_driver_capabilities) so I’d be surprised if it’s not set.

Are you sure this library is installed / available in the driver container? The toolkit will obviously only be able to injecting if it’s there.

**Comment by dbugit** [comment]
> Are you sure this library is installed / available in the driver container?

@klueska Turns out that it is not. From inside the driver daemonset container:

```shell
sh-4.2# find / -name 'libnvidia-nscq*'
find: File system loop detected; '/run/nvidia/driver' is part of the same file system loop as '/'.
```

and from inside the toolkit container:

```shell
sh-4.4# find / -name 'libnvidia-nscq*'
find: File system loop detected; '/run/nvidia/driver/run/nvidia' is part of the same file system loop as '/run/nvidia'.
find: File system loop detected; '/runtime/sock-dir/io.containerd.runtime.v2.task/k8s.io/2c2aa9cc2889cc7e4af96d42bb9cfc638f5501ae28119dd817e93097d7bf4710/rootfs' is part of the same file system loop as '/'.
```

**Comment by dbugit** [comment]
Note that my driver container image is:

```
image: nvcr.io/nvidia/driver:470.82.01-centos7
```

**Comment by shivamerla** [comment]
@klueska `nscq` packages are only installed by driver container with Ubuntu/RHCOS images. In this case its CentOS, so both fabirc-manager/nscq packages will not be installed. But from DCGM teams analysis(Doug) this seems like a warning and DCGM will continue to report other metrics.

@dbugit Can you please run the test pod spec i provided earlier to ensure if DCGM host-engine is actually listening on port 5555 or it exited due to these errors.

**Comment by klueska** [comment]
I see. OK. Sounds like the nscq error/warning is a red herring then.

**Comment by dbugit** [comment]
@shivamerla Here's some more data, run from another node in the cluster. Note that `192.168.11.7` is the GPU node. Some output below is cropped to not include data about off-topic processes.

```shell
$ ssh 192.168.11.7 'ss -ntl4p'
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
LISTEN     0      6            *:5555                     *:*                   users:(("nv-hostengine",pid=11651,fd=16))

$ nc -vvv 192.168.11.7 5555
Ncat: Version 7.50 ( https://nmap.org/ncat )
libnsock nsi_new2(): nsi_new (IOD #1)
libnsock nsock_connect_tcp(): TCP connection requested to 192.168.11.7:5555 (IOD #1) EID 8
libnsock nsock_trace_handler_callback(): Callback: CONNECT TIMEOUT for EID 8 [192.168.11.7:5555]
Ncat: Connection timed out.
```

Note that the timeout happens 5 seconds after connecting, same as what was reported in the `nvidia-dcgm-exporter-XXXXX` logs. And from what I can tell, it does actually connect, otherwise I would expect to have seen a `connection refused` or `host/network unreachable` for some other error.

I also just realized that I think I misread your test. I had created a `busybox` pod to run `nc` as a client to the DCGM server, which produces the same results as above, but you want me to tear down the DCGM server, stand up a `nc` server listening on port 5555, and see if the DCGM exporter client can connect?

**Comment by shivamerla** [comment]
> I also just realized that I think I misread your test. I had created a `busybox` pod to run `nc` as a client to the DCGM server, which produces the same results as above, but you want me to tear down the DCGM server, stand up a `nc` server listening on port 5555, and see if the DCGM exporter client can connect?

Yes, can you please label node `nvidia.com/gpu.dcgm.deploy=false` and run the test pod. If dcgm-exporter can reach to it then it eliminates the network issue. We can work with DCGM team on why DCGM host-engine is not accepting connections.

**Comment by shivamerla** [comment]
@dbugit Also, before disabling dcgm engine, can you run `/usr/bin/dcgmi discovery -l` from within DCGM pod?

**Comment by klueska** [comment]
Can you also rename this issue to something more descriptive since NSCQ is not actually part of the problem.

**Comment by dbugit** [comment]
Apologies, gents, for not having more time to spend on this today, and even more so because I won't be able to get back to it until Monday.

**Comment by dbugit** [comment]
Well, I'm embarrassed to say that the problem ended up being on our end. Turns out that on the one GPU node there was a stale `iptables` chain that was acting as a sink for port 5555, sending packets to a pod IP that no longer existed. It explains why I wasn't seeing any ICMP error messages in the DCGM exporter logs or connection attempts in the DCGM server logs, because the GPU node correctly saw a process listening on the destination port and happily accepted those packets, but then silently dropped them afterwards. After removing the errant chain and redeploying the `gpu-operator`, everything worked fine.

@shivamerla Your `netcat` test was a good suggestion. When that failed with similar behavior it led me to eventually look for firewall and `iptables` issues. Before that I was very much distracted by the ERROR messages in the DCGM server logs. I'm debating about whether to open a separate issue about that, if nothing else at least so that the discussion is documented.

@klueska I will rename this issue to reflect the initial behavior I saw, rather than what I had assumed to be the root cause based on that error.
