### ISSUE TITLE
Namespaces and CRD naming

### ISSUE THREAD

**Issue by Ethyling** [NVIDIA/gpu-operator#3]
Currently the CRD kind for the partitioning is `SpecialRessource`. I think we need to change that as it's really confusing. I think something like `SchedulingType` could be better. Any other ideas?

On another side, the namespaces names are `openshift-sro` and `openshift-sro-operator`. We need to change this. I don't know exactly which namespace is for what kind of resource. @zvonkok could you give us some details about this?

cc @RenaudWasTaken @guptaNswati @rajatchopra

**Comment by RenaudWasTaken** [comment]
For some context, `SpecialResource` is used to do cluster hard and soft partitioning. e.g:
- **hard partitioning**: Isolate GPU nodes from the cluster so that only GPU tasks can land on the node.
- **soft partitioning**: any tasks can run on a GPU node until a GPU task is scheduled onto it.

Considering the above operations, `ClusterPartioningPolicy` seems like a possible better fit. What do you think?

**Comment by RenaudWasTaken** [comment]
> On another side, the namespaces names are openshift-sro and openshift-sro-operator. We need to change this. I don't know exactly which namespace is for what kind of resource. @zvonkok could you give us some details about this?


What's the difference between the two?

**Comment by rajatchopra** [comment]
One namespace is where the operator runs in, the other that the operator works upon.

Can we have the namespaces templatized? We can install the operator using helm which can supply the namespaces at install time. For now we can just replace 'openshift' with kubernetes and 'sro' with 'gpu'.

**Comment by Ethyling** [comment]
https://github.com/NVIDIA/gpu-operator/pull/5 fix namespaces

**Comment by RenaudWasTaken** [comment]
Discussed `GPUSchedulingPolicy` in team meeting.

**Comment by RenaudWasTaken** [comment]
Discussed `kubernetes-gpu` and `kubernetes-gpu-operator`

**Comment by Ethyling** [comment]
> Discussed `kubernetes-gpu` and `kubernetes-gpu-operator`

I don't get the `kubernetes` part, why do we need to specify it?
