### ISSUE TITLE
GPU Operator fails after switching GPUs in the server

### ISSUE THREAD

**Issue by erikbohnhorst** [NVIDIA/gpu-operator#30]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? Yes
- [ ] Are you running Kubernetes v1.13+? Yes
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? Yes
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? Yes
- [ ] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`) Yes

### 1. Issue or feature description
GPU Operator worked as expected when I had a Quadro RTX6000 in my server. Once I replaced the RTX6000 with a T4 and powered on the server again, the GPU Operator failed (CrashLoopback on the special-resource-operator pod). Uninstalling and reinstalling the GPU Operator solved the issue though. I don't have the system anymore to share logs or screenshots but wanted to share the issue I encountered.
### 2. Steps to reproduce the issue
- Working GPU Operator instance on a node with a RTX6000 GPU
- Shutdown node and replace RTX6000 with T4
- Power on server
- Run kubectl get pods --all-namespaces to view CrashLoopback on the special-resource-operator pod

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /run/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by jannylund** [comment]
This may very well be the same issue as in #29

**Comment by nvjmayo** [comment]
I suspect deploying driver container again would make the issue go away. I also think it is fixed in 1.0.0,

I'd like to see a success before I close this. It'll take me some time before I can get to a physical machine in order to swap cards around.
