### ISSUE TITLE
kernel-header version

### ISSUE THREAD

**Issue by itmwiw** [NVIDIA/gpu-operator#300]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [FCOS Node ] Are you running on an Ubuntu 18.04 node? 
- [OKD 4.9 ] Are you running Kubernetes v1.13+?
- [ CRIO] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?

### 1. Issue or feature description
Hello,
I'm trying to use the nvidia gpu operator on OKD 4.9.0-0.okd-2021-12-12-025847. I am facing the following issue: Actually gpu-operator search for kernel-header version based on Host's kernel version. The problem is that the  OKD 4.9.0-0.okd-2021-12-12-025847's version install kernel version 5.14.14 wich does not have an equivalent kernel-header version:
* the kernel 5.14.14 exists: https://kojipkgs.fedoraproject.org/packages/kernel/
* the kernel-header 5.14.14  does not exists : https://kojipkgs.fedoraproject.org/packages/kernel-headers/
So my question is: Is there any way to force the gpu-operator to use a specific kernel-header version? (when building the driver container Image for example?)
Thanks in advance
Tarik
### 2. Steps to reproduce the issue
Install gpu-operator on OKD 4.9.0-0.okd-2021-12-12-025847

**Comment by cdesiniotis** [comment]
Currently we do not have a mechanism for this, and it would require changes in our Dockerfile/driver script.

However, there is [this option](https://gitlab.com/nvidia/container-images/driver/-/blob/master/rhel8/nvidia-driver#L614), `--kernel <kernel_version>`, you can pass to the driver script to specify a kernel version. When installing the GPU Operator, you can add this to the list of args passed to the driver daemonset:  `--set "driver.args={init,--kernel,5.14.14}"`. Please note that this has not been tested and will only work if the kernel version is identical on all your worker nodes, as this is a global option.
