### ISSUE TITLE
No ServiceMonitor set in Prometheus ? 

### ISSUE THREAD

**Issue by seb-835** [NVIDIA/gpu-operator#305]
Hi,
i have install the gpu-operator, i see the dcgm-exporter running, i can pull metrics manually with curl.
But i do not see any ServiceMonitor set in prometheus, so there is no gpu metrics in my Dashboard.

Do i have to manually setup a Prometheus ServiceMonitor ?  or do i missed an option in the helm chart settings.
Thanks for help.

**Comment by shivamerla** [comment]
@seb-835 Yes, currently this needs to be manually created(Only auto created for RedHat OCP). We will add this for K8s too with next release.

**Comment by rhaps0dy** [comment]
You can now do `--set dcgmExporter.serviceMonitor.enabled=true` and the chart creates the ServiceMonitor for you
