### ISSUE TITLE
Upgrade from 1.8 to 1.9 is a major

### ISSUE THREAD

**Issue by julian3xl** [NVIDIA/gpu-operator#306]
At the moment that you can't upgrade from a version to another version is a MAJOR change, that's all.

https://semver.org/

**Comment by shivamerla** [comment]
@julian3xl the reason for this is v1.8 we used to deploy gpu-operator in user specified namespace but its components in fixed namespace "gpu-operator-resources", while with v1.9 user can install operator and operand pods into any custom namespace.  Its documented here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html#known-limitations. This limitation will not apply with v1.9+ versions.
