### ISSUE TITLE
VMWare node with the GPU cards crashs

### ISSUE THREAD

**Issue by yengher** [NVIDIA/gpu-operator#307]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ x] Are you running on an Ubuntu 18.04 node?
- [ x] Are you running Kubernetes v1.13+?
- [ x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
The VMWare node with the GPU card attached to the VM's crash (purple). 

### 2. Steps to reproduce the issue
We replaced the system board, memory, and BIOS with no luck.  

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ x] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 -  foo
 
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 {
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "/usr/local/nvidia/toolkit/nvidia-container-runtime"
        },
        "nvidia-experimental": {
            "args": [],
            "path": "/usr/local/nvidia/toolkit/nvidia-container-runtime-experimental"
        }
    }
}

 - [ ] Docker runtime configuration: `docker info | grep runtime`

 Runtimes: nvidia-experimental runc nvidia
 Default Runtime: nvidia

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`

drwxr-xr-x  4 root root  120 Jan 17 13:49 .
drwxr-xr-x 34 root root 1200 Jan 18 17:26 ..
drwxr-xr-x  1 root root 4096 Jan 17 13:48 driver
-rw-r--r--  1 root root    5 Jan 17 13:48 nvidia-driver.pid
-rw-r--r--  1 root root    6 Jan 17 13:49 toolkit.pid
drwxr-xr-x  2 root root  120 Jan 17 13:49 validations

 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`

drwxr-xr-x 3 root root    4096 Jan 17 13:49 .
drwxr-xr-x 3 root root    4096 Jan 17 13:49 ..
drwxr-xr-x 3 root root    4096 Jan 17 13:49 .config
lrwxrwxrwx 1 root root      28 Jan 17 13:49 libnvidia-container.so.1 -> libnvidia-container.so.1.6.0
-rwxr-xr-x 1 root root  179216 Jan 17 13:49 libnvidia-container.so.1.6.0
-rwxr-xr-x 1 root root     154 Jan 17 13:49 nvidia-container-cli
-rwxr-xr-x 1 root root   43024 Jan 17 13:49 nvidia-container-cli.real
-rwxr-xr-x 1 root root     342 Jan 17 13:49 nvidia-container-runtime
-rwxr-xr-x 1 root root     429 Jan 17 13:49 nvidia-container-runtime-experimental
lrwxrwxrwx 1 root root      24 Jan 17 13:49 nvidia-container-runtime-hook -> nvidia-container-toolkit
-rwxr-xr-x 1 root root 4006376 Jan 17 13:49 nvidia-container-runtime.experimental
-rwxr-xr-x 1 root root 2260408 Jan 17 13:49 nvidia-container-runtime.real
-rwxr-xr-x 1 root root     198 Jan 17 13:49 nvidia-container-toolkit
-rwxr-xr-x 1 root root 2147896 Jan 17 13:49 nvidia-container-toolkit.real

 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`

total 104
drwxr-xr-x   1 root root  4096 Jan 17 13:48 .
drwxr-xr-x   4 root root   120 Jan 17 13:49 ..
-rwxr-xr-x   1 root root     0 Jan 17 13:48 .dockerenv
-rw-r--r--   1 root root 16047 Sep 17 21:26 NGC-DL-CONTAINER-LICENSE
drwxr-xr-x   1 root root  4096 Nov  3 01:52 bin
drwxr-xr-x   2 root root  4096 Apr 24  2018 boot
drwxr-xr-x  13 root root  3840 Jan 17 13:49 dev
drwxr-xr-x   1 root root  4096 Jan 17 13:49 etc
drwxr-xr-x   2 root root  4096 Apr 24  2018 home
drwxr-xr-x   2 root root  4096 Jan 17 13:48 host-etc
drwxr-xr-x   1 root root  4096 Jan 17 13:48 lib
drwxr-xr-x   2 root root  4096 Aug 27 07:18 lib64
drwxr-xr-x   2 root root  4096 Aug 27 07:16 media
drwxr-xr-x   2 root root  4096 Aug 27 07:16 mnt
drwxr-xr-x   2 root root  4096 Aug 27 07:16 opt
dr-xr-xr-x 487 root root     0 Jan 17 13:45 proc
drwx------   2 root root  4096 Aug 27 07:18 root
drwxr-xr-x   1 root root  4096 Jan 17 13:49 run
drwxr-xr-x   1 root root  4096 Nov  3 01:52 sbin
drwxr-xr-x   2 root root  4096 Aug 27 07:16 srv
dr-xr-xr-x  13 root root     0 Jan 18 06:25 sys
drwxrwxrwt   1 root root  4096 Jan 17 13:49 tmp
drwxr-xr-x   1 root root  4096 Aug 27 07:16 usr
drwxr-xr-x   1 root root  4096 Aug 27 07:18 var

 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by shivamerla** [comment]
@yengher Can you provide more information on this?

- Is this with vGPU or passthrough GPU attached to VM
- GPU type
- Does the guest driver get installed in the VM successfully before PSOD is seen?
- vSphere version
- `nvidia-smi` from the physical host if its with vGPU or from VM if driver is installed in the guest with passthrough.
- Double check these VM parameters are set.
- VMkernel logs or logs extracted from VMkernel dump.

```
pciPassthru.use64bitMMIO=”TRUE”
pciPassthru.64bitMMIOSizeGB=128
```

**Comment by shivamerla** [comment]
Closing this, as no response for a while. Please re-open if this is still happening with provided PCI settings.
