### ISSUE TITLE
nvidia driver image tag issue if you are using a nightly build of OCP 4.4 - rhcos4-4

### ISSUE THREAD

**Issue by dwojciec** [NVIDIA/gpu-operator#31]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [ X] Are you running Kubernetes v1.13+? 1.17.1
- [ x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? 
crio version 1.17.0-4.dev.rhaos4.4.gitc3436cc.el8
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`)

### 2. Steps to reproduce the issue
Install an OCP 4.4 cluster on AWS (nightly build). Here we are using openshift-install-linux-**4.4.0-0.nightly-2020-02-17-103442**.tar.gz
 using this helm command :
```
 helm install --devel https://nvidia.github.io/gpu-operator/gpu-operator-1.0.0-beta.0.tgz --set platform.openshift=true,operator.defaultRuntime=crio,nfd.enabled=false -n openshift-operators --generate-name --wait
NAME: gpu-operator-1-1581954405
LAST DEPLOYED: Mon Feb 17 15:46:45 2020
NAMESPACE: openshift-operators
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
We can find that the operator is installed but once it tries to deploy the resources they fail because it’s trying to use an image that does not exist in the docker.io/nvidia repository: 440.33.01-**rhcos4.4**. In the repository, at this moment, only **440.33.01-rhcos4.3** is published. 

We tried to change the values for the helm chart, we untar the helm chart and checking the image variable we can see in gpu-operator/templates/0320_configmap.yaml that it comes from some variables:

driver: "{{ .Values.driver.repository }}/{{ .Values.driver.image }}:{{ .Values.driver.version }}" 

We tried to change that value in gpu-operator/values.yaml but the operator include a fixed sufix “**-rhcos4.4**”, so even changing it to  440.33.01-rhcos4.3 the image that the operator uses will be 440.33.01-rhcos4.3-rhcos4.4.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /run/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

Workaround found 
So what we did is to pull the image from dockerhub and push it in our private repo (making it public) changing the “repository” key in the values file (values.yaml):

driver:
  repository: luisarizmendi
  image: driver
  version: "440.33.01"

Once it’s done the pod can get the image and continue with the installation.
Image is available here : https://hub.docker.com/r/luisarizmendi/driver/tags
the image is just the same binary as the : docker pull nvidia/driver:440.33.01-rhcos4.3

maybe having the image version inside the "version" like version: "440.33.01-rhcos4.3" and not only "440.33.01" or having an additional field like platform  with platform : rhcos4.3 and not to identify the platform automatically because in our case we are using a 4.3 driver on top of rhcos4.4. And it works. 

I identified the line of code where the concatenation is done 
https://github.com/NVIDIA/gpu-operator/blob/9fdae4d499ab21457cb37f5e9cecbe6e65d27eac/pkg/controller/specialresource/specialresource_controls.go#L323
and the values is coming from the NFD annotation 
    feature.node.kubernetes.io/system-os_release.ID: rhcos
    feature.node.kubernetes.io/system-os_release.VERSION_ID: "4.4"

We can understand you can't change the code because you are responsible of the driver version and you will build a driver image for each os_release. VERSION_ID . Not sure it's needed for each RHCOS minor version.  Or just offering the flexibility to decide which image we want to use.

**Comment by RenaudWasTaken** [comment]
I fixed the actual rhcos-4.4 bug by pushing a new driver container image.

I think this bug isn't really closed for now and we might want to re-evaluate our strategy for rhcos and driver container.

CC @nvjmayo as this is related to our questions around driver container tagging.

**Comment by nvjmayo** [comment]
I think it's fixed.  there has been a lot of activity around tagging and versioning. assigning to myself to remind myself to confirm soon.

**Comment by shivamerla** [comment]
rhcos4.4, rhcos4.5, rhcos4.6 tags are available now for driver container for OCP. They have been validated with GPU operator 1.3.1 available in RH catalog.
