### ISSUE TITLE
RFE: use OLM's dependency manager to install NFD

### ISSUE THREAD

**Issue by fcami** [NVIDIA/gpu-operator#310]
OLM can be used to express [dependencies](https://docs.openshift.com/container-platform/4.6/operators/understanding/olm/olm-understanding-dependency-resolution.html) between operators. This would manage dependencies and also help during upgrades, making sure always-compatible versions of NFD and gpu-operator are installed.

**Comment by shivamerla** [comment]
@fcami I think we had this dependency in the past and caused duplicate NFD instances in the cluster. Hence we moved this as an external dependency. Also, NFD is required for other operators( eg NVIDIA network-operator), so this is really not bound to one.
