### ISSUE TITLE
paused-for-driver-upgrade

### ISSUE THREAD

**Issue by fanminshi** [NVIDIA/gpu-operator#316]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
we are running on debian node
- [x] Are you running Kubernetes v1.13+?
yes 1.20.11
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
```
Container Runtime Version:  docker://20.10.2
```

### 1. Issue or feature description

I ran gpu-operator v1.7.1 without installing the gpu driver. The gpu-operator runs but nothing is created in the gpu-resources. However, I saw dameonset are created in gpu-resources but not scheduled or run. I check node status and saw this

```
kubectl describe node
...
                    node-role.kubernetes.io/master=
                    nvidia.com/gpu.deploy.container-toolkit=paused-for-driver-upgrade
                    nvidia.com/gpu.deploy.dcgm=paused-for-driver-upgrade
                    nvidia.com/gpu.deploy.dcgm-exporter=paused-for-driver-upgrade
                    nvidia.com/gpu.deploy.device-plugin=paused-for-driver-upgrade
                    nvidia.com/gpu.deploy.driver=true
                    nvidia.com/gpu.deploy.gpu-feature-discovery=paused-for-driver-upgrade
                    nvidia.com/gpu.deploy.node-status-exporter=true
                    nvidia.com/gpu.deploy.operator-validator=paused-for-driver-upgrade
                    nvidia.com/gpu.present=true
``` 
**Note**:  I didn't see any tags about `nvidia.com/cuda.driver.major`, `nvidia.com/cuda.driver.minor`; Maybe the nfd is not working properly.

Also logs for gpu-operator itself

```
time="2022-01-28T15:49:04Z" level=info msg=" - Labelnvidia.com/gpu.deploy.device-pluginvaluepaused-for-driver-upgrade" source="state_manager.go:137"
time="2022-01-28T15:49:04Z" level=info msg=" - Labelnvidia.com/gpu.deploy.dcgm-exportervaluepaused-for-driver-upgrade" source="state_manager.go:137"
time="2022-01-28T15:49:04Z" level=info msg=" - Labelnvidia.com/gpu.deploy.operator-validatorvaluepaused-for-driver-upgrade" source="state_manager.go:137"
time="2022-01-28T15:49:04Z" level=info msg=" - Labelnvidia.com/gpu.deploy.drivervaluetrue" source="state_manager.go:137"
time="2022-01-28T15:49:04Z" level=info msg=" - Labelnvidia.com/gpu.deploy.gpu-feature-discoveryvaluepaused-for-driver-upgrade" source="state_manager.go:137"
time="2022-01-28T15:49:04Z" level=info msg=" - Labelnvidia.com/gpu.deploy.container-toolkitvaluepaused-for-driver-upgrade" source="state_manager.go:137"
2022-01-28T15:49:04.975Z	INFO	controllers.ClusterPolicy	DEBUG: DaemonSet	{"LabelSelector": "app=nvidia-container-toolkit-daemonset"}
2022-01-28T15:49:05.075Z	INFO	controllers.ClusterPolicy	DEBUG: DaemonSet	{"NumberOfDaemonSets": 1}
2022-01-28T15:49:05.075Z	INFO	controllers.ClusterPolicy	DEBUG: DaemonSet	{"NumberUnavailable": 0}
2022-01-28T15:49:05.101Z	INFO	controllers.ClusterPolicy	DEBUG: DaemonSet	{"LabelSelector": "app=nvidia-operator-validator"}
```

I would like to understand what might cause `paused-for-driver-upgrade`?

**Comment by shivamerla** [comment]
@fanminshi Can you check logs of driver pod `kubectl logs <driver-pod> -n gpu-operator-resources -c k8s-driver-manager`. This happens if drivers are already loaded and busy while driver container is restarted. The initContainer tries to unload existing modules before installing them. This happens on every driver container restart: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#additional-controls-for-driver-upgrades

**Comment by fanminshi** [comment]
@shivamerla `gpu-operator-resources` namespace is empty. But I do see `DaemonSet` are created but no pod are scheduled. Also something I forget to mention is that a previous gpu-operator installation failed where pods in  `gpu-operator-resources` run but didn't succeed. So I delete them. Then the re-deployment of `gpu-operator` didn't work and I saw `/gpu.deploy.device-plugin=paused-for-driver-upgrade` label in nodes. 
I am able to get gpu-operator working again by re-creating k8s cluster.
