### ISSUE TITLE
Centos8 repos offline, driver installation now fails

### ISSUE THREAD

**Issue by mac-chaffee** [NVIDIA/gpu-operator#321]
### 1. Issue or feature description

The daemonset that installs the nvidia drivers for Centos8 fails now, since [Centos8 has been EoL'd since December 31st](https://www.centos.org/centos-linux-eol/). On January 31st, they pulled the Centos8 repos offline. That means when attempting to install drivers with the image tag `470.82.01-centos8`, the pod crashloops with the error:

```
Starting installation of NVIDIA driver version 470.82.01 for Linux kernel version 4.18.0-348.7.1.el8_5.x86_64

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
```

### 2. Steps to reproduce the issue

Run `helm upgrade --install gpu-operator -n gpu-operator nvidia/gpu-operator --version v1.9.1 --set toolkit.version=1.7.2-centos8 --set psp.enabled=true --set driver.enabled=false` on centos8. Observe crashloop.

**Comment by mac-chaffee** [comment]
Also related: once gpu-operator is installed, trying to `helm upgrade ... --set driver.enabled=false` doesn't seem to stop the driver daemonset from running. I also tried removing the node label `nvidia.com/gpu.deploy.driver: "true"`, but it was automatically re-added.

**Comment by mac-chaffee** [comment]
I was able to work around the issue by just installing the drivers manually on the host. I use RHEL8 and Tesla GPUs so I followed these instructions: https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#rhel8

Probably similar instructions out there for other distros and GPUs.

**Comment by shivamerla** [comment]
@mac-chaffee for disabling driver, yes this is an issue that we don't disable existing driver daemonset dynamically. we need to set `nvidia.com/gpu.deploy.driver: "false"` to disable it on specific node.

**Comment by shivamerla** [comment]
Closing this as we don't support CentOS8 currently.
