### ISSUE TITLE
appVersion not matching tag in Chart.yaml

### ISSUE THREAD

**Issue by nneram** [NVIDIA/gpu-operator#325]
I used the [Helm Chart](https://github.com/NVIDIA/gpu-operator/tree/v1.9.1/deployments/gpu-operator) version `1.9.1` to deploy **gpu-operator** and I notice that the `appVersion` is not corresponding with the tag as well as `version` which is still in `v1.0.0-devel` since this commit: https://github.com/NVIDIA/gpu-operator/commit/c8d4e801750920306f1ce7cebcc3da0488b65b81

Would it be possible to improve the version management in the Chart ? It would help me for my use of it. 
I am waiting for your opinion on this. Thanks

**Comment by nneram** [comment]
@shivamerla Ok so this [Chart](https://github.com/NVIDIA/gpu-operator/blob/release-1.9/deployments/gpu-operator/Chart.yaml) should match the release tag, do you have an idea when it will be revisit ? Ty

**Comment by shivamerla** [comment]
@nneram this will be updated with 1.10 release during March.

**Comment by nneram** [comment]
Ok thanks for the answer and the information 👍🏻
