### ISSUE TITLE
Typo in the NVIDIA offical documentation

### ISSUE THREAD

**Issue by teacher144123** [NVIDIA/gpu-operator#329]
HI, I'm not sure where the issue should be reported for.
Because there is no repo for NVIDIA official docs in https://docs.nvidia.com/datacenter/.

## The Problem
There is a typo in the namespace section of GPU-operator.

https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#namespace

The first code block of installation is ...
```shell
helm install --wait --generate-name \
     -n gpu-operator --create-namespace
     nvidia/gpu-operator
```

**The command of line 2 doesn't end with a backslash.**  :smile:
It should be as same as the code block below.

```shell
helm install --wait --generate-name \
     -n gpu-operator --create-namespace \  # <- this one
     nvidia/gpu-operator
```

If this issue isn't related to this repo. Feel free to close it.
I can contact NVIDIA by email sometime.

**Comment by elezar** [comment]
Hi @teacher144123. If you could create an MR with changes to https://gitlab.com/nvidia/cloud-native/cnt-docs/-/blob/master/gpu-operator/getting-started.rst (and the archived versions of that page where applicable), that would be a great help.

**Comment by teacher144123** [comment]
Thanks a lot!
I will try to create the PR in gitlab.
