### ISSUE TITLE
nvidia-dcgm-exporter daemonset issue inside pod-nvidia-gpu-metrics-exporter - directory of metrics issue

### ISSUE THREAD

**Issue by dwojciec** [NVIDIA/gpu-operator#33]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
rhcos 4.4
- [X] Are you running Kubernetes v1.13+?
1.17.1
- [ x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
crio
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`)

### 1. Issue or feature description
inside the **nvidia-dcgm-exporter** daemonset the pod-nvidia-gpu-metrics-exporter generate this log error 
open /run/dcgm/dcgm-pod.prom: no such file or directory

### 2. Steps to reproduce the issue
Install Openshift 4.x and the nvidia driver.
```
$ oc get pod nvidia-dcgm-exporter-mffsr
NAME                         READY   STATUS    RESTARTS   AGE
nvidia-dcgm-exporter-mffsr   2/2     Running   0          5h37m
```
$ oc logs nvidia-dcgm-exporter-mffsr -c pod-nvidia-gpu-metrics-exporter

```
E0218 15:54:50.547995       1 http.go:48] error responding to 10.131.2.18:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
E0218 15:54:50.548069       1 http.go:48] error responding to 10.131.2.18:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
E0218 15:54:51.548008       1 http.go:48] error responding to 10.131.2.18:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
E0218 15:54:51.548010       1 http.go:48] error responding to 10.131.2.18:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
E0218 15:54:52.548020       1 http.go:48] error responding to 10.131.2.18:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
E0218 15:54:52.548032       1 http.go:48] error responding to 10.131.2.18:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
```
the 2 pod are not referring the same directory :
/run/dcgm/dcgm-pod.prom 
and 
 /run/prometheus/dcgm.prom

The right directory seems to be /run/prometheus/dcgm.prom

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /run/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

Temporary Fix found is 
create a symbolic link /run/prometheus/dcgm.prom 

ls -l /run/dcgm/dcgm-pod.prom
lrwxrwxrwx. 1 root root 25 Feb 18 15:54 /run/dcgm/dcgm-pod.prom -> /run/prometheus/dcgm.prom

**Comment by RenaudWasTaken** [comment]
Forgot to answer on this one!
Thanks for the bug report :) We'll look into it!

**Comment by guptaNswati** [comment]
We are working on fixing it. It's happening because kubelet/pod-resources directory does not have the right permissions, causing pod-exporter to not create dcgm-pod.prom under /run/dcgm
```
root@nvidia-dcgm-exporter-f2qgb:/# ls var/lib/kubelet/pod-resources/
ls: cannot open directory 'var/lib/kubelet/pod-resources/': Permission denied
```

**Comment by itayvallach** [comment]
@guptaNswati Any update on this? Any manual workaround to make this work?

**Comment by nvjmayo** [comment]
I'll take this over while I look at other OpenShift issues.

**Comment by lamroger** [comment]
Hi @nvjmayo - any luck with this? We're using `nvidia/pod-gpu-metrics-exporter` and running into the same issue on 1.16. Would appreciate any thoughts on alternatives too. Thanks!

**Comment by shivamerla** [comment]
@lamroger Any specific reason you are not using one deployed by gpu-operator? it deploys exporter with image `nvidia/dcgm-exporter` and `/var/lib/kubelet/pod-resources` is correctly mounted.

**Comment by lamroger** [comment]
Tech debt 🤣 I'll give gpu-operator a try. Thank you for the quick response!
