### ISSUE TITLE
Support to Nvidia Jetson GPU 

### ISSUE THREAD

**Issue by Zigko** [NVIDIA/gpu-operator#333]
Hello,
I'm trying to understand if the GPU Operator can work properly with JETSON GPU...
I've found some articles where they could use jetson gpu on k3s cluster but all of them use docker runtime container and after some research I found out that docker is deprecated and now the NVIDIA GPU Operator suports containerd:
https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/

But when i went to see which GPU's that where given support from NVIDIA the JETSON does not belong to the list:
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html

My objective is:
Monitoring jetson GPU usage on k8s based ambient (microk8s or k3s) 
My question are:
Will I be able to use JETSON GPU with the GPU Operator on containerd? Or should I get another gpu?

I'm using Ubunto 20.04 for this purpose

**Comment by elezar** [comment]
Hi @Zigko the GPU operator does not (yet) officially support Jetson devices. This requires support in the lower-level components such as the k8s-device-plugin and the NVIDIA Container Toolkit. 

This is something that is on our roadmap, but we don't have concrete dates for this yet.

**Comment by shivamerla** [comment]
Closing this as the question is answered. Please re-open if you have additional questions.

**Comment by chrmel** [comment]
Hello!
Is there any change regarding Jetson support?
Thx

**Comment by czomo** [comment]
/reopen
Any update on Jetson support?

**Comment by MrYanMYN** [comment]
Any updates on jetson support?
