### ISSUE TITLE
RFE: Export GPU's capacity

### ISSUE THREAD

**Issue by mareklibra** [NVIDIA/gpu-operator#336]
When working on a GPU Dashboard to show actual usage per GPU and provide overview of all GPUs installed in a cluster, we would need to know capacity of a particular GPU (by its UUID probably).

This is relevant for non percent-based metrics. So far we query historical maximums of these metrics but this is not reliable source.

Examples:
- DCGM_FI_DEV_SM_CLOCK - what is the maximum per GPU? Is burst clock speed relevant?
- DCGM_FI_DEV_MEM_CLOCK - likewise
- DCGM_FI_DEV_POWER_USAGE - what is the maximal consumption? Can we think about any thresholds here?
- DCGM_FI_DEV_GPU_TEMP - what are the thresholds?

**Comment by shivamerla** [comment]
@mareklibra Can you post this question at dcgm-exporter repo: https://github.com/NVIDIA/dcgm-exporter. That is the right place for metrics discussion.

**Comment by mareklibra** [comment]
Thank you, @shivamerla 
Closing here.
