### ISSUE TITLE
driver installation failed on Air-gapped Environment

### ISSUE THREAD

**Issue by pikomen** [NVIDIA/gpu-operator#337]
- [ ] Centos-7
- [ ] Kubernetes v1.21.8
- [ ] docker://20.10.9
- [ ] Airgap environment
- [ ] chart gpu-operator-v1.0.0-devel       devel-ubi8  (from master)

### 1. Issue or feature description
airgap env
from (https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/install-gpu-operator-air-gapped.html#install-gpu-operator-air-gapped)
The driver installation process keep looking for packages on internet instead of my local repo 
/home/user/gpu-operator# kubectl logs -f -n gpu-operator nvidia-driver-daemonset-cf6ww

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 510.47.03 for Linux kernel version 3.10.0-1160.53.1.el7.x86_64

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"

inside the pod I can see my repo-file (configmap working)  + all defaults repo files (no internet access )
ls -al /etc/yum.repos.d/
total 48
-rw-r--r-- 1 root root 1664 Nov 23  2020 CentOS-Base.repo
-rw-r--r-- 1 root root 1309 Nov 23  2020 CentOS-CR.repo
-rw-r--r-- 1 root root  649 Nov 23  2020 CentOS-Debuginfo.repo
-rw-r--r-- 1 root root  314 Nov 23  2020 CentOS-fasttrack.repo
-rw-r--r-- 1 root root  630 Nov 23  2020 CentOS-Media.repo
-rw-r--r-- 1 root root 1331 Nov 23  2020 CentOS-Sources.repo
-rw-r--r-- 1 root root 8515 Nov 23  2020 CentOS-Vault.repo
-rw-r--r-- 1 root root  616 Nov 23  2020 CentOS-x86_64-kernel.repo
-rw-rw-rw- 1 root root  165 Jan 14 22:18 cuda.repo
-rw-r--r-- 1 root root  483 Apr 18 08:12 my-repo.repo

driver:
   repoConfig:
      configMapName: repo-config

what are the correct way to delete all other files?
I couldn't find the driver deamonset deploy file for passing empty dir instead of yum.repos.d

**Comment by shivamerla** [comment]
@pikomen Can you follow the workaround as the other user did: https://github.com/NVIDIA/gpu-operator/issues/299#issuecomment-1027051394, currently we don't support wiping out entire repo dir but mapping individual files.

**Comment by pikomen** [comment]
I allready rename config file as original repo ( not a solid workaround)
but i didn't saw on any article that there are need to clone the cuda repo
also. Where from I can clone it?

**Comment by shivamerla** [comment]
We don't pull any packages from cuda repository, you can ignore that.

**Comment by pikomen** [comment]
I can confirm that the workaround is working.

**Comment by pikomen** [comment]
Ok, I will disable it and will let you know
