### ISSUE TITLE
Can you bump helm chart to 1.10.1 ?

### ISSUE THREAD

**Issue by GuillaumeSmaha** [NVIDIA/gpu-operator#339]
Hi,
Can you bump helm chart to 1.10.1 ? like it was done here: https://github.com/NVIDIA/gpu-operator/commit/ab585b39ba69413a48d253a9e14d568e86cf8995

Thank you :)

**Comment by cdesiniotis** [comment]
Thanks @GuillaumeSmaha . We have bumped the helm chart version here: https://github.com/NVIDIA/gpu-operator/commit/e9837cc6728f64db949599ff07cc161a478f4943
