### ISSUE TITLE
not able to install gpu-operator latest chart

### ISSUE THREAD

**Issue by dogra-gopal** [NVIDIA/gpu-operator#342]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
gpu-operator installation is failing with error message:
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ClusterPolicy.spec.driver): unknown field "kernelModuleConfig" in com.nvidia.v1.ClusterPolicy.spec.driver

### 2. Steps to reproduce the issue
Add the NVIDIA Helm repository and try to install it using steps mentioned in https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html 
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by dogra-gopal** [comment]
It used to work earlier with 1.10 version. Looks like with 1.10.1 version, this issue is happening.

**Comment by dogra-gopal** [comment]
Not able to reproduce it on another device.. so closing it.

**Comment by 5had3z** [comment]
I've got the same issue when trying to upgrade to 1.10 from 1.9 due to the GPG key issue.
Ubuntu 20.04
ContainerD 1.6.4
Kubeadm 1.21.6
