### ISSUE TITLE
Vectoradd test pod not working with CUDA error

### ISSUE THREAD

**Issue by k8s-gpubuilder** [NVIDIA/gpu-operator#343]
Why can I spin up a vectoradd cuda test pod on a 4 GPU worker node with this image?

     image: "quay.io/giantswarm/nvidia-gpu-demo:latest"

BUT not with this one here (which is supposed to be official)

  containers:
  - name: cuda-vectoradd
    #image: "nvidia/samples:vectoradd-cuda11.2.1"
    #image: "nvidia/samples:vectoradd-cuda11.6.0"
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2" 

all of them don't work, giving this truly useless error message (no specific mention of the version requirement or mismatch)

[Vector addition of 50000 elements]
Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!

I got this error when the gpu-operator handled both CUDA and Nvidia driver, with option 

helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.enabled=true --set toolkit.enabled=true 

Then I installed the nvidia driver on the worker node and disabled the gpu-operator handling it. 

installing the packages on the worker node 

nvidia-headless-510-server
nvidia-utils-510-server 
nvidia-cuda-toolkit
(Ubuntu 20.04)

so:
helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.enabled=false --set toolkit.enabled=false

in hopes that this might fix the problem.
and same result, it fails with the same CUDA error.

**Comment by elezar** [comment]
@k8s-gpubuilder which version of the operator and toolkit container are you using?

**Comment by k8s-gpubuilder** [comment]
v1.10.1  for the gpu operator and I-m using this container image to build on: nvidia/cuda:11.6.0-base-ubuntu20.04

**Comment by k8s-gpubuilder** [comment]
Are there any examples of premade images / containers that can be used to make sure it is working and give a hint to what is broken? The gpu operator installs fine, no errors, but when I spin up a container, CUDA is never available, even though the operator provides everything: Driver, container toolkit and CUDA?

**Comment by elezar** [comment]
cc @shivamerla

**Comment by shivamerla** [comment]
Closing this as looks like this is resolved based on #350 and #349
