### ISSUE TITLE
Fresh new installation of gpu-operator failing after the latest merge

### ISSUE THREAD

**Issue by rodrigoscferraz** [NVIDIA/gpu-operator#347]
Hello folks, after the latest merge (https://github.com/NVIDIA/gpu-operator/commit/bfe95409b0a963e1f02833cb00b40dd126ef9b59) that removed the SecurityContext from the CRD file, when i try to intall GPU operator it says:

```
Helm install failed: unable to build kubernetes objects from release
        manifest: error validating "": error validating data:
        [ValidationError(ClusterPolicy.spec.devicePlugin): unknown field
        "securityContext" in com.nvidia.v1.ClusterPolicy.spec.devicePlugin,
        ValidationError(ClusterPolicy.spec.driver): unknown field
        "securityContext" in com.nvidia.v1.ClusterPolicy.spec.driver,
        ValidationError(ClusterPolicy.spec.migManager): unknown field
        "securityContext" in com.nvidia.v1.ClusterPolicy.spec.migManager,
        ValidationError(ClusterPolicy.spec.toolkit): unknown field
        "securityContext" in com.nvidia.v1.ClusterPolicy.spec.toolkit,
        ValidationError(ClusterPolicy.spec.validator): unknown field
        "securityContext" in com.nvidia.v1.ClusterPolicy.spec.validator]
```

I'm using a simple helm install gpu-operator nvidia-operator/gpu-operator -n gpu

I don't know if it is something related with the Node feature discovery helmchart that remains with the securityContext fields(https://github.com/NVIDIA/gpu-operator/blob/bfe95409b0a963e1f02833cb00b40dd126ef9b59/deployments/gpu-operator/charts/node-feature-discovery/values.yaml#L321)

Thank you

**Comment by shivamerla** [comment]
@rodrigoscferraz Can you confirm if you are explicitly changing `securityContext` in `values.yaml` passed during helm install? These should be applied [here](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/templates/clusterpolicy.yaml#L62) only when they are defined in values.yaml. Nevertheless this was missed in the original change and removing with follow up MR

**Comment by shivamerla** [comment]
The change has been merged where we don't use `securityContext` from values anymore.

**Comment by rodrigoscferraz** [comment]
@shivamerla  Yeah. I'm just doing a fresh helm install without any changes, so I guess that it is taking the default values of the chart.

**Comment by shivamerla** [comment]
Are you still seeing the issue on master branch?

**Comment by thewire247** [comment]
I've just tried this and am seeing the issue on master branch. K8s verison 1.22 EKS

**Comment by rodrigoscferraz** [comment]
@shivamerla maybe this is because the CRD that is installed using helm install(without override the default values) is different that the one on the repository([this one](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/crds/nvidia.com_clusterpolicies_crd.yaml)

I noticed that the helm install CRD comes with the SecurityContext field and the CRD presented on this repository not. There is a reason for that?

**Comment by shivamerla** [comment]
@rodrigoscferraz Its a known limitation with Helm. Installed CRD's will not be deleted upon re-install or upgrade. Here are the details: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

We documented proper steps to upgrade using helm here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#using-helm

**Comment by rayburgemeestre** [comment]
Just to add a note for other folks that end up here (like me). I ran into this issue after GPU operator v1.11.0 was installed, then uninstalled, and then v1.10.1 was attempted to be installed. The customresourcedefinition "clusterpolicies" was indeed not cleaned up. So manually deleting it before attempting to install the older version worked and was okay to do in this particular case (no risk of dataloss).

```
# kubectl get customresourcedefinition
NAME                                                  CREATED AT
bgpconfigurations.crd.projectcalico.org               2022-07-13T01:36:43Z
bgppeers.crd.projectcalico.org                        2022-07-13T01:36:43Z
blockaffinities.crd.projectcalico.org                 2022-07-13T01:36:43Z
clusterinformations.crd.projectcalico.org             2022-07-13T01:36:43Z
clusterpolicies.nvidia.com                            2022-07-13T18:19:22Z <<< left over
felixconfigurations.crd.projectcalico.org             2022-07-13T01:36:43Z
globalnetworkpolicies.crd.projectcalico.org           2022-07-13T01:36:43Z
globalnetworksets.crd.projectcalico.org               2022-07-13T01:36:43Z
hostendpoints.crd.projectcalico.org                   2022-07-13T01:36:43Z
ipamblocks.crd.projectcalico.org                      2022-07-13T01:36:43Z
ipamconfigs.crd.projectcalico.org                     2022-07-13T01:36:43Z
ipamhandles.crd.projectcalico.org                     2022-07-13T01:36:43Z
ippools.crd.projectcalico.org                         2022-07-13T01:36:43Z
kubecontrollersconfigurations.crd.projectcalico.org   2022-07-13T01:36:43Z
networkpolicies.crd.projectcalico.org                 2022-07-13T01:36:43Z
networksets.crd.projectcalico.org                     2022-07-13T01:36:43Z
# kubectl delete customresourcedefinition clusterpolicies.nvidia.com
customresourcedefinition.apiextensions.k8s.io "clusterpolicies.nvidia.com" deleted
```
