### ISSUE TITLE
Failed to get sandbox runtime: no runtime for "nvidia" is configured

### ISSUE THREAD

**Issue by k8s-gpubuilder** [NVIDIA/gpu-operator#349]
kubelet[1311]: E0505 18:42:19.812688    1311 pod_workers.go:949] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"nvidia-device-plugin-daemonset-h9kxw_gpu-operator(8e491f32-4d92-4657-bbef-abf9d3dcb6ab)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"nvidia-device-plugin-daemonset-h9kxw_gpu-operator(8e491f32-4d92-4657-bbef-abf9d3dcb6ab)\\\": rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \\\"nvidia\\\" is configured\"" pod="gpu-operator/nvidia-device-plugin-daemonset-h9kxw" podUID=8e491f32-4d92-4657-bbef-abf9d3dcb6ab
May 05 18:42:19 hawkeye kubelet[1311]: E0505 18:42:19.812950    1311 remote_runtime.go:209] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to get sandbox

This error repeats for all the pods / deamonsets of the gpu operator.

I'm setting up the gpu-operator via helm:
---------------------------------------------------------

helm install --wait gpu-operator -n gpu-operator --create-namespace nvidia/gpu-operator --set driver.enabled=true --set toolkit.enabled=true 

The version is v1.10.1, all the OSes are Ubuntu 20.04

There is no driver or container toolkit installed on the worker node with the GPUs, the gpu operator is set to handling it all.

**Comment by shivamerla** [comment]
@k8s-gpubuilder These logs are expected until the driver is loaded and toolkit is setup(~3-5min). toolkit will setup `nvidia` runtimeClass with containerd and after that pods(device-plugin, gpu-feature-discovery etc) can run with that runtimeClass.

**Comment by k8s-gpubuilder** [comment]
Except that I posted it 1 hour ago and no change: the logs still show the same repeating error message.

**Comment by k8s-gpubuilder** [comment]
Might this be a regression bug in the newest release v1.10.1? Should I try to revert back to an older release?

**Comment by shivamerla** [comment]
Can you check logs of initContainer? `kubect logs nvidia-driver-daemonset-45bdt -n gpu-operator -c k8s-driver-manager`

**Comment by k8s-gpubuilder** [comment]
Oh thank you, that was helpful. I could see that the driver was still loaded. I don't know how this happened, but the nvidia driver was installed on the OS, which it should not have been. After this, now the gpu operator works again on that node and the vectoradd example runs as it should.
