### ISSUE TITLE
NVIDIA Releases Open-Source GPU Kernel Modules Impacts on GPU-Operator?

### ISSUE THREAD

**Issue by fanminshi** [NVIDIA/gpu-operator#352]
Hi,

I have a general question. What's the implication or impact on the recent announcement of  Open-Source GPU Kernel Modules on GPU-Operator and its component? Specifically, I would like to know if it makes bundling nvidia-driver container with OS image easier in term of licensing.

Thanks,

**Comment by shivamerla** [comment]
@fanminshi Yes, this will enable OS vendors to make pre-compiled modules available through different distributions. w.r.t GPU Operator, this will simplify the deployment of cloud-native-stack even further, as drivers can be pre-installed through distro native packages for RedHat, SLES and Ubuntu.
