### ISSUE TITLE
Ubuntu 20.04 driver: GPG key cannot be verified

### ISSUE THREAD

**Issue by wjentner** [NVIDIA/gpu-operator#355]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
**==> Ubuntu 20.04**
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

The nvidia-driver-daemonset crashloops with the following log:

```
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr ========== NVIDIA Software Installer ==========
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Starting installation of NVIDIA driver version 510.47.03 for Linux kernel version 5.4.0-113-generic
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Stopping NVIDIA persistence daemon...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Unloading NVIDIA driver kernel modules...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Unmounting NVIDIA driver rootfs...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Checking NVIDIA driver packages...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Updating the package cache...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is no longer signed.
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Stopping NVIDIA persistence daemon...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Unloading NVIDIA driver kernel modules...
nvidia-driver-daemonset-2cjwf nvidia-driver-ctr Unmounting NVIDIA driver rootfs...
```

I think the issue is described in this blog post: https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
Perhaps the image was not updated after the keys were rotated?

### 2. Steps to reproduce the issue

Run the current chart version 1.10.1 with an Ubuntu 20.04 node.

### 3. Workaround

I have created an image that contains a workaround:

Dockerfile:
```Dockerfile
FROM nvcr.io/nvidia/driver:510.47.03-ubuntu20.04

# https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/
RUN apt-key del 7fa2af80

RUN apt update && apt install wget

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb

RUN dpkg -i cuda-keyring_1.0-1_all.deb
```

The image is located at https://hub.docker.com/layers/nvidia-driver/wjentner/nvidia-driver/510.47.03-ubuntu20.04/images/sha256-ec716dd366f4e80cb5533f7790df29340bb78d5fedf2ce995161bad4b99aa148?context=repo

With the values.yamls as following …

```yaml
driver:
  repository: docker.io/wjentner
  image: nvidia-driver
  version: "510.47.03"
```

… the operator is working as expected.

**Comment by shivamerla** [comment]
@wjentner This has already been fixed. Did you try to pull the updated image? https://github.com/NVIDIA/gpu-operator/issues/344

**Comment by wjentner** [comment]
@shivamerla I can see in the other issue that this is causing a lot of confusion. Therefore, I propose:

a: default the ImagePullPolicy to Always, as the driver images receive bugfixes without increasing the version
=> this will automatically fix this problem, but might cause problems in the future when a previously working driver image gets corrupted for some reason

b (preferred): update the chart/operator to pin the image. I.e., use the image digest (sha) to select the correct image.
=> This will give the users more fine control, is more deterministic, and eases debugging.

Either way, IMHO the chart should be updated to `1.10.2` which contains either (a) or preferably (b) to fix this issue and possibly upcoming issues.

**Comment by wjentner** [comment]
How many different OS versions are there?
Would it be feasible to write the SHAs from the helm chart into a ConfigMap, Secret, environment variable, etc.
and then the operator could look up the values from there? If no SHA could be found, then it could fall back to the current behavior.

**Comment by shivamerla** [comment]
There are quite a few (ubuntu18.04, ubuntu20.04, ubuntu22.04, centos7, rhel8 eventually sles15, rocky linux, photon os, flatcar etc). Also, default driver version in the chart can be overridden too (i.e 510.47.03, 470.103.01 etc). In that case, again it will not be useful. With recent driver images we have removed cuda repo from the the image, so at-least GPG key issues won't happen again. Agree that we need a different tagging mechanism than just driver-version-os-version. Did updating `imagePullPolicy` not work for you too?

**Comment by wjentner** [comment]
Hm, yea that seems too complicated. Yes, setting the imagePullPolicy works.
