### ISSUE TITLE
Pod does not start after installing GPU-operator

### ISSUE THREAD

**Issue by kousui-dev** [NVIDIA/gpu-operator#366]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ no] Are you running on an Ubuntu 18.04 node?
- [ no(Openshift4.6)] Are you running Kubernetes v1.13+?

### 1. Issue or feature description
I'm running OpenShift (version 4.6.48) with a mirror repository and I'm trying to install version 1.8.0 of the NVIDIA GPU operator from the web console. 
The GPU-Operator installation completed successfully, but the pod does not start normally.
```
# oc get pod
nvidia-container-toolkit-daemonset-rn8fv   0/1     Init:InvalidImageName   0          4m57s 
nvidia-driver-daemonset-lc4g4              0/1     Init:InvalidImageName   0          4m27s 
```
There is a message in Event
```
# oc get event
Failed to apply default image tag "FILLED_BY_THE_OPERATOR": couldn't parse image reference "FILLED_BY_THE_OPERATOR": invalid reference format: repository name must be lowercase
```

What can I do to fix this issue and launch the pod?
Thanks in advance for your help.

**Comment by shivamerla** [comment]
@kousui-dev Can you try with latest patch on that branch 1.8.2 for OCP 4.6?

**Comment by kousui-dev** [comment]
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html

Looking at the URL, it says that GPU-Operator 1.8+ is not supported in OCP 4.6.
Is GPU-Operator 1.8 available in OCP 4.6?

**Comment by shivamerla** [comment]
Sorry, yes, 1.8 only supported from 4.7+. You would need to install from 1.7 channel for 4.6. It will be best to upgrade to later versions of OCP for using newer operator versions.

**Comment by kousui-dev** [comment]
thank you for your answer.

Since GPU-Operator 1.8 is not supported in OCP 4.6.48, I decided to install GPU-Operator 1.6.2 for verification reasons and decided to update to 1.8 with OCP 4.7.

**Comment by kousui-dev** [comment]
I updated to OCP 4.7.51 and was able to install GPU-operator 1.8.2.
But I get the same error and the pod doesn't start.

**Comment by shivamerla** [comment]
@kousui-dev Can you gather support logs with `oc adm must-gather --image=$(oc -n nvidia-gpu-operator get deployment.apps/gpu-operator \
 -o jsonpath='{.spec.template.spec.containers[?(@.name == "gpu-operator")].image}') --dest-dir=/tmp/must-gather`

**Comment by kousui-dev** [comment]
[gpu-logs.zip](https://github.com/NVIDIA/gpu-operator/files/9075669/gpu-logs.zip)
@shivamerla 
I gathered logs. but some commands get error about namespace missing.
so trying it again with namespace:gpu-operator-resources 

`[root@bastion gpu-logs]# oc get clusterpolicy -o yaml > clusterpolicy.yaml
[root@bastion gpu-logs]# oc logs $(oc get pods -lapp=gpu-operator -oname -A) -n nvidia-gpu-operator > gpu-operator.log
Error from server (NotFound): namespaces "nvidia-gpu-operator" not found
[root@bastion gpu-logs]# oc logs $(oc get pods -lapp=gpu-operator -oname -A) -n
gpu-operator-resources > gpu-operator_namespace_gpu-operator-resources.log
Error from server (NotFound): pods "gpu-operator-55f879cc85-cwtsj" not found
[root@bastion gpu-logs]# oc get -o yaml $(oc get pods -lapp=nvidia-driver-daemonset -o name -A) -n nvidia-gpu-operator > driver-pod.yaml
Error from server (NotFound): namespaces "nvidia-gpu-operator" not found
[root@bastion gpu-logs]# oc get -o yaml $(oc get pods -lapp=nvidia-driver-daemonset -o name -A) -n gpu-operator-resources > driver-pod_namespace_gpu-operator-resources.yaml
`

best regards,

**Comment by shivamerla** [comment]
Looks like you have modified ClusterPolicy instance(devicePlugin.args) and omitted certain fields(driver.manager). Please delete the ClusterPolicy instance and create with default values embedded as i see none needs to be customized with the one created currently.
