### ISSUE TITLE
Failed to install the GPU operatior on AWS server

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#37]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ y] Are you running on an Ubuntu 18.04 node?
- [ y] Are you running Kubernetes v1.13+?
- [ y] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ y] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`)

### 1. Issue or feature description

Not running the NFD-worker container cause by the following error and special-resource-operator caused by 0/1 nodes are available: 1 node(s) didn't match node selector.

NFD error: 
---
CrashLoopBackOff: back-off 5m0s restarting failed container=nfd-worker pod=nfd-worker-llq8p_node-feature-discovery(b17c43b0-8938-48ec-9c60-9f353f4cacee)
---

### 2. Steps to reproduce the issue

Prepare the g3s.large server on AWS.
1. Install the Rancher Kubernetes Engin (v1.16.3) for one server(it means that installed the master and worker.)
2. Install the hlem on server and add the gpu-oprator repository and update the repo.
3. Run the "helm install --devel nvidia/gpu-operator --wait --generate-name"

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
---
NAMESPACE                NAME                                         READY   STATUS             RESTARTS   AGE
cattle-system            cattle-cluster-agent-ffbf44bff-nxz96         1/1     Running            0          13m
cattle-system            cattle-node-agent-v9dw5                      1/1     Running            0          13m
cattle-system            kube-api-auth-tn2z5                          1/1     Running            0          13m
gpu-operator             special-resource-operator-84cb9f5fcc-j6j8l   0/1     Pending            0          11m
kube-system              canal-nr5vd                                  2/2     Running            0          13m
kube-system              coredns-5c59fd465f-grwtj                     1/1     Running            0          13m
kube-system              coredns-autoscaler-d765c8497-6vdxc           1/1     Running            0          13m
kube-system              rke-coredns-addon-deploy-job-jwh5f           0/1     Completed          0          13m
kube-system              rke-network-plugin-deploy-job-g5wsr          0/1     Completed          0          13m
node-feature-discovery   nfd-worker-llq8p                             0/1     CrashLoopBackOff   7          11m
---
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
---
NAMESPACE                NAME                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
cattle-system            cattle-node-agent   1         1         1       1            1           <none>                            14m
cattle-system            kube-api-auth       1         1         1       1            1           <none>                            14m
kube-system              canal               1         1         1       1            1           <none>                            14m
node-feature-discovery   nfd-master          0         0         0       0            0           node-role.kubernetes.io/master=   12m
node-feature-discovery   nfd-worker          1         1         0       1            0           <none>                            12m
---
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
---
Name:         nfd-worker-llq8p
Namespace:    node-feature-discovery
Priority:     0
Node:         ip-172-31-4-107/172.31.4.107
Start Time:   Mon, 09 Mar 2020 07:42:30 +0000
Labels:       app=nfd-worker
              controller-revision-hash=6d56ccb444
              pod-template-generation=1
Annotations:  <none>
Status:       Running
IP:           172.31.4.107
IPs:
  IP:           172.31.4.107
Controlled By:  DaemonSet/nfd-worker
Containers:
  nfd-worker:
    Container ID:  docker://9992e0066d808518bef30a064ab9f838a6d9a8f79e4a43456f89487123458e43
    Image:         quay.io/kubernetes_incubator/node-feature-discovery:v0.4.0
    Image ID:      docker-pullable://quay.io/kubernetes_incubator/node-feature-discovery@sha256:e4900949a957f27a3fdab4061b9fa417a3766c7c3af6f40cbf7ebacee7e87d4c
    Port:          <none>
    Host Port:     <none>
    Command:
      nfd-worker
    Args:
      --sleep-interval=60s
      --server=nfd-master:8080
      --options={"sources": {"pci": { "deviceLabelFields": ["vendor"] }}}
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 09 Mar 2020 07:53:46 +0000
      Finished:     Mon, 09 Mar 2020 07:53:47 +0000
    Ready:          False
    Restart Count:  7
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /etc/kubernetes/node-feature-discovery/features.d/ from features-d (rw)
      /etc/kubernetes/node-feature-discovery/source.d/ from source-d (rw)
      /host-boot from host-boot (ro)
      /host-etc/os-release from host-os-release (ro)
      /host-sys from host-sys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nfd-worker-token-q85nb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  host-boot:
    Type:          HostPath (bare host directory volume)
    Path:          /boot
    HostPathType:  
  host-os-release:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  
  host-sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  source-d:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/node-feature-discovery/source.d/
    HostPathType:  
  features-d:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/node-feature-discovery/features.d/
    HostPathType:  
  nfd-worker-token-q85nb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nfd-worker-token-q85nb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                From                      Message
  ----     ------     ----               ----                      -------
  Normal   Scheduled  <unknown>          default-scheduler         Successfully assigned node-feature-discovery/nfd-worker-llq8p to ip-172-31-4-107
  Normal   Pulled     13m (x5 over 15m)  kubelet, ip-172-31-4-107  Container image "quay.io/kubernetes_incubator/node-feature-discovery:v0.4.0" already present on machine
  Normal   Created    13m (x5 over 15m)  kubelet, ip-172-31-4-107  Created container nfd-worker
  Normal   Started    13m (x5 over 15m)  kubelet, ip-172-31-4-107  Started container nfd-worker
  Warning  BackOff    0s (x70 over 15m)  kubelet, ip-172-31-4-107  Back-off restarting failed container
---
 - [ ] Docker runtime configuration: `docker info | grep runtime`
---
WARNING: No swap limit support
---
 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
---
ls: cannot access '/run/nvidia': No such file or directory
---
 - [ ] NVIDIA packages directory: `ls -la /run/nvidia/toolkit`
---
ls: cannot access '/run/nvidia/toolkit': No such file or directory
---
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
---
ls: cannot access '/run/nvidia/driver': No such file or directory
---
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`
---
-- Logs begin at Mon 2020-03-09 05:24:53 UTC, end at Mon 2020-03-09 08:01:08 UTC. --
-- No entries --
---

**Comment by RenaudWasTaken** [comment]
Hello!

Can you describe the following pod: gpu-operator special-resource-operator-84cb9f5fcc-j6j8l

My guess is that you have a single node that you forgot to untaint.

**Comment by Kaka1127** [comment]
Hi

I powered down the server. So, I re-created this environment and get the log. Please check it.
----
Name:           special-resource-operator-84cb9f5fcc-dq7pd
Namespace:      gpu-operator
Priority:       0
Node:           <none>
Labels:         name=special-resource-operator
                pod-template-hash=84cb9f5fcc
Annotations:    openshift.io/scc: restricted-readonly
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/special-resource-operator-84cb9f5fcc
Containers:
  special-resource-operator:
    Image:      nvidia/gpu-operator:1.0.0
    Port:       60000/TCP
    Host Port:  0/TCP
    Command:
      gpu-operator
    Readiness:  exec [stat /tmp/operator-sdk-ready] delay=4s timeout=1s period=10s #success=1 #failure=1
    Environment:
      NVIDIA_DRIVER:                   <set to the key 'driver' of config map 'operator-config'>  Optional: false
      NVIDIA_TOOLKIT_DEFAULT_RUNTIME:  docker
      NVIDIA_TOOLKIT:                  <set to the key 'toolkit' of config map 'operator-config'>          Optional: false
      NVIDIA_DEVICE_PLUGIN:            <set to the key 'devicePlugin' of config map 'operator-config'>     Optional: false
      NVIDIA_DCGM_EXPORTER:            <set to the key 'dcgmExporter' of config map 'operator-config'>     Optional: false
      NVIDIA_DCGM_POD_EXPORTER:        <set to the key 'dcgmPodExporter' of config map 'operator-config'>  Optional: false
      KUBE_UNSUPPORTED_FLAVOR:         <set to the key 'unsupported' of config map 'operator-config'>      Optional: false
      WATCH_NAMESPACE:                 
      POD_NAME:                        special-resource-operator-84cb9f5fcc-dq7pd (v1:metadata.name)
      OPERATOR_NAME:                   special-resource-operator
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from special-resource-operator-token-b9zxk (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  special-resource-operator-token-b9zxk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  special-resource-operator-token-b9zxk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  3s (x4 over 2m43s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match node selector.
----


Best regards.

**Comment by RenaudWasTaken** [comment]
In the future can you surround your logs with backticks, this allows to sift through the logs in a more readable format :) ?

As mentioned above, I believe you didn't untaint your master node. See https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation

Specifically:
```
kubectl taint nodes --all node-role.kubernetes.io/master-
```

**Comment by Kaka1127** [comment]
Thank!
