### ISSUE TITLE
Support devices as volume mounts

### ISSUE THREAD

**Issue by xhejtman** [NVIDIA/gpu-operator#372]
Hello,

it seems that current gpu-operator does not support devices as volume mounts as described here:
https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit

is there any plan to support it?

**Comment by shivamerla** [comment]
@xhejtman Yes, the plumbing is still not there through gpu-operator/container-toolkit for this. To get this working you need to set `DEVICE_LIST_STRATEGY` as `volume-mounts` for devicePlugin and modify file `/usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml `with

disable-require = false
**accept-nvidia-visible-devices-envvar-when-unprivileged = false
accept-nvidia-visible-devices-as-volume-mounts = true**

[nvidia-container-cli]
...

**Comment by xhejtman** [comment]
It does not work because `nvidia-cuda-validator` does not see any GPU as GPU are now forbidden to be used only via ENV vars and I guess the validator uses it this way? In this case, validator should request to be privileged?

**Comment by xhejtman** [comment]
It also seems that currently privileged containers do not see GPU via env vars.

**Comment by xhejtman** [comment]
I see there is a fix for this:
https://github.com/NVIDIA/gpu-operator/commit/6d4dec0f361082bed62fdb7e42cdc3663405bff9

and I can confirm it works with this fix. Will it be included in 1.11.1?

**Comment by shivamerla** [comment]
Yes, the fix will be part of `v1.11.1`

**Comment by Omoong** [comment]
well i took the Dockerfile from this github in the validator directory created a image from it with some tweaks, and tested it with those configurations and it worked! so as soon as the v1.11.1 is released and the validator image in ngc is updated it should work!

**Comment by shivamerla** [comment]
thanks for verifying this.

**Comment by xhejtman** [comment]
Any chance that support for this will be included in device toolkit container?

**Comment by shivamerla** [comment]
Yes, we have an internal ticket tracking the change, but cannot commit on the ETA for that. Will update here once i have more details.

**Comment by Omoong** [comment]
well although we plan on installing toolkit on the baseos instead of using the gpu operator container, but if i understand this correctly you are planning on allowing users to change this setting inside the toolkit container via methods such as changing envs for tookit in values.yam? am i understanding this correctly?

**Comment by shivamerla** [comment]
Yes, that is correct. These can be configured through `toolkit.env` options. See MR: https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/198/diffs

**Comment by Omoong** [comment]
@shivamerla oh nice!! thank you

**Comment by Alwinator** [comment]
> @xhejtman Yes, the plumbing is still not there through gpu-operator/container-toolkit for this.

@shivamerla Is there any news on this issue? Is the new solution already published? If so, where to find the according documentation?

Thank you in advance!

**Comment by elezar** [comment]
@Alwinator please see https://github.com/NVIDIA/gpu-operator/issues/421 where this feature is being discussed. There is no single toggle at present, but a user can configure both the device plugin and container toolkit to specify devices as volume mounts instead of usign the environment variables.

**Comment by Alwinator** [comment]
@elezar Thank you! :)
