### ISSUE TITLE
How to install gpu operator in K8s cluster with different GPU servers, HGX (fabric manager) and other GPU server.  

### ISSUE THREAD

**Issue by sricharandevops** [NVIDIA/gpu-operator#375]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? No, centos 7.9
- [ ] Are you running Kubernetes v1.13+?      1.21
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?  dockershim

### 1. Issue or feature description
Have a Kubernetes cluster 1.21 running with a bunch of nodes with GPU(A100) and Nvidia drivers got loaded with GPU operator and found No issues there and everything works.

Now we have added the HGX(A100) node to the same Kubernetes cluster, The nvidia-driver pod started to run on the HGX box, however, 
nvida-cuda-validator and nvidia-gpu-validator pods are in Init; Crashloopback error and 

`[root@cl3-ac-us-hgx1 ~]#
[root@cl3-ac-us-hgx1 ~]# kubectl  logs  nvidia-cuda-validator-vkfv6 -n gpu-operator-resources -c cuda-validation
Failed to allocate device vector A (error code system not yet initialized)!
[Vector addition of 50000 elements]
[root@cl3-ac-us-hgx1 ~]#`

Now the question is,

1. Given that HGX needs to have Fabric manager services to be up, Is it required to only load the drivers on the host? or can we use nvidia-drivers from the Nvidia-driver daemon pod?

2. If the Nvidia-driver needs to be loaded on the host, how can we enforce gpu-operator to not deploy its nvidia-driver ds pod on the HGX host where the driver is already installed?

3. given that without host drivers being installed, i am able to get the nvidia-driver-daemnset pod running  on HGX box and able to see the gpu allocated and discovered to containers correctly..  can we ignore  the init errors from " Nvidia-cuda-validator-vkfv6" and  nvidia-operator-validator-jw579 pids ?

This is current state of the pods-
![image](https://user-images.githubusercontent.com/89511243/180312114-20a3013e-7acb-4f88-bc00-f1d835f833d5.png)

**Comment by sricharandevops** [comment]
![image](https://user-images.githubusercontent.com/89511243/180312443-b16eecb0-2e41-49c0-b22a-d45a05b5e44b.png)

**Comment by shivamerla** [comment]
@sricharandevops The error can happen when fabric-manager services are not started on HGX system where drivers are pre-installed. We do support heterogenous nodes with v1.11.0 for this use case. On the node where driver is pre-installed, please set node label `nvidia.com/gpu.driver.deploy=false`. This will allow GPU operator to ignore those nodes for driver-container deployment.

**Comment by sricharandevops** [comment]
@shivamerla ,  I was able to label the node with the `nvidia.com/gpu.driver.deploy=false` ,  and installed fabric manger and nvidia-driver on the host,  now all other operator pods on this hgx are in crashloop back state, 
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/89511243/180579126-193b25f9-f855-4ee0-8729-331a84e74d04.png">


Can i go ahead and  update the nodelabel to update all these pods = false, any downside in this approach ..?
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/89511243/180579462-73538016-018f-48c3-ba11-a0feb325f327.png">

**Comment by sricharandevops** [comment]
@shivamerla , also after installing the drivers on  the host and fabric manager, i don't see the GPUs being discovered by node kubelet,  kubectl describe node does not show me the GPU  count available on the host.
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/89511243/180580270-9c800f55-ec6f-4acf-87e3-992cf795cf8d.png">

**Comment by shivamerla** [comment]
@sricharandevops Please don't disable any other operands with node labels. Just the driver container. Can you describe any of the pods in CrashLoop? Can you check if nvidia-fabricmanager service is running using systemctl?

**Comment by sricharandevops** [comment]
@shivamerla , now i have reinstalled gpu operator and with 1.10, using the below helm install command,
`helm install --wait --generate-name      -n gpu-operator --version=1.10.1 --create-namespace      nvidia/gpu-operator      --set toolkit.version=1.7.1-centos7`

now with 1.10 install, on other gpu nodes have 
driver-daemonset pods, toolkit pods running fine, 
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/89511243/180817097-98f54d7a-68ec-4e93-a996-e273a18be8e5.png">


but the  deviceplugin, mig-manager pods are in init state with the below error 
-
`kubectl describe pod nvidia-device-plugin-daemonset-4dlfq -n gpu-operator
kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = Exception calling application: ErrorUnknown:StatusCode.UNKNOWN:RuntimeHandler "nvidia" not supported
`

**Comment by shivamerla** [comment]
Can you check logs of "kubectl logs nvidia-operator-validator-chtj9 -n gpu-operator -c driver-validation", And similarly with other operator-validator pods on all nodes as well.

**Comment by sricharandevops** [comment]
`[root@cl3-ac-us-admin1 ~]# kubectl  describe pod nvidia-operator-validator-chtj9 -n gpu-operator

Events:
  Type     Reason                  Age                    From     Message
  ----     ------                  ----                   ----     -------
  Warning  FailedCreatePodSandBox  102s (x3733 over 13h)  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = Exception calling application: ErrorUnknown:StatusCode.UNKNOWN:RuntimeHandler "nvidia" not supported
`
```
[root@cl3-ac-us-admin1 ~]# kubectl logs nvidia-operator-validator-chtj9 -n gpu-operator -c driver-validation
Error from server (BadRequest): container "driver-validation" in pod "nvidia-operator-validator-chtj9" is waiting to start: PodInitializing
```

**Comment by sricharandevops** [comment]
@shivamerla , all other pods in init state are having the same issue  when i describe 
`RuntimeHandler "nvidia" not supported`

**Comment by shivamerla** [comment]
looks like container-toolkit is not setup right on all machines. Can you copy config from `/usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml` and also `/etc/containerd/config.toml`? from both the nodes where driver is loaded from a container and pre-installed.

**Comment by sricharandevops** [comment]
On host where container-driver-pod is running -

`[root@cl3-ac-us-gpu1 ~]# cat /usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml
disable-require = false

[nvidia-container-cli]
  environment = []
  ldconfig = "@/run/nvidia/driver/sbin/ldconfig"
  load-kmods = true
  path = "/usr/local/nvidia/toolkit/nvidia-container-cli"
  root = "/run/nvidia/driver"

[nvidia-container-runtime]
[root@cl3-ac-us-gpu1 ~]#  

cat /etc/containerd/config.toml
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia-experimental]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia-experimental.options]
            BinaryName = "/usr/local/nvidia/toolkit/nvidia-container-runtime-experimental"`

From the HGX host where driver is preinstalled with fabric manager- 
`cat /usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml
disable-require = false

[nvidia-container-cli]
  environment = []
  ldconfig = "@/run/nvidia/driver/sbin/ldconfig"
  load-kmods = true
  path = "/usr/local/nvidia/toolkit/nvidia-container-cli"
  root = "/run/nvidia/driver"

[nvidia-container-runtime]
[root@cl3-ac-us-hgx1 ~]# cat /etc/containerd/config.toml
cat: /etc/containerd/config.toml: No such file or directory
[root@cl3-ac-us-hgx1 ~]#`

**Comment by shivamerla** [comment]
On HGX nodes, please change 

```
root = "/run/nvidia/driver"
```

to 

```
root = "/"
```

and restart containerd.

**Comment by sricharandevops** [comment]
I did and  restarted dockershim.  the toolkit failed again after restart

`  Warning  Failed     4m9s (x5 over 5m40s)   kubelet            Error: Exception calling application: ErrorUnknown:StatusCode.UNKNOWN:failed to start container "driver-validation": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli.real: ldcache error: open failed: /run/nvidia/driver/sbin/ldconfig: no such file or directory: unknown
  Warning  BackOff    27s (x24 over 5m20s)   kubelet            Back-off restarting failed container
[root@cl3-ac-us-hgx1 ~]#`

should the driver version on all hosts preinstalled and containerdriver should be exactly same version?

**Comment by shivamerla** [comment]
@sricharandevops  somehow the `root` directory update is not taking effect and it is still referencing `/run/nvidia/driver`.  It should be `/` when driver is pre-installed on the node.

**Comment by sricharandevops** [comment]
@shivamerla  --
This is from a working node where driver is running inside nvidia-driver pod -

`[root@cl3-ac-us-gpu3 ~]# cat /usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml
disable-require = false

[nvidia-container-cli]
  environment = []
  ldconfig = "@/run/nvidia/driver/sbin/ldconfig.real"
  load-kmods = true
  path = "/usr/local/nvidia/toolkit/nvidia-container-cli"
  root = "/run/nvidia/driver"

[nvidia-container-runtime]
  log-level = "info"
  mode = "auto"
  runtimes = ["docker-runc", "runc"]

  [nvidia-container-runtime.modes]

    [nvidia-container-runtime.modes.csv]
      mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"`

Below is the non-working node where driver is running on host (HGX + driver+  FM running on host) 

`[root@cl3-ac-us-gpu3 ~]# cat /usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml
disable-require = false

[nvidia-container-cli]
  environment = []
  ldconfig = "@/run/nvidia/driver/sbin/ldconfig.real"
  load-kmods = true
  path = "/usr/local/nvidia/toolkit/nvidia-container-cli"
  root = "/run/nvidia/driver"

[nvidia-container-runtime]
  log-level = "info"
  mode = "auto"
  runtimes = ["docker-runc", "runc"]

  [nvidia-container-runtime.modes]

    [nvidia-container-runtime.modes.csv]
      mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"`

**Comment by sricharandevops** [comment]
@shivamerla , 
I was able to pass through the issue after cleanly removing this /usr/local/nvidia/toolkit after uninstall.

It appears the issue was  GPU operator uninstall is not cleaning these directories and As the  host previously had an older version of operator running and the /usr/local/nvidia/toolkit/.config/nvidia-container-runtime/config.toml file appeared to be referencing the stale one while installing 1.11 operator.

Now everything looks fine, except the  for cuda_validation-xx and nvidia-operator-validation-xx pod which are in crashloopback.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/89511243/181368852-b154080e-d4e1-45bd-8da0-0b5456016a37.png">

**Comment by shivamerla** [comment]
I will confirm if the toolkit cleanup is fixed with latest versions of toolkit container. The error with cuda validator can happen if fabric-manager service is not running on the host. Please check if the systemd service is running for fabric-manager.

**Comment by sricharandevops** [comment]
Thankyou @shivamerla  for the pointer.. this worked for me.

**Comment by shivamerla** [comment]
thanks for confirming.

**Comment by dmquant** [comment]
Also solved my same issue, thanks.
