### ISSUE TITLE
GPU Operator requires same kernel version on each node

### ISSUE THREAD

**Issue by linkvt** [NVIDIA/gpu-operator#38]
Hi guys,

we are using the GPU operator successfully in our clusters but noticed one problem after reinstalling a single host of the Kubernetes cluster causing it to have a more recent kernel version than the other nodes.

The reason is that the `nvidia-driver-daemonset` has a `nodeSelector` for the kernel version of the host it runs on (and yes I saw https://github.com/NVIDIA/gpu-operator/issues/21 :)): https://github.com/NVIDIA/gpu-operator/blob/27d1dc5863d5eb68d0b95e3bfe8b025e7a8787b6/pkg/controller/specialresource/specialresource_controls.go#L236-L238

After removing the kernel version nodeSelector the driver-daemonset pod ran fine, or is there still a reason to keep this after the 1.0.0 release?
The other ticket linked above also says that it should be removed in Feb-March - was it maybe _missed_ before the 1.0.0 release?

I could also try to do a PR if this helps with getting it done quicker.

Thanks,
Vincent

**Comment by RenaudWasTaken** [comment]
Hello!

Just to make sure that I understood correctly, you have:
1. A node that had Kernel version X
2. A driver container that was scheduled on that node for version X
3. Re-imaged or updated the kernel to version Y
4. The driver container did not get re-created to include version Y

Also do you have multiple nodes in your cluster? (In other words is your cluster heterogeneous?)

**Comment by linkvt** [comment]
Hi @RenaudWasTaken, 
we have multiple GPU and non-GPU nodes in our cluster and one GPU node was reinstalled from scratch and received a more recent kernel version causing the cluster to have GPU nodes with two different kernel versions.

The issue comes now from the restriction that the nvidia driver installation specifies the exact kernel version that it finds on one of the Kubernetes nodes (as in the linked code section above). As the kernel versions differ on this node vs on the other nodes it will not be installed on all GPU nodes but only on the ones with the same kernel version which is specified in the driver installation DaemonSet.
To my understanding this restriction is not needed (also as I understand your comment in https://github.com/NVIDIA/gpu-operator/issues/21#issuecomment-574292501) as the driver is built on each node individually anyways.

In theory it is of course possible to have all nodes on the same kernel version, but at some in time I need to begin updating my nodes e.g. by reinstalling them or removing and adding new nodes to the cluster.
When this starts all new GPU nodes will unusable as the driver installation is not being scheduled there (to my understanding at least from what I see now, I don't know the complete Operator implementation).

Thanks!

**Comment by RenaudWasTaken** [comment]
Some progress on this here: https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/82

**Comment by RenaudWasTaken** [comment]
It's in the nightly!

**Comment by linkvt** [comment]
Hi @RenaudWasTaken , thanks a lot for the quick fix!
Unfortunately I'm affected by the break of automotive companies in Germany/Europe so I will not be able to test this in the upcoming 2+ weeks at work. We could still close this ticket of course and I will give feedback when I'm able to test this again.

**Comment by nvjmayo** [comment]
Closing. I looks to me that MR !82 addresses the issue. re-open if there is further changes necessary.
