### ISSUE TITLE
NVIDIA GPU Operator - Node effects of Operator's updates

### ISSUE THREAD

**Issue by adionisieva** [NVIDIA/gpu-operator#380]
Hello,

We are using NVIDIA GPU Operator version 1.9.1 in OCP cluster with version 4.8.31 and we are interested if this Operator has the permissions to update nodes or to make automatic changes on the nodes. I have checked the yaml of the Operator and its configuration is the following:
- apiGroups:
- ''
resources:
- pods
- services
- services/finalizers
- endpoints
- persistentvolumeclaims
- events
- configmaps
- secrets
- nodes
- namespaces
- serviceaccounts
verbs:
- create
- delete
- get
- list
- patch
- update
- watch

Does it mean that if the nodes with GPUs are in a MachineConfigPool (MCP) which is unpaused, the Nvidia Operator can patch/update the nodes without admins’ knowledge, causing drain and restart of the machines?
We are using the Operator in Manual Update Approval which should overwrite the updates that the driver Daemonset is trying to apply. Could you please confirm if that is correct? Or is there another setting that we should use in order to guarantee node stability?

Please let me know if more details are needed.
Thank you.

Best regards,
Anna-Maria

**Comment by shivamerla** [comment]
@adionisieva Please refer to [this](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#additional-controls-for-driver-upgrades) guide for info on driver upgrades. If you want to disable auto-drain of the node, you can set `driver.manager.env` with `ENABLE_AUTO_DRAIN` as `false`. GPU Operator will update node labels and perform node drain when driver couldn't be unloaded during updates. This is the last resort to evict all Pods using the GPUs to re-install the driver. We don't reboot the nodes.

**Comment by shivamerla** [comment]
Please check on more controls for driver upgrades [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-driver-upgrades.html)
