### ISSUE TITLE
nvidia-cuda-validator pods crashlooping in Openshift 4.8

### ISSUE THREAD

**Issue by Muscule** [NVIDIA/gpu-operator#382]
I have 3 nodes with Tesla-T4, A100 and A30. With Tesla-T4 nvidia-cuda-validator completed successfully, but with A100 and A30 nvidia-cuda-validator keeps crashlooping. "[Vector addition of 50000 elements] Failed to allocate vector A (error code initialization error)!" is in cuda-validator container's log. Is there any way to fix?

_Originally posted by @Muscule in https://github.com/NVIDIA/gpu-operator/issues/259#issuecomment-1205312265_

**Comment by shivamerla** [comment]
@Muscule what version of GPU Operator are you using?

**Comment by Muscule** [comment]
> @Muscule what version of GPU Operator are you using?

1.11.0

**Comment by shivamerla** [comment]
Can you run the below must-gather command and provide us the output.

```
oc adm must-gather --image=nvcr.io/nvidia/gpu-operator:v1.11.0 --dest-dir=/tmp/must-gather
```

**Comment by Muscule** [comment]
> Can you run the below must-gather command and provide us the output.
> 
> ```
> oc adm must-gather --image=nvcr.io/nvidia/gpu-operator:v1.11.0 --dest-dir=/tmp/must-gather
> ```
[must-gather.zip](https://github.com/NVIDIA/gpu-operator/files/9269229/must-gather.zip)

**Comment by shivamerla** [comment]
On A30/A100 machines i see MIG mode is enabled but no MIG devices are created, cuda failure might be due to this.

```
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] Thu Aug  4 09:18:08 2022       
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |-------------------------------+----------------------+----------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |               MIG M. |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |===============================+======================+======================|
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |   0  NVIDIA A30          On   | 00000000:17:00.0 Off |                   On |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | N/A   29C    P0    28W / 165W |      0MiB / 24576MiB |     N/A      Default |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |              Enabled |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-------------------------------+----------------------+----------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |   1  NVIDIA A30          On   | 00000000:65:00.0 Off |                   On |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | N/A   30C    P0    29W / 165W |      0MiB / 24576MiB |     N/A      Default |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |              Enabled |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-------------------------------+----------------------+----------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |   2  NVIDIA A30          On   | 00000000:CA:00.0 Off |                   On |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | N/A   28C    P0    35W / 165W |      0MiB / 24576MiB |     N/A      Default |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |              Enabled |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-------------------------------+----------------------+----------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] 
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | MIG devices:                                                                |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +------------------+----------------------+-----------+-----------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                  |                      |        ECC|                       |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |==================+======================+===========+=======================|
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |  No MIG devices found                                                       |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation]                                                                                
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] | Processes:                                                                  |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |        ID   ID                                                   Usage      |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |=============================================================================|
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] |  No running processes found                                                 |
[pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
```

Also, on A100 machine, can you check the memory mapped to the VM?

```
[  221.458953] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  515.48.07  Fri May 27 03:26:43 UTC 2022
[  221.488180] nvidia-uvm: Loaded the UVM driver, major device number 511.
[  221.498830] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  515.48.07  Fri May 27 03:18:00 UTC 2022
[  221.806467] resource sanity check: requesting [mem 0x000e0000-0x000fffff], which spans more than PCI Bus 0000:00 [mem 0x000e0000-0x000e3fff window]
[  221.820016] caller _nv033027rm+0x2a/0x60 [nvidia] mapping multiple BARs
```

**Comment by Muscule** [comment]
> On A30/A100 machines i see MIG mode is enabled but no MIG devices are created, cuda failure might be due to this.
> 
> ```
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] Thu Aug  4 09:18:08 2022       
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |-------------------------------+----------------------+----------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |               MIG M. |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |===============================+======================+======================|
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |   0  NVIDIA A30          On   | 00000000:17:00.0 Off |                   On |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | N/A   29C    P0    28W / 165W |      0MiB / 24576MiB |     N/A      Default |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |              Enabled |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-------------------------------+----------------------+----------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |   1  NVIDIA A30          On   | 00000000:65:00.0 Off |                   On |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | N/A   30C    P0    29W / 165W |      0MiB / 24576MiB |     N/A      Default |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |              Enabled |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-------------------------------+----------------------+----------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |   2  NVIDIA A30          On   | 00000000:CA:00.0 Off |                   On |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | N/A   28C    P0    35W / 165W |      0MiB / 24576MiB |     N/A      Default |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                               |                      |              Enabled |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-------------------------------+----------------------+----------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] 
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | MIG devices:                                                                |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +------------------+----------------------+-----------+-----------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |                  |                      |        ECC|                       |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |==================+======================+===========+=======================|
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |  No MIG devices found                                                       |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation]                                                                                
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] | Processes:                                                                  |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |        ID   ID                                                   Usage      |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |=============================================================================|
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] |  No running processes found                                                 |
> [pod/nvidia-operator-validator-lg2lf/toolkit-validation] +-----------------------------------------------------------------------------+
> ```
> 
> Also, on A100 machine, can you check the memory mapped to the VM?
> 
> ```
> [  221.458953] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  515.48.07  Fri May 27 03:26:43 UTC 2022
> [  221.488180] nvidia-uvm: Loaded the UVM driver, major device number 511.
> [  221.498830] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  515.48.07  Fri May 27 03:18:00 UTC 2022
> [  221.806467] resource sanity check: requesting [mem 0x000e0000-0x000fffff], which spans more than PCI Bus 0000:00 [mem 0x000e0000-0x000e3fff window]
> [  221.820016] caller _nv033027rm+0x2a/0x60 [nvidia] mapping multiple BARs
> ```

Thank you so mach! I changed strategy in cluster-policy from none to single, labeled nodes with mig.config, and cuda validation passed on A100/A30.
