### ISSUE TITLE
helm install gpu-operator error

### ISSUE THREAD

**Issue by yanchaocc** [NVIDIA/gpu-operator#383]
k8s version: v1.21

```
helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
helm repo update

export N_GO=gpu-operator
helm install --dry-run --wait --generate-name -n $N_GO --create-namespace nvidia/gpu-operator --set nfd.enabled=true
```

![image](https://user-images.githubusercontent.com/17809819/183131402-d3600e67-99d5-4733-b513-6a76641d84f5.png)

get error:

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterPolicy" in version "nvidia.com/v1"

**Comment by shivamerla** [comment]
@yanchaocc This seems like limitation with Helm with `--dry-run` option where CRD(under crds/ folder) is ignored. Install itself works fine.

```
ubuntu@kubernetes-master:~$ helm install  --generate-name -n $N_GO --create-namespace nvidia/gpu-operator --set nfd.enabled=true
NAME: gpu-operator-1659723066
LAST DEPLOYED: Fri Aug  5 18:11:08 2022
NAMESPACE: gpu-operator
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
