### ISSUE TITLE
default-mig-parted-config cannot be modified

### ISSUE THREAD

**Issue by chenxj1997** [NVIDIA/gpu-operator#384]
I modified the ConfigMap named default-mig-parted-config，

I  added custom-config to default-mig-parted-config ,but default-mig-parted-config was reset

How can I modify it so that it is not reset?

**Comment by shivamerla** [comment]
@chenxj1997 you cannot modify the default ConfigMap created by Operator, but you can pass a custom ConfigMap for this in the same namespace using `--set migManager.config.name=<custom-config-map-name>`. You can reference default config-map [here](https://github.com/NVIDIA/gpu-operator/blob/master/assets/state-mig-manager/0400_configmap.yaml) and edit the configs, namespace and name.
