### ISSUE TITLE
Docker unusable after reboot due to missing /run/nvidia directory

### ISSUE THREAD

**Issue by linkvt** [NVIDIA/gpu-operator#39]
Hi,

we noticed another IMO really critical issue with the GPU operator that happens after rebooting a system, we are using the 1.0.0 version.

### Issue Description
The GPU operator missuses the `/run` mount as per the [Linux Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html):

> This directory contains system information data describing the system since it was booted. **Files under this directory must be cleared (removed or truncated as appropriate) at the beginning of the boot process.**

If this directory is missing you are not able to start any docker container as the container-runtime configured for docker in the `/etc/docker/daemon.json` is not available as `/run` and the contained symlink to the `nvidia-container-runtime` are missing after reboot.

### Further Explanation
This prevents docker and thus also all Kubernetes components on that node from starting with the following error:
```
$ sudo docker run --rm -it alpine
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
c9b1b535fdd9: Already exists 
Digest: sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
Status: Downloaded newer image for alpine:latest
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/115fc504d4d2f9dcfbf1b801ba3d32ec1923c7bda96477c936fca27bb6553045/log.json: no such file or directory): fork/exec /run/nvidia/toolkit/nvidia-container-runtime: no such file or directory: : unknown.
```
If you check the `/etc/docker/daemon.json` you see the reason, the path for the default runtime does not exist.
```
cat /etc/docker/daemon.json
{
  "runtimes": {
    "nvidia": {
      "path": "/run/nvidia/toolkit/nvidia-container-runtime"
    }
  },
  "default-runtime": "nvidia"
}
```
The operator creates the directory `/run/nvidia` with the following content during the driver installation (IIRC):
```
$ ll /run/nvidia/
total 4
drwxr-xr-x  2 root root   80 Mar  9 15:31 ./
drwxr-xr-x 30 root root 1080 Mar  9 15:31 ../
lrwxrwxrwx  1 root root   25 Mar  9 15:31 toolkit -> /usr/local/nvidia/toolkit/
-rw-r--r--  1 root root    6 Mar  9 15:31 toolkit.pid
```
If this is missing there is also no valid symlink to the `nvidia-container-runtime` located in:
```
$ realpath /run/nvidia/toolkit/nvidia-container-runtime
/usr/local/nvidia/toolkit/nvidia-container-runtime
```

Why is `/run` being used and why don't you just use the realpath instead of the symlink going through `/run/nvidia`?

BR, Vincent

**Comment by RenaudWasTaken** [comment]
I agree that's a critical bug, we'll try to prioritize this one first.

**Comment by RenaudWasTaken** [comment]
Some progress on this, I believe this PR will fix this issue: https://gitlab.com/nvidia/container-toolkit/container-config/-/merge_requests/25/

I'll tag a new version and propagate to the GPU Operator as soon as it's in :)

**Comment by RenaudWasTaken** [comment]
It's in the nightly!

**Comment by linkvt** [comment]
Hi @RenaudWasTaken , thanks a lot for the quick fix!
Unfortunately I'm affected by the break of automotive companies in Germany/Europe so I will not be able to test this in the upcoming 2+ weeks at work. We could still close this ticket of course and I will give feedback when I'm able to test this again.

**Comment by RenaudWasTaken** [comment]
I think this one is fixed now, closing :)
