### ISSUE TITLE
Ability to specify my own labels on pods

### ISSUE THREAD

**Issue by boniek83** [NVIDIA/gpu-operator#402]
### 1. Issue or feature description
I would love to have ability to specify my own set of labels on pods. My organization uses them for pod ownership (resource cost allocation and incident support).
I'm using helm chart 1.10.1.

**Comment by tariq1890** [comment]
I believe this can be closed as this [change](https://github.com/NVIDIA/gpu-operator/commit/082607342e844d78ea8bd543dac0b01992f78c25) is available in "v22.9.1" release 

@boniek83 Can you verify?

**Comment by boniek83** [comment]
Yes, this is what I wanted. Thank you!
