### ISSUE TITLE
CUDA version cannot change in GPU-Operatorv1.11.1

### ISSUE THREAD

**Issue by carlwang87** [NVIDIA/gpu-operator#408]
In the values.xml, the cuda version is 11.6.0-base-ubi8 in operator.initContainer.version.
`
operator: 
  use_ocp_driver_toolkit: false  
  initContainer:
    image: cuda
    repository: nvcr.io/nvidia
    version: 11.6.0-base-ubi8
    imagePullPolicy: IfNotPresent
`

After applied the gpu-operator succssfully in my cluster env, I entered into the container with following command:
`kubectl exec -i -t -n hsc-gpu gpu-operator-dfb584dff-rj79t -c gpu-operator -- sh -c "clear; (bash || ash || sh)"`

And I found the cuda directory under /usr/local is 11.7 as below picture:
![image](https://user-images.githubusercontent.com/9320929/191240338-b2d4b37f-dec0-4a28-a2cc-0f1090227c7f.png)

Then I entered into the  nvidia-container-toolkit-daemonset container, the cuda version is 11.6 as below:
![image](https://user-images.githubusercontent.com/9320929/191240668-5111e78a-1694-4fff-904c-407b4f3e2671.png)

So how can we change the version of CUDA in the gpu-operator  container? How can we make cuda version same in the cluster environment?

**Comment by shivamerla** [comment]
@carlwang87 These are CUDA compat libs that depends on the CUDA images that these images were built on. We got rid of compat libs from the operator/operand images with upcoming release(v22.9) which is coming out later this month. Also, what issues have you seen with compat libs being part of these images? The libs that container-toolkit will inject into app containers is based on the libs installed by the NVIDIA driver and not the compat libs.

**Comment by carlwang87** [comment]
The issue is that the cuda samples cannot run with the following logs:
`Failed to allocate device vector A (error code CUDA driver version is insufficient for CUDA runtime version)!`

**Comment by shivamerla** [comment]
This is similar to issue https://github.com/NVIDIA/gpu-operator/issues/389. It will be fixed as part of next release(next week).

**Comment by hoangtnm** [comment]
Hi @shivamerla, when will it be released? Because I think that today might be your mentioned next release (week).

**Comment by shivamerla** [comment]
@hoangtnm It will be released today.

**Comment by cdesiniotis** [comment]
GPU Operator v22.9.0 has been released: https://github.com/NVIDIA/gpu-operator/releases/tag/v22.9.0

@carlwang87 Please re-open if v22.9.0 does not fix this issue.

**Comment by carlwang87** [comment]
OS Version: Red Hat Enterprise Linux release 8.4

kernel: 4.18.0-305.el8.x86_64
K3S Version: v1.24.3+k3s1

GPU Operator Version: v22.9.0
CUDA Version: 11.7.1-base-ubi8

Driver Pre-installed: No
Driver Version：515.65.01-rhel8.4

Container-Toolkit Pre-installed: No
Container-Toolkit Version: v1.11.0-ubi8

GPU Type: Tesla P100
cuda-sample: cuda-sample:vectoradd-cuda11.7.1-ubi8
