### ISSUE TITLE
node.k8s.io/v1beta1 deprecated in Kubernetes 1.25

### ISSUE THREAD

**Issue by benlsheets** [NVIDIA/gpu-operator#409]
### 1. Quick Debug Checklist
- [❌ ] Are you running on an Ubuntu 18.04 node?
- [✅ ] Are you running Kubernetes v1.13+?
- [❌ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [  ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Release 1.11.1 deploys resources under the node.k8s.io/v1beta1 API which seems to be deprecated in Kubernetes 1.25.

### 2. Steps to reproduce the issue
Install the 1.11.1 gpu operator on a Kubernetes 1.25 cluster.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

`kubectl logs -n gpu-operator gpu-operator-56c9cf6799-gldjl`
ERROR	controller.clusterpolicy-controller	Reconciler error	{"name": "cluster-policy", "namespace": "", "error": "no matches for kind \"RuntimeClass\" in version \"node.k8s.io/v1beta1\""}

**Comment by cdesiniotis** [comment]
@benlsheets This is a known issue and has been fixed [here](https://github.com/NVIDIA/gpu-operator/commit/67715494de7b019fe7868496065d7f25c1700adf). The fix will be included in our next release at the end of this month.

**Comment by damjanek** [comment]
When it will be released? We're already past the end of September.

**Comment by cdesiniotis** [comment]
@damjanek It will be released later today. I will update this thread when complete.

**Comment by cdesiniotis** [comment]
GPU Operator v22.9.0 has been released: https://github.com/NVIDIA/gpu-operator/releases/tag/v22.9.0

@benlsheets @damjanek can you verify if v22.9.0 resolves this issue? Thanks.

**Comment by benlsheets** [comment]
> GPU Operator v22.9.0 has been released: https://github.com/NVIDIA/gpu-operator/releases/tag/v22.9.0
> 
> @benlsheets @damjanek can you verify if v22.9.0 resolves this issue? Thanks.

Confirmed v22.9.0 is working with Kubernetes 1.25.2. Thanks for your help and candor.
