### ISSUE TITLE
[Question] Check installed version of gpu-operator

### ISSUE THREAD

**Issue by hoangtnm** [NVIDIA/gpu-operator#410]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
Hi, I'm trying to enable GPU on microk8s with `microk8s enable gpu` but I'm not sure which version of gpu-operator and driver is installed with this Addon. Is there any way to check it or view the installed config?

**Comment by shivamerla** [comment]
@hoangtnm which microk8s version are you using, looks like with v1.23 default operator version used is `v1.11.0` from [here](https://github.com/canonical/microk8s/blob/1.23/microk8s-resources/actions/enable.gpu.sh).
