### ISSUE TITLE
 nvidia-dcgm-exporter failing after setting env var

### ISSUE THREAD

**Issue by sasajl** [NVIDIA/gpu-operator#414]
I was exploring the Prometheus support, and on this instruction: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#:~:text=In%20this%20scenario%2C%20we%20need%20to%20set

Found that the dcgm-exporter is now failing. 
I'd like to get back to a known good state. Short of redeploying the gpu-operator, what's the best way to fix this?

Here's the error:
ubectl logs nvidia-dcgm-exporter-w2ths -n gpu-operator
time="2022-09-29T12:09:09Z" level=info msg="Starting dcgm-exporter"
time="2022-09-29T12:09:09Z" level=info msg="Attemping to connect to remote hostengine at localhost:5555"
time="2022-09-29T12:09:14Z" level=fatal msg="Error connecting to nv-hostengine: Host engine connection invalid/disconnected"

**Comment by shivamerla** [comment]
@sasajl which version of GPU Operator are you using? Can you show the status of all pods `kubectl get pods -n gpu-operator` and also `kubectl describe clusterpolicy`

**Comment by sasajl** [comment]
Hi Shiva,

Chart version: gpu-operator-v1.11.1

kubectl get pods -n gpu-operator
NAME                                                          READY   STATUS                  RESTARTS           AGE
gpu-feature-discovery-4szks                                   0/2     Init:CrashLoopBackOff   2277 (3m34s ago)   8d
gpu-feature-discovery-khw7d                                   2/2     Running                 0                  8d
gpu-operator-84d9f557c8-lqp5z                                 1/1     Running                 0                  8d
gpu-operator-node-feature-discovery-master-59b4b67f4f-bqjdb   1/1     Running                 0                  8d
gpu-operator-node-feature-discovery-worker-5lf94              1/1     Running                 0                  8d
gpu-operator-node-feature-discovery-worker-c5xql              1/1     Running                 0                  8d
gpu-operator-node-feature-discovery-worker-hs9t4              1/1     Running                 0                  8d
nvidia-container-toolkit-daemonset-c222w                      1/1     Running                 0                  8d
nvidia-container-toolkit-daemonset-vgsxf                      1/1     Running                 1 (8d ago)         8d
nvidia-cuda-validator-ll675                                   0/1     Completed               0                  8d
nvidia-cuda-validator-phl2c                                   0/1     Completed               0                  8d
nvidia-dcgm-exporter-549vb                                    0/1     CrashLoopBackOff        267 (3m25s ago)    22h
nvidia-dcgm-exporter-w2ths                                    0/1     CrashLoopBackOff        268 (21s ago)      22h
nvidia-device-plugin-daemonset-7gszr                          2/2     Running                 0                  8d
nvidia-device-plugin-daemonset-wpzgh                          0/2     Init:CrashLoopBackOff   2276 (2m3s ago)    8d
nvidia-device-plugin-validator-zrlcv                          0/1     Completed               0                  8d
nvidia-driver-daemonset-lklfd                                 1/1     Running                 0                  8d
nvidia-driver-daemonset-rn9r6                                 1/1     Running                 0                  8d
nvidia-operator-validator-db47h                               1/1     Running                 0                  8d
nvidia-operator-validator-n84cx                               0/1     Init:CrashLoopBackOff   1529 (91s ago)     8d


kubectl describe clusterpolicy
Name:         cluster-policy
Namespace:
Labels:       app.kubernetes.io/component=gpu-operator
              app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: gpu-operator
              meta.helm.sh/release-namespace: gpu-operator
API Version:  nvidia.com/v1
Kind:         ClusterPolicy
Metadata:
  Creation Timestamp:  2022-09-21T17:05:40Z
  Generation:          6
  Managed Fields:
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:daemonsets:
          .:
          f:priorityClassName:
          f:tolerations:
        f:dcgm:
          .:
          f:enabled:
          f:hostPort:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:dcgmExporter:
          .:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:devicePlugin:
          .:
          f:config:
            .:
            f:default:
            f:name:
          f:env:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:driver:
          .:
          f:certConfig:
            .:
            f:name:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:kernelModuleConfig:
            .:
            f:name:
          f:licensingConfig:
            .:
            f:configMapName:
            f:nlsEnabled:
          f:manager:
            .:
            f:env:
            f:image:
            f:imagePullPolicy:
            f:repository:
            f:version:
          f:rdma:
            .:
            f:enabled:
            f:useHostMofed:
          f:repoConfig:
            .:
            f:configMapName:
          f:repository:
          f:rollingUpdate:
            .:
            f:maxUnavailable:
          f:version:
          f:virtualTopology:
            .:
            f:config:
        f:gfd:
          .:
          f:env:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:mig:
          .:
          f:strategy:
        f:migManager:
          .:
          f:config:
            .:
            f:name:
          f:enabled:
          f:env:
          f:gpuClientsConfig:
            .:
            f:name:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:nodeStatusExporter:
          .:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:operator:
          .:
          f:defaultRuntime:
          f:initContainer:
            .:
            f:image:
            f:imagePullPolicy:
            f:repository:
            f:version:
          f:runtimeClass:
        f:psp:
          .:
          f:enabled:
        f:toolkit:
          .:
          f:enabled:
          f:env:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:validator:
          .:
          f:image:
          f:imagePullPolicy:
          f:plugin:
            .:
            f:env:
          f:repository:
          f:version:
    Manager:      helm
    Operation:    Update
    Time:         2022-09-21T17:05:40Z
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:dcgmExporter:
          f:env:
    Manager:         kubectl-patch
    Operation:       Update
    Time:            2022-09-28T19:46:07Z
  Resource Version:  27149201
  UID:               f9977396-1221-4779-90fe-7a298478bedd
Spec:
  Daemonsets:
    Priority Class Name:  system-node-critical
    Tolerations:
      Effect:    NoSchedule
      Key:       nvidia.com/gpu
      Operator:  Exists
  Dcgm:
    Enabled:            false
    Host Port:          5555
    Image:              dcgm
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            2.4.5-1-ubuntu20.04
  Dcgm Exporter:
    Env:
      Name:             DCGM_EXPORTER_LISTEN
      Value:            :9400
      Name:             DCGM_EXPORTER_KUBERNETES
      Value:            true
      Name:             DCGM_EXPORTER_COLLECTORS
      Value:            /etc/dcgm-exporter/dcp-metrics-included.csv
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            localhost:5555
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            embedded
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            $hostname:5555
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            localhost:5555
    Image:              dcgm-exporter
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/k8s
    Version:            2.4.5-2.6.7-ubuntu20.04
  Device Plugin:
    Config:
      Default:
      Name:     time-slicing-config
    Env:
      Name:             PASS_DEVICE_SPECS
      Value:            true
      Name:             FAIL_ON_INIT_ERROR
      Value:            true
      Name:             DEVICE_LIST_STRATEGY
      Value:            envvar
      Name:             DEVICE_ID_STRATEGY
      Value:            uuid
      Name:             NVIDIA_VISIBLE_DEVICES
      Value:            all
      Name:             NVIDIA_DRIVER_CAPABILITIES
      Value:            all
    Image:              k8s-device-plugin
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia
    Version:            v0.12.2-ubi8
  Driver:
    Cert Config:
      Name:
    Enabled:            true
    Image:              driver
    Image Pull Policy:  IfNotPresent
    Kernel Module Config:
      Name:
    Licensing Config:
      Config Map Name:
      Nls Enabled:      false
    Manager:
      Env:
        Name:             ENABLE_AUTO_DRAIN
        Value:            true
        Name:             DRAIN_USE_FORCE
        Value:            false
        Name:             DRAIN_POD_SELECTOR_LABEL
        Value:
        Name:             DRAIN_TIMEOUT_SECONDS
        Value:            0s
        Name:             DRAIN_DELETE_EMPTYDIR_DATA
        Value:            false
      Image:              k8s-driver-manager
      Image Pull Policy:  IfNotPresent
      Repository:         nvcr.io/nvidia/cloud-native
      Version:            v0.4.1
    Rdma:
      Enabled:         false
      Use Host Mofed:  false
    Repo Config:
      Config Map Name:
    Repository:         nvcr.io/nvidia
    Rolling Update:
      Max Unavailable:  1
    Version:            515.48.07
    Virtual Topology:
      Config:
  Gfd:
    Env:
      Name:             GFD_SLEEP_INTERVAL
      Value:            60s
      Name:             GFD_FAIL_ON_INIT_ERROR
      Value:            true
    Image:              gpu-feature-discovery
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia
    Version:            v0.6.1-ubi8
  Mig:
    Strategy:  single
  Mig Manager:
    Config:
      Name:
    Enabled:  true
    Env:
      Name:   WITH_REBOOT
      Value:  false
    Gpu Clients Config:
      Name:
    Image:              k8s-mig-manager
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            v0.4.2-ubuntu20.04
  Node Status Exporter:
    Enabled:            false
    Image:              gpu-operator-validator
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            v1.11.1
  Operator:
    Default Runtime:  containerd
    Init Container:
      Image:              cuda
      Image Pull Policy:  IfNotPresent
      Repository:         nvcr.io/nvidia
      Version:            11.6.0-base-ubi8
    Runtime Class:        nvidia
  Psp:
    Enabled:  false
  Toolkit:
    Enabled:  true
    Env:
      Name:             CONTAINERD_CONFIG
      Value:            /var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl
      Name:             CONTAINERD_SOCKET
      Value:            /run/k3s/containerd/containerd.sock
    Image:              container-toolkit
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/k8s
    Version:            v1.10.0-ubuntu20.04
  Validator:
    Image:              gpu-operator-validator
    Image Pull Policy:  IfNotPresent
    Plugin:
      Env:
        Name:    WITH_WORKLOAD
       Value:   true
    Repository:  nvcr.io/nvidia/cloud-native
    Version:     v1.11.1
Events:          <none>

**Comment by shivamerla** [comment]
```      
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            localhost:5555
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            embedded
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            $hostname:5555
      Name:             DCGM_REMOTE_HOSTENGINE_INFO
      Value:            localhost:5555```

not sure why these are added with exporter, can you remove them from clusterpolicy, by default it will use embedded host-engine. Also on the other node(where all other pods are failing) looks like driver install is not successful. Can you run "sudo chroot /run/nvidia/driver nvidia-smi" from that node.

**Comment by sasajl** [comment]
Thanks!

I’ll give it a try.

For the second node: it’s ok. I don’t have the rtx-6000 configuration in place, so it fails… it’s straightforward to fix.
________________________________

**Comment by sasajl** [comment]
that worked. Thanks! I used the Rancher UI to edit these env's out.
