### ISSUE TITLE
Unable to pull driver image: not found

### ISSUE THREAD

**Issue by Zubnix** [NVIDIA/gpu-operator#418]
The nvidia-driver-daemonset pod fails to start:
`Failed to pull image "nvcr.io/nvidia/driver:515.65.01-buildroot2021.02.12": rpc error: code = NotFound desc = failed to pull and unpack image "nvcr.io/nvidia/driver:515.65.01-buildroot2021.02.12": failed to resolve reference "nvcr.io/nvidia/driver:515.65.01-buildroot2021.02.12": nvcr.io/nvidia/driver:515.65.01-buildroot2021.02.12: not found`

The command used to deploy was `helm install --wait --generate-name -n gpu-operator --create-namespace nvidia/gpu-operator`

**Comment by shivamerla** [comment]
@Zubnix We only publish driver images for supported OS distributions [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/platform-support.html#supported-operating-systems-and-kubernetes-platforms).

**Comment by Zubnix** [comment]
oh ic, yeah that makes sense!
