### ISSUE TITLE
nvidia-driver-daemonset reinstall gpu driver when gpu node restarts

### ISSUE THREAD

**Issue by carlwang87** [NVIDIA/gpu-operator#424]
There is a node called node1 with gpu installed gpu operator successfully, and gpu driver installed successfully, when I restart the node1, I find the nvidia-driver-daemonset reinstall gpu driver. 

So is there some solution or configuation in gpu operator to avoid to reinstall gpu driver?

Thanks.

**Comment by shivamerla** [comment]
@carlwang87 Unfortunately this is the limitation today as no driver files get installed onto the host filesystem itself. They will be bind mounted from the driver container. So we would have to re-install and re-mount to make all driver files accessible for the container-toolkit to inject into GPU apps. We will explore to persist driver module files and config onto the host filesystem with a configurable option.

**Comment by carlwang87** [comment]
@shivamerla  Thank you very much!
