### ISSUE TITLE
DCGM exporter NodePort vs ClusterIP

### ISSUE THREAD

**Issue by dcarrion87** [NVIDIA/gpu-operator#439]
We traditionally had dcgm-exporter sitting on our A100 nodes directly.

With move to kubernetes we're wanting to leverage the dcgm-exporter that comes baked with the gpu-operator. We noticed the service is set to ClusterIP as opposed to NodePort and I can't see an obvious way to override this config.

What's the general best practice here for this implementation. I could always add an additional service with NodePort but wanted to ask first. Should we look to have a Prometheus instance in cluster and leverage that instead? How does this handle with multi node?

I have read through [this](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#custom-metrics-config) and it essentially talks of having a prometheus system in cluster whereas ours lives outside. 

Any thoughts welcomed.

**Comment by whnbaek** [comment]
I'm currently suffering from the same problem that you wrote above. Is there any way to expose dcgm-exporter outside so that my Prometheus instance on EKS can access to the exporter?

**Comment by likku123** [comment]
+1
