### ISSUE TITLE
Enhancements - nvidia-dcgm-exporter

### ISSUE THREAD

**Issue by BarthV** [NVIDIA/gpu-operator#44]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node? :heavy_check_mark: 
- [x] Are you running Kubernetes v1.13+? :heavy_check_mark: **(1.17.2)**
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? :heavy_check_mark: **(19.03.8)**
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? :heavy_check_mark: 
- [x] Did you apply the CRD (`kubectl describe specialresources --all-namespaces`) :heavy_check_mark: 

### 1. Issue or feature description
RFE : 
* capability to disable nvidia-dcgm-exporter using a chart variable
* defining a http port to nvidia-dcgm-exporter daemontset specs (currently there's no port set at all)
* adding a serviceMonitor together with the exporter (disabled by default)

### 2. Information to attach
`kubectl describe daemonsets.apps -n gpu-operator-resources nvidia-dcgm-exporter`
```
Name:           nvidia-dcgm-exporter
Selector:       app=nvidia-dcgm-exporter
Node-Selector:  feature.node.kubernetes.io/pci-10de.present=true
Labels:         app=nvidia-dcgm-exporter
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 1
Number of Nodes Misscheduled: 0
Pods Status:  1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=nvidia-dcgm-exporter
  Annotations:      scheduler.alpha.kubernetes.io/critical-pod: 
  Service Account:  nvidia-dcgm-exporter
  Containers:
   pod-nvidia-gpu-metrics-exporter:
    Image:        nvidia/pod-gpu-metrics-exporter:v1.0.0-alpha
    Port:         <none>
    Host Port:    <none>
    Readiness:    http-get http://:9400/gpu/metrics delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /run/prometheus from device-metrics (ro)
      /var/lib/kubelet/pod-resources from pod-gpu-resources (ro)
   nvidia-dcgm-exporter:
    Image:        nvidia/dcgm-exporter:1.0.0-beta-ubuntu18.04
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /run/prometheus from device-metrics (rw)
  Volumes:
   pod-gpu-resources:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pod-resources
    HostPathType:  
   device-metrics:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
```

**Comment by RenaudWasTaken** [comment]
Hello!

This is definitely part of the plan, though I'm interested in why you would want to change the port :) ?

**Comment by nvjmayo** [comment]
The ability to set the port has been added to gpu-monitoring-tools as DCGM_EXPORTER_LISTEN and gpu-operator sets this from .Values.service.port see deployment/dcgm-exporter/values.yaml for an example.

**Comment by boniek83** [comment]
There is still no ServiceMonitor for dcgm-exporter...

**Comment by shivamerla** [comment]
@boniek83 We currently create ServiceMonitor by default only with OpenShift as necessary CRD's are already present. With K8s, user would need to install required CRD's and create ServiceMonitor resources. It should be done part of Prometheus setup.

**Comment by boniek83** [comment]
> @boniek83 We currently create ServiceMonitor by default only with OpenShift as necessary CRD's are already present. With K8s, user would need to install required CRD's and create ServiceMonitor resources. It should be done part of Prometheus setup.

Since descriptor is already there it would be great to have ServiceMonitor behind some sort of helm flag eg. dcgmExporter.serviceMonitor.enabled = true. It could be be disabled by default. Since my kubernetes cluster is not OpenShift but already has prometheus-operator it would be a time saver.

**Comment by shivamerla** [comment]
@boniek83 Sure, will look into adding this.
