### ISSUE TITLE
Nvidia T4 GPU Model shown as unknown

### ISSUE THREAD

**Issue by Alwinator** [NVIDIA/gpu-operator#445]
### 1. Quick Debug Checklist
* Are you running on an Ubuntu 18.04 node? No, I am running **Red Hat Enterprise Linux CoreOS 410.84.202209231843-0**
* Are you running Kubernetes v1.13+? Yes, I am running **OpenShift 4.10.35** with **Kubernetes 1.23**
* Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? Yes, **CRI-O 1.23.3-17.rhaos4.10.git016b1ca.el8**
* GPU Operator version: 22.9.0

### 1. Issue or feature description
For our clients, we need to add a label including the GPU model to our OpenShift Nodes. To do that, we use an in-house tool that reads the `/proc/driver/nvidia/gpus/X/information` file. That worked very well for a long time, however, after updating our OpenShift Clusters to the GPU Operator 22.9.0 we noticed that our Nvidia T4 GPUs are shown as Unknown:

```
cat /proc/driver/nvidia/gpus/0000\:XX\:00.0/information
Model:           Unknown
IRQ:             272
GPU UUID:        GPU-XXX
Video BIOS:      90.04.38.00.03
Bus Type:        PCIe
DMA Size:        47 bits
DMA Mask:        0x7fffffffffff
Bus Location:    0000:XX:00.0
Device Minor:    0
GPU Firmware:    515.65.01
GPU Excluded:    No 
```

We have not seen this problem with Nvidia A30 and Nvidia A100 cards so far.

### 2. Steps to reproduce the issue
1. Setup an OpenShift cluster with the version above
2. Add nodes with the Tesla-T4
3. Install the GPU operator
4. Run `cat /proc/driver/nvidia/gpus/0000:XX:00.0/information` on the node

Expected output: Model: Nvidia-T4
Actual Output: Model: Unknown

### 3. Information to attach
- All pods in the Nvidia GPU Operator namespace are running without errors in the logs

**Comment by shivamerla** [comment]
@Alwinator can you check the node labels added by the `gpu-feature-discovery` (GFD) pod and see if it matches? Below are the labels added by GFD for e.g.

```
                    nvidia.com/cuda.driver.major=470
                    nvidia.com/cuda.driver.minor=141
                    nvidia.com/cuda.driver.rev=03
                    nvidia.com/cuda.runtime.major=11
                    nvidia.com/cuda.runtime.minor=4
                    nvidia.com/gfd.timestamp=1668541005
                    nvidia.com/gpu.compute.major=7
                    nvidia.com/gpu.compute.minor=5
                    nvidia.com/gpu.count=1
                    nvidia.com/gpu.family=turing
                    nvidia.com/gpu.machine=g4dn.xlarge
                    nvidia.com/gpu.memory=15109
                    nvidia.com/gpu.present=true
                    nvidia.com/gpu.product=Tesla-T4
                    nvidia.com/gpu.replicas=1
                    nvidia.com/mig.capable=false
                    nvidia.com/mig.strategy=single
```

**Comment by Alwinator** [comment]
Thank you very much that fixes our issue.

**Comment by Alwinator** [comment]
After a long investigation, we realized that there are nodes that don't contain the gpu.model label. They only contain the following labels from Nvidia:

    nvidia.com/gpu.deploy.dcgm-exporter: 'true'
    nvidia.com/gpu.deploy.device-plugin: 'true'
    nvidia.com/gpu.deploy.nvsm: ''
    nvidia.com/gpu.deploy.dcgm: 'true'
    nvidia.com/gpu.deploy.driver: 'true'
    nvidia.com/gpu.deploy.operator-validator: 'true'
    nvidia.com/gpu.deploy.container-toolkit: 'true'
    nvidia.com/gpu.deploy.gpu-feature-discovery: 'true'
    nvidia.com/gpu.deploy.node-status-exporter: 'true'
    nvidia.com/gpu.present: 'true'
    
@shivamerla Any idea why that could be the case?

**Comment by shivamerla** [comment]
Can you check if `gpu-feature-discovery` pod is running?
