### ISSUE TITLE
Hello, does the defaultruntime set by gpu-operator affect other pods running on this node?

### ISSUE THREAD

**Issue by SakuraAxy** [NVIDIA/gpu-operator#450]
Hello, does the defaultruntime set by gpu-operator affect other containers running on this node?

**Comment by shivamerla** [comment]
@SakuraAxy No, it doesn't affect other containers which doesn't request for GPUs. nvidia-container-runtime will fallback to `runc` for those containers. This is decided based on the env `NVIDIA_VISIBLE_DEVICES` set for the container (which all cuda images have). This env is also set when a GPU resource request is made through the Pod spec. @elezar or @klueska can provide more details.

**Comment by SakuraAxy** [comment]
> @SakuraAxy不，它不会影响其他不请求 GPU 的容器。nvidia-container-runtime 将回退到这些容器。这是根据容器的环境集（所有 cuda 图像都具有）决定的。当通过 Pod 规范发出 GPU 资源请求时，也会设置此 env@elezar或者@klueska可以提供更多详细信息。`runc``NVIDIA_VISIBLE_DEVICES`

Thanks, @elezar @klueska can provide more details?

**Comment by SakuraAxy** [comment]
> @SakuraAxy No, it doesn't affect other containers which doesn't request for GPUs. nvidia-container-runtime will fallback to `runc` for those containers. This is decided based on the env `NVIDIA_VISIBLE_DEVICES` set for the container (which all cuda images have). This env is also set when a GPU resource request is made through the Pod spec. @elezar or @klueska can provide more details.

Thanks, @elezar  @klueska can provide more details?

**Comment by SakuraAxy** [comment]
> While the default runtime set by the GPU Operator does technically affect other containers, @shivamerla is correct that as long as these do not have the `NVIDIA_VISIBLE_DEVICES` set there should be no effect on their behaviour.
> 
> A detailed description of what happens. Having the `nvidia-container-runtime` set as the default container runtime will mean that this runtime is used for _all_ containers. By default, this runtime is a shim that injects the NVIDIA Container Runtime hook (`nvidia-container-runtime-hook`) as a `prestart` hook into the OCI runtime specification of the container being started before forwarding the create container request to `runc`. This hook is run by `runc` for all containers, but if the `NVIDIA_VISIBLE_DEVICES` is not set (or is `void`), the hook is a no-op. If the `NVIDIA_VISIBLE_DEVICES` environment variable is set, then the NVIDIA Container CLI is invoked to ensure that the requested devices and driver libraries, binaries, and IPC sockets are injected into the container.
> 
> If you would like more control over how containers are being launched and are using `containerd`, the recommendation is to make use of Runtime Classes to specifically select the NVIDIA Container Runtime for containers where these resources are required.

Thank you for the careful introduction, thanks again!
