### ISSUE TITLE
Chcon command fails in nvidia-driver init - nvidia driver installation aborts

### ISSUE THREAD

**Issue by snirkatriel** [NVIDIA/gpu-operator#452]
### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? RHEL 8.6
- [ ] Are you running Kubernetes v1.13+? v.1.19 (k3s)
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? CRIO
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? 
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`) Yes

### 1. Issue or feature description
When installing gpu-operator on my k3s environment on RHEL 8.6, I'm getting this error and then nvidia-driver init fails:
`Change device files security context for selinux compatibility
chcon: can't apply partial context to unlabeled file 'nvidia-modeset'
chcon: can't apply partial context to unlabeled file 'nvidia0'
chcon: can't apply partial context to unlabeled file 'nvidiactl'
chcon: can't apply partial context to unlabeled file 'core'
chcon: can't apply partial context to unlabeled file 'stderr'
chcon: can't apply partial context to unlabeled file 'stdout'
chcon: can't apply partial context to unlabeled file 'stdin'
chcon: can't apply partial context to unlabeled file 'fd'
chcon: can't apply partial context to unlabeled file 'ptmx'
chcon: can't apply partial context to unlabeled file 'zero'
chcon: can't apply partial context to unlabeled file 'vhost-vsock'
chcon: can't apply partial context to unlabeled file 'vhost-net'
chcon: can't apply partial context to unlabeled file 'vhci'
chcon: can't apply partial context to unlabeled file 'vga_arbiter'
chcon: can't apply partial context to unlabeled file 'vfio'
chcon: can't apply partial context to unlabeled file 'vfio'
chcon: can't apply partial context to unlabeled file 'vcsa6'
chcon: can't apply partial context to unlabeled file 'vcsa1'
chcon: can't apply partial context to unlabeled file 'vcsa'
chcon: can't apply partial context to unlabeled file 'vcs6'
chcon: can't apply partial context to unlabeled file 'vcs1'
chcon: can't apply partial context to unlabeled file 'vcs'
chcon: can't apply partial context to unlabeled file 'usbmon0'
chcon: can't apply partial context to unlabeled file 'urandom'
chcon: can't apply partial context to unlabeled file 'uinput'
chcon: can't apply partial context to unlabeled file 'uhid'
chcon: can't apply partial context to unlabeled file 'ttyS3'
chcon: can't apply partial context to unlabeled file 'ttyS2'
chcon: can't apply partial context to unlabeled file 'ttyS1'
chcon: can't apply partial context to unlabeled file 'ttyS0'
chcon: can't apply partial context to unlabeled file 'tty9'
chcon: can't apply partial context to unlabeled file 'tty8'
chcon: can't apply partial context to unlabeled file 'tty7'
chcon: can't apply partial context to unlabeled file 'tty63'
chcon: can't apply partial context to unlabeled file 'tty62'
chcon: can't apply partial context to unlabeled file 'tty61'
chcon: can't apply partial context to unlabeled file 'tty60'
chcon: can't apply partial context to unlabeled file 'tty6'
chcon: can't apply partial context to unlabeled file 'tty59'
chcon: can't apply partial context to unlabeled file 'tty58'
chcon: can't apply partial context to unlabeled file 'tty57'
chcon: can't apply partial context to unlabeled file 'tty56'
chcon: can't apply partial context to unlabeled file 'tty55'
chcon: can't apply partial context to unlabeled file 'tty54'
chcon: can't apply partial context to unlabeled file 'tty53'
chcon: can't apply partial context to unlabeled file 'tty52'
chcon: can't apply partial context to unlabeled file 'tty51'
chcon: can't apply partial context to unlabeled file 'tty50'
chcon: can't apply partial context to unlabeled file 'tty5'
chcon: can't apply partial context to unlabeled file 'tty49'
chcon: can't apply partial context to unlabeled file 'tty48'
chcon: can't apply partial context to unlabeled file 'tty47'
chcon: can't apply partial context to unlabeled file 'tty46'
chcon: can't apply partial context to unlabeled file 'tty45'
chcon: can't apply partial context to unlabeled file 'tty44'
chcon: can't apply partial context to unlabeled file 'tty43'
chcon: can't apply partial context to unlabeled file 'tty42'
chcon: can't apply partial context to unlabeled file 'tty41'
chcon: can't apply partial context to unlabeled file 'tty40'
chcon: can't apply partial context to unlabeled file 'tty4'
chcon: can't apply partial context to unlabeled file 'tty39'
chcon: can't apply partial context to unlabeled file 'tty38'
chcon: can't apply partial context to unlabeled file 'tty37'
chcon: can't apply partial context to unlabeled file 'tty36'
chcon: can't apply partial context to unlabeled file 'tty35'
chcon: can't apply partial context to unlabeled file 'tty34'
chcon: can't apply partial context to unlabeled file 'tty33'
chcon: can't apply partial context to unlabeled file 'tty32'
chcon: can't apply partial context to unlabeled file 'tty31'
chcon: can't apply partial context to unlabeled file 'tty30'
chcon: can't apply partial context to unlabeled file 'tty3'
chcon: can't apply partial context to unlabeled file 'tty29'
chcon: can't apply partial context to unlabeled file 'tty28'
chcon: can't apply partial context to unlabeled file 'tty27'
chcon: can't apply partial context to unlabeled file 'tty26'
chcon: can't apply partial context to unlabeled file 'tty25'
chcon: can't apply partial context to unlabeled file 'tty24'
chcon: can't apply partial context to unlabeled file 'tty23'
chcon: can't apply partial context to unlabeled file 'tty22'
chcon: can't apply partial context to unlabeled file 'tty21'
chcon: can't apply partial context to unlabeled file 'tty20'
chcon: can't apply partial context to unlabeled file 'tty2'
chcon: can't apply partial context to unlabeled file 'tty19'
chcon: can't apply partial context to unlabeled file 'tty18'
chcon: can't apply partial context to unlabeled file 'tty17'
chcon: can't apply partial context to unlabeled file 'tty16'
chcon: can't apply partial context to unlabeled file 'tty15'
chcon: can't apply partial context to unlabeled file 'tty14'
chcon: can't apply partial context to unlabeled file 'tty13'
chcon: can't apply partial context to unlabeled file 'tty12'
chcon: can't apply partial context to unlabeled file 'tty11'
chcon: can't apply partial context to unlabeled file 'tty10'
chcon: can't apply partial context to unlabeled file 'tty1'
chcon: can't apply partial context to unlabeled file 'tty0'
chcon: can't apply partial context to unlabeled file 'tty'
chcon: can't apply partial context to unlabeled file 'timer'
chcon: can't apply partial context to unlabeled file 'seq'
chcon: can't apply partial context to unlabeled file 'snd'
chcon: can't apply partial context to unlabeled file 'snapshot'
chcon: can't apply partial context to unlabeled file 'rtc0'
chcon: can't apply partial context to unlabeled file 'rawctl'
chcon: can't apply partial context to unlabeled file 'raw'
chcon: can't apply partial context to unlabeled file 'random'
chcon: can't apply partial context to unlabeled file 'ppp'
chcon: can't apply partial context to unlabeled file 'port'
chcon: can't apply partial context to unlabeled file 'nvram'
chcon: can't apply partial context to unlabeled file 'nvme1n1'
chcon: can't apply partial context to unlabeled file 'nvme1'
chcon: can't apply partial context to unlabeled file 'nvme0n1p2'
chcon: can't apply partial context to unlabeled file 'nvme0n1p1'
chcon: can't apply partial context to unlabeled file 'nvme0n1'
chcon: can't apply partial context to unlabeled file 'nvme0'
chcon: can't apply partial context to unlabeled file 'null'
chcon: can't apply partial context to unlabeled file 'ng1n1'
chcon: can't apply partial context to unlabeled file 'ng0n1'
chcon: can't apply partial context to unlabeled file 'tun'
chcon: can't apply partial context to unlabeled file 'net'
chcon: can't apply partial context to unlabeled file 'mem'
chcon: can't apply partial context to unlabeled file 'mcelog'
chcon: can't apply partial context to unlabeled file 'control'
chcon: can't apply partial context to unlabeled file 'mapper'
chcon: can't apply partial context to unlabeled file 'loop-control'
chcon: can't apply partial context to unlabeled file 'kmsg'
chcon: can't apply partial context to unlabeled file 'mouse0'
chcon: can't apply partial context to unlabeled file 'mice'
chcon: can't apply partial context to unlabeled file 'event3'
chcon: can't apply partial context to unlabeled file 'event2'
chcon: can't apply partial context to unlabeled file 'event1'
chcon: can't apply partial context to unlabeled file 'event0'
chcon: can't apply partial context to unlabeled file 'input'
chcon: can't apply partial context to unlabeled file 'hwrng'
chcon: can't apply partial context to unlabeled file 'hpet'
chcon: can't apply partial context to unlabeled file 'fuse'
chcon: can't apply partial context to unlabeled file 'full'
chcon: can't apply partial context to unlabeled file 'cpu_dma_latency'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '9'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '8'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '7'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '6'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '5'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '4'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '3'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '2'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '15'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '14'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '13'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '12'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '11'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '10'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '1'
chcon: can't apply partial context to unlabeled file 'msr'
chcon: can't apply partial context to unlabeled file 'cpuid'
chcon: can't apply partial context to unlabeled file '0'
chcon: can't apply partial context to unlabeled file 'cpu'
chcon: can't apply partial context to unlabeled file 'autofs'
chcon: can't apply partial context to unlabeled file 'termination-log'
chcon: can't apply partial context to unlabeled file 'log'
chcon: can't apply partial context to unlabeled file 'shm'
chcon: failed to get security context of 'mqueue': Operation not supported
chcon: failed to get security context of '0': Operation not supported
chcon: failed to get security context of 'ptmx': Operation not supported
chcon: failed to get security context of 'pts': Operation not supported
chcon: can't apply partial context to unlabeled file '/run/nvidia/driver/dev'
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...`

SElinux is disabled in my environment, and the `chcon` command seems to be not functional due to this fact.
When commenting this line in nvidia-driver script, it seems to work well and all other pods are running:
`#    echo "Change device files security context for selinux compatibility"
  #chcon -R -t container_file_t ${RUN_DIR}/driver/dev`

### 2. Steps to reproduce the issue
Run gpu-operator on SElinux enabled env.

**Comment by snirkatriel** [comment]
Hi guys, Is there a change to get a comment on this?

**Comment by cdesiniotis** [comment]
@snirkatriel yes this is a known limitation which we have documented here: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-default-configurations-on-red-hat-enterprise-linux.
SELinux has to be enabled (either in `permissive` or `enforcing` mode).

**Comment by cdesiniotis** [comment]
To remove this limitation, we would need to check if SELinux is enabled on the system first prior to changing any security contexts. Contributions are welcome here if you are interested: https://gitlab.com/nvidia/container-images/driver

**Comment by snirkatriel** [comment]
@cdesiniotis https://gitlab.com/nvidia/container-images/driver/-/merge_requests/208 👍
