### ISSUE TITLE
no matches for kind "ServiceMonitor" in version "monitoring.coreos

### ISSUE THREAD

**Issue by Kry1702** [NVIDIA/gpu-operator#453]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?  CentOS 7.6 
- [ ] Are you running Kubernetes v1.13+?  Kubernetes v1.24.4
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?  containerd v1.5.5

### 1. Issue or feature description
```
kubectl apply -f 0700_service_monitor_openshift.yaml
error: resource mapping not found for name: "nvidia-dcgm-exporter" namespace: "default" from "0700_service_monitor_openshift.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

### 2. Steps to reproduce the issue
install dcgm exporter
```
git clone -b release-1.11 https://github.com/NVIDIA/gpu-operator.git
cd gpu-operator/assets/state-dcgm-exporter
```
modify Yaml file
modify namespace
```
find . -name "*.yaml" -exec  sed  -i  "s#FILLED\ BY\ THE\ OPERATOR#default#g" {} \;
```
modify images
```
vi ./0900_daemonset.yaml
The toolkit-validation images mirror changed to nvidia/samples:vectoradd-cuda11.6.0-ubi8
The nvidia-dcgm-exporter images mirror changed to nvidia/dcgm-exporter:3.0.4-3.0.0-ubuntu20.04
```
deployment service
```
kubectl apply -f 0100_service_account.yaml
kubectl apply -f 0200_role.yaml
kubectl apply -f 0300_rolebinding.yaml
kubectl apply -f 0400_prom_role_openshift.yaml
kubectl apply -f 0500_prom_rolebinding_openshift.yaml
kubectl apply -f 0600_service.yaml
kubectl apply -f 0700_service_monitor_openshift.yaml
error: resource mapping not found for name: "nvidia-dcgm-exporter" namespace: "default" from "0700_service_monitor_openshift.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

Note: Prior to this the host has completed the following steps:
1. Graphics card driver installation;
2. nvidia-container-toolkit installation and containerd configuration modification
3. Kubernetes cluster installation
4. NVIDIA Device Plugin Installation
5. Prometheus and Grafana installation

**Comment by shivamerla** [comment]
@Kry1702 Did you configure Prometheus before enabling ServiceMonitor through operator manifests? It is a pre-requisite to install below CRD's before this:

https://github.com/helm/charts/tree/master/stable/prometheus-operator/crds

**Comment by shivamerla** [comment]
Closing this as expected, please re-open if you see other issues.
