### ISSUE TITLE
gpu operator vs special resource operator for Openshift 4

### ISSUE THREAD

**Issue by przem123** [NVIDIA/gpu-operator#46]
The GPU operator seems to be available for Openshift 4. I am already using Special Resource Operator from Redhat (https://github.com/openshift-psap/special-resource-operator). Is your operator something different? Or is it a helm wrapper for the SRO ?

**Comment by nvjmayo** [comment]
Although they are independent implementation, both gpu-operator and special-resource-operator use many of the same components: nvidia-container-toolkit, gpu-feature-discovery, and NFD. 

If you're only interested in GPUs then either operator can work. In the future special-resource-operator might support for non-GPU resources. For now, gpu-operator's goals are to get more cutting edge GPU related functionality.
