### ISSUE TITLE
Changing MIG strategy while Kubernetes cluster and gpu-operator running

### ISSUE THREAD

**Issue by esparig** [NVIDIA/gpu-operator#460]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
Here my previous issue configuring the gpu-operator (https://github.com/NVIDIA/gpu-operator/issues/442)
Kubernetes 1.23.7
Ubuntu 20.04
Docker 19.3.11
gpu-operator v22.9.0 deployed via helm
Node with an NVIDIA A30 GPU

### 1. Issue or feature description
Now, I want to change from mixed (1-1-2) strategy to single ( all-4g.24gb) to do some tests, I tried editing the values of the chart from:
```
mig:
  strategy: mixed
```
 to:
```
mig:
  strategy: single
```
But I get the following error in the nvidia-device-plugin-daemonset Pod:
```
2022/12/15 12:28:28 Retreiving plugins.
panic: At least one device with migEnabled=true was not configured correctly: More than one MIG device type present on node

goroutine 1 [running]:
main.(*migStrategySingle).GetPlugins(0xc0001321b0)
	/build/cmd/nvidia-device-plugin/mig-strategy.go:87 +0x336
main.startPlugins(0xc0001e7c58?, {0xc000258460, 0x9, 0xe}, 0x9?)
	/build/cmd/nvidia-device-plugin/main.go:247 +0x4bd
main.start(0x10d7b20?, {0xc000258460, 0x9, 0xe})
	/build/cmd/nvidia-device-plugin/main.go:147 +0x355
main.main.func1(0xc000258460?)
	/build/cmd/nvidia-device-plugin/main.go:43 +0x32
github.com/urfave/cli/v2.(*App).RunContext(0xc000264b60, {0xca9328?, 0xc00019c020}, {0xc0001801f0, 0x1, 0x1})
	/build/vendor/github.com/urfave/cli/v2/app.go:322 +0x953
github.com/urfave/cli/v2.(*App).Run(...)
	/build/vendor/github.com/urfave/cli/v2/app.go:224
main.main()
	/build/cmd/nvidia-device-plugin/main.go:91 +0x665
2022/12/15 12:33:43 Starting FS watcher.
2022/12/15 12:33:43 Starting OS watcher.
```
Not sure how I should change the MIG configuration, or if is even possible. Thx.

**Comment by cdesiniotis** [comment]
@esparig can you apply the `all-4g.24gb` configuration first before changing the `mig.strategy`:
```
$ kubectl label node <node-name> nvidia.com/mig.config=all-4g.24gb 
````
Once the `mig-manager` pod has finished reconfiguring MIG, the node will be labelled with `nvidia.com/mig.status=success`. Then you can change from `mixed` to `single` strategy.

**Comment by esparig** [comment]
It worked perfectly well. Thank you!
