### ISSUE TITLE
Cluster policy templating broken with default values

### ISSUE THREAD

**Issue by danmx** [NVIDIA/gpu-operator#461]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

During my deployment I'm getting this error:

```
ClusterPolicy.nvidia.com "cluster-policy" is invalid: spec.devicePlugin.config: Invalid value: "null": spec.devicePlugin.config in body must be of type object: "null"
```

I think it's related to this template:

https://github.com/NVIDIA/gpu-operator/blob/082607342e844d78ea8bd543dac0b01992f78c25/deployments/gpu-operator/templates/clusterpolicy.yaml#L357

and those default values:

https://github.com/NVIDIA/gpu-operator/blob/082607342e844d78ea8bd543dac0b01992f78c25/deployments/gpu-operator/values.yaml#L205-L207

Basically IF statement it `true` when `config` key exists, completely ignoring the `create` key.

### 2. Steps to reproduce the issue

Use chart version `v22.9.1` with default values.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by danmx** [comment]
Fixing the issue in [Gitlab MR 594](https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/594)

**Comment by shivamerla** [comment]
@danmx the idea was to use `config.create` and `config.data` only to create a ConfigMap during helm install, those need not be added to ClusterPolicy instance. When we install with default values as `config` object is nil we don't see that created.

```
 $ helm install gpu-operator gpu-operator-v22.9.1.tgz -n gpu-operator

$ kubectl get clusterpolicy -o json | jq '.items[0].spec.devicePlugin'
{
  "enabled": true,
  "env": [
    {
      "name": "PASS_DEVICE_SPECS",
      "value": "true"
    },
    {
      "name": "FAIL_ON_INIT_ERROR",
      "value": "true"
    },
    {
      "name": "DEVICE_LIST_STRATEGY",
      "value": "envvar"
    },
    {
      "name": "DEVICE_ID_STRATEGY",
      "value": "uuid"
    },
    {
      "name": "NVIDIA_VISIBLE_DEVICES",
      "value": "all"
    },
    {
      "name": "NVIDIA_DRIVER_CAPABILITIES",
      "value": "all"
    }
  ],
  "image": "k8s-device-plugin",
  "imagePullPolicy": "IfNotPresent",
  "repository": "nvcr.io/nvidia",
  "version": "v0.13.0-ubi8"
}
```

Can you give me the exact steps that caused this for you? What was the `devicePlugin.config` setting in your case?

**Comment by FredericJames** [comment]
Hello
I have a similar issue on the installation of the gpu operator.
k8s version: 1.24
gpu operator version: v22.9.2

Here's the result:
![image](https://user-images.githubusercontent.com/6051126/226922219-9062b49f-855e-4ae8-ac13-c1de32189e7f.png)

Here's my value file:
![image](https://user-images.githubusercontent.com/6051126/226922393-be50eb4e-ab5d-42e3-a461-0219be0ab867.png)


To make it work I had to add multiple values on driver setup (even if it's disabled)
I had to create a configmap for the devicePlugin too.

Here's my working values file.

![image](https://user-images.githubusercontent.com/6051126/226923577-188d50b8-a874-44bb-9c3f-0d075fb97388.png)

**Comment by shivamerla** [comment]
@FredericJames we will address these in the upcoming release v23.3.0.

**Comment by shivamerla** [comment]
@FredericJames @danmx this has been fixed in `v23.3.0` please try out and re-open this if you still see issue.

**Comment by holdenk** [comment]
I had  helm install --wait --generate-name \
>     -n gpu-operator --create-namespace \
>     nvidia/gpu-operator \
>     --version=v24.9.2
Error: INSTALLATION FAILED: template: gpu-operator/templates/clusterpolicy.yaml:514:53: executing "gpu-operator/templates/clusterpolicy.yaml" at <.Values.dcgmExporter.config.name>: nil pointer evaluating interface {}.name
but it works with 23.3.0 on k3s

**Comment by rtkgupta** [comment]
Running in to the same issue, older version works: `helm install --wait --generate-name \
    -n gpu-operator --create-namespace \
    nvidia/gpu-operator \
    --version=v24.9.2
Error: INSTALLATION FAILED: template: gpu-operator/templates/clusterpolicy.yaml:514:53: executing "gpu-operator/templates/clusterpolicy.yaml" at <.Values.dcgmExporter.config.name>: nil pointer evaluating interface {}.name`

**Comment by cdesiniotis** [comment]
@holdenk @rtkgupta what version of helm are you using? This issue should be fixed in newer versions of helm.
