### ISSUE TITLE
Gpu operator does not work with cri-o user namespaces

### ISSUE THREAD

**Issue by robertdavidsmith** [NVIDIA/gpu-operator#466]
### 1. Quick Debug Checklist
- [] Are you running on an Ubuntu 18.04 node?
- [/] Are you running Kubernetes v1.13+?
- [/] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [/] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [/] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
We have gpu operator working with cri-o on Flatcar Linux and this combination works fine. We are using DEVICE_LIST_STRATEGY volume-mounts.

However enabling user namespaces with annotation `io.kubernetes.cri-o.userns-mode: auto` breaks gpu jobs. The error (visible in describe pod) can be one of three errors
```
Warning  Failed     25s               kubelet, workspaces-01--gpu--node1.ospr-k8s-batch-d.diva-h2.c3.zone  Error: container create failed: time="2023-01-04T09:19:12Z" leve
l=error msg="runc create failed: unable to start container process: error during container init: error creating device nodes: mount /dev/nvidiactl:/var/lib/containers/storag
e/overlay/bd769cb61dcc2ee7ee6c41388d8be8ec897adf68141d763b5f3c057bc907be5d/merged/dev/nvidiactl (via /proc/self/fd/14), flags: 0x1000: no such file or directory"
```

```
  Warning  Failed     10s                kubelet            Error: container create failed: time="2023-01-03T16:47:58Z" level=error 
  msg="runc create failed: 
  unable to start container process: error during container init: 
  error mounting \"tmpfs\" to rootfs at \"/run\": tmpcopyup: failed to copy /run to /proc/self/fd/17 (/tmp/runctop3362038855/runctmpdir3781597208):
  lchown /tmp/runctop3362038855/runctmpdir3781597208/nvidia-container-devices/GPU-e2f48e6b-245c-c81f-487e-93f0632de94e: no such file or directory"
  
```

```
Error: container create failed: time="2023-01-10T15:23:50Z" level=error 
msg="runc create failed: 
unable to start container process: error during container init: error preparing rootfs
: mount /var/lib/containers/storage/overlay/b3b7f38c4a886d8f63621cbd6ddfb66f92b776db971cdd8857c65e5abf326761/merged:
        /var/lib/containers/storage/overlay/b3b7f38c4a886d8f63621cbd6ddfb66f92b776db971cdd8857c65e5abf326761/merged, flags: 0x5000: permission denied"  
```

Interestingly you can reproduce the 2nd error on a machine without gpus or gpu-operator, as long as cri-o userns is enabled. Just mount `/dev/null` to `/var/run/mytest` using a k8s hostPath volume and volumeMount. This error can probably be fixed by changing the volume-mounts dummy hostPath from `/var/run/nvidia-container-devices` to a path not under `/var/run`.

Versions are:
- gpu-operator: 11.6.0-base-ubi8
- container-toolkit: v1.11.0-ubuntu20.04
- k8s: v1.22.13 
- os: Flatcar Linux 3033.2.4
- kernel: 5.10.107-flatcar
- cri-o: 1.22.5

### 2. Steps to reproduce the issue
- Set up k8s with cri-o.
- Set up gpu operator with `DEVICE_LIST_STRATEGY=volume-mounts`. 
- Submit a gpu job with user namespaces enabled (annotation `io.kubernetes.cri-o.userns-mode: auto`).

Example job
```
apiVersion: v1
kind: Pod
metadata:
  name: simple-gpu
  namespace: gpu-operator
  annotations:
    io.kubernetes.cri-o.Devices: /dev/fuse
    io.kubernetes.cri-o.UnifiedCgroup: "true"
    io.kubernetes.cri-o.cgroup2-mount-hierarchy-rw: "true"
    io.kubernetes.cri-o.userns-mode: auto
spec:
  containers:
  - args:
    - -c
    - 'sleep 3600;exit 1'
    command:
    - sh
    image: tensorflow/tensorflow:2.6.0-gpu-jupyter
    imagePullPolicy: IfNotPresent
    name: gputest
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 16Gi
        memory: 32Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "1"
        ephemeral-storage: 16Gi
        memory: 32Gi
        nvidia.com/gpu: "1"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000
```

Thanks,

Rob

**Comment by shivamerla** [comment]
@klueska any thoughts on this?

**Comment by robertdavidsmith** [comment]
This can now be fixed by configuring gpu-operator to use CDI. Closing.
