### ISSUE TITLE
Not able to see DCGM Metrics in prometheus

### ISSUE THREAD

**Issue by harjitdotsingh** [NVIDIA/gpu-operator#467]
I'm installing the operator using the following options
`helm install gpu-operator nvidia/gpu-operator -n gpu-operator \
--set devicePlugin.config.name=time-slicing-config \
--set dcgmExporter.config.name=metrics-config \
--set dcgmExporter.env[0].name=DCGM_EXPORTER_COLLECTORS \
--set dcgmExporter.env[0].value=/etc/dcgm-exporter/dcgm-metrics.csv \
--set extraConfigMapVolumes[0].name=exporter-metrics-volume \
--set extraConfigMapVolumes[0].configMap.name=exporter-metrics-config-map \
--set extraEnv[0].name=DCGM_EXPORTER_CONFIGMAP_DATA \
--set extraEnv[0].value=default:exporter-metrics-volume`

Looking at the logs I see the following

time="2023-01-11T18:03:34Z" level=info msg="Starting dcgm-exporter"
time="2023-01-11T18:03:34Z" level=info msg="DCGM successfully initialized!"
time="2023-01-11T18:03:34Z" level=info msg="Collecting DCP Metrics"
time="2023-01-11T18:03:34Z" level=info msg="No configmap data specified, falling back to metric file /etc/dcgm-exporter/dcgm-metrics.csv"
time="2023-01-11T18:03:34Z" level=info msg="Initializing system entities of type: GPU"
time="2023-01-11T18:03:34Z" level=info msg="Initializing system entities of type: NvSwitch"
time="2023-01-11T18:03:34Z" level=info msg="Not collecting switch metrics: no switches to monitor"
time="2023-01-11T18:03:34Z" level=info msg="Initializing system entities of type: NvLink"
time="2023-01-11T18:03:34Z" level=info msg="Not collecting link metrics: no switches to monitor"
time="2023-01-11T18:03:34Z" level=info msg="Kubernetes metrics collection enabled!"
time="2023-01-11T18:03:34Z" level=info msg="Pipeline starting"
time="2023-01-11T18:03:34Z" level=info msg="Starting webserver"

When I go to port 9090 I don't see that DCGM_FI_DEV_GPU_UTIL in the dropdown as an option.  when I go to  port 9400 and look at the metrics in DCGM I see the following output
`# HELP DCGM_FI_DEV_SM_CLOCK SM clock frequency (in MHz).
# TYPE DCGM_FI_DEV_SM_CLOCK gauge
DCGM_FI_DEV_SM_CLOCK{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 1410
# HELP DCGM_FI_DEV_MEM_CLOCK Memory clock frequency (in MHz).
# TYPE DCGM_FI_DEV_MEM_CLOCK gauge
DCGM_FI_DEV_MEM_CLOCK{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 1512
# HELP DCGM_FI_DEV_MEMORY_TEMP Memory temperature (in C).
# TYPE DCGM_FI_DEV_MEMORY_TEMP gauge
DCGM_FI_DEV_MEMORY_TEMP{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 67
# HELP DCGM_FI_DEV_GPU_TEMP GPU temperature (in C).
# TYPE DCGM_FI_DEV_GPU_TEMP gauge
DCGM_FI_DEV_GPU_TEMP{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 60
# HELP DCGM_FI_DEV_POWER_USAGE Power draw (in W).
# TYPE DCGM_FI_DEV_POWER_USAGE gauge
DCGM_FI_DEV_POWER_USAGE{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 190.839000
# HELP DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION Total energy consumption since boot (in mJ).
# TYPE DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION counter
DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 234436059
# HELP DCGM_FI_DEV_PCIE_REPLAY_COUNTER Total number of PCIe retries.
# TYPE DCGM_FI_DEV_PCIE_REPLAY_COUNTER counter
DCGM_FI_DEV_PCIE_REPLAY_COUNTER{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_GPU_UTIL GPU utilization (in %).
# TYPE DCGM_FI_DEV_GPU_UTIL gauge
DCGM_FI_DEV_GPU_UTIL{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 36
# HELP DCGM_FI_DEV_MEM_COPY_UTIL Memory utilization (in %).
# TYPE DCGM_FI_DEV_MEM_COPY_UTIL gauge
DCGM_FI_DEV_MEM_COPY_UTIL{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 5
# HELP DCGM_FI_DEV_ENC_UTIL Encoder utilization (in %).
# TYPE DCGM_FI_DEV_ENC_UTIL gauge
DCGM_FI_DEV_ENC_UTIL{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_DEC_UTIL Decoder utilization (in %).
# TYPE DCGM_FI_DEV_DEC_UTIL gauge
DCGM_FI_DEV_DEC_UTIL{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_XID_ERRORS Value of the last XID error encountered.
# TYPE DCGM_FI_DEV_XID_ERRORS gauge
DCGM_FI_DEV_XID_ERRORS{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_FB_FREE Framebuffer memory free (in MiB).
# TYPE DCGM_FI_DEV_FB_FREE gauge
DCGM_FI_DEV_FB_FREE{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 80328
# HELP DCGM_FI_DEV_FB_USED Framebuffer memory used (in MiB).
# TYPE DCGM_FI_DEV_FB_USED gauge
DCGM_FI_DEV_FB_USED{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 741
# HELP DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL Total number of NVLink bandwidth counters for all lanes.
# TYPE DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL counter
DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS Number of remapped rows for uncorrectable errors
# TYPE DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS counter
DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS Number of remapped rows for correctable errors
# TYPE DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS counter
DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_DEV_ROW_REMAP_FAILURE Whether remapping of rows has failed
# TYPE DCGM_FI_DEV_ROW_REMAP_FAILURE gauge
DCGM_FI_DEV_ROW_REMAP_FAILURE{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0
# HELP DCGM_FI_PROF_GR_ENGINE_ACTIVE Ratio of time the graphics engine is active (in %).
# TYPE DCGM_FI_PROF_GR_ENGINE_ACTIVE gauge
DCGM_FI_PROF_GR_ENGINE_ACTIVE{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0.268721
# HELP DCGM_FI_PROF_PIPE_TENSOR_ACTIVE Ratio of cycles the tensor (HMMA) pipe is active (in %).
# TYPE DCGM_FI_PROF_PIPE_TENSOR_ACTIVE gauge
DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0.207267
# HELP DCGM_FI_PROF_DRAM_ACTIVE Ratio of cycles the device memory interface is active sending or receiving data (in %).
# TYPE DCGM_FI_PROF_DRAM_ACTIVE gauge
DCGM_FI_PROF_DRAM_ACTIVE{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 0.056517
# HELP DCGM_FI_PROF_PCIE_TX_BYTES The rate of data transmitted over the PCIe bus - including both protocol headers and data payloads - in bytes per second.
# TYPE DCGM_FI_PROF_PCIE_TX_BYTES gauge
DCGM_FI_PROF_PCIE_TX_BYTES{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 48908346
# HELP DCGM_FI_PROF_PCIE_RX_BYTES The rate of data received over the PCIe bus - including both protocol headers and data payloads - in bytes per second.
# TYPE DCGM_FI_PROF_PCIE_RX_BYTES gauge
DCGM_FI_PROF_PCIE_RX_BYTES{gpu="0",UUID="GPU-c89b14a3-ce7c-6725-8424-b55d37d9c332",device="nvidia0",modelName="NVIDIA A100 80GB PCIe",Hostname="nvidia-dcgm-exporter-d2khm",DCGM_FI_DRIVER_VERSION="510.47.03",container="",namespace="",pod=""} 146570071`

Not sure where I'm missing something.

**Comment by shivamerla** [comment]
@harjitdotsingh GPU metrics are exposed through dcgm-exporter service with port 9400 by default. Not sure why you are checking on 9090, is that something you customized? Also below options are not valid for GPU operator chart, the configmap provided will be automatically mounted by the operator into the dcgm-exporter pod.

```
--set extraConfigMapVolumes[0].name=exporter-metrics-volume \ --set extraConfigMapVolumes[0].configMap.name=exporter-metrics-config-map \ --set extraEnv[0].name=DCGM_EXPORTER_CONFIGMAP_DATA \ --set extraEnv[0].value=default:exporter-metrics-volume
```

**Comment by harjitdotsingh** [comment]
@shivamerla  - I'm trying to look at the metrics in Prometheus and hence looking at port 9090. I'm following the instructions which are on this page [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#gpu-telemetry) so I should see the metrics in Prometheus as shown in the example. Hope that makes sense.

**Comment by harjitdotsingh** [comment]
We can close this as I was able to make it work.

**Comment by divyanjali1** [comment]
@harjitdotsingh Can you please share the steps here on how did you make it work ?

**Comment by harjitdotsingh** [comment]
I was looking at the wrong port... So what issues are you having?
