### ISSUE TITLE
Support for Jetson Platfrom( Arm64 )

### ISSUE THREAD

**Issue by zacfpearson** [NVIDIA/gpu-operator#47]
Is there any plan to support the Jetson Platform in the future?

**Comment by turowicz** [comment]
The new announcement website mentions Nano and Xavier support. I hope the Nano part is true.

**Comment by zacfpearson** [comment]
@turowicz interesting! I hope so too. Would you be able to provide a link? I can't find an announcement that mentions that.

**Comment by turowicz** [comment]
It's on the landing page mentioned in Readme.

**Comment by turowicz** [comment]
In this repo: https://github.com/NVIDIA/egx-platform

**Comment by Shaked** [comment]
> In this repo: https://github.com/NVIDIA/egx-platform

Hey @turowicz, where can I find ARM64 support for the GPU operator? I saw Jetson Nano but it requires docker while the x86 allows to use containerd.
