### ISSUE TITLE
Openshift 4.x deployment fails because 'node-feature-discovery' daemonset is using wrong SCC

### ISSUE THREAD

**Issue by nnachefski** [NVIDIA/gpu-operator#48]
Just like $TOPIC says.  Granting the the 'node-feature-discovery' daemonset the 'privileged' SCC fixes the deployment.  Openshift 4.4 pre-release on RHCOS

oc adm policy add-scc-to-user privileged -z gpu-operator-1585286165-node-feature-discovery

`Error creating: pods "gpu-operator-1585286165-node-feature-discovery-worker-" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used `

**Comment by zvonkok** [comment]
@nnachefski If you're running on OpenShift  install NFD operator from  OperatorHub, --set nfd.enabled=false for the chart. The worker does not need the privileged SCC, the OpenShift version of NFD is creating the "right" SCC for the worker.

**Comment by shivamerla** [comment]
This has been fixed from GPU operator 1.3.0 as we use upstream NFD chart bundle now, than in-house copy earlier. For OLM bundle, we have a pre-requisite of NFD operator to be installed prior to deploying GPU operator through RH catalog.
