### ISSUE TITLE
Helm chart v1.0.0 is actually a nightly version

### ISSUE THREAD

**Issue by linkvt** [NVIDIA/gpu-operator#50]
Hi,

it seems that a nightly gpu-operator version was incorrectly tagged as v1.0.0, see the last line:
https://github.com/NVIDIA/gpu-operator/blob/0328060705f5f8c73a030fdd4f66776f7707739a/index.yaml#L4-L19

Proof:
```
 $ helm template --version "v1.0.0" nvidia/gpu-operator | grep nightly -B2
      containers:
      - name: special-resource-operator
        image: nvidia/gpu-operator:1.0.0-nightly-64ae160d
```

I guess this is unintended as the old v1.0.0 is still there and you probably don't plan to retag versions.

BR, Vincent

**Comment by RenaudWasTaken** [comment]
Good catch! I'll take a stab at it today :) !

**Comment by RenaudWasTaken** [comment]
Fixed (a bit late sorry)!

I've split everything in stable and nightly. The root now points to the stable repo :)
