### ISSUE TITLE
Openshift: NVIDIA GPU Operator: nvidia-container-toolkit-daemonset: InvalidImageName

### ISSUE THREAD

**Issue by tormig-softronic** [NVIDIA/gpu-operator#513]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [X] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

Running on Openshift  4.11.25

### 1. Issue or feature description
After an upgrade to 23.3.0 the gpu-cluster-policy fails. 

The nvidia-container-toolkit-daemonset appears to a have an erroneous image tag:

 Failed to apply default image tag "nvcr.io/nvidia/k8s/container-toolkit@sha256:489125ceae5864280e4d6a9ab52ab0f650b3179349a7298c4a204feb60b661a": couldn't parse image reference "nvcr.io/nvidia/k8s/container-toolkit@sha256:489125ceae5864280e4d6a9ab52ab0f650b3179349a7298c4a204feb60b661a": invalid checksum digest length

### 2. Steps to reproduce the issue
Upgrade the operatro to 23.3.0 from 22.9.2, the ClusterPolicy fails to install. Remove the policy and applied a new, it still fails

**Comment by tormig-softronic** [comment]
Adding a "5" in front of the current sha256 it started to work i.e.:

**5**489125ceae5864280e4d6a9ab52ab0f650b3179349a7298c4a204feb60b661a

So perhaps just a typo?

**Comment by arpitsharma-hexad** [comment]
Hello Team, We are also facing the issue. I am afraid that these manual changes will get reconciled by the operator. Can you please suggest some permanent fixes here?
Thanks

**Comment by tormig-softronic** [comment]
You can add this to the ClusterPolicy manifest:

  toolkit:
    image: >-
      nvcr.io/nvidia/k8s/container-toolkit@sha256:5489125ceae5864280e4d6a9ab52ab0f650b3179349a7298c4a204feb60b661a

Then i should stick, but it's still a hack though

**Comment by shivamerla** [comment]
@tormig-softronic thanks for reporting this. Yes this is a typo with the image digest of container-toolkit (v1.13.0) in the [CSV](https://github.com/NVIDIA/gpu-operator/blob/release-23.03/bundle/manifests/gpu-operator-certified.clusterserviceversion.yaml#L162) file. We will fix this. Meanwhile as you did already, the toolkit image have to be overridden in the `ClusterPolicy` instance.

**Comment by shivamerla** [comment]
@tormig-softronic `v23.3.1` patch has been published with the fix, Please verify and re-open if you still see the issue.

**Comment by tormig-softronic** [comment]
@shivamerla I can confirm that it works, thank you.

**Comment by arpitsharma-hexad** [comment]
It works for us as well :)
Thanks
