### ISSUE TITLE
Add priorityClassName to nfd's pods

### ISSUE THREAD

**Issue by boniek83** [NVIDIA/gpu-operator#514]
### 1. Issue or feature description
I would like to set priorityClassName for nfd's pods.
### 2. Steps to reproduce the issue
It is not possible at the moment in the helm chart.

**Comment by shivamerla** [comment]
@ArangoGutierrez another small improvement with NFD.

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery/pull/1587
