### ISSUE TITLE
Rename mig resources 

### ISSUE THREAD

**Issue by maaft** [NVIDIA/gpu-operator#518]
**tl;dr** I want to request just `nvidia.com/gpu` - I don't care about the actual GPU layout.

This is the problem I try to solve:
- I have MIG GPUs and regular GPUs in my cluster
- I need to automatically schedule workloads on my GPUs
- I don't care on which GPU my workload is running
- All GPUs should be fully utilized.

I want to avoid doing manual checks a lá:
> "are all `nvidia.com/mig-1g.10gb` resources allocated? then request `nvidia.com/gpu` for the next job"

since this can lead to race-conditions when multiple jobs are being requested at the same time.

Is it possible to rename mig resources? E.g. `nvidia.com/mig-1g.10gb` -> `nvidia.com/gpu`

Any other solutions?

**Comment by shivamerla** [comment]
You can set `mig.strategy=single` in the `ClusterPolicy` instance and all GPUs will be advertised as `nvidia.com/gpu` resources. This setting is default with the operator.

**Comment by maaft** [comment]
Oh, what about this note in the docs?

```
Note

mig.strategy should be set to mixed when MIG mode is not enabled on all GPUs on a node.
```

Since I have mig- and non-mig-devices in my cluster I thought that I need to use `mixed`. I will try to use `single` and report back.

**Comment by shivamerla** [comment]
That is a general recommendation so that you can assign either MIG instances or full GPU by specific resource name. In your case, looks like that differentiation is not required, so setting to `single` should be fine.

**Comment by maaft** [comment]
okay, thanks! It works!
