### ISSUE TITLE
Changelog for version 1.1.0?

### ISSUE THREAD

**Issue by linkvt** [NVIDIA/gpu-operator#52]
Hi guys,

I just noticed that [version 1.1.0 was released](https://github.com/NVIDIA/gpu-operator/releases/tag/1.1.0) a few days ago, really appreciate the fixes of at least the tickets I opened :).

I wanted to ask, if there is some kind of changelog as the changes are [quite extensive](https://github.com/NVIDIA/gpu-operator/compare/1.0.0...1.1.0) and googling didn't yield anything?

Changelogs are IMO very important as tell me as someone who operates k8s clusters what I need to test and look at, where new issues might appear, of course what new features exist for the end users and if I need to change anything in my configuration.

Thanks in advance,
Vincent

**Comment by RenaudWasTaken** [comment]
It's in progress!
https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/89

**Comment by RenaudWasTaken** [comment]
Merged!
