### ISSUE TITLE
GPU-Operator does not install the specified driver version in AKS GPU Node

### ISSUE THREAD

**Issue by xcheng85** [NVIDIA/gpu-operator#525]
1. Quick Debug Checklist
- [Y] Are you running on an Ubuntu 18.04 node?
- [ ] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ Y] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

1. Issue or feature description
   AKS install the default nvidia driver for gpu node and the gpu operator's driver version config is ignored. 
   
2. Steps to reproduce the issue
    a. create the gpu node pool with az cli
    b. helm install --wait --generate-name --set driver.enabled=true --set driver.version=515.86.01 --set operator.cleanupCRD=true -n gpu-operator --create-namespace nvidia/gpu-operator

    Then  kubectl exec -n gpu-operator nvidia-device-plugin-daemonset-mxfhb -- /usr/bin/nvidia-smi
    It print out the default driver version installed by Azure.

**Comment by shivamerla** [comment]
@xcheng85 The GPU operator cannot override the driver(modules+libs packages) installed on the host filesystem, instead it disables the driver container. That is the only supported way on AKS. Please pass `--set toolkit.enabled=false --set driver.enabled=false --set operator.runtimeClass=nvidia-container-runtime` to get operator working with the bits(container-toolkit/driver) already installed by AKS.

**Comment by sjkoelle** [comment]
Is the implication here that it is actually impossible to update the driver on prebuilt systems using the gpu-operator?

**Comment by sjkoelle** [comment]
The answer was yet.  FTD'ing the instructions linked in the other thread (in particular using the recommended Ubuntu AMI) solved the issue for me.
