### ISSUE TITLE
nvidia-device-plugin-validator and nvidia-operator-validator in CrashLoopBackOff

### ISSUE THREAD

**Issue by visla-xugeng** [NVIDIA/gpu-operator#528]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? No, I am on AL2_x86_64_GPU (LINUX machine)
- [ ] Are you running Kubernetes v1.13+? Yes
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? No K8s
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? NO
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`) NO

### 1. Issue or feature description
I followed the instruction to install gpu-operator and node_feature_discovery two charts. Two pods are in CrashLoopBackOff

```
nvidia-device-plugin-validator-whr6m             0/1     Init:CrashLoopBackOff   5 (2m18s ago)   5m25s
nvidia-operator-validator-d5c26                  0/1     Init:CrashLoopBackOff   4 (24s ago)     25m
```

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

```
kubectl logs -n nvidia nvidia-device-plugin-validator-wfxm7
Error from server (BadRequest): container "nvidia-device-plugin-validator" in pod "nvidia-device-plugin-validator-wfxm7" is waiting to start: PodInitializing
```

```
kubectl -n nvidia describe pod nvidia-device-plugin-validator-z8s66

Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Normal   Pulled   101s (x5 over 3m11s)  kubelet  Container image "nvcr.io/nvidia/cloud-native/gpu-operator-validator:v23.3.1" already present on machine
  Normal   Created  101s (x5 over 3m11s)  kubelet  Created container plugin-validation
  Warning  Failed   101s (x5 over 3m11s)  kubelet  Error: failed to create containerd task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: /usr/local/nvidia/toolkit/nvidia-container-cli.real: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/nvidia/toolkit/libnvidia-container.so.1): unknown
  Warning  BackOff  86s (x10 over 3m9s)   kubelet  Back-off restarting failed container
```

```

kubectl logs -n nvidia nvidia-operator-validator-d5c26 -c plugin-validation
time="2023-05-18T20:01:30Z" level=info msg="pod nvidia-device-plugin-validator-v2xcf is curently in Pending phase"
time="2023-05-18T20:01:35Z" level=info msg="pod nvidia-device-plugin-validator-v2xcf is curently in Pending phase"
time="2023-05-18T20:01:40Z" level=info msg="pod nvidia-device-plugin-validator-v2xcf is curently in Pending phase"
time="2023-05-18T20:01:45Z" level=info msg="pod nvidia-device-plugin-validator-v2xcf is curently in Pending phase"
```

This one(nvidia-smi) looks good
```

[root@nvidia-device-plugin-daemonset-4xkwd /]# nvidia-smi
Thu May 18 20:13:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   42C    P8    16W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[root@nvidia-device-plugin-daemonset-4xkwd /]# 
```

**Comment by visla-xugeng** [comment]
Since our EC2 instance (GPU) has  nvidia driver and nvidia-container-runtime installed by default, I disabled the drive installation in this GPU operator installation. And set the 

`defaultRuntime: containerd`

```

kubectl -n nvidia get pods
NAME                                             READY   STATUS                  RESTARTS       AGE
gpu-feature-discovery-bsdxx                      1/1     Running                 0              40m
gpu-operator-6869589d45-7jtbc                    1/1     Running                 0              41m
node-feature-discovery-master-7dcbf77f95-9sstj   1/1     Running                 0              41m
node-feature-discovery-worker-27m5c              1/1     Running                 0              41m
nvidia-container-toolkit-daemonset-846rh         1/1     Running                 0              40m
nvidia-cuda-validator-g4986                      0/1     Completed               0              40m
nvidia-dcgm-exporter-cbb5d                       1/1     Running                 0              40m
nvidia-device-plugin-daemonset-4xkwd             1/1     Running                 0              40m
nvidia-device-plugin-validator-z8s66             0/1     Init:CrashLoopBackOff   6 (69s ago)    6m42s
nvidia-operator-validator-d5c26                  0/1     Init:CrashLoopBackOff   6 (102s ago)   40m
```

**Comment by shivamerla** [comment]
Please select the ubi8 variant of container toolikit with `--set toolkit.version=v1.13.1-ubi8`

**Comment by visla-xugeng** [comment]
Hi,
I tried to reinstall two charts
**gpu_operator and node_feature_discovery.** The installation are all good, but several pods in CrashLoopBackOff. 

```
NAME                                             READY   STATUS                  RESTARTS        AGE
gpu-feature-discovery-t9zf5                      0/1     CrashLoopBackOff        7 (4m51s ago)   16m
gpu-operator-6869589d45-ssf4f                    1/1     Running                 0               16m
node-feature-discovery-master-7dcbf77f95-btlql   1/1     Running                 0               28m
node-feature-discovery-worker-2cl4d              1/1     Running                 0               28m
nvidia-container-toolkit-daemonset-n66ws         1/1     Running                 0               16m
nvidia-dcgm-exporter-f5qwr                       0/1     CrashLoopBackOff        3 (42s ago)     89s
nvidia-device-plugin-daemonset-9zjdf             0/1     RunContainerError       2 (10s ago)     28s
nvidia-operator-validator-7hw28                  0/1     Init:CrashLoopBackOff   7 (4m54s ago)   16m
```

 after checking these bad pods and found this error:

`  Warning  Failed     10s (x4 over 54s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: /usr/local/nvidia/toolkit/nvidia-container-cli.real: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/nvidia/toolkit/libnvidia-container.so.1): unknown`

**Comment by elezar** [comment]
@visla-xugeng what Linux distribution is the cluster running? If you're running `centos7` please use `--set toolkit.version=v1.13.1-centos7` in this case.

**Comment by visla-xugeng** [comment]
@elezar Thanks for your update. I think the `set toolkit.version=v1.13.1-centos7` fix the issue. 
(A quick suggestion here. Are you able to put these instructions in somewhere like README that will be really helpful for us?)

**Comment by elezar** [comment]
@cdesiniotis @shivamerla are you aware of any place where this is documented?

**Comment by shivamerla** [comment]
Yes, this is covered [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-default-configurations-on-centos).

**Comment by visla-xugeng** [comment]
@shivamerla Thank you so much. I should spend more time on these docs before the installation. Thank you all.

**Comment by pythonking6** [comment]
Hello, I am seeing a similar issue when using the gpu-operator, however, I am using kubernetes 1.29 on eks. The gpu-operator runs fine actually, including all its validator pods, however, the pod that is spun up and about to do the work has the following issue:

 Warning  Failed            3s     kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: /usr/local/nvidia/toolkit/nvidia-container-cli.real: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/nvidia/toolkit/libnvidia-container.so.1): unknown
 
 The node has the following ami:
 https://github.com/awslabs/amazon-eks-ami/releases
 
 Any guidance here would be greatly appreciated!!

**Comment by sks** [comment]
similar issue reported in https://github.com/NVIDIA/gpu-operator/issues/755 for newer ami's
