### ISSUE TITLE
GPU Operator installation failure in AKS

### ISSUE THREAD

**Issue by sidharthkumarpradhan** [NVIDIA/gpu-operator#529]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node?
- [ ] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
**I am trying to install GPU Operator in AKS with Kubernetes version 1.24.9. Getting the  below error**

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ClusterPolicy.spec): unknown field "cdi" in com.nvidia.v1.ClusterPolicy.spec, ValidationError(ClusterPolicy.spec.daemonsets): unknown field "labels" in com.nvidia.v1.ClusterPolicy.spec.daemonsets, ValidationError(ClusterPolicy.spec.daemonsets): unknown field "rollingUpdate" in com.nvidia.v1.ClusterPolicy.spec.daemonsets, ValidationError(ClusterPolicy.spec.daemonsets): unknown field "updateStrategy" in com.nvidia.v1.ClusterPolicy.spec.daemonsets, ValidationError(ClusterPolicy.spec.driver): unknown field "upgradePolicy" in com.nvidia.v1.ClusterPolicy.spec.driver, ValidationError(ClusterPolicy.spec.driver): unknown field "usePrecompiled" in com.nvidia.v1.ClusterPolicy.spec.driver, ValidationError(ClusterPolicy.spec.migManager.config): unknown field "default" in com.nvidia.v1.ClusterPolicy.spec.migManager.config`

### 2. Steps to reproduce the issue
**Just following the documentation here.**
[](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#operator-install-guide)

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by sidharthkumarpradhan** [comment]
**I described the cluster policy, and found out the below one.**

`Name:         cluster-policy
Namespace:
Labels:       app.kubernetes.io/component=gpu-operator
              app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: gpu-operator
              meta.helm.sh/release-namespace: gpu-operator
API Version:  nvidia.com/v1
Kind:         ClusterPolicy
Metadata:
  Creation Timestamp:  2023-04-27T11:39:46Z
  Generation:          2
  Managed Fields:
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:daemonsets:
          .:
          f:priorityClassName:
          f:tolerations:
        f:dcgm:
          .:
          f:enabled:
          f:hostPort:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:dcgmExporter:
          .:
          f:enabled:
          f:env:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:serviceMonitor:
            .:
            f:additionalLabels:
            f:enabled:
            f:honorLabels:
            f:interval:
          f:version:
        f:devicePlugin:
          .:
          f:config:
          f:enabled:
          f:env:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:driver:
          .:
          f:certConfig:
            .:
            f:name:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:kernelModuleConfig:
            .:
            f:name:
          f:licensingConfig:
            .:
            f:configMapName:
            f:nlsEnabled:
          f:manager:
            .:
            f:env:
            f:image:
            f:imagePullPolicy:
            f:repository:
            f:version:
          f:rdma:
            .:
            f:enabled:
            f:useHostMofed:
          f:repoConfig:
            .:
            f:configMapName:
          f:repository:
          f:rollingUpdate:
            .:
            f:maxUnavailable:
          f:version:
          f:virtualTopology:
            .:
            f:config:
        f:gfd:
          .:
          f:enabled:
          f:env:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:mig:
          .:
          f:strategy:
        f:migManager:
          .:
          f:config:
            .:
            f:name:
          f:enabled:
          f:env:
          f:gpuClientsConfig:
            .:
            f:name:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:nodeStatusExporter:
          .:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:operator:
          .:
          f:defaultRuntime:
          f:initContainer:
            .:
            f:image:
            f:imagePullPolicy:
            f:repository:
            f:version:
          f:runtimeClass:
        f:psp:
          .:
          f:enabled:
        f:sandboxDevicePlugin:
          .:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:sandboxWorkloads:
          .:
          f:defaultWorkload:
          f:enabled:
        f:toolkit:
          .:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:installDir:
          f:repository:
          f:version:
        f:validator:
          .:
          f:image:
          f:imagePullPolicy:
          f:plugin:
            .:
            f:env:
          f:repository:
          f:version:
        f:vfioManager:
          .:
          f:driverManager:
            .:
            f:env:
            f:image:
            f:imagePullPolicy:
            f:repository:
            f:version:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:vgpuDeviceManager:
          .:
          f:config:
            .:
            f:default:
            f:name:
          f:enabled:
          f:image:
          f:imagePullPolicy:
          f:repository:
          f:version:
        f:vgpuManager:
          .:
          f:driverManager:
            .:
            f:env:
            f:image:
            f:imagePullPolicy:
            f:repository:
            f:version:
          f:enabled:
          f:image:
          f:imagePullPolicy:
    Manager:      helm
    Operation:    Update
    Time:         2023-04-27T11:39:46Z
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:namespace:
        f:state:
    Manager:      gpu-operator
    Operation:    Update
    Subresource:  status
    Time:         2023-04-27T11:40:02Z
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:devicePlugin:
          f:config:
            f:default:
            f:name:
    Manager:         kubectl-patch
    Operation:       Update
    Time:            2023-04-27T11:42:47Z
  Resource Version:  25411431
  UID:               9dbdb303-6efe-4e3d-a8d5-7c4f43e46ddf
Spec:
  Daemonsets:
    Priority Class Name:  system-node-critical
    Tolerations:
      Effect:    NoSchedule
      Key:       nvidia.com/gpu
      Operator:  Exists
  Dcgm:
    Enabled:            false
    Host Port:          5555
    Image:              dcgm
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            3.0.4-1-ubuntu20.04
  Dcgm Exporter:
    Enabled:  true
    Env:
      Name:             DCGM_EXPORTER_LISTEN
      Value:            :9400
      Name:             DCGM_EXPORTER_KUBERNETES
      Value:            true
      Name:             DCGM_EXPORTER_COLLECTORS
      Value:            /etc/dcgm-exporter/dcp-metrics-included.csv
    Image:              dcgm-exporter
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/k8s
    Service Monitor:
      Additional Labels:
      Enabled:       false
      Honor Labels:  false
      Interval:      15s
    Version:         3.0.4-3.0.0-ubuntu20.04
  Device Plugin:
    Config:
      Default:  any
      Name:     time-slicing-config-all
    Enabled:    true
    Env:
      Name:             PASS_DEVICE_SPECS
      Value:            true
      Name:             FAIL_ON_INIT_ERROR
      Value:            true
      Name:             DEVICE_LIST_STRATEGY
      Value:            envvar
      Name:             DEVICE_ID_STRATEGY
      Value:            uuid
      Name:             NVIDIA_VISIBLE_DEVICES
      Value:            all
      Name:             NVIDIA_DRIVER_CAPABILITIES
      Value:            all
    Image:              k8s-device-plugin
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia
    Version:            v0.12.3-ubi8
  Driver:
    Cert Config:
      Name:
    Enabled:            true
    Image:              driver
    Image Pull Policy:  IfNotPresent
    Kernel Module Config:
      Name:
    Licensing Config:
      Config Map Name:
      Nls Enabled:      false
    Manager:
      Env:
        Name:             ENABLE_AUTO_DRAIN
        Value:            true
        Name:             DRAIN_USE_FORCE
        Value:            false
        Name:             DRAIN_POD_SELECTOR_LABEL
        Value:
        Name:             DRAIN_TIMEOUT_SECONDS
        Value:            0s
        Name:             DRAIN_DELETE_EMPTYDIR_DATA
        Value:            false
      Image:              k8s-driver-manager
      Image Pull Policy:  IfNotPresent
      Repository:         nvcr.io/nvidia/cloud-native
      Version:            v0.4.2
    Rdma:
      Enabled:         false
      Use Host Mofed:  false
    Repo Config:
      Config Map Name:
    Repository:         nvcr.io/nvidia
    Rolling Update:
      Max Unavailable:  1
    Version:            515.65.01
    Virtual Topology:
      Config:
  Gfd:
    Enabled:  true
    Env:
      Name:             GFD_SLEEP_INTERVAL
      Value:            60s
      Name:             GFD_FAIL_ON_INIT_ERROR
      Value:            true
    Image:              gpu-feature-discovery
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia
    Version:            v0.6.2-ubi8
  Mig:
    Strategy:  single
  Mig Manager:
    Config:
      Name:
    Enabled:  true
    Env:
      Name:   WITH_REBOOT
      Value:  false
    Gpu Clients Config:
      Name:
    Image:              k8s-mig-manager
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            v0.5.0-ubuntu20.04
  Node Status Exporter:
    Enabled:            false
    Image:              gpu-operator-validator
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            v22.9.0
  Operator:
    Default Runtime:  docker
    Init Container:
      Image:              cuda
      Image Pull Policy:  IfNotPresent
      Repository:         nvcr.io/nvidia
      Version:            11.7.1-base-ubi8
    Runtime Class:        nvidia
  Psp:
    Enabled:  false
  Sandbox Device Plugin:
    Enabled:            true
    Image:              kubevirt-gpu-device-plugin
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia
    Version:            v1.2.1
  Sandbox Workloads:
    Default Workload:  container
    Enabled:           false
  Toolkit:
    Enabled:            true
    Image:              container-toolkit
    Image Pull Policy:  IfNotPresent
    Install Dir:        /usr/local/nvidia
    Repository:         nvcr.io/nvidia/k8s
    Version:            v1.11.0-ubuntu20.04
  Validator:
    Image:              gpu-operator-validator
    Image Pull Policy:  IfNotPresent
    Plugin:
      Env:
        Name:    WITH_WORKLOAD
        Value:   true
    Repository:  nvcr.io/nvidia/cloud-native
    Version:     v22.9.0
  Vfio Manager:
    Driver Manager:
      Env:
        Name:             ENABLE_AUTO_DRAIN
        Value:            false
      Image:              k8s-driver-manager
      Image Pull Policy:  IfNotPresent
      Repository:         nvcr.io/nvidia/cloud-native
      Version:            v0.4.2
    Enabled:              true
    Image:                cuda
    Image Pull Policy:    IfNotPresent
    Repository:           nvcr.io/nvidia
    Version:              11.7.1-base-ubi8
  Vgpu Device Manager:
    Config:
      Default:          default
      Name:
    Enabled:            true
    Image:              vgpu-device-manager
    Image Pull Policy:  IfNotPresent
    Repository:         nvcr.io/nvidia/cloud-native
    Version:            v0.2.0
  Vgpu Manager:
    Driver Manager:
      Env:
        Name:             ENABLE_AUTO_DRAIN
        Value:            false
      Image:              k8s-driver-manager
      Image Pull Policy:  IfNotPresent
      Repository:         nvcr.io/nvidia/cloud-native
      Version:            v0.4.2
    Enabled:              false
    Image:                vgpu-manager
    Image Pull Policy:    IfNotPresent
Status:
  Namespace:  gpu-operator
  State:      ready
Events:       <none>`

**Comment by sidharthkumarpradhan** [comment]
My main aim is to use time slicing for GPU sharing. Is it possible in AKS ? if not, how could I share GPUs in AKS. Thank you.

**Comment by sidharthkumarpradhan** [comment]
Hello Shiv, Thank you so much for your help on this. Unfortunately, I have came across to another hurdle, The installation got successfully completed. But the time slicing is not working , as the node does not advertise additional GPU resources,

Steps I have taken:
**Installation:**
 helm install --wait gpu-operator --set toolkit.enabled=false --set driver.enabled=false --set operator.runtimeClass=nvidia-container-runtime  --set devicePlugin.config.name=time-slicing-config --set operator.cleanupCRD=true -n gpu-operator  nvidia/gpu-operator
**ClusterPolicy:**
kubectl patch clusterpolicy/cluster-policy     -n gpu-operator --type merge     -p '{"spec": {"devicePlugin": {"config": {"name": "time-slicing-config-all", "default": "any"}}}}'
**Time Slicing Yaml:**
`kubectl patch clusterpolicy/cluster-policy     -n gpu-operator --type merge     -p '{"spec": {"devicePlugin": {"config": {"name": "time-slicing-config-all", "default": "any"}}}}'`

**I was expecting like below:**
Following this documentation
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-sharing.html
`...
Labels:
                  nvidia.com/gpu.count=4
                  nvidia.com/gpu.product=Tesla-T4-SHARED
                  nvidia.com/gpu.replicas=4
Capacity:
  nvidia.com/gpu: 16
  ...
Allocatable:
  nvidia.com/gpu: 16
  ...
`
But when I described the node, I am got getting the additional GPU getting advertised

![image](https://github.com/NVIDIA/gpu-operator/assets/66263561/740fcf95-0ec4-49cb-9c1d-331c7c513372)

These are lables 
![image](https://github.com/NVIDIA/gpu-operator/assets/66263561/cb92409c-df97-489b-82aa-47a5cd83a298)

**One thing I came across is, that our nodes are tainted with below parameters,** 
![image](https://github.com/NVIDIA/gpu-operator/assets/66263561/f31ce9e4-27c2-4ea6-873b-ac26369a70ae)

Do you thing, it could have something to do with it?
Could you kindly help me here?

Thanking you.

**Comment by shivamerla** [comment]
@sidharthkumarpradhan Can you share logs from the k8s-device-plugin pod in the operator namespace? Can you also try with node label `kubectl label node <node-name> nvidia.com/device-plugin.config=any` to verify if timeslicing config is applied.

**Comment by sidharthkumarpradhan** [comment]
Hello Shiv, Thanks for getting back to me. As per your direction, 
1. When I tried to search the namespace for **k8s-device-plugin** pods , I could not find any. I only see these pods.

![image](https://github.com/NVIDIA/gpu-operator/assets/66263561/8a584be7-b9a1-44f9-93df-4c69fc469ac9)

2. When I tried to label the node, it got labelled.
`kubectl label node aks-gpunvpool-12148823-vmss000002 nvidia.com/device-plugin.config=any
node/aks-gpunvpool-12148823-vmss000002 labeled`

**Comment by shivamerla** [comment]
so looks like AKS deploys a device-plugin with GPU node pool. You can confirm by listing pods in all namespaces. After disabling that, you need to pass any required tolerations for operator deployed Daemonsets to run. This is set in ClusterPolicy with [daemonsets.tolerations](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/values.yaml#L26) parameter. Verify the Taints set on the GPU node and pass them as tolerations.

**Comment by sidharthkumarpradhan** [comment]
Thank you so much Shiv, It seems like the daemonset what causing the issue. It was not getting up , with gpu-operator installation for some reason, because the node was not tainted, it could be some other issue. But finally we are seeing what we were expecting , the Time Slicing is working. YAY! . So excited. Grateful for your time and guidance. 

**Finally seeing 4 Gpu are being advertised.**

![image](https://github.com/NVIDIA/gpu-operator/assets/66263561/ad70e867-b675-4691-b012-6e82e3f1df33)

Thanking you
