### ISSUE TITLE
Not able to deploy Nvidia GPU Operator in Managed Kubernetes Service provided by OVH Cloud

### ISSUE THREAD

**Issue by altruistcoder** [NVIDIA/gpu-operator#530]
Hello,

I have created a new K8s cluster using the Managed Kubernetes Service provided by the OVH cloud.
We have a bunch of CPU nodes and one GPU node in the nodepools of the cluster.

While trying to deploy the **Nvidia GPU Operator** using **Helm** (by following the article given [here](https://help.ovhcloud.com/csm/en-gb-public-cloud-kubernetes-deploy-gpu-application?id=kb_article_view&sysparm_article=KB0049707) in official OVH docs), we are facing the below error:

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "gpu-operator" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "gpu-operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "gpu-operator"
```

The error seems to be weird because when we try to get the clusterrole named "gpu-operator", nothing comes out but still the error message seems to say that it is present somewhere in the cluster:

![image](https://github.com/NVIDIA/gpu-operator/assets/31319270/215b2cfa-5fe1-4ec7-83a4-a894c0c005d6)

Can anyone please help in resolving this issue as soon as possible because we are stuck in completing our work due to this?

**Comment by altruistcoder** [comment]
Hello @shivamerla,

This issue is fixed. Thanks.

**Comment by athithya-raj** [comment]
@shivamerla how you fixed?

**Comment by Vacxe** [comment]
@altruistcoder how did you fixed it?
