### ISSUE TITLE
Relabelings for ServiceMonitor

### ISSUE THREAD

**Issue by faurik** [NVIDIA/gpu-operator#537]
### Issue or feature description
Currently, GPU-Operator can manage ServiceMonitors for DCGM-exporter. It would be nice to have ability to set relabelings (a.k.a. relabel_configs in Prometheus) on the ServiceMonitors using the operator (otherwise I have to set spec.dcgmExporter,serviceMonitor.enabled=false and create the SM manually).

**Comment by shivamerla** [comment]
Closing this as changes are merged and will be available with v23.3.3 (late July).
