### ISSUE TITLE
Support for additional products/distributions

### ISSUE THREAD

**Issue by saschagrunert** [NVIDIA/gpu-operator#54]
Hey 👋, I’m wondering if contributions for additional products or distributions are wanted or maybe out of scope of this project.

Things we need to do right now to support NVIDIA GPUs on our product (a Kubernetes distribution):
- install drivers
- install the OCI hook (already packaged on our side) to work with CRI-O
- deploy the NVIDIA k8s device plugin DaemonSet

Bundling those steps in a single operator sounds reasonable to me in the first place.

What do you think? 🙂

cc @klaven

**Comment by RenaudWasTaken** [comment]
> Hey 👋, I’m wondering if contributions for additional products or distributions are wanted or maybe out of scope of this project.

They are completely in scope for this project!

> install drivers
> install the OCI hook (already packaged on our side) to work with CRI-O
> deploy the NVIDIA k8s device plugin DaemonSet

The GPU Operator looks like a great fit to me!

**Comment by saschagrunert** [comment]
Thanks, I'll check what's needed and come up with pull requests if necessary :)

**Comment by shivamerla** [comment]
Closing this as current GPU operator satisfies this requirement.
