### ISSUE TITLE
Unable to deploy GPU Operator on MicroShift 4.13

### ISSUE THREAD

**Issue by sjug** [NVIDIA/gpu-operator#540]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node? no
- [x] Are you running Kubernetes v1.13+? Yes, v1.26.3
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? Yes, cri-o v1.26.3
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? no `i2c_core`, yes `ipmi_msghandler`
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)? yes ([CRD output](http://ix.io/4ycW))

### 1. Issue or feature description
MicroShift is a new flavor of OpenShift that is designed for the device edge with a very minimal resource footprint. This makes it much more minimal than SNO, so the [typical OpenShift installation methods](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/openshift/install-gpu-ocp.html) for the GPU operator do not apply as there are virtually no operators in MicroShift. MicroShift has two installation methods, [one is enabling repos on RHEL9.2+ and doing a `dnf install microshift`](https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html/installing/microshift-embed-in-rpm-ostree), and the other is [embedding the MicroShift artifacts in an RHCOS image](https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.13/html/installing/microshift-embed-in-rpm-ostree). For simplicity, I am using a RHEL9.2 host with the MicroShift 4.13.1 package installed.

```
$ oc get node
NAME                                   STATUS   ROLES                         AGE   VERSION
perfdgx3                              Ready    control-plane,master,worker   75s   v1.26.3
$ oc get ns
NAME                                 STATUS   AGE
default                              Active   2m6s
kube-node-lease                      Active   2m8s
kube-public                          Active   2m8s
kube-system                          Active   2m8s
openshift-dns                        Active   94s
openshift-infra                      Active   105s
openshift-ingress                    Active   94s
openshift-kube-controller-manager    Active   105s
openshift-ovn-kubernetes             Active   94s
openshift-route-controller-manager   Active   103s
openshift-service-ca                 Active   100s
```

### 2. Steps to reproduce the issue
Following the [default configurations deploying with helm on Red Hat Enterprise Linux](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#bare-metal-passthrough-with-default-configurations-on-red-hat-enterprise-linux):
```
$ helm install --wait --generate-name \
     -n gpu-operator --create-namespace \
     nvidia/gpu-operator
```

Initially the NFD is unable to deploy due to the `HostPath` mounts and [PodSecurityStandards](https://connect.redhat.com/en/blog/important-openshift-changes-pod-security-standards):
```
$ oc describe ns gpu-operator
Name:         gpu-operator
Labels:       kubernetes.io/metadata.name=gpu-operator
              name=gpu-operator
              pod-security.kubernetes.io/audit=privileged
              pod-security.kubernetes.io/audit-version=v1.24
              pod-security.kubernetes.io/warn=privileged
              pod-security.kubernetes.io/warn-version=v1.24
Annotations:  openshift.io/sa.scc.mcs: s0:c11,c0
              openshift.io/sa.scc.supplemental-groups: 1000110000/10000
              openshift.io/sa.scc.uid-range: 1000110000/10000
Status:       Active
$ oc get ev -n gpu-operator
7s          Warning   FailedCreate        replicaset/gpu-operator-7db8447d6c                                            (combined from similar events): Error creating: pods "gpu-operator-7db8447d6c-xrz7d" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "gpu-operator" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "gpu-operator" must set securityContext.capabilities.drop=["ALL"]), restricted volume types (volume "host-os-release" uses restricted volume type "hostPath"), runAsNonRoot != true (pod or container "gpu-operator" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "gpu-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

If we relabel the `gpu-operator` namespace (to add ` pod-security.kubernetes.io/enforce`) then the NFD is able to deploy.

```
$ oc describe ns gpu-operator
Name:         gpu-operator
Labels:       kubernetes.io/metadata.name=gpu-operator
              name=gpu-operator
              pod-security.kubernetes.io/audit=privileged
              pod-security.kubernetes.io/audit-version=v1.24
              pod-security.kubernetes.io/enforce=privileged
              pod-security.kubernetes.io/enforce-version=v1.24
              pod-security.kubernetes.io/warn=privileged
              pod-security.kubernetes.io/warn-version=v1.24
Annotations:  openshift.io/sa.scc.mcs: s0:c11,c0
              openshift.io/sa.scc.supplemental-groups: 1000110000/10000
              openshift.io/sa.scc.uid-range: 1000110000/10000
Status:       Active
```

Once the NFD is deployed we get wedged trying to roll out the GPU operator. The GPU operator also labels the node `SchedulingDisabled`.
```
$ oc get no
NAME                                   STATUS                     ROLES                         AGE   VERSION
perfdgx3.perf.lab.eng.bos.redhat.com   Ready,SchedulingDisabled   control-plane,master,worker   27m   v1.26.3
```

Several of the pods fail with:
```
Warning   FailedCreatePodSandBox   pod/nvidia-device-plugin-daemonset-l8h89                                      Failed to create pod sandbox: rpc error: code = Unknown desc = failed to find runtime handler nvidia from runtime list map[crun:0xc000e73680 runc:0xc000e73800]
```

I would appreciate some help in getting the GPU Operator working on MicroShift.

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)

 - [x] kubernetes pods status: `oc get pods -A`: [oc-get-po-A.txt](https://github.com/NVIDIA/gpu-operator/files/11747335/oc-get-po-A.txt)
 - [x] kubernetes daemonset status: `oc get ds -A`: [oc-get-ds-A.txt](https://github.com/NVIDIA/gpu-operator/files/11747332/oc-get-ds-A.txt)
 - [x] kubernets events `oc get ev -n gpu-operator`: [oc-get-ev-n-gpu-operator.txt](https://github.com/NVIDIA/gpu-operator/files/11747334/oc-get-ev-n-gpu-operator.txt)
 - [x] If a pod/ds is in an error state or pending state `oc describe pod -n NAMESPACE POD_NAME`
[gpu-feature-discovery-zbcsv.txt](https://github.com/NVIDIA/gpu-operator/files/11747326/gpu-feature-discovery-zbcsv.txt)
[nvidia-container-toolkit-daemonset-7cpwv.txt](https://github.com/NVIDIA/gpu-operator/files/11747327/nvidia-container-toolkit-daemonset-7cpwv.txt)
[nvidia-dcgm-exporter-qcv9m.txt](https://github.com/NVIDIA/gpu-operator/files/11747328/nvidia-dcgm-exporter-qcv9m.txt)
[nvidia-device-plugin-daemonset-g57sn.txt](https://github.com/NVIDIA/gpu-operator/files/11747329/nvidia-device-plugin-daemonset-g57sn.txt)
[nvidia-driver-daemonset-rpdq7.txt](https://github.com/NVIDIA/gpu-operator/files/11747330/nvidia-driver-daemonset-rpdq7.txt)
[nvidia-operator-validator-f58s5.txt](https://github.com/NVIDIA/gpu-operator/files/11747331/nvidia-operator-validator-f58s5.txt)
 - [x] If a pod/ds is in an error state or pending state `oc logs -n gpu-operator POD_NAME` - pods are all waiting to init or ImagePullBackOff

 - [x] Output of running a container on the GPU machine: `podman run -it alpine echo foo`
 ```
$ podman run -it alpine echo foo
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 8a49fdb3b6a5 done
Copying config 5e2b554c1c done
Writing manifest to image destination
Storing signatures
foo
```
 - [x] Podman configuration file: `cat /etc/crio/crio.conf`: [crio.conf.txt](https://github.com/NVIDIA/gpu-operator/files/11747391/crio.conf.txt)

 - [x]  Runtime configuration: As of OpenShift/MicroShift 4.13 we are using the `crun` runtime

 - [x] NVIDIA shared directory: `ls -la /run/nvidia`
```
ls -la /run/nvidia
total 0
drwxr-xr-x.  4 root root   80 Jun 14 10:05 .
drwxr-xr-x. 54 root root 1400 Jun 14 10:05 ..
drwxr-xr-x.  2 root root   40 Jun 14 10:05 driver
drwxr-xr-x.  2 root root   40 Jun 14 10:05 validations
```
 - [x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
```
ls: cannot access '/usr/local/nvidia/toolkit': No such file or directory
```
 - [x] NVIDIA driver directory: `ls -la /run/nvidia/driver`
```
total 0
drwxr-xr-x. 2 root root 40 Jun 14 10:05 .
drwxr-xr-x. 4 root root 80 Jun 14 10:05 ..
```
 - [x] kubelet logs `journalctl -u microshift > kubelet-log.txt`: [kubelet-logs.txt](https://github.com/NVIDIA/gpu-operator/files/11747385/kubelet-logs.txt)

**Comment by sjug** [comment]
I think part of the question is if the GPU Operator is the supported/suggested method to use NVIDIA GPUs on MicroShift.
There is [this documentation as well which is MicroShift specific](https://docs.nvidia.com/datacenter/cloud-native/edge/nvidia-gpu-with-device-edge.html).

**Comment by shivamerla** [comment]
@sjug GPU Operator is not supported on MicroShift. Please follow the steps documented in the link above.

**Comment by sjug** [comment]
Yeah, I haven't had any luck with those instructions either but that's a separate issue. Closing, thanks.

**Comment by arthur-r-oliveira** [comment]
> Warning   FailedCreatePodSandBox   pod/nvidia-device-plugin-daemonset-l8h89                                      Failed to create pod sandbox: rpc error: code = Unknown desc = failed to find runtime handler nvidia from runtime list map[crun:0xc000e73680 runc:0xc000e73800]

Have you configured crio https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-cri-o and later the runtime as nvidia? 

The crio conf will looks like this: 
~~~
$ cat /etc/crio/crio.conf
(..)
    [crio.runtime.runtimes]

      [crio.runtime.runtimes.crun]
(..)

      [crio.runtime.runtimes.nvidia]
        allowed_annotations = ["io.containers.trace-syscall", "io.kubernetes.cri-o.Devices"]
        monitor_cgroup = "system.slice"
        monitor_env = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
        monitor_exec_cgroup = ""
        monitor_path = ""
        privileged_without_host_devices = false
        runtime_config_path = ""
        runtime_path = "/usr/bin/nvidia-container-runtime"
        runtime_root = "/run/runc"
        runtime_type = "oci"

      [crio.runtime.runtimes.runc]
(..)
~~~


And the microshift config as: 

~~~
$ grep default /etc/crio/crio.conf.d/microshift.conf 
default_env = [
default_runtime = "nvidia"
default_sysctls = [
~~~
