### ISSUE TITLE
How can I make a pod use a specific GPU from a k8s node?

### ISSUE THREAD

**Issue by FLM210** [NVIDIA/gpu-operator#563]
How can I configure the pod to use a specific model of GPU from the two different GPU models available on my node?

**Comment by FLM210** [comment]
> 
Ex:  my machine has both RTX 3080 and RTX 3080 Ti. I want the pod to use the RTX 3080 Ti.

**Comment by evopen** [comment]
maybe https://gitlab.com/nvidia/kubernetes/device-plugin/-/merge_requests/127 will help

**Comment by shivamerla** [comment]
@FLM210 mixed GPU types are currently not supported by the device-plugin and gpu-feature-discovery. Above linked PR will allow resource-renaming of GPUs, but that is not officially supported (disabled in the code). Those features will be available with the upcoming [Dynamic Resource Allocation ](https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/)plugin later this year.

**Comment by FLM210** [comment]
@shivamerla Okay ~~~

**Comment by PotapIlya** [comment]
@shivamerla 
hi, is it now supported?

i installed sandboxDevicePlugin and it works for vm (nvidia.com/GH100_H100L_94GB)

but i cant get the same result on default devicePlugin
