### ISSUE TITLE
How to VFIO passthrough multiple gpus into a single k8s pod with kata runtime

### ISSUE THREAD

**Issue by liricky** [NVIDIA/gpu-operator#576]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

### 1. Quick Debug Information
* OS/Version: Ubuntu20.04
* Kernel Version: 5.8.0-43-generic
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): Containerd
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): K8s
* GPU Operator Version:23.6.0
* runtime: kata

### 2. Issue or feature description
I want to passthrough multiple gpus into a single pod, but I don't know how to set the annotations in the metadata of k8s yaml. Does gpu operator support passing multiple gpus into the same pod in the case of using VFIO?

### 3. Steps to reproduce the issue
Try to passthrough multiply gpus into a single pod.

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

This bundle can be submitted to us via email: **operator_feedback@nvidia.com**

**Comment by liricky** [comment]
In addition, [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) can automatically assign gpus without explicitly assigning a specific index, does gpu-operator also support transparent assignment when using VFIO passthrough to provide gpus for kata containers? Or do we need to additionally manage the allocation of gpus?

**Comment by klueska** [comment]
Have you read through this:
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-confidential-containers.html

**Comment by liricky** [comment]
> Have you read through this:
> https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-confidential-containers.html

Limitations and Restrictions[](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-confidential-containers.html#limitations-and-restrictions)

GPUs are available to containers as a single GPU in passthrough mode only. Multi-GPU passthrough and vGPU are not supported.
