### ISSUE TITLE
":9400/metrics: dial tcp :9400: connect: connection refused" for prometheus metrics. 

### ISSUE THREAD

**Issue by dkozlov** [NVIDIA/gpu-operator#60]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description
I am getting  ":9400/metrics: dial tcp :9400: connect: connection refused" error for Prometheus metrics. nvidia/dcgm-exporter:1.7.2-2.0.0-rc.5-ubuntu18.04 container is listening on 8080 port by default. So I propose to change the target port for "nvidia-dcgm-exporter" service from 9040 to 8080

```
root@nvidia-dcgm-exporter-9xjcl:/# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0      0 :::8080                 :::*                    LISTEN      1/dcgm-exporter     
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
```
```
$ kubectl get service/nvidia-dcgm-exporter -n gpu-operator-resources -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-05-03T17:31:33Z"
  labels:
    app: nvidia-dcgm-exporter
  name: nvidia-dcgm-exporter
  namespace: gpu-operator-resources
  ownerReferences:
  - apiVersion: nvidia.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterPolicy
    name: cluster-policy
    uid: 382f9f19-8c23-4f55-9ff5-576d5b3b3b5d
  resourceVersion: "31564"
  selfLink: /api/v1/namespaces/gpu-operator-resources/services/nvidia-dcgm-exporter
  uid: af38e6b1-6821-4e89-8442-7e4916efdbf1
spec:
  clusterIP: 10.233.60.41
  ports:
  - name: gpu-metrics
    port: 9400
    protocol: TCP
    targetPort: 9400
  selector:
    app: nvidia-dcgm-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

### 2. Steps to reproduce the issue

Install gpu-operator and prometheus-operator, configure following ServiceMonitor:

```
   - name: "gpu-metrics"
     jobLabel: "gpu-metrics"
     namespaceSelector:
       matchNames:
         - gpu-operator-resources
     selector:
       matchLabels:
         app: nvidia-dcgm-exporter
     endpoints:
       - port: gpu-metrics
         interval: 30s
         path: /metrics
```

**Comment by dkozlov** [comment]
https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/94

**Comment by nvjmayo** [comment]
there was a disconnect between an update I did for DCGM (gpu-monitoring-tools). I'll close this issue once I confirm a fix.
