### ISSUE TITLE
gpu operator with vPC licences, B series, nvidia.com/vgpu.config=A2-1B - errors

### ISSUE THREAD

**Issue by benth42** [NVIDIA/gpu-operator#600]
Hello,

We like to use kubernetes, kubevirt and gpu operator to  run Linux VM with accelerated desktop rendering (light 3D rendering, h264 encoding/decoding,), actually no cuda or opencl are planned.  And we will use thoses Linux desktop as remote desktop thourgh xrdp and/or vnc.

Commercials tells us : ok vPC licences and nvidia A2 cards will be good enough for your needs. 

For vPC licences, seems to must use B series profils from : [nvidia licences profiles](https://docs.nvidia.com/grid/15.0/grid-licensing-user-guide/index.html#intro-to-grid-licensing)

But when I go for nvidia.com/vgpu.config=A2-1**B**, thing goes bad : 
- nvidia-sandbox-validator logs thoses errors on container vgpu-devices-validation : No vGPU devices found, retrying after 5 seconds ..
- nvidia-sandbox-device-plugin-daemonset ; vgpu-devices-validation : waiting for vGPU devices...

I have see that there is no B series in config map "default-vgpu-devices-config". I have try to create mine with A2-1B entries without success.

So I test with A2-1**Q** profils : nvidia.com/vgpu.config=A2-1Q
Things goes better, all pods are running. And I have sucessfully create VM (Ubuntu) with vGPU nvidia vGPU. 
But I can't register the VM to the DLS server instance .... because the nvidia gridd want vWS licences and not vPC ... :(

Any help would be very appreciate : bugs in gpu-operator ? configuration errors ? or wrong licences for kubernertes kubevirt  (ie vPC not compatible with kubernetes kubevirt usage ) ? Any possibility to get it work ?

Thank you in advance

**Comment by shivamerla** [comment]
@benth42 we currently support only below products with NVIDIA vGPU with the GPU Operator. vPC and vApps are not supported currently.

- NVIDIA® RTX Virtual Workstation (vWS)
- NVIDIA Virtual Compute Server (vCS)

**Comment by benth42** [comment]
Hello,

Thank you for your returns. Hope I will change one day :)

Regards,
