### ISSUE TITLE
Limit devices visible in a Kubernetes node

### ISSUE THREAD

**Issue by MassimoGirondi** [NVIDIA/gpu-operator#612]
What is the proper way to limit GPUs visibility to a Kubernetes node?

The use case is a shared environment where we would like to run both Kubernetes and Docker, and we would like to limit the GPUs visible in the node to a subset.

I found references to `CUDA_VISIBLE_DEVICES` and `NVIDIA_VISIBLE_DEVICES`, but it's not clear (to me) how these affect the GPUs assigned and what is the suggested way to implement such a limitation.

**Comment by b-lerohellec** [comment]
https://github.com/NVIDIA/k8s-device-plugin/issues/435#issuecomment-1930087603

**Comment by MassimoGirondi** [comment]
This may be a solution to our needs indeed.
Thanks!
