### ISSUE TITLE
Cannot see gpu threads in container

### ISSUE THREAD

**Issue by NUTSHELL-X** [NVIDIA/gpu-operator#629]
### 1. Quick Debug Information
* OS/Version:Ubuntu22.04
* Kernel Version: 6.2.0-26-generic
* Container Runtime Type/Version:Docker with cri-dockerd
* K8s Flavor/Version:K8s v1.28.2
* GPU Operator Version:v23.6.1

### 2. Issue or feature description
Cannot see gpu process using "nvidia-smi" in container,but I can see it on host
Host nvidia-smi:
![gpu process host](https://github.com/NVIDIA/gpu-operator/assets/73533698/7543ae30-4b8e-4364-9e17-d04f8dced8ee)
Container nvidia-smi:
![gpu process0](https://github.com/NVIDIA/gpu-operator/assets/73533698/0a9bf1aa-7fd6-48bf-9eb3-c12e51745f43)

### 3. Steps to reproduce the issue
Install docker,cri-dockerd,k8s and install nvidia gpu operator via helm,simply start a pod with gpu from k8s.Run a gpu program(in my case deep learning training),use "nvidia-smi" command to get info about gpu in container cmd,the program is running normally but I can't see it in processes inside container,but I do see it on the container host.

### 4. Information to [attach]
Everything seems to work fine,"kubectl get pod" ,I can see it is running ;"kubectl describe pod" ,nothing seems to have problems
![kubectl describe](https://github.com/NVIDIA/gpu-operator/assets/73533698/4881b9f7-62df-4af1-a155-870e412152b0)

**Comment by shivamerla** [comment]
@NUTSHELL-X this is a known limitation currently. To see all processes you need to run this from a container with `hostPID: true`. You can run this from the driver container for e.g. More details on this limitation discussed [here](https://github.com/NVIDIA/nvidia-docker/issues/179#issuecomment-242150861).

**Comment by zeddit** [comment]
@shivamerla when enabling `hostPID: true`, people could see all process on the host, and people could kill process with the same user id, which would be a common case in cloud environment.

I found there is an alternative to set up `MIG` partition to solve this problem. would it be the recommended way and should be highlighted in the official documentation. great thanks.

**Comment by shivamerla** [comment]
@zeddit not sure how MIG partitioning is related to the issue reported here. To list all the active processes, please run `nvidia-smi` from the driver container or host itself using `chroot /run/nvidia/driver nvidia-smi`.
