### ISSUE TITLE
In GPU operator v23.9.0 driver Image is missing for rhel8.9 

### ISSUE THREAD

**Issue by moditanisha22** [NVIDIA/gpu-operator#635]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04): rhel8.9
* Kernel Version:
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): Containerd
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): K8s
* GPU Operator Version: 23.9.0

### 2. Issue or feature description
I tried to install GPU operator v23.9.0 on the Kubernetes cluster having os version rhel8.9. The GPU operator by default tries to pull nvcr.io/nvidia/driver:535.104.12-rhel8.9 , It fails to say that the image is not present in the registry.

### 3. Steps to reproduce the issue
Install Vanilla Kubernetes cluster with OS version rhel 8.9.
Deploy GPU operator v23.9.0 using helm.

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Error: ImagePullBack0ff
Pulling image "nvcr.io/nvidia/driver:535.104.12-rhel8.9"
Failed to pull image "nvcr.io/nvidia/driver:535.104.12-rhel8.9": rpc error: code = NotFound desc = failed to pull and u
pack image "nvcr.io/nvidia/driver:535.104.12-rhel8.9": failed to resolve reference "nvcr.io/nvidia/driver:535.104.12-rhel8.9": nvcr.io/nvidia/driver:535.104.12-rhel8.9: not found
Error: ErrImagePull
Back-off pulling image "nvcr.io/nvidia/driver:535.104.12-rhel8.9"

https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags -- the image is not present.
Can we have this Image so that we are able to install the GPU operator with 23.9.0 on rhel8.9

**Comment by shivamerla** [comment]
Thanks for reporting this. `nvcr.io/nvidia/driver:535.104.12-rhel8.9` is now published.
