### ISSUE TITLE
Does not show the XBOX App Game capture screen

### ISSUE THREAD

**Issue by fabiohcnobre** [NVIDIA/gpu-operator#636]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04): Windows 11
* GPU Operator Version: NVIDIA GeForce RTX 3050 6GB laptop GPU 
* Version 546.33
* NVIDIA Experiencia 3.27.0.120

### 2. Issue or feature description
Does not show the XBOX App Game capture screen

### 3. Steps to reproduce the issue
Steps to Reproduce
Open Xbox or Xbox Game Streaming
Streaming XBox
Open OBS
New Captuure Game

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

https://github.com/obsproject/obs-studio/issues/9876

**Comment by shivamerla** [comment]
@fabiohcnobre please report this with NVIDIA developer forums. This is not gpu-operator related.
