### ISSUE TITLE
spec.driver.useNvidiaDriverCRD: field not declared in schema .status.conditions: field not declared in schema

### ISSUE THREAD

**Issue by ProboticsX** [NVIDIA/gpu-operator#654]
### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04): Ubuntu22.04
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): Containerd
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): EKS
* GPU Operator Version: v23.9.1

### 2. Issue or feature description
I've been seeing the following error when deploying gpu-operator on my EKS cluster managed through argocd:
`spec.driver.useNvidiaDriverCRD: field not declared in schema .status.conditions: field not declared in schema`

Although the gpu-operator still works fine and the gpu-workload does get assigned to a gpu-node but I still see this problem with the configuration in argocd which is not letting the application sync:

![image](https://github.com/GoogleCloudPlatform/k8s-config-connector/assets/36927669/aad1eb89-5921-45d6-8140-6d1365694c73)

![image](https://github.com/GoogleCloudPlatform/k8s-config-connector/assets/36927669/d6925f78-9253-40ef-b238-f168a529f46a)

### 3. Steps to reproduce the issue
I'm using the gpu-operator v23.9.1

I downloaded the gpu operator using the command below:
- helm fetch nvidia/gpu-operator --untar

And then installed the gpu operator using argocd
### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods -n ops-gpu-operator`
 
![image](https://github.com/NVIDIA/gpu-operator/assets/36927669/129d996d-4aef-4549-a2aa-8304d088fb2e)

 - [ ] kubernetes daemonset status: `kubectl get ds -n ops-gpu-operator`
![image](https://github.com/NVIDIA/gpu-operator/assets/36927669/fb859bfd-7038-496c-8cbf-6b44bd1a667e)

**Comment by cdesiniotis** [comment]
@ProboticsX I suspect the version of the `clusterpolicy` CRD deployed in your cluster is stale. Please follow our recommendations for managing CRDs when upgrading the gpu-operator: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/upgrade.html

**Comment by cdesiniotis** [comment]
It appears this is an open issue with ArgoCD concerning schema validation of the new CRD. See these related issues: 
https://github.com/NVIDIA/gpu-operator/issues/602#issuecomment-1804631305
https://github.com/argoproj/argo-cd/issues/16144
