### ISSUE TITLE
EOL for 470 drviers

### ISSUE THREAD

**Issue by KodieGlosserIBM** [NVIDIA/gpu-operator#657]
I just have a general question as we crossed this site https://endoflife.date/nvidia which shows that the 470 drivers end of life in 6 months (20 Jul 2024). 

Does this mean that past this date we will no longer be receiving security patches on the drivers or does it mean that all new features will stop, or both? 

If security patches stop, is there any way for us to continue to receive security patches on 470 or is our only choice to move to 535?

**Comment by cdesiniotis** [comment]
EOL means there will be no more updates on that branch. So yes, moving to 535 would be recommended.

**Comment by KodieGlosserIBM** [comment]
thanks!
