### ISSUE TITLE
Need to configure labels, annotations, and tolerations for default nvidiaDriver CR

### ISSUE THREAD

**Issue by age9990** [NVIDIA/gpu-operator#665]
The template of default nvidiaDriver CR does not include labels, annotations, and tolerations set in values.yaml.
It is preferable to load from the following configuration.
daemonsets:
  labels:
  annotations: 
  tolerations:

**Comment by cdesiniotis** [comment]
Thanks @age9990 for pointing this out. Agree we should be creating the default NvidiaDriver CR with any common labels, annotations, and tolerations set in values.yaml.

**Comment by tariq1890** [comment]
This has been fixed in https://github.com/NVIDIA/gpu-operator/commit/541093e9286ea852a7abf540985424d2525a16a1

The change will be made available as part of the next release of gpu-operator
