### ISSUE TITLE
use gpu operator，does it also need install cuda by ourself images?

### ISSUE THREAD

**Issue by lvcaiping** [NVIDIA/gpu-operator#67]

**Comment by nvjmayo** [comment]
Make sure your container has the libraries you need for your application. Using [official CUDA images](https://hub.docker.com/r/nvidia/cuda/) as your base image can make this easier.

gpu-operator uses [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime) to expose CUDA to containers. The [installation instructions](https://nvidia.github.io/nvidia-container-runtime/) should hopefully help you understand how gpu-operator and CUDA work.

**Comment by valeriano-manassero** [comment]
@nvjmayo do you plan to have also CUDA library folder exposed to container trough operator in future?

Using official CUDA images requires a lot of work sometimes on some projects and it forces the need of having custom images build and then reference them for many deployment in Helm charts.

Having a CUDA library folder exposed in container using GPU would make everything totally transparent from charting perspecive.

wdyt?
