### ISSUE TITLE
Two GDS-related bugfix not merged into v23.9.2 release

### ISSUE THREAD

**Issue by age9990** [NVIDIA/gpu-operator#677]
There are two GDS-related commits to fix the following issue. However, the two commits are not merged(cherry-picked) from master to   v23.9 branch.
I have tested the v23.9.2 gpu-operator, repoConfig is still not mounted into GDS container.
Could help to merge them back and release a fixed version ASAP? I have waited a long time for new version but still not usable.
#608 repoConfig is not mounted into GDS container

The commits are
https://github.com/NVIDIA/gpu-operator/commit/9c2772d8f394f598f652da6f06283fb27186292f
https://github.com/NVIDIA/gpu-operator/commit/18083ce099814d3918bdd8a7d66cf49587431467

**Comment by cdesiniotis** [comment]
@age9990 apologies for the delay on this. These commits were missed. We have a release planned for end of this month that will have these changes. In the meantime, you can try out these changes by using a gpu-operator image built off our `master` branch on Gitlab --  you can use our `latest` tag, `registry.gitlab.com/nvidia/kubernetes/gpu-operator/staging/gpu-operator:master-latest-ubi8`, or pick up the latest commit sha, `registry.gitlab.com/nvidia/kubernetes/gpu-operator/staging/gpu-operator:00a4045b`.

**Comment by cdesiniotis** [comment]
Hi @age9990 GPU Operator 24.3.0 has been released and contains a fix for this issue.
https://github.com/NVIDIA/gpu-operator/releases/tag/v24.3.0

I am closing this issue. But please re-open if you still encountering this with 24.3.0.
