### ISSUE TITLE
Precompiled 535 driver can't be installed : image pull failure

### ISSUE THREAD

**Issue by easyrider14** [NVIDIA/gpu-operator#682]
### 1. Quick Debug Information
* OS/Version: Ubuntu22.04
* Container Runtime Type/Version: Containerd
* K8s Flavor/Version: K8s
* GPU Operator Version: 23.9.0 and 23.9.2

### 2. Issue or feature description
nvidia-driver-daemonset tries to pull an image that does not exist
it tries to pull nvcr.io/nvidia/driver:535-5.15.0-100-generic-ubuntu22.04

I've been using version 23.9.0 of gpu-operator for a while now, using unmodified helm templates (usePrecompiled: true, version: 535)
It was working as expected until a few days ago. While installing a new cluster, nvidia-driver-daemonset failed to install driver
The daemonset was named nvidia-driver-daemonset-5.15.0-100-generic-ubuntu22.04. The image it tries to pull does not exist in nvidia's catalog, only tag 535-5.15.0-97-generic-ubuntu22.04 exists.
I've updated gpu operator from 23.9.0 to latest 23.9.2, but it still fails
I can make it work by setting usePrecompiled to false, and setting the complete driver version

**Comment by shivamerla** [comment]
@easyrider14 thanks for reporting this. We needed a small [fix](https://gitlab.com/nvidia/container-images/driver/-/merge_requests/311) in the CI to address this. We will publish these images soon.

**Comment by shivamerla** [comment]
This is now fixed
