### ISSUE TITLE
docs: Incomplete table of values for the Helm chart

### ISSUE THREAD

**Issue by lindhe** [NVIDIA/gpu-operator#698]
I found that the chart values documented [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#chart-customization-options) are incomplete. They are at least missing the `devicePlugin` object as documented [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#configuring-time-slicing-before-installing-the-nvidia-gpu-operator). Would be great if that was updated! 👍 

I couldn't easily find the docs here, so maybe I'm in the wrong repo? In that case: I'm sorry for posting here, can you please point me in the right direction?

**Comment by shivamerla** [comment]
@mikemckiernan PTAL

**Comment by lindhe** [comment]
Will do. Thanks for the pointer.
