### ISSUE TITLE
nvidia.com/gpu.deploy.mig-manager label not delete 

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/gpu-operator#701]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04):  centos7.9
* Kernel Version: 3.10.0-1160.el7.x86_64
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): Containerd
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): K8s
* GPU Operator Version: gpu-operator:v23.9.0

### 2. Issue or feature description

I hope to use this label to detect whether the current node GPU has `mig` enabled.

After I shut down a MIG device, the `nvidia.com/gpu.deploy.mig-manager` label still exists on the node's label, and its value is true.

### 3. Steps to reproduce the issue
- Enable GPU mig model.
- Disable GPU mig model.
- Watch node labels for `nvidia.com/gpu.deploy.mig-manager` value.

**Comment by shivamerla** [comment]
@lengrongfu i assume you are applying MIG profiles through `nvidia.com/mig.config` label on the node. To disable MIG you can set this label to `all-disabled` and `nvidia.com/mig.config.state` will indicate the result of it. These labels should be used to track the current status. `nvidia.com/gpu.deploy.mig-manager` label indicates that GPU Operator will deploy MIG Manager Daemonset Pod on the node as there are MIG capable GPUs. This doesn't indicate the current state on the node.

**Comment by lengrongfu** [comment]
Thank you for your reply.
If the user previously turned on MIG and specified `nvidia.com/mig.config`, and then turned off the MIG function, will `nvidia.com/mig.config` be automatically updated to `all-disabled`?

**Comment by lengrongfu** [comment]
> What do you mean by "and then turned off the MIG function". The way you turn off MIG is to set `nvidia.com/mig.config=all-disabled`.

Because i use `gpu-operator` to manage MIG enable/disable, if i no longer in use MIG model, i just need update `clusterpolicies` CR field `migManager.enable: false`, i don't change `nvidia.com/mig.config` this lable.

**Comment by klueska** [comment]
`migManager.enable=false` will disable the mig manager, but not disable MIG on the node. You would need to first set `nvidia.com/mig.config=all-disabled` to trigger the mig-manager to disable MIG on all the nodes, and only once that completed, set `migManager.enable=false`.

All of that said, what is the reason for you to set `migManager.enable=false`? The mig manager typically remains enabled on all nodes that are "MIG capable", providing an automated way to control how you want MIG configured on those nodes (including *disabling* MIG on one or all of the GPUs on the node via the `nvidia.com/mig.config` label.

**Comment by klueska** [comment]
No problem. Happy to help.
