### ISSUE TITLE
In GPU operator v23.9.2 driver Image is missing for bottlerocket1.19.2

### ISSUE THREAD

**Issue by OS-walidslim** [NVIDIA/gpu-operator#709]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

### 1. Quick Debug Information
* bottlerocket1.19.2:
* Kernel Version:
* Container Runtime Type/Version: Containerd
* K8s Flavor/Version: EKS
* GPU Operator Version: 23.9.2

### 2. Issue or feature description
Failed to pull image "[nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2](http://nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2)": rpc error: code = NotFound desc = failed to pull and unpack image "[nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2](http://nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2)": failed to resolve reference "[nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2](http://nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2)": [nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2](http://nvcr.io/nvidia/driver:535.104.05-bottlerocket1.19.2): not **found**

Image doesn't exist also on the [image repository](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags?filters=&orderBy=weightPopularDESC&query=&page=&pageSize=)

### 3. Steps to reproduce the issue
Deploy gpu operator charts on EKS

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods -n OPERATOR_NAMESPACE`
 - [ ] kubernetes daemonset status: `kubectl get ds -n OPERATOR_NAMESPACE`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n OPERATOR_NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n OPERATOR_NAMESPACE POD_NAME --all-containers`
 - [ ] Output from running `nvidia-smi` from the driver container: `kubectl exec DRIVER_POD_NAME -n OPERATOR_NAMESPACE -c nvidia-driver-ctr -- nvidia-smi`
 - [ ] containerd logs `journalctl -u containerd > containerd.log`

Collecting full debug bundle (optional):

```
curl -o must-gather.sh -L https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/hack/must-gather.sh 
chmod +x must-gather.sh
./must-gather.sh
```
**NOTE**: please refer to the [must-gather](https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/hack/must-gather.sh) script for debug data collected.

This bundle can be submitted to us via email: **operator_feedback@nvidia.com**

**Comment by cdesiniotis** [comment]
Hi @OS-walidslim, this is expected behavior as we do not support Bottlerocket OS. Please refer to: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html#supported-operating-systems-and-kubernetes-platforms
