### ISSUE TITLE
Use NVIDIADriver CRD to install GPU driver in a centos7 and a ubuntu22.04

### ISSUE THREAD

**Issue by lengrongfu** [NVIDIA/gpu-operator#725]
I currently have two nodes, one with Ubuntu 22.04 operating system and one with CentOS 7 operating system. I use `NVIDIADriver` for heterogeneous installation of drivers, but I found that the `toolkit` image can only be set in the CRD of `ClusterPolicy` and can only be set to `container-toolkit:v1.15.0-ubuntu22.04` version. How can I solve this problem?

**Comment by lengrongfu** [comment]
@elezar Can you help look this issue?

**Comment by cdesiniotis** [comment]
@lengrongfu a cluster with different operating system types is not a configuration we currently support. There are some discussions ongoing for using a single `container-toolkit` image that can be used across distributions, which would help address the issue you are encountering.

**Comment by lengrongfu** [comment]
> @lengrongfu a cluster with different operating system types is not a configuration we currently support. There are some discussions ongoing for using a single `container-toolkit` image that can be used across distributions, which would help address the issue you are encountering.

Yes, if we can provide a single `container-toolkit` image can be used across distributions, this is better, i am looking forward.

**Comment by lengrongfu** [comment]
We found current only three image, `-packaging` this image is what doing? 
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/k8s/containers/container-toolkit/tags
<img width="924" alt="image" src="https://github.com/user-attachments/assets/db4b89ec-4bb4-4273-9843-446d1f0b283f">

**Comment by lengrongfu** [comment]
Current can use two toolkit image to adaption all os system, issue solved.
