### ISSUE TITLE
Standardised mechanism for node selector in hybrid clusters

### ISSUE THREAD

**Issue by nwalker-nvidia** [NVIDIA/gpu-operator#74]
With a cluster with:
- CPU Only nodes
- GPU Nodes
- DGX Nodes

What is the recommended mechanism to ensure that GPU Operator will only deploy to the second type of node ? And correctly identify and not try to deploy gpu operator on DGX or CPU only nodes ?
Also, the NFD part of GPU Operator to scan the gpu capability, can it be implemented on DGX ?
N.

**Comment by shivamerla** [comment]
@nwalker-nvidia we already have a mechanism to differentiate CPU and GPU nodes using NFD and operands pods deploy only on GPU nodes. For DGX, drivers and container-toolkit will come pre-installed, so mixing these nodes with other GPU nodes is currently not supported and something we are planning to add with 1.11 release of operator.
