### ISSUE TITLE
label to nodes are too much, especially label non-gpu nodes. 

### ISSUE THREAD

**Issue by johnzheng1975** [NVIDIA/gpu-operator#742]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04): aws linux
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): eks 1.29
* GPU Operator Version: 
 url: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      version: v24.3.0

### 2. Issue or feature description
label to nodes are too much (we can say crazy ^_^ ), especially label non-gpu nodes. 

![image](https://github.com/NVIDIA/gpu-operator/assets/17720035/806512ba-626a-4a02-850f-070998ffe97f)

I hope, at least for non-gpu node, pls do not add labels to it, or only add one to two labels.

### 3. Steps to reproduce the issue
_Detailed steps to reproduce the issue._
Install gpu-operator
View the nodes labels;

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods -n OPERATOR_NAMESPACE`
 - [ ] kubernetes daemonset status: `kubectl get ds -n OPERATOR_NAMESPACE`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n OPERATOR_NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n OPERATOR_NAMESPACE POD_NAME --all-containers`
 - [ ] Output from running `nvidia-smi` from the driver container: `kubectl exec DRIVER_POD_NAME -n OPERATOR_NAMESPACE -c nvidia-driver-ctr -- nvidia-smi`
 - [ ] containerd logs `journalctl -u containerd > containerd.log`

Collecting full debug bundle (optional):

```
curl -o must-gather.sh -L https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/hack/must-gather.sh 
chmod +x must-gather.sh
./must-gather.sh
```
**NOTE**: please refer to the [must-gather](https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/hack/must-gather.sh) script for debug data collected.

This bundle can be submitted to us via email: **operator_feedback@nvidia.com**

**Comment by cdesiniotis** [comment]
All of the labels prefixed with `feature.node.kubernete.io/` are added by Node Feature Discovery. Please see my comment https://github.com/NVIDIA/gpu-operator/issues/728#issuecomment-2266237661 on why we deploy NFD and how to restrict it from running on non-GPU nodes.

There are a number of labels prefixed with `nvidia.com/` that GPU Operator adds -- many of these labels are configured as node selectors for our daemonsets and are used to control where components get scheduled to. Additionally, there are a number of labels prefixed with `nvidia.com/` added by GPU Feature Discovery -- which provide GPU / driver related information.
