### ISSUE TITLE
 /sys/module/firmware_class/parameters/path: Read-only file system -- nvidia-vgpu-manager-daemonset

### ISSUE THREAD

**Issue by davidhwua** [NVIDIA/gpu-operator#761]
### 1. Quick Debug Information
* OS/Version:Ubuntu22.04
* Kernel Version: Linux  5.15.0-112-generic
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker): nvida
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS): k8s 1.80 
* GPU Operator Version: gpu-operator-v24.3.0v24.3.0 
* Tesla T4
### 2. Issue or feature description

When I install the vgpu-manager, the error appears to be unable to write custom firmware "/run/nvidia/driver/lib/firmware/module/firmware" to GPU server /sys/module/firmware_class/parameters/path.I manually write this line to  /run/nvidia/driver/lib/firmware/module/firmware was passed,can somebody help me how to pass this error?

### 3. Steps to reproduce the issue
`helm install --wait --generate-name       -n gpu-operator --create-namespace       nvidia/gpu-operator      \
         --set sandboxWorkloads.enabled=true      \
         --set vgpuManager.enabled=true   \
          --set toolkit.enabled=true \
          --set vgpuManager.repository=registry.xxxx.com/    \
           --set vgpuManager.image=vgpu-manager \
           --set vgpuManager.version=550.54.10 \
           --set vgpuManager.imagePullSecrets={***}  --timeout 3600s`

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
Pods
`root@k8s-gpu1:~# getpod
NAME                                                              READY   STATUS     RESTARTS       AGE
gpu-operator-1718359653-node-feature-discovery-gc-644fbf54zsjcm   1/1     Running    0              19m
gpu-operator-1718359653-node-feature-discovery-master-7f5f4dg2q   1/1     Running    0              19m
gpu-operator-1718359653-node-feature-discovery-worker-cnblz       1/1     Running    0              19m
gpu-operator-1718359653-node-feature-discovery-worker-vhtxp       1/1     Running    0              19m
gpu-operator-66567bfffb-k9ltp                                     1/1     Running    0              19m
nvidia-sandbox-device-plugin-daemonset-48zr6                      0/1     Init:1/2   0              18m
nvidia-sandbox-validator-5bbkv                                    0/1     Init:1/3   0              18m
nvidia-vgpu-device-manager-zwjqh                                  0/1     Init:0/1   0              18m
nvidia-vgpu-manager-daemonset-4fp89                               1/1     Running    3 (5m3s ago)   19m`

Error : 
`+ _set_fw_search_path
+ local nv_fw_search_path=/run/nvidia/driver/lib/firmware
+ local fw_path_config_file=/sys/module/firmware_class/parameters/path
++ grep '[^[:space:]]' /sys/module/firmware_class/parameters/path
+ [[ ! -z '' ]]
+ echo 'Configuring the following firmware search path in '\''/sys/module/firmware_class/parameters/path'\'': /run/nvidia/driver/lib/firmware'
+ echo -n /run/nvidia/driver/lib/firmware
/usr/local/bin/nvidia-driver: line 132: /sys/module/firmware_class/parameters/path: Read-only file system
+ popd
/usr/local/bin/nvidia-driver: line 1: popd: directory stack empty
Configuring the following firmware search path in '/sys/module/firmware_class/parameters/path': /run/nvidia/driver/lib/firmware`

./must-gather.sh

Saving nvidia-bug-report from k8s-gpu2 ...
Failed to collect nvidia-bug-report from k8s-gpu2
tar: Removing leading `/' from member names
tar: /tmp/nvidia-bug-report.log.gz: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

`

**Comment by cdesiniotis** [comment]
@davidhwua we do [mount](https://github.com/NVIDIA/gpu-operator/blob/v24.3.0/assets/state-vgpu-manager/0500_daemonset.yaml#L61-L62) the host's /sys into the `vgpu-manager` container, and we run as privileged, so I would expect us to be able to write to this file. Would you be able to describe your system a bit more? Is this a vanilla ubuntu 22.04 node?

As you mentioned, manually adding the fw search path to this file should unblock the container.

**Comment by t1mk1k** [comment]
We're also running into a similar issue when trying to deploy the GPU operator with Helm on a kubeadm cluster with Ubuntu 22.04.

The `nvidia-driver-daemonset` pods get stuck with a ContainerCreatingError:

```{bash}
  Warning  Failed     78s (x2 over 90s)     kubelet            (combined from similar events): Error: failed to generate container "5dcfff291b851b1c2b7cef2b78bf8e6afa542e456309390213113ee175128cb1" spec: failed to generate spec: failed to mkdir "/sys/module/firmware_class/parameters/path": mkdir /sys/module/firmware_class: operation not permitted
```

Probably because 1) the path does not exist on the host and 2) the kubelet is not allowed to create this path and neither is a root user in a privileged pod.

When I manually edit the `firmware-search-path` mount in the `nvidia-driver-daemonset`, the driver pods start and I can run the cuda-vectoradd example.

```{yaml}
        - mountPath: /sys/module/
          name: firmware-search-path
...
      - hostPath:
          path: /sys/module
          type: ""
        name: firmware-search-path
```

Is there a way to adjust the location of the firmware search path through the Helm deployment?

**Comment by cdesiniotis** [comment]
@t1mk1k can you share the logs of `nvidia-driver-daemonset` after you edit the volume mount?

**Comment by t1mk1k** [comment]
There you go @cdesiniotis:

```{bash}
✗ kubectl logs -n nvidia-gpu-operator nvidia-driver-daemonset-67lsz                             
DRIVER_ARCH is x86_64
Creating directory NVIDIA-Linux-x86_64-550.54.15
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 550.54.15........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

WARNING: Unable to determine the default X library path. The path /tmp/null/lib will be used, but this path was not detected in the ldconfig(8) cache, and no directory exists at this path, so it is likely that libraries installed there will not be found by the loader.


WARNING: You specified the '--no-kernel-modules' command line option, nvidia-installer will not install any kernel modules as part of this driver installation, and it will not remove existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that NVIDIA kernel modules matching this driver version are installed separately.


WARNING: This NVIDIA driver package includes Vulkan components, but no Vulkan ICD loader was detected on this system. The NVIDIA Vulkan ICD will not function without the loader. Most distributions package the Vulkan loader; try installing the "vulkan-loader", "vulkan-icd-loader", or "libvulkan1" package.


========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 550.54.15 for Linux kernel version 5.15.0-1057-kvm

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Resolving Linux kernel version...
Proceeding with Linux kernel version 5.15.0-1057-kvm
Installing Linux kernel headers...
Installing Linux kernel module files...
Generating Linux kernel version string...
Compiling NVIDIA driver kernel modules...
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  You are using:           cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Skipping BTF generation for /usr/src/nvidia-550.54.15/kernel/nvidia-peermem.ko due to unavailability of vmlinux
Skipping BTF generation for /usr/src/nvidia-550.54.15/kernel/nvidia-drm.ko due to unavailability of vmlinux
Skipping BTF generation for /usr/src/nvidia-550.54.15/kernel/nvidia-modeset.ko due to unavailability of vmlinux
Skipping BTF generation for /usr/src/nvidia-550.54.15/kernel/nvidia-uvm.ko due to unavailability of vmlinux
Skipping BTF generation for /usr/src/nvidia-550.54.15/kernel/nvidia.ko due to unavailability of vmlinux
Relinking NVIDIA driver kernel modules...
Building NVIDIA driver package nvidia-modules-5.15.0-1057...
Installing NVIDIA driver kernel modules...

WARNING: The nvidia-drm module will not be installed. As a result, DRM-KMS will not function with this installation of the NVIDIA driver.


ERROR: Unable to open 'kernel/dkms.conf' for copying (No such file or directory)


Welcome to the NVIDIA Software Installer for Unix/Linux

Detected 5 CPUs online; setting concurrency level to 5.
Unable to locate any tools for listing initramfs contents.
Unable to scan initramfs: no tool found
Installing NVIDIA driver version 550.54.15.
Performing CC sanity check with CC="/usr/bin/cc".
Performing CC check.
Kernel source path: '/lib/modules/5.15.0-1057-kvm/build'

Kernel output path: '/lib/modules/5.15.0-1057-kvm/build'

Performing Compiler check.
Performing Dom0 check.
Performing Xen check.
Performing PREEMPT_RT check.
Performing vgpu_kvm check.
Cleaning kernel module build directory.
Building kernel modules: 

  [##############################] 100%
Kernel module compilation complete.
Unable to determine if Secure Boot is enabled: No such file or directory
Kernel messages:
[25904.720936] IPv6: ADDRCONF(NETDEV_CHANGE): cali2a8b8dfa312: link becomes ready
[25908.831465] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[25908.831485] IPv6: ADDRCONF(NETDEV_CHANGE): cali1276953e283: link becomes ready
[25966.619223] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[25966.619243] IPv6: ADDRCONF(NETDEV_CHANGE): caliaff2d5b8c1c: link becomes ready
[25969.092139] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[25969.092159] IPv6: ADDRCONF(NETDEV_CHANGE): calid5c5368083b: link becomes ready
[26064.804032] IPv6: ADDRCONF(NETDEV_CHANGE): califba42e7c3bd: link becomes ready
[26067.276770] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[26067.276790] IPv6: ADDRCONF(NETDEV_CHANGE): cali9e24a390a1c: link becomes ready
[26169.870365] nvidia: loading out-of-tree module taints kernel.
[26169.870375] nvidia: module license 'NVIDIA' taints kernel.
[26169.870377] Disabling lock debugging due to kernel taint
[26169.897729] nvidia: module verification failed: signature and/or required key missing - tainting kernel
[26169.908869] nvidia-nvlink: Nvlink Core is being initialized, major device number 245

[26169.924648] ACPI: \_SB_.LNKA: Enabled at IRQ 11
[26169.925217] nvidia 0000:00:05.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=io+mem
[26169.974675] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  550.54.15  Tue Mar  5 22:23:56 UTC 2024
[26170.005094] nvidia_uvm: module uses symbols from proprietary module nvidia, inheriting taint.
[26170.009097] nvidia-uvm: Loaded the UVM driver, major device number 243.
[26170.013350] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  550.54.15  Tue Mar  5 21:59:57 UTC 2024
[26170.017915] nvidia-modeset: Unloading
[26170.036108] nvidia-uvm: Unloaded the UVM driver.
[26170.068616] nvidia-nvlink: Unregistered Nvlink Core, major device number 245
Installing 'NVIDIA Accelerated Graphics Driver for Linux-x86_64' (550.54.15):: Installing

  [                              ]   0%
Unable to determine whether NVIDIA kernel modules are present in the initramfs. Existing NVIDIA kernel modules in the initramfs, if any, may interfere with the newly installed driver.

  [##############################] 100%
Driver file installation is complete.
Running post-install sanity check:: Checking

  [##############################] 100%
Post-install sanity check passed.

Installation of the kernel module for the NVIDIA Accelerated Graphics Driver for Linux-x86_64 (version: 550.54.15) is now complete.

Parsing kernel module parameters...
Configuring the following firmware search path in '/sys/module/firmware_class/parameters/path': /run/nvidia/driver/lib/firmware
grep: /sys/module/firmware_class/parameters/path: No such file or directory
/usr/local/bin/nvidia-driver: line 284: /sys/module/firmware_class/parameters/path: No such file or directory
WARNING: Failed to configure firmware search path
Loading ipmi and i2c_core kernel modules...
modprobe: WARNING: Module i2c_core not found in directory /lib/modules/5.15.0-1057-kvm
modprobe: WARNING: Module ipmi_msghandler not found in directory /lib/modules/5.15.0-1057-kvm
modprobe: WARNING: Module ipmi_devintf not found in directory /lib/modules/5.15.0-1057-kvm
Loading NVIDIA driver kernel modules...
+ modprobe nvidia
+ modprobe nvidia-uvm
+ modprobe nvidia-modeset
+ set +o xtrace -o nounset
Starting NVIDIA persistence daemon...
Mounting NVIDIA driver rootfs...
Done, now waiting for signal
```

**Comment by cdesiniotis** [comment]
@t1mk1k Thanks. The logs indicate that writing to `/sys/module/firmware_class/parameters/path` fails but the script continues without failing. 

Since `/sys/module/firmware_class` does not exist on your system, I assume the `firmware_class` module is not built into your kernel. Would you be able to load this kernel module and re-run the driver container?

**Comment by t1mk1k** [comment]
@cdesiniotis You're right! The firmware_class is not built into this kernel and loading the module fails:

```{bash}
root@ubuntu-76645486f4-jg9wq:/# modprobe firmware_class
modprobe: FATAL: Module firmware_class not found in directory /lib/modules/5.15.0-1057-kvm
```

```{bash}
root@ubuntu-76645486f4-jg9wq:/# cat /boot/config-$(uname -r) | grep FW_LOADER
# CONFIG_FW_LOADER is not set
```

It will take me some time to add the module to the kernel, as I currently have less than ideal access to the nodes of this cluster.

In the meantime, I had two questions for you because I'm not so familiiar with this area: 
Is it common for the `firmware_class` module to be available in the kernel? 
And, probably more important, does the gpu operator depend on it in some way?

**Comment by cdesiniotis** [comment]
@davidhwua it appears my initial comment https://github.com/NVIDIA/gpu-operator/issues/761#issuecomment-2224109557 was incorrect. We do not mount `/sys/module/firmware_class/parameters/path` into the vGPU Manager container, and thus, this explains the error you are seeing.

I have opened https://github.com/NVIDIA/gpu-operator/pull/865 which should resolve this issue and allow for the driver to properly make use of the GSP firmware. cc @tariq1890 @shivamerla

**Comment by cdesiniotis** [comment]
>In the meantime, I had two questions for you because I'm not so familiiar with this area:
Is it common for the firmware_class module to be available in the kernel?
And, probably more important, does the gpu operator depend on it in some way?

@t1mk1k yes, this is a common module built into most kernels AFAIK. As currently implemented, our driver container requires this module to update the firmware search path on the system. Without customizing this parameter, the NVIDIA driver module will not be able to find and load the GSP firmware file (which is required when using the open sourced NVIDIA kernel modules).

**Comment by cdesiniotis** [comment]
GPU Operator 24.6.0 has been released and contains a fix for this issue. Please re-open if you are still facing problems.
