### ISSUE TITLE
How do I upgrade GPU Operator and components?

### ISSUE THREAD

**Issue by superbrothers** [NVIDIA/gpu-operator#80]
How should I upgrade the GPU Operator? Are there any steps to take before updating the GPU Operator? Is there a document that describes it?

I would also like to know the steps for updating components such as NVIDIA driver by updating ClusterPolicy CR.

**Comment by shivamerla** [comment]
@superbrothers  Please stay tuned on this, we are working on upgrades support through OLM and update of individual GPU operator components. Will share the steps required for driver upgrades to work too.

**Comment by hongweijia** [comment]
Hi @shivamerla,
Do you have any update for upgrading the GPU Operator? Thanks!
BTW, we are using GPU Operator on OCP 4.3. We plan to upgrade to OCP 4.5. But we would like to know how to upgrade the GPU Operator after the OCP 4.3 upgraded to 4.5.
Any idea?

**Comment by shivamerla** [comment]
@hongweijia GPU operator pods should come up with the updated worker nodes. We already have driver tags published for rhcos 4.4/4.5/4.6, so on new nodes corresponding image tag is pulled. Also, we have published 1.5.1 of operator which multiple fixes and feature updates. Please un-install and re-install new one when possible.

**Comment by hongweijia** [comment]
Hi @shivamerla,
Thanks a lot for your sharing!
