### ISSUE TITLE
nvidia/driver could not resolve resolve Linux kernel version

### ISSUE THREAD

**Issue by liuchintao** [NVIDIA/gpu-operator#85]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?

```text
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

- [x] Are you running Kubernetes v1.13+?

```text
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?

```text
docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 nvidia:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?

```text
lsmod |grep -i -E 'i2c_core|ipmi_msghandler'
ipmi_msghandler       102400  3 ipmi_devintf,ipmi_si,ipmi_ssif
```

- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

```text
 kubectl describe clusterpolicies --all-namespaces
Name:         cluster-policy
Namespace:
Labels:       app.kubernetes.io/component=gpu-operator
              app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: gpu-operator-1601262093
              meta.helm.sh/release-namespace: default
API Version:  nvidia.com/v1
Kind:         ClusterPolicy
Metadata:
  Creation Timestamp:  2020-09-28T03:01:37Z
  Generation:          1
  Managed Fields:
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:dcgmExporter:
          .:
          f:image:
          f:repository:
          f:version:
        f:devicePlugin:
          .:
          f:image:
          f:repository:
          f:version:
        f:driver:
          .:
          f:image:
          f:repository:
          f:version:
        f:operator:
          .:
          f:defaultRuntime:
        f:toolkit:
          .:
          f:image:
          f:repository:
          f:version:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2020-09-28T03:01:37Z
    API Version:  nvidia.com/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:state:
    Manager:         gpu-operator
    Operation:       Update
    Time:            2020-09-28T03:01:41Z
  Resource Version:  1692
  Self Link:         /apis/nvidia.com/v1/clusterpolicies/cluster-policy
  UID:               4d19a1ee-b495-4a9f-a03b-0d8f16bb7c26
Spec:
  Dcgm Exporter:
    Image:       dcgm-exporter
    Repository:  nvidia
    Version:     1.7.2-2.0.0-rc.9-ubuntu18.04
  Device Plugin:
    Image:       k8s-device-plugin
    Repository:  nvidia
    Version:     1.0.0-beta6
  Driver:
    Image:       driver
    Repository:  nvidia
    Version:     440.64.00
  Operator:
    Default Runtime:  docker
  Toolkit:
    Image:       container-toolkit
    Repository:  nvidia
    Version:     1.0.2
Status:
  State:  ready
Events:   <none>
```

### 1. Issue or feature description

When I follow [scripts](https://github.com/NVIDIA/egx-platform/blob/master/install-guides/Ubuntu_Server_v2.0.md) step by step,
the `gpu-operator-resources` could not work.

```
kubectl get po -A
NAMESPACE                NAME                                                              READY   STATUS             RESTARTS   AGE
default                  gpu-operator-1601262093-node-feature-discovery-master-7948wlt8q   1/1     Running            0          13m
default                  gpu-operator-1601262093-node-feature-discovery-worker-qlpbr       1/1     Running            0          13m
default                  gpu-operator-6c76f78c64-5j7vg                                     1/1     Running            0          13m
gpu-operator-resources   nvidia-container-toolkit-daemonset-fsfs6                          1/1     Running            0          12m
gpu-operator-resources   nvidia-dcgm-exporter-t4cwr                                        0/1     CrashLoopBackOff   7          12m
gpu-operator-resources   nvidia-device-plugin-daemonset-ktdrb                              0/1     CrashLoopBackOff   7          12m
gpu-operator-resources   nvidia-device-plugin-validation                                   0/1     Pending            0          13m
gpu-operator-resources   nvidia-driver-daemonset-v7v74                                     0/1     CrashLoopBackOff   6          12m
gpu-operator-resources   nvidia-driver-validation                                          0/1     CrashLoopBackOff   7          13m
```

And I checked the driver's log, it shows as below:

```
kubectl logs nvidia-driver-daemonset-v7v74 -n gpu-operator-resources

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 440.64.00 for Linux kernel version 5.3.0-050300-generic

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
Resolving Linux kernel version...
Could not resolve Linux kernel version
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
```

### 2. Steps to reproduce the issue

I just follow the [tutorial](https://github.com/NVIDIA/egx-platform/blob/master/install-guides/Ubuntu_Server_v2.0.md) :-(

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [x] kubernetes daemonset status: `kubectl get ds --all-namespaces`

```
kubectl get ds -n gpu-operator-resources
NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                      AGE
nvidia-container-toolkit-daemonset   1         1         1       1            1           feature.node.kubernetes.io/pci-10de.present=true   16m
nvidia-dcgm-exporter                 1         1         0       1            0           feature.node.kubernetes.io/pci-10de.present=true   16m
nvidia-device-plugin-daemonset       1         1         0       1            0           feature.node.kubernetes.io/pci-10de.present=true   16m
nvidia-driver-daemonset              1         1         0       1            0           feature.node.kubernetes.io/pci-10de.present=true   16m
```

 - [x] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [x] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [x] Output of running a container on the GPU machine: `docker run -it alpine echo foo`

It works well.....

```
docker run --rm -it alpine echo foo
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
df20fa9351a1: Pull complete
Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
Status: Downloaded newer image for alpine:latest
foo
```

 - [x] Docker configuration file: `cat /etc/docker/daemon.json`

```
{
  "runtimes": {
    "nvidia": {
      "path": "/usr/local/nvidia/toolkit/nvidia-container-runtime"
    }
  },
  "default-runtime": "nvidia"
}
```

 - [x] Docker runtime configuration: `docker info | grep runtime`

```
Runtimes: nvidia runc
Default Runtime: nvidia
```

 - [x] NVIDIA shared directory: `ls -la /run/nvidia`
 - [x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`

```
ls /usr/local/nvidia/toolkit/
libnvidia-container.so.1      nvidia-container-cli       nvidia-container-runtime       nvidia-container-runtime.real  nvidia-container-toolkit.real
libnvidia-container.so.1.0.7  nvidia-container-cli.real  nvidia-container-runtime-hook  nvidia-container-toolkit
```

 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`

There is nothing....

 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by nvjmayo** [comment]
Thank you for your feedback. I'm not seeing this on my end or in our CI/CD. But I will attempt to reproduce once I have a plan on what the problem might be.

**Comment by liuchintao** [comment]
> Thank you for your feedback. I'm not seeing this on my end or in our CI/CD. But I will attempt to reproduce once I have a plan on what the problem might be.

@nvjmayo Thanks for your reply, I think I find the reason of this issue, my host kernel version is `5.3.0-050300-generic`, 
but I can not find it by `apt-cache search linux-headers`.

Does GPU operator just match kernel version from apt source?

**Comment by thomasdbaker** [comment]
I am in the exact same position, Problem statement in the nvidia-driver pod logs:

Could not resolve Linux kernel version
Resolving Linux kernel version...
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...


 If I take a look at the Worker discover pod I see:

2020/10/06 19:29:07 kernel-version.major = 4
2020/10/06 19:29:07 kernel-version.minor = 15
2020/10/06 19:29:07 kernel-version.revision = 0
2020/10/06 19:29:07 kernel-config.NO_HZ = true
2020/10/06 19:29:07 kernel-config.NO_HZ_IDLE = true
2020/10/06 19:29:07 kernel-version.full = 4.15.0-115-generic

All nvidia pods, besides toolkit. remain in a crash loop backoff.

gpu-operator-7fb8494b76-dx9w2                                 1/1     Running            0          3d20h
gpu-operator-node-feature-discovery-master-75c588c7cb-9cc9q   1/1     Running            0          3d20h
gpu-operator-node-feature-discovery-worker-ltb6c              1/1     Running            0          3d20h
nvidia-container-toolkit-daemonset-qxtmv                      1/1     Running            0          3d20h
nvidia-dcgm-exporter-4f8fz                                    0/1     CrashLoopBackOff   1106       3d20h
nvidia-device-plugin-daemonset-42pzg                          0/1     CrashLoopBackOff   1102       3d20h
nvidia-device-plugin-validation                               0/1     Pending            0          3d20h
nvidia-driver-daemonset-m7h82                                 0/1     CrashLoopBackOff   1091       3d20h
nvidia-driver-validation                                      0/1     CrashLoopBackOff   1105       3d20h


Did you get this working?

**Comment by shivamerla** [comment]
@liuchintao @thomasdbaker Yes, driver container will look for linux-kernel-headers with underlying kernel version. if one is not available(deleted from Ubuntu repositories overtime), we will end up with this. Please upgrade the kernel for this to work.

**Comment by liuchintao** [comment]
@thomasdbaker hi, I solved this issue by install linux-kernel-headers manually.

But unfortunately, I did not install operator successfully for various reasons.

@shivamerla Thanks for your reply, this issue is resolved.

By the way, installing driver in container is really cool. 👍
