### ISSUE TITLE
driver image not found

### ISSUE THREAD

**Issue by 13567436138** [NVIDIA/gpu-operator#858]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._
![image](https://github.com/user-attachments/assets/866cb904-6c6a-491e-af9a-24dc24f3b50f)

### 1. Quick Debug Information
* OS/Version(e.g. RHEL8.6, Ubuntu22.04):
* Kernel Version:
* Container Runtime Type/Version(e.g. Containerd, CRI-O, Docker):
* K8s Flavor/Version(e.g. K8s, OCP, Rancher, GKE, EKS):
* GPU Operator Version:

### 2. Issue or feature description
_Briefly explain the issue in terms of expected behavior and current behavior._

### 3. Steps to reproduce the issue
_Detailed steps to reproduce the issue._

### 4. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods -n OPERATOR_NAMESPACE`
 - [ ] kubernetes daemonset status: `kubectl get ds -n OPERATOR_NAMESPACE`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n OPERATOR_NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n OPERATOR_NAMESPACE POD_NAME --all-containers`
 - [ ] Output from running `nvidia-smi` from the driver container: `kubectl exec DRIVER_POD_NAME -n OPERATOR_NAMESPACE -c nvidia-driver-ctr -- nvidia-smi`
 - [ ] containerd logs `journalctl -u containerd > containerd.log`

Collecting full debug bundle (optional):

```
curl -o must-gather.sh -L https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/hack/must-gather.sh 
chmod +x must-gather.sh
./must-gather.sh
```
**NOTE**: please refer to the [must-gather](https://raw.githubusercontent.com/NVIDIA/gpu-operator/master/hack/must-gather.sh) script for debug data collected.

This bundle can be submitted to us via email: **operator_feedback@nvidia.com**

**Comment by 13567436138** [comment]
ctr image pull nvcr.io/nvidia/driver:550.90.07-ubuntu20.04   this is ok
but 
ctr image pull nvcr.io/nvidia/driver:550.90.07-ubuntu24.04 is 404

**Comment by lengrongfu** [comment]
You can get all driver image from https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags

**Comment by cdesiniotis** [comment]
We do not support ubuntu24.04. As mentioned, you can see all the driver tags at https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags
