### ISSUE TITLE
Change nvidia-driver-validation image path?

### ISSUE THREAD

**Issue by thomasdbaker** [NVIDIA/gpu-operator#86]
Anyone know where I can change the image path for nvidia-driver-validation image path  we are behind a proxy and use a private internal repo,  I can't find the reference  in the manifests and also kustomized the entire deployment swapping image path with no luck.

  containerStatuses:
  - image: nvidia/samples:cuda10.2-vectorAdd
    imageID: ""
    lastState: {}
    name: cuda-vector-add
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "nvidia/samples:cuda10.2-vectorAdd"
        reason: ImagePullBackOff

Thanks!

**Comment by shivamerla** [comment]
@thomasdbaker currently we don't have a way to configure this via helm or ClusterPolicy(CR). Its hardcoded [here](https://github.com/NVIDIA/gpu-operator/blob/master/assets/state-driver-validation/cuda-vector-add-raw.yaml#L16). will look into making these configurable too.

**Comment by shivamerla** [comment]
@thomasdbaker this [commit ](https://github.com/NVIDIA/gpu-operator/commit/3bbe937ff06b71309e9f6e177ba0b556715ef413) allows users to specify repo/image/tag for validation pods for air-gapped installs.
