### ISSUE TITLE
Publish v1.2.0 to Red Hat Certified Operator Hub

### ISSUE THREAD

**Issue by rmkraus** [NVIDIA/gpu-operator#89]
### 1. Issue or feature description

Version 1.2.0 was published last Friday. Is there an ETA on when this new version will be available on Red Hat's Certified Operator Hub? If I am following along, version 1.2.0 should fix the Kernel mismatch issues on CoreOS.

https://catalog.redhat.com/software/operators/nvidia/gpu-operator/5ea882962937381642a232cd?container-tabs=overview

**Comment by shivamerla** [comment]
@rmkraus Its targeted to be published to OperatorHub with certification by end of next week.

**Comment by rmkraus** [comment]
👍 

Great! Thanks for the update.

**Comment by rmkraus** [comment]
1.1.7-r2 has been published and can be pulled.
