### ISSUE TITLE
GET https://helm.ngc.nvidia.com/nvidia returns 401

### ISSUE THREAD

**Issue by cwyl02** [NVIDIA/gpu-operator#921]
Similar to https://github.com/NVIDIA/gpu-operator/issues/748

But only to `https://helm.ngc.nvidia.com/nvidia`. `https://helm.ngc.nvidia.com/nvidia/index.yaml` and `helm repo add --pass-credentials nvidia https://helm.ngc.nvidia.com/nvidia` works on my laptop.

_**Important Note:  NVIDIA AI Enterprise customers can get support from NVIDIA Enterprise support. Please open a case [here](https://enterprise-support.nvidia.com/s/create-case)**._

### 2. Issue or feature description
GET https://helm.ngc.nvidia.com/nvidia returns 401

This blocks our CICD pipelines.

### 3. Steps to reproduce the issue
browser/curl https://helm.ngc.nvidia.com/nvidia

**Comment by coderRenxy** [comment]
have a same question

**Comment by atanasovskib** [comment]
Any update from the maintainers? It's been 8 hours and the issue still persists

**Comment by mrsimonemms** [comment]
They're probably based in the US - it's not yet 7am on the East Coast. I'd hope that someone will be on it in the next couple of hours as I'm blocked and have a deadline to meet.

**Comment by jimmidyson** [comment]
@cdesiniotis @elezar Can either of you help out here? 🙏

**Comment by klueska** [comment]
I see an internal bug report for it against NGC. It's affecting all repos, not just the operator.

**Comment by kpitzen** [comment]
+1 this is a blocker for us as well

**Comment by ikarlashov** [comment]
Any Update from maintainers? Our development process is completely blocked.
What is ETA for fix? Is there any mirror repo?

**Comment by mrsimonemms** [comment]
It's not ready yet, but (for hopefully obvious reasons), I'm creating a mirror at https://github.com/mrsimonemms/nvidia-helm-mirror. Charts and Docker images will be hosted there to avoid this problem again.

**Comment by davegallant** [comment]
https://github.com/NVIDIA/gpu-operator/issues/748#issuecomment-2289127855

**Comment by mrsimonemms** [comment]
It seems to be (mostly) working now. My mirrored repo has downloaded all the `gpu-operator` charts successfully - there were some other charts that were still returning a `401` error

**Comment by cdesiniotis** [comment]
The issue is resolved now. Please report back if you are still encountering this.
