### ISSUE TITLE
How to install gpu-operator on OKD 4.5 GA cluster?

### ISSUE THREAD

**Issue by rupang790** [NVIDIA/gpu-operator#95]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? Fedora CoreOS 32
- [*] Are you running Kubernetes v1.13+?
- [*] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? CRIO 1.18.2
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

I would like to use and test the GPU on OKD 4.5 Cluster, so I tried to follow installation guide as below link:
https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#prerequisites

After Install by helm chart, nvidia-driver-daemonset pod shows "ImagePullBackOff". When I checked the daemonset yaml, it seems to check the Redhat os version. So I remove the checking os version on spec.env part and add 'fedora32' after driver version as like : 
![image](https://user-images.githubusercontent.com/40801176/98086514-3c5abb80-1ec2-11eb-952b-89c26523f0fa.png)

But it still shows 'ImagePullBackOff' message on nvidia-driver-daemonset pod with the event message as:
![image](https://user-images.githubusercontent.com/40801176/98086644-66ac7900-1ec2-11eb-84df-aeb0e47e3046.png)

Could you recommend how to install plugin on OKD4.5 cluster which worker node uses Fedora CoreOS32 ?

 
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] kubernetes pods status: `kubectl get pods --all-namespaces`
 - [ ] kubernetes daemonset status: `kubectl get ds --all-namespaces`
 - [ ] If a pod/ds is in an error state or pending state `kubectl describe pod -n NAMESPACE POD_NAME`
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [ ] Docker runtime configuration: `docker info | grep runtime`

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

**Comment by snelis** [comment]
Similar setup here. Installing OKD on Fedora CoreOS.
This will result in:
`Back-off pulling image "nvcr.io/nvidia/driver:450.80.02-fedora32"`

It seems there are only tags for RHEL, RHCOS and Ubuntu
https://ngc.nvidia.com/catalog/containers/nvidia:driver/tags

**Comment by zvonkok** [comment]
@rupang790 @snelis PTAL [https://hackmd.io/-vpQKhC8SVmDewmJLQgGnw](https://hackmd.io/-vpQKhC8SVmDewmJLQgGnw )

**Comment by snelis** [comment]
ah nice - i was on the right track - there was a problem with the driver image gcc version that conflicted with the kernel gcc version.
I was trying an upgrade, but the downgrade was my next step.
Thanks for sharing ! :+1:

**Comment by rupang790** [comment]
> @rupang790 @snelis PTAL https://hackmd.io/-vpQKhC8SVmDewmJLQgGnw

Thanks for sharing. I will try to do soon.
However, before trying installation, I have 2 more questions more.

1. Is MachineSet setting for GPU Node mandatory? Is there no way to use GPU on OKD without MachineSet configuration? 
2. In part "Create a DriverContainer for F32, working with NVIDIA to add Fedora CoreOS support", you push the image to <registry>/<repo>. Which <registry>/<repo> I can use for? It can be local registry or git registry?

**Comment by snelis** [comment]
In the end I opted for building a driver image with gcc-10.1.1 - this works and i got my GPU working now.

**Comment by rupang790** [comment]
Do you have any idea about below error?
![image](https://user-images.githubusercontent.com/40801176/98780874-d679b100-2438-11eb-8a2a-595dfccb6f54.png)

I pushed the driver image to OpenShift internet image registry and I already check that I can pull that image by Podman pull command. After that I tried to install gpu-operator as your shared doc, however the driver pod could not pull the image with authentication error. Do you have any case to resolve that?
(Create imageStream on openshift-image-registry namespace and I used cluster-admin user to do that)
![image](https://user-images.githubusercontent.com/40801176/98781210-5738ad00-2439-11eb-8620-dd8ee34e57b0.png)

**Comment by zvonkok** [comment]
@rupang790 See this:[https://docs.openshift.com/container-platform/4.5/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-across-projects_using-image-pull-secrets]( https://docs.openshift.com/container-platform/4.5/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-across-projects_using-image-pull-secrets)

The nvidia-driver serviceaccount needs to be updated. 

```
$ oc policy add-role-to-user \
    system:image-puller system:serviceaccount:gpu-operator-resources:nvidia-driver \
    --namespace=openshift-image-registry
```

**Comment by rupang790** [comment]
@zvonkok 
Thanks for help. I missed that points.  Now all gpu-operator are running correctly.
I would like you to know that toolkit version 1.0.2 is not working to pull the image, so I changed to 1.3.0-ubi8 on 'nvidia-container-toolkit-daemonset' yaml.
Thanks once again.
![image](https://user-images.githubusercontent.com/40801176/98785166-8520f000-243f-11eb-8b83-702c94e1874c.png)
