### ISSUE TITLE
ERROR: failed to get OpenShift version

### ISSUE THREAD

**Issue by weishiuchang** [NVIDIA/gpu-operator#96]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node? No. RHEL7.8
- [x] Are you running Kubernetes v1.13+? Yes. 1.19
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)? docker-ce 19.03.12
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes? Yes to ipmi_msghandler; i2c_core should be in default kernel.
- [ ] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`) No. I am unable to deploy gpu-operator in the first place.

### 1. Issue or feature description

helm install fails with: "Failed to apply transformation 'nvidia-driver-daemonset' with error: 'ERROR: failed to get OpenShift version: the server could not find the requested resource (get clusterversions.config.openshift.io version)'"

### 2. Steps to reproduce the issue

RHEL 7.8 servers
NOT running OpenShift; Deployed kubernetes 1.19 via kubeadm.
helm upgrade --atomic --debug --install gpu-operator nvidia/gpu-operator

Looking at https://github.com/NVIDIA/gpu-operator/blob/4a26988fb2a9b79a714e415c5689e3121a81cbf6/pkg/controller/clusterpolicy/object_controls.go#L370 it seems TransformDriver will always fail on non-openshift kubernetes RHEL clusters?

**Comment by weishiuchang** [comment]
Rather strong assumption there, that if someone is running RHEL they must therefore be running OpenShift.

**Comment by shivamerla** [comment]
https://gitlab.com/nvidia/kubernetes/gpu-operator/-/merge_requests/138 this should take care of it.

**Comment by shivamerla** [comment]
Closing this as the PR is merged.
