### ISSUE TITLE
Is k8s 1.21 no longer supported by any version of gpu-operator?

### ISSUE THREAD

**Issue by qingfenghcy** [NVIDIA/gpu-operator#971]
My k8s cluster version is 1.21, and I'm having some trouble installing gpu-operator. Is k8s 1.21 no longer supported by any version of gpu-operator? Thanks.

**Comment by cdesiniotis** [comment]
GPU Operator does not support k8s 1.21. You can refer to https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/24.6.1/platform-support.html#platform-support

**Comment by cdesiniotis** [comment]
Since it is the last version which supports k8s 1.21, it is the version I would recommend for k8s 1.21.
