### ISSUE TITLE
Deploying GPU-Operator on AWS EKS 

### ISSUE THREAD

**Issue by brianrudolf** [NVIDIA/gpu-operator#98]
### 1. Quick Debug Checklist
- [x] Are you running on an Ubuntu 18.04 node?
- [x] Are you running Kubernetes v1.13+?
- [ ] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
docker://17.3.2
- [ ] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

The GPU operator does not finish deploying due to perpetual `ContainerCreating` nvidia-driver-validation pod. Suspect the outdated Docker runtime is to blame (using Container Runtime Version:  docker://17.3.2 bundled with [Ubuntu AMI for EKS](https://cloud-images.ubuntu.com/docs/aws/eks/)). Before I build a custom AMI to upgrade the Docker runtime, I would like to confirm this is the cause. Relevant `kubectl` output below.

Prior to using the Ubuntu AMI, the [Amazon Linux 2 AMI for EKS](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html) was used but the operator installation failed earlier in the process when it encountered an issue pulling containers as the GPU Operator attempted to pull images with `-amzn2` appended to the tag for OS version. It appears the [driver image repo](https://ngc.nvidia.com/catalog/containers/nvidia:driver/tags) only has images tagged for REHL & Ubuntu. *Is it possible to use the REHL tagged images on Amazon Linux 2 as they both use the `yum` package manager?

### 2. Steps to reproduce the issue
Fresh AWS EKS cluster (created using Terraform), running a g4dn.xlarge node with ami-0fe1026f574d6be2e.
Helm install GPU-operator:
`helm upgrade --install gpu-operator nvidia/gpu-operator `

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

Key error message comes from `kubectl describe pod -n gpu-operator-resources nvidia-driver-validation`:
**Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nvidia-driver-validation": Error response from daemon: containerd: container not started**

 - [x] kubernetes pods status: `kubectl get pods --all-namespaces`
[all_pods.txt](https://github.com/NVIDIA/gpu-operator/files/5495982/all_pods.txt)
 - [x] kubernetes daemonset status: `kubectl get ds --all-namespaces`
[all_ds.txt](https://github.com/NVIDIA/gpu-operator/files/5495984/all_ds.txt)
 - [x] If a pod/ds is in an error state or pending state `kubectl describe pod -n gpu-operator-resources nvidia-driver-validation`
[describe-pod-nvidia-driver-validation.txt](https://github.com/NVIDIA/gpu-operator/files/5495958/describe-pod-nvidia-driver-validation.txt)
 - [ ] If a pod/ds is in an error state or pending state `kubectl logs -n NAMESPACE POD_NAME`

 - [ ] Output of running a container on the GPU machine: `docker run -it alpine echo foo`
 - [ ] Docker configuration file: `cat /etc/docker/daemon.json`
 - [x] Docker runtime configuration: ~`docker info | grep runtime`~ `kubectl describe node ip-10-0-3-72.ca-central-`.compute.internal`
[describe-node.txt](https://github.com/NVIDIA/gpu-operator/files/5496043/describe-node.txt)

 - [ ] NVIDIA shared directory: `ls -la /run/nvidia`
 - [ ] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
 - [ ] NVIDIA driver directory: `ls -la /run/nvidia/driver`
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`

 - [x] `kubectl apply -f tests/nvidia-smi.yaml`
Tried to run a pod with `nvidia-smi` by using nodeSelector, see YAML contents:
[nvidia-smi.txt](https://github.com/NVIDIA/gpu-operator/files/5496026/nvidia-smi.txt)
 - [x] `kubectl describe pod nvidia-smi`:
[nvidia-smi-pod.txt](https://github.com/NVIDIA/gpu-operator/files/5496035/nvidia-smi-pod.txt)

Currently having trouble SSH-ing into node, hopefully can update this Issue with further outputs.

**Comment by shivamerla** [comment]
@brianrudolf It does appear to be due to docker version. Attaching docker/kubelet logs will help to root cause. If you can upgrade to latest docker and verify, that will be great: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#pre-requisites

For support with Amazon Linux, RHEL/RHCOS images have binding to OCP versions passed to them to pull right packages. We are looking to add support with CentOS, which could be used with Amazon Linux too. You can build Centos7/8 images from here and give it a try: https://gitlab.com/nvidia/container-images/driver

**Comment by brianrudolf** [comment]
Thank you @shivamerla for the quick response. I can provide docker and kubelet logs tomorrow, and I'll try out manually upgrading docker on the Ubuntu based machines.

**Comment by brianrudolf** [comment]
@shivamerla I am attempting to build the CentOS images locally from either [centos7](https://gitlab.com/nvidia/container-images/driver/-/tree/master/centos7) or [centos8](https://gitlab.com/nvidia/container-images/driver/-/tree/master/centos8) but am unsure how to handle the PUBLIC_KEY and PRIVATE_KEY docker build arguments. 

The kernel version of my EKS node is `4.14.198-152.320.amzn2.x86_64` so that is what I am setting the KERNEL_VERSION build argument to.

Docker command attempt:
```
docker build -t nvidia/driver:450.80.02-centos8 \
    --build-arg KERNEL_VERSION="4.14.198-152.320.amzn2.x86_64" \
    --build-arg DRIVER_VERSION="450.80.02" \
    --file Dockerfile .
```
Can you advise ?

**Comment by shivamerla** [comment]
@brianrudolf keys are required only to build signed driver modules in case if secure boot is enabled, otherwise above command looks good.
